node-red/node-red

- packages/node_modules/@node-red/editor-client/src/js/ui/common/popover.js
Closing subflow template tab while *Hide flow* tooltip is shown, leaves the tooltip shown.
This PR try to fix this issue by handling remove target event.
> fix to hide tooltip after removing subflow tab

- packages/node_modules/@node-red/editor-client/src/js/ui/deploy.js
After introduction of [PR#3304](https://github.com/node-red/node-red/pull/3304), when deploying a new dashboard flow, the following warning is displayed.
This is because node validation does not apply to certain config nodes (`ui_base` in this case).
This PR try to fix this problem.
> fix node validation to be applied to config node

- packages/node_modules/@node-red/registry/lib/loader.js
Removes a rogue console.log that shouldn't be there.
> Remove console.log when ignoring disabled module

- packages/node_modules/@node-red/editor-client/src/js/ui/view.js
Fixes #3433
wrap the push to `removedLinks` array to ensure removed links are removed from `selectedLinks` (to avoid duplicate additions to undo history
> bug fix: Dont add wires to undo buffer twice

- packages/node_modules/@node-red/editor-client/src/js/ui/editors/code-editors/monaco.js
- packages/node_modules/@node-red/editor-client/src/types/node-red/func.d.ts
- update jsdoc for `env.get`
- add Predefined Environment Variables to snippet suggestions
Discussed in meeting (no links to discussion sorry) but it does refer to the 2.2.0 additions [here](https://nodered.org/blog/2022/01/27/version-2-2-released#predefined-environment-variables)
> Coding help for recently added node-red Predefined Environment Variables

- packages/node_modules/@node-red/nodes/core/function/10-switch.js
- test/nodes/core/function/10-switch_spec.js
and add test
to fix issue #3408
This PR - addresses #3408 and makes NaN input to the is of type number test report as false - which is what most humans would expect.
Technically this is a slight change in behaviour and so should be flagged in the v3 release notes - but is very much an edge case that is caused by the weirdness of javascript types.
This does not alter the handling of infinity but does add a test case for it.
> switch node - add check for NaN in is of type number to be false

- packages/node_modules/@node-red/editor-client/src/js/nodes.js
Whilst the fix in #3437 prevents the the bug in undo history adding duplicate wires, this PR ensures `RED.nodes.addLink` will filter out duplicate links wherever they come from.
This will also fixup any flows that were broken in 2.2.0 due to the original bug.
> Prevent duplicate links being added between nodes

- packages/node_modules/@node-red/editor-client/src/js/ui/keyboard.js
Fixes #3400
Uses `.toLowerCase()` on the filter term so it works.
> Handle mixed-cased filter terms in keyboard shortcut dialog

- packages/node_modules/@node-red/nodes/core/function/89-delay.html
Fixes #3407
This partially reverts #3351 in that it allows the `nbRateUnits` property of the Delay node to be undefined. This means very old nodes don't get incorrectly flagged as invalid
> Allow nbRateUnits to be undefined when validating

- packages/node_modules/@node-red/editor-client/locales/en-US/editor.json
- packages/node_modules/@node-red/editor-client/src/js/ui/search.js
- packages/node_modules/@node-red/editor-client/src/js/ui/tab-info-outliner.js
- packages/node_modules/@node-red/editor-client/src/js/ui/workspaces.js
Add `is:modified` feature to permit user to find all changed nodes
This addresses the issue where by a user cannot find (due to potentially hundreds of nodes) what has changed.
> New Feature: Add ability to find modified nodes/flows.

- packages/node_modules/@node-red/runtime/lib/nodes/Node.js
fixes #3389
- adds additional info to aid sourcing the issue
- removes lots of undefined info when node type is incorrect
- stores and reports original stack before internal try/catch exception
- ensure this._flow is something before attempting to call `handleError`
> improve "Unexpected Node Error" logging

- packages/node_modules/@node-red/runtime/lib/flows/util.js
- test/nodes/core/common/20-inject_spec.js
Substituting environment variable $ {NR_NODE_PATH} does not work properly. 
This is because the environment variable replacement is performed before setting ` _path` attribute of the node.
> Fix substitution of NR_NODE_PATH

- packages/node_modules/@node-red/util/lib/hooks.js
fixes #3401
- handles brackets and no brackets in stack line
- handles short stack
* Ensure "TypeError: Cannot read property 'slice' of undefined" if called from within callback does not occur
* if short stack, location is assigned `"unknown:0:0"` and node-red debug log will contain the hook name and stack
* if an error occurs parsing a stack, location is assigned `"unknown:0:0"` and node-red debug log will contain the hook name and stack
I wrapped the new code in a temporary function and tested locally in a Node JS 16 env REPL...
refactor code to permit testing?
> Improve module location parsing (of stack info) when adding hook

- packages/node_modules/@node-red/nodes/core/network/10-mqtt.js
fixes #2934
Prevent the `close timed out` issue (see references below)
* Move all calls to `node.client.end()` to one location in code base (broker node function `.disconnect()` ) to reduce code paths and early calls.
* Ensure `done` is always called for the "close" event in MQTT In/Out/Broker nodes (`node.on('close'`) by removing the `done` callback from the `node.client.end()` signature - since it is (at best) unreliable due to the myriad of combination of user options and order of events (i.e. which nodes close first, flow file ordering, whether node has a `close` packet to sent etc)
https://github.com/node-red/node-red/issues/2934
https://github.com/martin-doyle/node-red-contrib-aedes/issues/46
https://github.com/martin-doyle/node-red-contrib-aedes/issues/54 …
> Fix "close timed out" error when performing full deploy or modifying broker node.

- packages/node_modules/@node-red/nodes/core/network/10-mqtt.js
fixes #3471
Ensure a false v5 property is set false in v5 packet options object
> fix: ensure mqtt v5 props can be set false

- packages/node_modules/@node-red/editor-client/src/js/ui/view.js
- if a node is behind the d3 chart scrollbar, it is not scrolled into view when it is revealed (flashed) by a search
- jQuery `.width()` & `.width()` actually includes the scroll bar.
- using native `clientWidth` and `clientHeight` fixes this ([extra info](https://stackoverflow.com/a/39330216/4018881))
> Improve scroll into view

- packages/node_modules/@node-red/editor-client/locales/en-US/editor.json
- packages/node_modules/@node-red/editor-client/src/js/history.js
- packages/node_modules/@node-red/editor-client/src/js/keymap.json
- packages/node_modules/@node-red/editor-client/src/js/nodes.js
- packages/node_modules/@node-red/editor-client/src/js/red.js
- packages/node_modules/@node-red/editor-client/src/js/ui/view-tools.js
- packages/node_modules/@node-red/editor-client/src/js/ui/view.js
Introduces "Split wire to link nodes"
Resolves #3416 
Discussed here: https://discourse.nodered.org/t/opinion-wanted-potential-new-feature-split-wire-with-link-nodes/57867
Trello item here: https://trello.com/c/z2A7xA51/266-editor-split-wire-with-link-nodes-action
* Added `RED.view.tools.splitWiresWithLinkNodes`
* Refactored calculation of grid snap offsets to `RED.view.tools.calculateGridSnapOffsets`
* Same calculation code was written twice already & I would have added a third
* Refactored `AddNode` in `view.js` to `RED.nodes.createNode`
* `AddNode` was not exposed from `view.js` but was needed in `RED.view.tools` for new feature. Seemed sensible to move this to `RED.nodes`. 
* Renamed to `createNode` since `addNode` is already a function in `nodes.js` but functionally does a different …
> Add feature: split-wire-to-links

- packages/node_modules/@node-red/editor-client/src/js/ui/view.js
* fully qualify call to `calculateGridSnapOffsets`
* use .x and .y properties of calculated offsets (not array indexes)
> fix PR 'split wire with link nodes' #3416

- packages/node_modules/@node-red/editor-client/src/js/nodes.js
Replaced `instanceof Array` with the [recommended alternative `Array.isArray`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/isArray#instanceof_vs_isarray), which was breaking `RED.nodes.import` when Node-RED is embedded in an `iframe`
Fixes https://github.com/node-red/node-red/issues/3483
> fix nodes losing their wires when in an iframe

- packages/node_modules/@node-red/editor-client/src/js/ui/editors/panes/properties.js
fixes #3475
Use `JSON.stringify` to compare old value to new value. This takes care of array and object values & prevents the node signalling a change (thus preventing the deploy button becoming enabled)
More details in issue #3475
> do JSON comparison of old value/new value

- packages/node_modules/@node-red/nodes/core/network/10-mqtt.js
Fixes #3501
Fix typo to permit `will` v5 properties being correctly set in broker.
NOTE: this was discovered due to new MQTT tests #3497
> fix typo of will properties (properies)

- packages/node_modules/@node-red/editor-client/src/sass/colors.scss
- packages/node_modules/@node-red/editor-client/src/sass/diff.scss
While reviewing the themes, I noticed that there is currently no way to customize the colors on certain parts of the diff. This PR fixes that by adding two new SASS variables.
Before
After
> Add the ability to customize diff colors even more

- packages/node_modules/@node-red/editor-client/src/js/ui/tab-config.js
"Configuration" sidebar shows wrong tooltip for filter button "All". Fixed.
Is: `Show all unused config nodes`
Should be: `Show all config nodes`
> Fix: Sidebar "Configuration" filter button tooltip

- packages/node_modules/@node-red/editor-client/src/js/ui/deploy.js
fixes #3509
Inhibit deploy if `#red-ui-header-shade` is visible. 
This prevents a deploy shortcut from operating deploy action when an edit panel is open and the deploy button is shaded.
> Prevent shortcut deploy when deploy button shaded

- packages/node_modules/@node-red/editor-client/src/js/red.js
fixes #3453 
Modify regex from `/^[a-zA-Z]/` to `/^[@a-zA-Z]/` so that scoped package names are translated.
before...
after...
> Ensure i18n of scoped package name

- packages/node_modules/@node-red/editor-client/src/js/ui/common/searchBox.js
fixes #3491
Only show the drop down in the search menu if the search term is blank 
Fixes the issue where after you have typed something in the action bar search field & you press down to select a found item, the dropdown menu is shown! 
NOTE: this is targeted to `dev` because the addition of the dropdown menu in the action bar search field is currently in `dev` branch.
> Fix down arrow triggering menu in search box

- packages/node_modules/@node-red/editor-client/src/sass/debug.scss
- packages/node_modules/@node-red/editor-client/src/sass/popover.scss
- packages/node_modules/@node-red/nodes/core/common/21-debug.html
- packages/node_modules/@node-red/nodes/core/common/lib/debug/debug-utils.js
When hovering over a node id in the top right corner of a Debug message, this PR adds a tooltip that appears with a full hierarchy of flows/subflows/nodes to identify where the node is. All of those elements are clickable to take you to the appropriate spot.
> Add a tooltip to debug sidebar messages to reveal full path to node

- packages/node_modules/@node-red/nodes/core/network/21-httprequest.html
- packages/node_modules/@node-red/nodes/core/network/21-httprequest.js
- packages/node_modules/@node-red/nodes/locales/en-US/network/21-httprequest.html
- test/nodes/core/network/21-httprequest_spec.js
fixes #3428
* Add UI for headers
* Update built in help
* Add test - "should use ui headers"
* verifies the RULES stated below
* Modify test - "should upload a file" to use UI entry for Content-Type instead of passing it in via `msg.headers`
* If header `"FOO": "BAR"` is sent in `msg.headers` and is NOT present in the UI, then `"FOO"` is added to `req.headers`
* If header `"FOO": "BAR"` is sent in `msg.headers` and is `"FOO": "BAZ"` in the UI, then the `"FOO"` header is overwritten with `"BAZ"` in `req.headers`
* If header `"FOO": "QUX"` is sent in `msg.headers` and is `"FOO": ""` (i.e. no value) in the UI, then `"FOO"` is deleted from `req.headers`
* Header names are set in the case specified by the user
* UI Header names are Camel Case by default
* If user wants to send `content-type` …
> Add UI for Http Request node headers

- packages/node_modules/@node-red/nodes/core/network/22-websocket.js
fixes #3527
As discussed in #3527 ...
> this issue is *mostly a visual problem. (some internal state is modified by the old sockets disconnect event)
>
> I can see why this happens ...
> 
> restarting flows re-creates the node
> the newly created websocket is opened - causing the CONNECTED status
> then the previous websocket reports it has closed - causing the DISCONNECTED status
> 
>
>  ![chrome_i2GPcRyAeo](https://user-images.githubusercontent.com/44235289/163364213-d5911de8-043c-444c-9087-1e0050e5f37d.gif)
Monitor the ws `readyState` using a 20ms interval & call done() once `readyState == closed` OR a MAX of 1000ms (whichever comes first)?
e.g...
```js
node.on("close", function(done) {
node.closing = true;
node.server.close();
//wait 20*50 (1000ms max) for ws to close
const …
```
> call done after ws disconnects

- packages/node_modules/@node-red/editor-api/lib/auth/index.js
- packages/node_modules/@node-red/editor-client/src/js/user.js
Adds an option to `adminAuth` when using a `strategy` type scheme to automatically redirect the user to the required auth system rather than prompt with a dialog to click a button first.
The dialog will still get shown if there are any errors whilst handling the login.
```
adminAuth: {
type: 'strategy',
strategy: {
...
autoLogin: true,
...
}
}
```
> Allow adminAuth to auto-login users when using passport strategy

- packages/node_modules/@node-red/nodes/core/common/60-link.html
fixes #3248
* Make link call display targets both inside its own subflow and on regular flows
* Ensure link in & link out nodes on a subflow ONLY show targets inside the same subflow
* Ensure link targets inside a subflow are not displayed for link nodes on regular flows
> Display link targets of nodes in a regular flow, for Link Call nodes inside a subflow

- packages/node_modules/@node-red/editor-api/lib/auth/index.js
tldr; 
get passport strategy in verify function to allow redirects
When using an authentication provider with a single-sign-on login session like (none exclusive!) keycloak, you login once and as long as your login session is valid every auth-client get its tokens without further user interaction. To switch your identity you have to terminate your login session. 
There are two situations where this affects Node-Red as an auth-client:
1. Logout a valid user session with active editor access
To achieve a login-session termination on logout you can configure settings.editorTheme.logout.redirect to hit the logout URL and redirect back to your httpAdminRoot. See https://discourse.nodered.org/t/oauth-openid-logout-with-keycloak/57492
1. Change your identity when your current login session does …
> OAuth/OpenID logout with Keycloak - Forum 57492

- packages/node_modules/@node-red/nodes/core/common/21-debug.js
If a debug node receives a message with `msg.status = null` it causes following error:
```
TypeError: Cannot read property 'hasOwnProperty' of null
```
This PR try to fix this isseue.
> fix reference error of msg.status in debug node

- packages/node_modules/@node-red/editor-api/lib/auth/strategies.js
- test/unit/@node-red/editor-api/lib/auth/strategies_spec.js
As discussed [here](https://discourse.nodered.org/t/custom-authentication-storing-own-token/59006/4), this proposed change aims to close the loop for authentication with external APIs.
Currently:
1. You can authenticate via external API with username and password.
2. You can validate a _token_ via external API.
3. But you **can't** save your _token_ when you authenticate via external API, so you can then validate the _token_ via the same external API.
This feature adds the possibility for number 3, where you can return a _token_ with your user and it gets stored instead of the Node-RED generated _token_.
Here is an example of how to use it (this would be placed on settings.js):
```
adminAuth: {
...
authenticate: function(username,password) {
return new Promise(function(resolve) {
// Do …
```
> Feature add: Store external token when authenticate if provided

- packages/node_modules/node-red/settings.js
Set monaco as the default code editor from node-red V3
> Set monaco as default code editor as of v3.x

- packages/node_modules/@node-red/runtime/lib/index.js
- packages/node_modules/node-red/red.js
- packages/node_modules/node-red/settings.js
closes #3510
Permits single or multiple static source paths and allows each of those to be served from a different root
By adding the `httpStaticRoot` we can avoid the need for changing `httpAdminRoot` when `httpStatic` is enabled.
==========
```js
httpStatic: 'c:\\temp',
//httpStaticRoot: '/',
```
```log
22 Apr 17:05:34 - [info] HTTP Static    : c:\temp > /
```
<br>
```js
httpStatic: [{path:'c:\\temp'}, {path:'c:\\tmp'}],
httpStaticRoot: '/static_stuff/',
```
```log
22 Apr 17:05:34 - [info] HTTP Static    : c:\temp > /static_stuff/
22 Apr 17:05:34 - [info] HTTP Static    : c:\tmp > /static_stuff/
```
<br>
```js
httpStatic: [{path:'c:\\temp', root: "/stuff/"}, {path:'c:\\tmp', root: "/other/"}],
//httpStaticRoot: '/',
```
```log
22 Apr 17:05:34 - [info] HTTP Static    : c:\temp > /stuff/ …
```
> Add support for multiple static paths with optional static root

- packages/node_modules/@node-red/registry/lib/util.js
This allows a Node-RED node module (one that provides nodes) to *also* be loaded as an external module in the Function node.
For example, a module may provide a set of nodes and a library for the Function node to help work with the data those nodes produce or consume.
The fix ensures we generate the proper url for the module to take into account the `main` entry in its package.json file.
> Fix importing external module from node-red module

- packages/node_modules/@node-red/nodes/core/network/10-mqtt.js
fixes #3550
Ensure force closes a bad MQTT connection attempt & prevent late events changing the status of the node.
> Fix incorrect MQTT status

- packages/node_modules/@node-red/editor-client/src/js/ui/common/typedInput.js
- packages/node_modules/@node-red/editor-client/src/js/ui/editor.js
- packages/node_modules/@node-red/editor-client/src/js/ui/editors/buffer.js
- packages/node_modules/@node-red/editor-client/src/js/ui/editors/code-editors/ace.js
- packages/node_modules/@node-red/editor-client/src/js/ui/editors/code-editors/monaco.js
- packages/node_modules/@node-red/editor-client/src/js/ui/editors/expression.js
- packages/node_modules/@node-red/editor-client/src/js/ui/editors/js.js
- packages/node_modules/@node-red/editor-client/src/js/ui/editors/json.js
- packages/node_modules/@node-red/editor-client/src/js/ui/editors/markdown.js
- packages/node_modules/@node-red/editor-client/src/js/ui/editors/panes/description.js
- packages/node_modules/@node-red/editor-client/src/js/ui/editors/panes/flowProperties.js
- packages/node_modules/@node-red/editor-client/src/js/ui/editors/text.js
- packages/node_modules/@node-red/editor-client/src/js/ui/projects/projectSettings.js
- packages/node_modules/@node-red/editor-client/src/js/ui/tray.js
- packages/node_modules/@node-red/nodes/core/function/10-function.html
- packages/node_modules/@node-red/nodes/core/function/80-template.html
Discussed here:  https://discourse.nodered.org/t/suggestion-of-enhancements-for-the-template-and-function-nodes/61704
* Save and restore editor state 
* selection(s), cursor(s), scroll pos etc
* Improve focusing of editor at appropriate times
* e.g. switching tabs, returing from expanded editor
* Works with both ace and monaco
* Backwards compatible and (almost) fully functional with existing contrib nodes that use the NR Editor APIs
* not all improvements are possible without slight tweak of contrib node but most do
1. A `stateId` is generated for each editor instance based on various factors (primarily the node.id & edit mode (and its dom position if there are more than one)
2. The state of the editor is stored against the `stateId` in a global object as required (on blur, on close etc) …
> Code editor ux improvements around remembering state of each code editor in a flow

- packages/node_modules/@node-red/nodes/core/storage/10-file.html
- packages/node_modules/@node-red/nodes/core/storage/10-file.js
- packages/node_modules/@node-red/nodes/locales/en-US/storage/10-file.html
- test/nodes/core/storage/10-file_spec.js
As discussed on forum: https://discourse.nodered.org/t/dynamically-passing-msg-filename-from-watch-node-into-file-in-node/61011/15
* use typedInput for file nodes to reduce the confusion around whether the field should be blank or contain filename to use `msg.filename`
NOTE: I have deliberately excluded `flow.` and `global.` from the typed input as I suspect it would lead to confusion.
* continue to operate as per v2 - see demo below
* To auto upgrade file nodes to use the typedInput when opened -  see demo below
* update tests to cover new properties 
* The existing tests are all passing:  `√ 195 tests are passing (22s)`
> Feature: Change basic Filename field to a typedInput 

- packages/node_modules/@node-red/editor-client/src/sass/ui/common/typedInput.scss
Closes the gap between the borders by increasing the border-radius on .red-ui-typedInput-container from 4px to 5px.
Fixes #3548
> Fix gap between typedInput containers borders

- packages/node_modules/@node-red/editor-client/src/sass/colors.scss
- packages/node_modules/@node-red/editor-client/src/sass/tab-config.scss
Based on #3270 and the discussion in #3555, it seems to be a better option to prevent themes from changing the colors of configuration nodes. This PR does that.
> Don't let themes change node config colors

- packages/node_modules/@node-red/nodes/core/network/10-mqtt.html
- packages/node_modules/@node-red/nodes/core/network/10-mqtt.js
- test/nodes/core/network/21-mqtt_spec.js
closes #3557
1. Validate topics in client side
1. Validate topics in runtime
1. Required some de-duplication & re-arranging of code in `doPublish` and `node.publish`
2. This was necessary as the existing code for checking a topic at runtime was in `doPublish` but was required for both `doPublish` and `node.publish`.  
**NOTE:** All code in  `doPublish()` was originally inside the MQTT OUT `on("input", ...` event but was refactored to `doPublish()` when the Dynamic MQTT was under design. If you recall, there was a design note for the MQTT IN node (when in dynamic mode) to ALSO perform a publish. So the code was refactored to be called by both the MQTT IN (via the `action` property) and of-course the MQTT OUT.  When we dropped the `publish` `action`, it made little sense to revert the …
> Add client and Runtime MQTT topic validation and fix subsequent connection lockup (that arises due to bad birth/will topic)

- packages/node_modules/@node-red/editor-client/locales/de/editor.json
- packages/node_modules/@node-red/editor-client/locales/en-US/editor.json
- packages/node_modules/@node-red/editor-client/locales/ja/editor.json
- packages/node_modules/@node-red/editor-client/locales/ko/editor.json
- packages/node_modules/@node-red/editor-client/locales/ru/editor.json
- packages/node_modules/@node-red/editor-client/locales/zh-CN/editor.json
- packages/node_modules/@node-red/editor-client/locales/zh-TW/editor.json
- packages/node_modules/@node-red/editor-client/src/js/red.js
- packages/node_modules/@node-red/editor-client/src/js/ui/deploy.js
As discussed here: https://discourse.nodered.org/t/flows-stopped-due-to-missing-node-types-a-feature-suggestion-to-help/61995
Adds buttons...
* "Search unused config nodes",
* "Search for unknown nodes",
* "Search for invalid nodes",
* Look at last two screenshots. 
* 3. has no primary accent (white) on the <kbd>close</kbd> button (this is original condition)
* 4. has primary accent (red) on the <kbd>close</kbd> button (this is new - this notification never had a close button)
* **Which is preferable?**
* When clicking the "Search for xxxxx" should the notification close or remain open?
> Add "search for" buttons to notifications

- packages/node_modules/@node-red/runtime/lib/api/diagnostics.js
Calling `show-system-info` action causes ` TypeError: Cannot convert undefined or null to object` if `contextStorage` is not defined in settings.  This PR tries to fix the issue.
> fix error on system-info action

- packages/node_modules/@node-red/editor-client/src/js/ui/view.js
fixes #3587
Ensure `sourcePort` is not undefined when linking from a regular nodes INPUT, backwards to a junction. 
Where it was falling down was in `addLink` [here](https://github.com/node-red/node-red/blob/b918b75414fb9a393a19c3f8b6a539b19fd0a62d/packages/node_modules/@node-red/editor-client/src/js/nodes.js#L610-L620) because `sourcePort`  of the junction node was undefined, this `isUnique` test considered it unique & returned without linking.
```js
if (nodeLinks[l.source.id]) {
const isUnique = nodeLinks[l.source.id].out.every(function(link) {
return link.sourcePort !== l.sourcePort || link.target.id !== l.target.id
})
if (!isUnique) {
return  //<< HERE
}
}
```
The fix chosen was to ensure `sourcePort` is set to `0` [here](https://github.com/node-red/node-red/blob/b918b75414fb9a393a19c3 …
> Fix junction: when wiring from a regular nodes INPUT, backwards to a junction

- packages/node_modules/@node-red/editor-client/src/js/ui/editors/json.js
- packages/node_modules/@node-red/nodes/99-sample.html.demo
- packages/node_modules/@node-red/nodes/core/function/10-switch.html
- packages/node_modules/@node-red/nodes/core/network/21-httpin.html
- packages/node_modules/@node-red/nodes/core/sequence/17-split.html
While I was translating the message catalog, I found that some icon paths are png.
To avoid path confusion in reusing code, I changed the file path from png to svg.
> Fix image paths where `red/image/typedInput/XXXX.png` should be `red/image/typedInput/XXXX.svg`

- packages/node_modules/@node-red/editor-client/src/js/nodes.js
fixes #3588
Ensure lookup objects `junctions` and `junctionsByZ` inside the closure `RED.nodes` are cleared to prevent the "Duplicate Nodes" warning (as seen in #3588) and permit the flows to be loaded in the editor.  This fixes a compound issue when loading projects that due to there being no flow loaded client side, the incoming debug messages cannot lookup the "flow tab" name & thus cause a secondary error in `23-debug.html` where inside `this.handleDebugMessage()` an exception occurs.
We might want to add try/catch handlers on the new code inside `handleDebugMessage()` - something like...
```js
if (o.path && RED.workspaces.count()) { //<<< check workspaces are present
// Path is a `/`-separated list of ids that identifies the
// complete parentage of the node that generated this …
```
> Fix project switching when junctions are present

- packages/node_modules/@node-red/editor-client/src/js/ui/view.js
- packages/node_modules/@node-red/editor-client/src/sass/flow.scss
The first iteration of Junctions were drawn as a single blob. The mouse interactions with that blob had to handle both moving and wiring. That led to it behaving node-like in some cases (click-drag to move) and port-like in others (ctrl-click to start wiring). But it also meant there was a bunch of half-duplicated code to reproduce those behaviours as needed.
Based on feedback on 3.0.0-beta.1, this PR changes Junctions to be more consistent in their UX. An added benefit is a lot of junction-specific logic could be removed and the existing node/port event handles reused (with a couple minor special cases for Junctions).
With this PR:
- the appearance of a junction changes when you hover over it to reveal a more familiar node+port arrangement (albeit still at a smaller scale)
- The ports …
> Rework Junctions to be more node like in their event handling

- packages/node_modules/@node-red/editor-client/src/js/ui/view.js
The slice-junction action should not apply to link node virtual wires.
The slice action does apply as it is a valid way to delete virtual wires.
> Do not slice-junction link node wires

- packages/node_modules/@node-red/nodes/core/common/lib/debug/debug-utils.js
- packages/node_modules/@node-red/nodes/locales/en-US/messages.json
- packages/node_modules/@node-red/nodes/locales/ja/messages.json
In debug sidebar, `node` label of an output debug node id is not i18n-ed. 
This PR make it i18n ready and updates English/Japanese message catalogues.
> i18n debug sidebar node label

- packages/node_modules/@node-red/nodes/core/network/10-mqtt.js
fixes #3625 
In circumstances where WS connection is use and a proxy is defined and the address matches a noproxy entry, it can cause an exception
Declare `noproxy` variable
> MQTT Node: define noproxy variable

- packages/node_modules/@node-red/nodes/core/network/31-tcpin.js
fixes #3619 
It looks like on some systems and certain conditions, both the `error` and `close` event handers are operating causing the code to (try to) remove the socket twice.  Since it is an array and uses the `splice` method, it can end up removing more that the problem socket
Change `connectedSockets` from an `array` to a `Set` to better manage the connections
> Dont delete TCP socket twice

- packages/node_modules/@node-red/editor-client/src/js/ui/view.js
A node dragged from the palette can be placed halfway out of the workspace.
Since the movement of nodes within the workspace is designed to fit within the workspace, this PR change the dragged node placed within the workspace.
> Fix to place a node dragged from palette within the workspace

- packages/node_modules/@node-red/editor-client/src/sass/palette.scss
When dragging a node from the palette into the workspace, the node is displayed below the tab label as shown below.
> Fix layer of palette node

- packages/node_modules/@node-red/util/lib/util.js
- test/unit/@node-red/util/lib/util_spec.js
If inject node is configured to inject buffer with value `12`, it causes following error:
```
TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received type number (12)
```
This message is difficult to understand for users. 
This PR try to make it more understandable.
> fix buffer parse error message of evaluateNodeProperty

- packages/node_modules/@node-red/editor-client/src/js/ui/common/tabs.js
Tooltip for tab name is displayed without sanitization as shown below.
This PR try to fix this issue.
> Fix to sanitize tab name

- packages/node_modules/@node-red/registry/lib/externalModules.js
Fixes #3627
Uses `module.createRequire` to properly resolve both CJS and ESM module import paths.
> Fix ESM module loading in Function node

- packages/node_modules/@node-red/editor-client/src/js/ui/palette.js
Subflow category name with special characters  (e.g. @ABC) causes editor runtime error because it is used to create CSS ID.
> Fix to extend escaped subflow category characters

- packages/node_modules/@node-red/editor-client/src/sass/base.scss
Fixed https://github.com/node-red/node-red/issues/3648. The `z-index` of the nodes in the palette is currently `4`. Therefore, the `z-index` of the shade should have `5` or more (The maximum value seems to be `9`).
> Fix z-index value for shade to cover nodes in palette

- packages/node_modules/@node-red/editor-client/src/js/history.js
- packages/node_modules/@node-red/editor-client/src/js/nodes.js
- packages/node_modules/@node-red/editor-client/src/js/ui/subflow.js
[This PR](https://github.com/node-red/node-red/pull/3652) solves the problem of converting Junction node to SUBFLOW.  
However, this conversion cannot be undone. 
This PR attempts to solve the issue.
> Fix undoing junction to subflow

- packages/node_modules/@node-red/editor-client/src/ace/mode/nrjavascript_worker.js
fixes #3610 in v2.x
backports: Ensure ACE worker options are set #3611
> Ensure ACE worker options are set (Backport 3611 to v2.x)

- packages/node_modules/@node-red/editor-client/src/js/ui/palette.js
Manually implements @HiroyasuNishiyama commit 30d88bbe7efcbf72519e18bbbca246de6a5e0484 (cherry-pick not possible)
> Fix to extend escaped subflow category characters (backport #3647 to v2.x)

- packages/node_modules/@node-red/nodes/core/function/10-function.html
Initial cursor position of on star/on stop tab of function node is beginning of second line.
This is middle of comment and not appropriate for inserting code.
This PR changes the cursor position to the beginning of last line.
> Fix initial cursor position of init/finalize tab of function node

- Gruntfile.js
- packages/node_modules/@node-red/editor-client/src/js/ui/actions.js
- packages/node_modules/@node-red/editor-client/src/js/ui/common/menu.js
- packages/node_modules/@node-red/editor-client/src/js/ui/common/popover.js
- packages/node_modules/@node-red/editor-client/src/js/ui/contextMenu.js
- packages/node_modules/@node-red/editor-client/src/js/ui/typeSearch.js
- packages/node_modules/@node-red/editor-client/src/js/ui/utils.js
- packages/node_modules/@node-red/editor-client/src/js/ui/view-tools.js
- packages/node_modules/@node-red/editor-client/src/js/ui/view.js
- packages/node_modules/@node-red/editor-client/src/sass/dropdownMenu.scss
Adds a right-click context menu to the workspace - making a number of actions more accessible.
The menu is selection-aware - so shows options relevant to the current selection (group/ungroup for eg).
There's a bit more work around i18n to handle - but propose to do that post beta.3
> Right click menu

- packages/node_modules/@node-red/editor-client/src/js/ui/common/treeList.js
- packages/node_modules/@node-red/editor-client/src/js/ui/editors/json.js
Fixes #3682
The treeList keyboard handling was consuming the event - used
to select the item in the list.
The fix here adds a 'selectable' flag on the treeList that can
be used to disabled (=false) the keyboard selection of items.
> Fix handling of spacebar inside JSON visual editor

- packages/node_modules/@node-red/editor-client/src/js/ui/editors/code-editor.js
- packages/node_modules/@node-red/runtime/lib/api/settings.js
In an earlier PR we changed the default settings.js to specify monaco. With this PR, we now default to monaco if the settings file doesn't specify anything.
> Set default editor to monaco in absence of user preference

- packages/node_modules/@node-red/editor-client/src/sass/search.scss
fixes #3568
Increase quick-add height from 150px to 195px to reveal 2 most recent entries
> Increase quick-add height to reveal 2 most recent entries

- packages/node_modules/@node-red/editor-client/src/sass/tab-config.scss
fixes #3572
* Use `$node-port-background` for config node background (this seems to make sense since it should contrast the `$node-port-label-color` used already for icon text)
* Only show pointer if node icon has count
> Use solid colour as config node icon background to hide text overflow

- packages/node_modules/@node-red/editor-client/src/js/ui/view-tools.js
- packages/node_modules/@node-red/editor-client/src/js/ui/view.js
- packages/node_modules/@node-red/nodes/core/common/21-debug.html
- packages/node_modules/@node-red/nodes/core/common/60-link.html
- packages/node_modules/@node-red/nodes/core/function/10-function.html
fixes #3701
Ensures undo after dropping a debug/function/link onto workspace results in a clean (`!dirty`) workspace
* When creating a new node (`createNode()`), get workspace `dirty` state BEFORE generating the node
* ensure `generateHistory` is false for `onadd()` calls in debug, link and function nodes
* ensure `generateNodeNames` options are merged (not overwritten)
* correct JSDoc for `generateNodeNames`
> Ensure workspace clean after undoing dropped node

- packages/node_modules/node-red/settings.js
Leave Monaco theme commented out by default.
If it’s commented out and a theme doesn’t have it defined, it defaults to that same value anyway.
And themes that define it won't have to request the user to comment it out in settings.js to have their customizations loaded.
> Leave Monaco theme commented out by default

- packages/node_modules/@node-red/nodes/core/function/80-template.js
- test/nodes/core/function/80-template_spec.js
This feature adds template node be able evaluate env variables within the mustache template.
It solves adding intermediate change node which is the goto solution.
Very useful in subflow to evaluate the subflow properties.
> Add support for evalulating {{env.<var>}} within a template node

- packages/node_modules/@node-red/nodes/core/sequence/17-split.js
see https://discourse.nodered.org/t/no-response-object-after-split-join/63919
When in reduce mode the join node currently creates a new msg rather than re-using the existing one - which then drops things like any msg.res from a http request. This patch tries to fix that.
> Join node in reduce mode doesn't keep existing msg properties

- packages/node_modules/@node-red/nodes/core/parsers/70-CSV.js
- test/nodes/core/parsers/70-CSV_spec.js
and add tests
As pointed out here - https://discourse.nodered.org/t/csv-string-values-containing-new-lines/64437
the CSV node does not escape any strings that contain \n within hem when outputting to csv file. 
This fix wraps the field in " so that they can then be imported into excel etc.
> Fix CSV node to handle \n when outputting text fields

- package.json
- packages/node_modules/@node-red/nodes/core/common/60-link.js
- test/nodes/core/common/60-link_spec.js
fixes #3694
depends on node-red-node-test-helper@0.3.0
Discussed here: https://node-red.slack.com/archives/C9RSU6S56/p1655726225125419 
* Ensures registered nodes are removed from the cache to avoid the "Multiple nodes with name" error
* Adds a suitable test that loads a flow with 2 link nodes named the same then deploys a name change
NOTE: Depends on [node-red-node-test-helper@0.3.0 #54](https://github.com/node-red/node-red-node-test-helper/pull/54) being merged and published
> Ensure link-call cache is updated when link-in is modified

- packages/node_modules/@node-red/editor-client/src/js/ui/editors/envVarList.js
If a typedInput-style environment variable input item of subflow template is defined with credential as default type, it changes to credential-style input item.
**Steps to reproduce:**
1. Create a subflow
2. Open subflow template properties edit panel.
3. Add an environment variable.
a. Set  "input type" of the variable to "input" with "credential" selected,
b. Change default value type to "credential".
4. Re-open subflow template properties edit panel.
5. "input type" of the variable changes to "credential".
> Fix credential type input item of subflow template

- packages/node_modules/@node-red/editor-client/src/js/nodes.js
fixes #3722
double check `options.importMap` is "something" to prevent exception
> Ensure importMap is not null when using import UI

- packages/node_modules/@node-red/editor-client/src/js/ui/contextMenu.js
This PR updates the context menu handling of 'add junction' to address some feedback from the beta:
- 'Insert -> Junction' is now available in more cases. When nothing is selected, it inserts a bare junction in the workspace. When only nodes are selected, the junction option is disabled. If wires are selected (ignoring any nodes) the junctions are inserted
- The positioning of the Inject -> Node quick add dialog is now accounts for snapToGrid and whether the workspace is scrolled.
> Update add-junction menu to work in more cases

- packages/node_modules/@node-red/editor-api/lib/editor/theme.js
- test/unit/@node-red/editor-api/lib/editor/theme_spec.js
We didn't do a complete enough job of defaulting to monaco. If the settings.js file doesn't contain a `codeEditor` entry, the editor will default to monaco, but the runtime will not have ensured the monaco library was loaded by the editor.
> Fix defaulting to monaco if settings does not contain codeEditor

- packages/node_modules/@node-red/editor-client/src/sass/tab-config.scss
This is another attempt to fix the issue raised in #3572.
As-Is (3.0.0-beta.4):
To-Be:
> Fix label overflow @ config-node palette

- packages/node_modules/@node-red/nodes/core/common/21-debug.html
Global debug message causes editor runtime error.
**Steps to reproduce**:
1. Import web socket node example and deploy it,
2. Delete the imported flow,
3. Re-Deploy,
4. (3) causes `Error: stopping node: Close timed out`,
5. (4) results in editor runtime error `TypeError: Cannot read properties of undefined`.
> fix handling of global debug message

- packages/node_modules/@node-red/nodes/core/network/22-websocket.js
Re-deploying a flow containing web socket node causes `Error stopping node: Close timed out`.
**Steps to reproduce**:
1. Import web socket node example and deploy it,
2. Delete the imported flow,
3. Re-Deploy,
4. (3) causes `Error: stopping node: Close timed out`,
> Fix close timeout of websocket node

- packages/node_modules/@node-red/editor-client/src/sass/colors.scss
- packages/node_modules/@node-red/editor-client/src/sass/tab-config.scss
- packages/node_modules/@node-red/editor-client/src/sass/variables.scss
While testing the changes from #3730, I noticed that I left disabled config nodes out of #3564.
This PR fixes that by using the same background color as in the default theme.
> Don't let themes change disabled config node background color

- packages/node_modules/@node-red/editor-client/src/js/ui/view.js
Fixes #3629
After cutting a flow to the clipboard, we shouldn't generate new ids when it gets pasted. This ensures any nodes that were targeting the cut nodes (link-call, catch etc) still target the nodes after they are pasted.
When pasting a flow that was *copied* to the clipboard, we still generate ids as before.
This feels a more expected behaviour.
> Do not generate new node-ids when pasting a cut flow

- packages/node_modules/@node-red/editor-client/src/js/ui/contextMenu.js
fixes #3739 
[Fix insert=>link nodes enable/disable state](https://github.com/node-red/node-red/commit/eaa85ae8d505d259d8b346ba0e9cd705c521ba34)
[Allow escape key to close context menu](https://github.com/node-red/node-red/commit/03f758720cbcacabb8aa13ee95d9b814b26e878c)
[Allow editor events to close context menu](https://github.com/node-red/node-red/commit/21d3261eecea2889699ef08410f4b805796d2df4)
[code linting and remove excessive new lines](https://github.com/node-red/node-red/commit/7216c6d62a2f8420d1524772a9e5907398bebe6c)
> Fix context menu issues ready for v3 beta.5

- packages/node_modules/@node-red/editor-client/src/js/ui/view.js
fixes #3740 (Uncaught TypeError error in browser console when deleting nodes from canvas)
Check that node exists inside the timer callback - before attempting to generate a tooltip and calculate offsets etc.
> prevent exception generating tooltip for deleted nodes

- packages/node_modules/@node-red/nodes/core/common/lib/debug/debug-utils.js
Selecting `Clear pinned paths` of debug sidebar item menu for global message causes editor runtime error.
```
debug-utils.js:468 Uncaught TypeError: activeMenuMessage.clearPinned is not a function
at Object.onselect (debug-utils.js:468:43)
at f (red.min.js?v=3.0.0-beta.4:18:47386)
at HTMLAnchorElement.<anonymous> (red.min.js?v=3.0.0-beta.4:18:46029)
at HTMLAnchorElement.dispatch (vendor.js?v=3.0.0-beta.4:2:43090)
at v.handle (vendor.js?v=3.0.0-beta.4:2:41074)
```
> Fix clear pinned paths of debug sidebar menu

- packages/node_modules/@node-red/editor-client/src/js/ui/contextMenu.js
- packages/node_modules/@node-red/editor-client/src/sass/dropdownMenu.scss
- packages/node_modules/@node-red/editor-client/src/sass/header.scss
This PR includes #3744 - adding a fix for the positioning of the menu caret icon for dropdown menus that pull left.
> Fix display direction of context sub-menu

- packages/node_modules/@node-red/editor-client/src/js/ui/view-tools.js
fixes #3747
include dirty state in history event
> include dirty state in history event

- packages/node_modules/@node-red/nodes/core/function/15-change.js
Fix a typo introduced in https://github.com/node-red/node-red/pull/2822 that breaks using context to replace a value.
The bug can be replicated with the following minimalist flow :
```JSON
[{"id":"906bd15b.bf1a5","type":"change","z":"40930c8d.9ea28c","name":"","rules":[{"t":"set","p":"prefix","pt":"flow","to":"myFilePrefix/","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":560,"y":1160,"wires":[["98a5ca24.feff1"]]},{"id":"98a5ca24.feff1","type":"change","z":"40930c8d.9ea28c","name":"","rules":[{"t":"change","p":"filename","pt":"msg","from":"prefix","fromt":"flow","to":"","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":760,"y":1160,"wires":[["3341cce4.c0dc14"]]},{"id":"9ef6ce5a.decc","type":"inject","z":"40930c8d.9ea28c","name":"specific …
```
> Fix change node, not handling from field properly when using context

- packages/node_modules/@node-red/editor-client/src/js/ui/subflow.js
Fixes #3749
If a subflow property has a UI defined with multiple types, including credential - the value is lost if the type is set to credential. This fix ensure the value does not get lost.
> Fix storing subflow credential type when input has multiple types

- packages/node_modules/@node-red/editor-client/src/js/ui/view.js
- packages/node_modules/@node-red/editor-client/src/sass/palette.scss
This PR extends the work done in #3756 to ensure the node icon shade has properly rounded corners.
See #3755 for the original issue
> Ensure node icon shade has properly rounded corners

- packages/node_modules/@node-red/editor-api/lib/editor/theme.js
* Permit a theme plugin to specify `header` and `page` values
* Only use theme `page` and `header` values if `settings.js` values are not present
* If neither are present, then NR defaults are used (as per v2.x)
* If settings.js values are present, use them (as per v2.x)
| settings.js | theme | Results in... |
| - | - | - |
| `page.favicon = null` | `page.favicon = null` | uses default NR favicon | 
| `page.favicon = null` | `page.favicon = 'common/favicon.ico'` | uses theme favicon | 
| `page.favicon = 'custom-icon.ico'` | `page.favicon = 'common/favicon.ico'` | uses settings.js custom favicon | 
| . | . | . |
| `page.title = null` | `page.title = null` | uses default NR title | 
| `page.title = null` | `page.title = 'theme title'` | uses theme title | 
| `page.title = 'settings.js …
> Use theme page and header values if settings.js values are not present

- packages/node_modules/@node-red/editor-client/src/js/ui/contextMenu.js
- packages/node_modules/@node-red/editor-client/src/js/ui/view-tools.js
fixes #3765
* [Ensure only wire links are split with junctions/links](https://github.com/node-red/node-red/commit/e2f42fddb5afa66e57dacb043fd8b581eb09075f)
* [fix context menu insert junc/links enabled state](https://github.com/node-red/node-red/commit/c648e1e8d621fd79e1494c921fe57c379e6ffc5a)
* [Ensure added junc(s) are selected](https://github.com/node-red/node-red/commit/75d3444391306155aaa3655e39f92a184bf77c53)
* Feature parity with "Add Node" "Split wires with links" etc
> Fix "split with" on virtual links

- packages/node_modules/@node-red/editor-client/src/js/ui/view.js
Fixes #3778
Whilst all major browsers support Object.hasOwn, it is realistically a bit too new. We are getting too many issues with users on slightly out of date browsers - such as those included in LTS OS releases.
Given we only use it in one place, and is easily replaced, it is better to remove it than require browser upgrades.
> Remove use of Object.hasOwn

- packages/node_modules/@node-red/editor-client/src/js/ui/typeSearch.js
The change in 3.0 to make the Quick Add dialog taller didn't get carried through to the code that repositions the menu if it goes off the bottom of the screen. As a result, it was covering the ghost node.
This PR adds the additional height into the calculations
> Ensure quick-add dialog does not obscure ghost node when shifted

- packages/node_modules/@node-red/editor-client/src/js/ui/contextMenu.js
- packages/node_modules/@node-red/editor-client/src/js/ui/view.js
Fixes #3781
This properly takes into account both scroll and scale of the workspace when positioning the quick-add dialog.
This applies both to the Ctrl-Click opening of the dialog, and when it is opened via the context menu.
> Properly position quick-add dialog in all cases

- packages/node_modules/@node-red/editor-client/src/js/ui/search.js
Fixes #3777
Sometimes it is valid to have a config node that is "unused" - such as the `ui_base` node from Dashboard.
Such nodes can set a property called `hasUsers` to `false` in their definition. This stops the Configuration Nodes sidebar from showing them as unused, and for the unused-nodes check to flag them after a deploy.
This fix updates the search filter `is:unused` to take the flag in to account.
> Do not flag hasUsers=false nodes as unused in search

- packages/node_modules/@node-red/editor-client/src/js/ui/common/typedInput.js
Fixes #3780
Otherwise they act as type="submit" and the browser will click on them when enter is pressed in an input
> Ensure all typedInput buttons have button type set

- packages/node_modules/@node-red/editor-client/src/js/red.js
- packages/node_modules/@node-red/editor-client/src/js/ui/contextMenu.js
- packages/node_modules/@node-red/editor-client/src/js/ui/editor.js
fixes #3783
1. [ensure red-ui-editor-stack is focusable](https://github.com/node-red/node-red/commit/7c5413e568eab28c1fe892c51e39557492cbaaef)
2. [focus stack when re-showing nested editor](https://github.com/node-red/node-red/commit/1b53b5b92792b714600869f5d0b8822f1e140079)
3. [focus search input when opened via context menu](https://github.com/node-red/node-red/commit/273404e24df2ca863ef7397a82cc1b344fed50ac)
> Fix focus issues

- packages/node_modules/@node-red/editor-client/src/js/ui/editors/code-editors/monaco.js
fixes #3774
If `options.mode` and `options.title` are missing, ensure the suffix argument of `RED.editor.generateViewStateId` is something.
This permits creating an editor with minimal options.
NOTE: the user should ALWAYS provide an `options` object with the target `element`. In not doing so, the `monaco` editor has no idea where to display the editor.  As a level of compatibility to earlier node-red versions (and to prevent an exception), a hidden element will be auto generated in the event of `options` or `options.element` being missing (and a warning will be generated in the browser indicating this) but the UI will not see the editor.
> Allow `mode` and `title` to be omitted in `options` argument for `createEditor`

- packages/node_modules/@node-red/runtime/lib/api/diagnostics.js
- test/unit/@node-red/runtime/lib/api/diagnostics_spec.js
fixes #3771
* [include flows stop/start state](https://github.com/node-red/node-red/commit/af4f07cb263f98d27ed424fca48a3eb1212afa6a)
* Include flows run / stop state in the report 
* This differs from the existing `runtime.isStarted` (which is true if the runtime is finished initialising)
* [add a handful of missing settings to basic report](https://github.com/node-red/node-red/commit/a4d66622a5130728e5391e0478db8fa6746e4d45)
* Opportunistic chance to add a few missing items that are (functionally) inconsequential but useful for diagnostics
* I can remove from PR if you prefer these to be in 3.1.0
> Sys info (diagnostics report) amendments

- packages/node_modules/@node-red/editor-api/lib/editor/theme.js
fixes #3779
[Allow codeEditor theme to be set even if `codeEditor` is not set in settings.js](https://github.com/node-red/node-red/commit/bc7852c1cc0889ec9f4686d0efca00592a99a0d0)
> Allow codeEditor theme to be set even if `codeEditor` is not set in settings.js

- packages/node_modules/@node-red/editor-client/src/js/nodes.js
- packages/node_modules/@node-red/editor-client/src/js/ui/subflow.js
Fixes #3805
Exporting subflows did not properly include junctions or groups - which would break things when reimporting.
This also tidies up logic around removing junctions when a subflow definition or flow is deleted.
> Include junctions/groups when exporting subflows plus related fixes

- packages/node_modules/@node-red/runtime/lib/flows/util.js
Fixes #3798
When creating a subflow module instance, we would create the Subflow object then start it before returning back to the parent Flow. However, starting the subflow requires all of its nodes being started - which could involve node lookups (eg `mqtt in` node calling `RED.nodes.getNode()` to get ahold of its broker node. For that type of node lookup to work, the flow needs to know the subflow module instance exists - but as that is being done as part of the start code which happens *before* the parent flow knows about it, the lookups will fail.
This PR fixes it by getting the subflow instance registered with the parent Flow before the instance gets started. It isn't the most beautiful fix as the Flow's view of subflow instances should not be externally modifiable like this... but …
> Register subflow module instance node with parent flow

- packages/node_modules/@node-red/editor-client/src/js/ui/common/editableList.js
- packages/node_modules/@node-red/editor-client/src/js/ui/tab-help.js
- packages/node_modules/@node-red/editor-client/src/js/ui/tab-info.js
- packages/node_modules/@node-red/editor-client/src/sass/debug.scss
- packages/node_modules/@node-red/editor-client/src/sass/editor.scss
- packages/node_modules/@node-red/editor-client/src/sass/projects.scss
- packages/node_modules/@node-red/editor-client/src/sass/tab-context.scss
- packages/node_modules/@node-red/editor-client/src/sass/userSettings.scss
As I mentioned on Slack, most sidebar panels show scrollbars even when they're not needed. This PR changes that by hiding the scrollbars until the content overflows.
Tested on a Mac in Chrome, Safari, and Firefox.
> Hide scrollbars until they're needed

- packages/node_modules/@node-red/editor-client/src/js/ui/view-tools.js
Fixes #3813
Handles names that contain things like `+` by escaping them.
> Allow generateNodeNames to handle names containing regex control chars

- packages/node_modules/@node-red/editor-client/src/js/ui/editors/colorPicker.js
- packages/node_modules/@node-red/editor-client/src/js/ui/editors/panes/appearance.js
- packages/node_modules/@node-red/editor-client/src/js/ui/group.js
To solve the situation in #3800, I submitted this pull request.
> Support color reset to the default in subflow and group

- packages/node_modules/@node-red/editor-client/src/sass/workspace.scss
While investigating why there is a gray bar at the bottom of the workspace chart, I noticed that the horizontal scrollbar is partially overlapped by the footer.
It happens because the current value for the bottom property doesn't seem to consider the width of the workspace footer border.
This PR fixes that.
> Fix workspace chart bottom property

- packages/node_modules/@node-red/nodes/core/network/21-httprequest.html
- packages/node_modules/@node-red/nodes/core/network/21-httprequest.js
- packages/node_modules/@node-red/nodes/locales/en-US/messages.json
Allow the relaxing of HTTP Header parsing
potential fix for #3772
Need to think about how to add tests for "broken" headers when using express as the test http server
> Allow HTTP Headers not in spec

- packages/node_modules/@node-red/nodes/core/network/06-httpproxy.html
- packages/node_modules/@node-red/nodes/core/network/21-httpin.html
- packages/node_modules/@node-red/nodes/core/network/21-httprequest.html
I added the options to make the list sortable on the property UI of the http request and http response nodes.
We discussed this new functionality on the following Node-RED forum.
https://discourse.nodered.org/t/sortable-list-in-the-header-area-of-the-http-request-node/67076
> Support sortable list on property UI of http request and http response nodes

- packages/node_modules/@node-red/nodes/core/network/10-mqtt.js
- test/nodes/core/network/21-mqtt_spec.js
fixes #3838 
Ensure MQTT v5 `options.property.sessionExpiryInterval` is set if configured in UI or passed in as an option with the "connect" action
NOTE: This PR also addresses some existing issues with the local MQTT tests namely...
* `done` being called more than once
* MQTT `birth` being published BEFORE `connect` is complete, making it impossible to test birth msg correctly
```
MQTT Nodes
√ should be loaded and have default values (MQTT V4) (108ms)  << modified to check MQTT v5 properties are not present
√ should be loaded and have default values (MQTT V5)  << new test to check MQTT v5 properties are present
√ basic send and receive tests (64ms)
√ should send JSON and receive string (auto mode)
√ should send JSON and receive object (auto-detect mode) (43ms)
√ should send invalid JSON …
```
> ensure sessionExpiry(Interval) is applied

- packages/node_modules/@node-red/editor-client/src/vendor/jsonata/formatter.js
While editing JSONata, monaco editor do not show `$clone` as an candidate for completion.
> Add $clone as supported function

- packages/node_modules/@node-red/nodes/core/network/10-mqtt.js
fixes #3865
ensure `done` is present otherwise call `node.error`
NOTE: upon connect, when a birth message is sent, the context in which execution arrives at the `done` call is from within the callback of the MQTT client connect (not within the context the node-red node) meaning there is no `done` callback to call.
> Prevent invalid mqtt birth topic crashing node-red

- packages/node_modules/@node-red/editor-client/src/js/ui/projects/projects.js
The following radio button to select enable or disable encryption in the project dialog is not checked as the default. Therefore, I make the first one marked as the default by this pull request.
> Check radio button as default in project dialog

- packages/node_modules/@node-red/editor-client/src/js/ui/projects/projects.js
- packages/node_modules/@node-red/nodes/core/common/24-complete.html
- packages/node_modules/@node-red/nodes/core/common/25-catch.html
- packages/node_modules/@node-red/nodes/core/common/25-status.html
- packages/node_modules/@node-red/nodes/core/function/10-function.html
- packages/node_modules/@node-red/nodes/core/function/80-template.html
- packages/node_modules/@node-red/nodes/core/network/05-tls.html
The project feature dialog has the same issue as https://github.com/node-red/node-red/pull/3788.
After pressing the enter key in the above area, the UI to add the SSH key emerges incorrectly.
In this pull request, I added the `button` type into the button to avoid the issue.
> Add button type to the adding SSH key button

- packages/node_modules/@node-red/editor-client/src/js/ui/editors/code-editors/monaco.js
- packages/node_modules/@node-red/editor-client/src/types/node-red/func.d.ts
fixes #3851
`util` and `promisify` are added into the server side function node `vm` but the monaco environment did not recognise these variables and did not offer type hints etc.
This PR adds them to the type d.ts file & pre-loads the `util` module
> add function node monaco types util and promisify

- packages/node_modules/@node-red/nodes/core/function/10-function.html
In the external modules UI of the function node, the variable name is automatically converted to fit JavaScript code. In this UI, I found that it cannot handle module names including a dot. For example, `fft.js` is not converted but it should be `fftJs` to use in JavaScript code.
In this pull request, I added the change to support converting dot.
> Remove dot from variable name for external module in function node

- packages/node_modules/@node-red/editor-client/locales/en-US/editor.json
- packages/node_modules/@node-red/editor-client/locales/ja/editor.json
- packages/node_modules/@node-red/editor-client/src/js/ui/editors/expression.js
Current JSONata editor reports extended functions `$flowContext` and `$globalContext` as not testable but not reports for `$env`, `$moment`, and `$clone`.
This PR makes all these functions reported as not testable.
> Fix error hanndling of JSONata expression editor for extended functions

- packages/node_modules/@node-red/editor-client/locales/en-US/editor.json
- packages/node_modules/@node-red/editor-client/src/js/red.js
- packages/node_modules/@node-red/editor-client/src/js/ui/tab-info.js
- packages/node_modules/@node-red/editor-client/src/js/ui/view-tools.js
- packages/node_modules/@node-red/editor-client/src/js/ui/view.js
- packages/node_modules/@node-red/editor-client/src/js/ui/workspaces.js
Implements https://github.com/node-red/designs/discussions/79 to support uri fragments linking directly to any node or group in the workspace.
> Support uri fragments for nodes and groups including edit support

- .github/workflows/release.yml
- .github/workflows/tests.yml
This PR adds minimum token permissions for the GITHUB_TOKEN in GitHub Actions workflows using [secure-workflows](https://github.com/step-security/secure-workflows).
The GitHub Actions workflow has a GITHUB_TOKEN with write access to multiple scopes. Here is an example of the permissions in one of the workflow runs:
https://github.com/node-red/node-red/actions/runs/3158895012/jobs/5141453438#step:1:19
After this change, the scopes will be reduced to the minimum needed for the following workflows:
- release.yml
- tests.yml
- This is a security best practice, so if the GITHUB_TOKEN is compromised due to a vulnerability or compromised Action, the damage will be reduced.
- [GitHub recommends](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permiss …
> ci: add minimum GitHub token permissions for workflows

- packages/node_modules/@node-red/nodes/core/parsers/70-CSV.js
- test/nodes/core/parsers/70-CSV_spec.js
to close #3900 main issue
and add tests
(other fix is commented out but no tests)
As per #3900 the CSV node omits a string "undefined" if present when going from object to csv - as it assumes it is undefined :-)...
This fix - fixes that - and adds tests.
It also add some extra fixes to actually honour the "include nulls flag" that is currently only used when going from csv to object and not this way round (obj - csv). But these are commented out as they are a change in behaviour so we may not want to release them as-is without nore thought... (and would need changes to tests).
> Fix for CSV undefined property

- packages/node_modules/@node-red/nodes/core/function/89-delay.js
- test/nodes/core/function/89-delay_spec.js
and add tests
Now that we support a numeric parameter for flush (rather than flush all) - then it now makes sense that if the users specifies flush and reset that we honour the flush part before the reset. (Current behaviour is to ignore the flush and just reset). This PR fixes that so the flush occurs first. And adds tests.
> let delay node handle both flush then reset

- test/nodes/core/network/21-httprequest_spec.js
The unit tests for the httprequest node have been broken for a little while but gone unnoticed.
This is due to some new tests that were recently added in #3776. Took me a moment to track down the issue as the tests check the version of node and only run if on the versions of node that introduced the strict parser... and I was slightly down-level so couldn't recreate.
The tests was looking for a very specific error message - however it appears the text of the error changes in different node versions. So I've relaxed the test just to check for an error, rather than the full text.
> Fix httprequest tests to be more lenient on error message

- packages/node_modules/@node-red/editor-client/locales/en-US/editor.json
- packages/node_modules/@node-red/editor-client/locales/ja/editor.json
- packages/node_modules/@node-red/editor-client/src/js/ui/view-tools.js
Notification message of copy item URL is not i18n ready.
This PR tries to make it i18n ready and adds Japanese message.
> i18n item URL copy notification & add Japanese message

- .jshintrc
From Node-RED 3.0, Node version changed to Node 14 or later.
It supports almost all features of ES2020 (es11) according to [this site](https://node.green/).
But JSHint rule checked by grunt is restricted to ES2015(es6).
This causes `locking-flow` branch fail in checking by grunt.
This PR try to fix the issue by updating target ES version to es11.
> fix to allow es11 for jshint check

- test/nodes/core/storage/23-watch_spec.js
On the following environment, watch node test fails
- OS: MacOS 12.6.1 
- CPU: Apple M1
- Node: v14.21.0
```
1) watch Node
should watch a file to be changed:
AssertionError: expected Object {
payload: '/Users/nisiyama/src/Curry/Git/node-red/test/resources/23-watch-test-dir/base0/file0.txt',
topic: '/Users/nisiyama/src/Curry/Git/node-red/test/resources/23-watch-test-dir/base0/file0.txt',
file: 'file0.txt',
filename: '/Users/nisiyama/src/Curry/Git/node-red/test/resources/23-watch-test-dir/base0/file0.txt',
event: 'update',
size: 0,
type: 'file',
_msgid: '80e22be98b873189'
} to have property size of 5 (got 0)
at Assertion.fail (node_modules/should/cjs/should.js:275:17)
at Assertion.value [as property] (node_modules/should/cjs/should.js:356:19)
at Object._inputCallback …
```
> fix watch node test on MacOS/ARM

- packages/node_modules/@node-red/editor-client/src/js/ui/editor.js
- packages/node_modules/@node-red/nodes/core/function/80-template.html
- [x ] Bugfix (non-breaking change which fixes an issue)
Applies CSS class to visible (as opposed to hidden) element.
- [x ] I have read the [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md)
> Fix #3939, red border red-ui-typedInput-container

- packages/node_modules/@node-red/editor-client/src/js/nodes.js
This fixes two issues related to replacing unknown nodes in the editor.
One reported https://discourse.nodered.org/t/group-does-not-show-styling-until-browser-refresh-made/69078 - the other discovered whilst fixing the first one.
Background: when importing a flow, any unrecognised types are replaced by a special `unknown` node. If that unrecognised type gets registered later on (either some very async work was done before the type registered, or the user had to install it via the Palette Managed), the editor would swap out the unknown nodes for the 'real' node.
This PR fixes two scenarios that were not being handled properly:
1. if the node was in a group, the group was left with the `unknown` node still referenced in its internal list of nodes
This fix ensures the `unknown` node is …
> Handle replacing unknown node inside group or subflow

- packages/node_modules/@node-red/nodes/core/parsers/70-CSV.js
- test/nodes/core/network/21-httprequest_spec.js
- test/nodes/core/parsers/70-CSV_spec.js
and add test
to close #3919
Fixes Issue #3919 - if property names contain quotes (unusual but no impossible) then we should output then as the header line of the CSV correctly rather than breaking
> CSV node check header properties for ' and "

- packages/node_modules/@node-red/registry/lib/loader.js
- packages/node_modules/@node-red/registry/lib/localfilesystem.js
- packages/node_modules/@node-red/registry/lib/registry.js
- packages/node_modules/@node-red/runtime/lib/index.js
- packages/node_modules/@node-red/runtime/locales/en-US/runtime.json
- test/unit/@node-red/registry/lib/localfilesystem_spec.js
- test/unit/@node-red/registry/lib/resources/nodesDir2/@lower-case2/lower-case2/lower-case.html
- test/unit/@node-red/registry/lib/resources/nodesDir2/@lower-case2/lower-case2/lower-case.js
- test/unit/@node-red/registry/lib/resources/nodesDir2/@lower-case2/package.json
- test/unit/@node-red/registry/lib/resources/nodesDir2/lower-case/lower-case/lower-case.html
- test/unit/@node-red/registry/lib/resources/nodesDir2/lower-case/lower-case/lower-case.js
- test/unit/@node-red/registry/lib/resources/nodesDir2/lower-case/package.json
fixes #3861 
First, please read through the issue detailed in [this comment](https://github.com/node-red/node-red/issues/3861#issuecomment-1236124417)
* Normalise path before splitting (`loader.js`)
* Skip calling statSync on empty string  (`loader.js`)
* Shortcut scanning of a directories files/folders if the directory contains a package.json (`localfilesystem.js`)
* Prevent crashing node-red when `set.types` is not set  (`registry.js`)
* Print out which node caused the error 
* BEFORE: 
```
TypeError: Cannot read properties of undefined (reading 'forEach')
at Object.addModule (/usr/lib/node_modules/node-red/node_modules/@node-red/registry/lib/registry.js:195:27)
at /usr/lib/node_modules/node-red/node_modules/@node-red/registry/lib/loader.js:153:34
```
* AFTER:    (Updated 2022/09/29, …
> Fix nodesDir scan when node package has js/html in sub dir to package.json

- packages/node_modules/@node-red/nodes/core/network/21-httpin.js
Fixes #3878
This is done to ensure `msg.req.headers` shows up in the Debug sidebar.
However it isn't ideal. We have to balance the UX of the editor, versus the overall performance of flows. This change ensures the headers show up in the Debug sidebar, but comes at the cost of a small bit of additional work in the HTTP In node - work that is *only* required to solve the Debug sidebar issue.
> Ensure msg.req.headers is enumerable

- packages/node_modules/@node-red/nodes/core/function/16-range.html
- packages/node_modules/@node-red/nodes/core/function/16-range.js
- packages/node_modules/@node-red/nodes/locales/en-US/function/16-range.html
- packages/node_modules/@node-red/nodes/locales/en-US/messages.json
- test/nodes/core/function/16-range_spec.js
As per a user request https://discourse.nodered.org/t/range-node-requested-action-scale-and-drop-message-outside-input-range/69772 - this PR adds a drop mode to the range node.
If the input msg property is outside of the input range the entire message is dropped... this acts a a simple input filter for out of range messages.
Includes a test.
> Add drop mode to range node

- packages/node_modules/@node-red/runtime/lib/storage/localfilesystem/projects/git/index.js
See https://discourse.nodered.org/t/cant-clone-remote-repository/9957/2?u=knolleary for reference
If the username has a space in it, then the generated path needs to be properly quoted to work.
> Ensure key_path is quoted in GIT_SSH_COMMAND in case of spaces in pathname

- packages/node_modules/@node-red/runtime/lib/nodes/Node.js
- packages/node_modules/@node-red/runtime/locales/en-US/runtime.json
Fixes #3876
We already had a similar check in the Function node - where end users could accidentally try to return the wrong type of thing.
We didn't do this on the core messaging path on the assumption that a Node implementation would always do the right thing. But if they didn't there was no feedback to help them identify the issue. This adds an explicit check and logging if a node doesn't do the right thing.
> Add check that node sends object rather than primitive type

- packages/node_modules/@node-red/nodes/core/network/10-mqtt.js
fixes #3927 
When deploying an edit, the nodes `close` handler is called  & this deregisters the association with the broker node as expected. When only 1 MQTT node exists, at this point, the broker has `0` associations and it auto disconnects.
When the deployment is completed, the node is re-registered but due to the speed of this action, the broker has not yet "called back" with its disconnected state - meaning the node beleieves it is already connected. Then, after a few ms, the broker disconnected event comes through causing the connection to be closed.
If the single node is edited once more, the connection is restored correctly because it is already disconnected & the `connect` function progresses past the `canConnect` check.
see #3927 for further detail
* Dont disconnect client from …
> fix single subscription mqtt node status

- packages/node_modules/@node-red/editor-client/src/js/ui/view.js
> Prevent dbl-click opening node edit dialog with text selected

- packages/node_modules/@node-red/nodes/core/parsers/70-CSV.js
- packages/node_modules/@node-red/nodes/locales/en-US/parsers/70-CSV.html
mentioned in Issue #3989
As mentioned in #3989 - this PR just updates the CSV node to use replaceAll instead of replace. Probably never going to be a problem - but hey just in case.
> Csv change replace to replaceAll

- packages/node_modules/@node-red/editor-client/src/js/ui/clipboard.js
closes #3849
Saving flow is a specific format is not necessarily how a user wants to export a flow, especially when pasting to a forum/slack thread.
This PR remembers the user choice and reselects that mode in the export dialog.
> Remember compact/pretty flow export user choice

- packages/node_modules/@node-red/nodes/core/network/10-mqtt.js
This fixes an issue reported on slack where the MQTT nodes would not always reconnect following a modified-flows type deploy.
1. Create a flow with a single MQTT Subscriber node, connected to a *remote* broker, with function node and debug node.
2. Setup something outside of Node-RED to publish regularly to the same topic
3. Deploy and verify the publishes are arriving in debug
4. Modify the Function node (add a newline.. anything to cause it to be marked dirty)
5. To a Modified-Flows type deploy
6. See the messages stop arriving in Debug
I found it important to use a remote broker in order to increase the time taken to disconnect, and so to hit the necessary timing window.
When an MQTT In/Out node deregisters itself as part of stopping, if it was the last node using the broker node, the …
> Fix mqtt nodes not reconnecting on modified-flows deploy

- packages/node_modules/node-red/lib/red.js
to fix Issue #4010
and others (eg) email node server connect fails, and some reported on SO
This change forces the dns to prioritise ipv4 over ipv6 (node18 has set this other way round - which is causing user issues - eg Issue #4010  - and maybe this https://stackoverflow.com/questions/75200314/node-red-install-fails?noredirect=1#comment132702598_75200314 - and also several recent email node failures to connect to email servers.
> Force IPv4 name resolution to have priority

- packages/node_modules/@node-red/nodes/core/sequence/17-split.js
Fixes #3982
When splitting buffers in a stream, the node stores any 'left-over' bits following the split to be joined with the next message in the stream. It stored the `done` event until that left-over bit was made whole.
However, if there were no left-over bits (length === 0), it was storing `done` for later *and* calling `done`.
The fix is to not store the `done` for later if there is no left-over bit.
But, this does also raise a question of a difference in behaviour between string and buffer modes. I think for String streams, it always calls done after splitting, regardless of any left-over bits... whereas for Buffer streams, as described above, it waits until left-overs are handled.
This could do with tidying up, but needs more investigation and test cases to properly figure out the …
> Split node: avoid duplicate done call for buffer split

- packages/node_modules/@node-red/editor-client/src/js/ui/workspaces.js
When tabs are all hidden, opening tab menu causes reference error of undefined value.
> fix workspace reference error in case of empty tabs

- packages/node_modules/@node-red/editor-client/src/js/ui/workspaces.js
If only one tab exists, it cannot be deleted. 
However, delete item of tab menu is enabled.
This PR disables the delete menu item when only one tab exists.
> Disable delete tab menu when single tab exists

- packages/node_modules/@node-red/editor-client/locales/en-US/editor.json
- packages/node_modules/@node-red/editor-client/locales/ja/editor.json
- packages/node_modules/@node-red/editor-client/src/js/ui/common/tabs.js
Tooltip for closing button of subflow tab is shown as `Hide flow`.  
But, it actually closes the tab.
This PR try to fix the tooltip text.
> fix hide subflow tooltip

- packages/node_modules/@node-red/editor-client/src/js/ui/workspaces.js
`Hide all flows` tab menu is enabled even when all tabs are hidden.
This PR tries to disable the menu when no tabs are shown.
> Disable hide all menu if all tabs hidden

- packages/node_modules/@node-red/runtime/lib/storage/localfilesystem/projects/git/index.js
Currently, the `main` branch has been commonly used as a default name on GitHub, GitLab, and Apple Git. On the other hand, the latest git command still uses the `master` branch. Because this difference affects the UI on the history tab and project settings, it leads the confusion for some beginner users who start to use Git from Node-RED. To be the same name as possible, the code in this pull request uses an explicit name when executing the `git init` command.
> Use main branch as default in project feature

- packages/node_modules/@node-red/editor-client/src/sass/notifications.scss
if flows stopped due to missing too many node types manage-project-dep button displays none. Like this
after fixed:
> fix .red-ui-notification class

- packages/node_modules/@node-red/nodes/core/sequence/17-split.html
- packages/node_modules/@node-red/nodes/core/sequence/19-batch.html
This PR adds the configured count number to the join node when in manual mode. It also adds a + if set to "and all subsequent messages" mode.
It also adds the count to the batch node label, or the timeout value when in timeout mode.
> Add count to join and batch node labels

- packages/node_modules/@node-red/nodes/core/function/89-trigger.html
to address https://discourse.nodered.org/t/trigger-node-how-to-delay-and-repeat-message/74117/5
this fixes the UI so when send nothing is selected the option to repeat send is hidden.
> Hide trigger node repeat send  option if sending nothing

- packages/node_modules/@node-red/nodes/core/common/20-inject.js
Fixes #4014
The Inject node was using `RED.util.evaluateNodeProperty()` in synchronous-only mode. This meant it couldn't be used with async-only context stores.
I've searched through the other nodes and cannot find any others that are doing this.
> Allow Inject node to work with async context stores

- packages/node_modules/@node-red/nodes/locales/en-US/common/90-comment.html
The text will appear in the information tab of the side panel and not in the help tab of the side panel.
Textual change.
The location of the text of the comment node will appear in the help tab of the side panel and not in the information tab of the side panel. This change makes that more clear.
> Comment node: Clarify where the text will appear

- package-lock.json
- packages/node_modules/@node-red/editor-client/locales/en-US/editor.json
- packages/node_modules/@node-red/editor-client/locales/ja/editor.json
- packages/node_modules/@node-red/editor-client/src/js/ui/editors/code-editor.js
- packages/node_modules/@node-red/editor-client/src/js/ui/editors/markdown.js
- packages/node_modules/@node-red/editor-client/src/sass/dragdrop.scss
This PR adds inline figure support to the markdown editor of Node-RED editor used for describing node's as documents discussed at [this forum thread](https://discourse.nodered.org/t/proposal-support-of-inline-figure-in-markdown-editor/72666/20).
- inserting an inline image as data URL (<img src="data:..." />) by drag & drop of an image file.
This PR is one of two features included in the [previous PR](https://github.com/node-red/node-red/pull/4001).
> Add support for inline image in markdown editor by drag and drop of an image file

- packages/node_modules/@node-red/editor-client/src/js/ui/view.js
When adding a node to a group, the group position changes in some case.
However, undoing the node addition do not restore the group position.
> fix group position after undo

- packages/node_modules/@node-red/editor-client/src/sass/notifications.scss
The pull request, https://github.com/node-red/node-red/pull/4035 is helpful to click the button on the notification dialog but the scrollbar area always exists in other dialogs. It seems to affect the layout of the dialog like the following screenshot.
In this pull request, the dialog uses the scrollbar area only when it is needed.
> Show scrollbar in notification dialog only when needed

- packages/node_modules/@node-red/editor-client/src/tours/3.0/welcome.js
In Node-RED v3.1 beta.1, the welcome tour for v3.0 has no image due to the invalid path. Therefore, I fixed the image URLs.
> Fix image URLs for v3.0 tour

- packages/node_modules/@node-red/nodes/core/common/24-complete.html
- packages/node_modules/@node-red/nodes/core/common/60-link.html
- packages/node_modules/@node-red/nodes/core/common/60-link.js
- packages/node_modules/@node-red/nodes/locales/en-US/messages.json
- packages/node_modules/@node-red/nodes/locales/ja/messages.json
Some nodes with validators have guided users to set appropriate settings. For example, an `http-in` node with an error triangle is easy to understand the lack of the URL path. To guide users in the same style, I added the validators for complete and link call nodes.
> Add validators for complete and link call nodes

- packages/node_modules/@node-red/editor-client/src/js/ui/tab-info-outliner.js
Empty marker is shown in outliner when last node is removed from it.
However it is not shown when copy and pasting an empty group or loading
a flow containing it.
> Fix to add empty marker to empty group

- packages/node_modules/@node-red/editor-client/locales/en-US/editor.json
- packages/node_modules/@node-red/editor-client/locales/ja/editor.json
- packages/node_modules/@node-red/editor-client/src/js/ui/editor.js
I found that the lock and unlock buttons on the flow property UI have English messages in other language environments.
Therefore, in this pull request, I added the commit to support the internationalization of the button label.
> Support i18n of lock/unlock buttons in flow property UI

- packages/node_modules/@node-red/editor-client/src/js/ui/view-tools.js
This PR addresses the feature request made by me in the  [node-red forums](https://discourse.nodered.org/t/connect-one-or-multiple-selected-nodes-to-the-same-target-in-one-go/73662).
It allows the user to quickly connect multiple nodes' outputs to the input of a single node via a keyboard shortcut `wire-multiple-to-node`. This is the counterpart to the existing `wire-node-to-multiple` functionality.
The logic is as follows:
The user first selects the nodes that should be connected. The node that is selected last is the target node for the connections.
If a source node has already outputs that are connected to the target node, the first output port that doesn't have a connection to the target node is connected.
I've done some debugging in Chrome and it seems to work great. The …
> Added editor feature for connecting multiple nodes to single node

- packages/node_modules/@node-red/editor-client/src/js/ui/common/tabs.js
Reverses the direction the tab bar scrolls when using the mouse scroll wheel. This should now match the behaviour of other apps.
> Reverse direction of tab scroll to expected direction

- packages/node_modules/node-red/red.js
It is necessary to partially modify the EADDRINUSE error handling code that occurs when ports are duplicated. 
In node-red/red.js file, the if conditional statement that occurs when ports are duplicated is incorrect. The EADDRINUSE error is the "code" property of the err object, but is currently conditional on the "errno" property. 
So EADDRINUSE errors are caught in Uncaught Exception.
> Fix "EADDRINUSE" error

- packages/node_modules/@node-red/editor-client/src/js/ui/editor.js
- packages/node_modules/@node-red/editor-client/src/sass/editor.scss
Adds a button to the footer of the node/config-node edit dialogs that will open the help for the node in the help sidebar.
> Add link to node help in node edit dialog footer

- .github/workflows/tests.yml
- packages/node_modules/@node-red/nodes/core/storage/10-file.js
- test/nodes/core/storage/10-file_spec.js
ref Issue #3913
If you write a file (previously read in - with msg.parts attached) - in per line mode - with append linefeed set - we currently add an extra line feed due to the blank / null line at the end that closes the file. This fix detects that and stops it happening so you can write out an identical file to that read in more correctly..
This is to address the Issue #3913
> Fix extra newline append for multipart file write

- packages/node_modules/@node-red/editor-client/locales/en-US/editor.json
- packages/node_modules/@node-red/editor-client/locales/ja/editor.json
I removed duplicated definitions, `"find": "Find in workspace"` in the message catalog.
> Remove duplicated messages in the message catalog

- packages/node_modules/@node-red/editor-client/src/js/ui/clipboard.js
- packages/node_modules/@node-red/editor-client/src/js/ui/contextMenu.js
- packages/node_modules/@node-red/editor-client/src/js/ui/editor.js
- packages/node_modules/@node-red/editor-client/src/js/ui/group.js
- packages/node_modules/@node-red/editor-client/src/js/ui/subflow.js
- packages/node_modules/@node-red/editor-client/src/js/ui/view-tools.js
- packages/node_modules/@node-red/editor-client/src/js/ui/view.js
- packages/node_modules/@node-red/editor-client/src/js/ui/workspaces.js
When on a locked flow, this prevents a node's edit dialog from being opened via any means. In 3.1-beta.1 is was reported that the Info sidebar provided a route to open a node's edit dialog even if its flow was locked.
> Prevent opening locked node's edit dialog

- packages/node_modules/@node-red/editor-client/src/js/nodes.js
When importing a set of connected link nodes into a subflow, we have some code that ensures we don't end up with link nodes connected from inside to outside of a subflow.
The code was checking the other end of the link and ensuring it was also in the subflow. However it didn't consider nodes being imported at the same time.
> Fix importing connected link nodes into a subflow

- packages/node_modules/@node-red/editor-client/src/js/ui/projects/projects.js
In the project feature, the default file name of flow is `flow.json`. It works correctly in the project feature but users manually need to specify `flow.json` when they start Node-RED in the project directory under the `~/.node-red/projects/`. If users modify `package.json` to enable the runnable project, they also need to add the `flow.json` like the following.
``
"scripts": {
"start": "node-red flow.json"
},
``
I thought that `flows.json` is more appropriate for the default file name. Therefore, I submitted this pull request to change the file name.
> Change default file name to flows.json in project feature

- packages/node_modules/@node-red/editor-client/src/js/history.js
- packages/node_modules/@node-red/editor-client/src/js/nodes.js
- packages/node_modules/@node-red/editor-client/src/js/ui/common/tabs.js
- packages/node_modules/@node-red/editor-client/src/js/ui/contextMenu.js
- packages/node_modules/@node-red/editor-client/src/js/ui/deploy.js
- packages/node_modules/@node-red/editor-client/src/js/ui/group.js
- packages/node_modules/@node-red/editor-client/src/js/ui/tab-config.js
- packages/node_modules/@node-red/editor-client/src/js/ui/view-tools.js
- packages/node_modules/@node-red/editor-client/src/js/ui/view.js
- packages/node_modules/@node-red/editor-client/src/js/ui/workspaces.js
- packages/node_modules/@node-red/editor-client/src/sass/workspace.scss
This adds a change icon (blue circle) to the tabs based on whether their context have changed at all. This will help users find things that have changed and provide another visual cue they have un-deployed changes.
Whilst we did a good job of track changes on individual nodes, being able to properly track tabs that contain changes was actually quite hard to do. However, the Node Proxy object added as part of locking flows gave us the start of a mechanism to centralise the logic for reacting to the node's changed/moved state changing. But this had to be extended to include Groups and Junctions.
Tracking links was harder still, as their whole lifecycle is just a bit different to other flow objects.
Along the way, found and fixed a couple pre-existing bugs around tracking change history with …
> Add change icon to tabs

- packages/node_modules/@node-red/editor-client/src/js/ui/common/editableList.js
Node-RED beta-1 introduced locking flow feature.
However, this causes an issue in Node-RED Dashboards when changing the layout of widgets contained in a locked flow.
[This PR](https://github.com/node-red/node-red-dashboard/pull/799) is attempt to solve the issue.  It requires moving of items in `editableList` to be cancelled.   However, current `editableList` do not support it.   So, this PR adds support of `cancel` operation to `editableList`.
> add cancel operation to editableList

- packages/node_modules/@node-red/editor-client/src/js/ui/view-tools.js
An error occurs when performing align action on nodes on a locked tab.
This PR restores the workaround code that was commented out.
I don't understand why it's commented out, so maybe there's something else wrong.
> fix align nodes on locked tab

- packages/node_modules/@node-red/editor-client/src/js/nodes.js
- packages/node_modules/@node-red/editor-client/src/js/ui/contextMenu.js
- packages/node_modules/@node-red/editor-client/src/js/ui/view.js
It has always been possible to create a loop with nodes - and there are valid use cases for that. However a loop of pure junctions is never going to be okay - and impossible to break out of.
This PR prevents the user from creating infinite loops with junction nodes.
> Prevent loops being created with junction nodes

- packages/node_modules/@node-red/nodes/core/common/60-link.js
Fixes #3959
This ensures Link-Call nodes clean up any of its timeouts when the node is closed.
> Clear link-call timeouts when node is closed

- packages/node_modules/@node-red/editor-client/src/js/ui/workspaces.js
When locking/unlocking a flow, we weren't redrawing the flow to update the enabled/disabled node buttons.
This fix ensures we mark the nodes as dirty so they get redrawn in the correct state.
> Ensure node buttons are redrawn when flow lock state is changed

- packages/node_modules/@node-red/editor-client/src/js/ui/view-navigator.js
- packages/node_modules/@node-red/editor-client/src/js/ui/view.js
We occasionally get asked to increase the size of a flow canvas.
It has been 5000x5000 since the start of the project and for some users, it isn't enough.
Generally I've felt that once you're using that much space in a single flow, you have other organisational options available to better structure your flows.
One proposal was to make the workspace an infinite canvas. That is still an option, but is actually quite hard to get right.
So far the sake of a quick fix, this increases the workspace to 8000x8000 - giving 2.5x more space.
> Increase workspace size to 8000x8000

- packages/node_modules/@node-red/editor-client/src/js/ui/palette.js
Reported against 3.1.0-beta.2, the search button for any given node type could only be clicked once. Subsequent clicks did nothing until the editor was reloaded.
The problem is the way the popover content is managed. When the popover hides its contents is removed from the DOM. When it gets shown again, the content is reattached to the DOM.
However this removes any event handlers registered on the elements - so the button only appears to work once.
One fix would be to properly `detach` rather than `remove` the popover content.
Instead I went with making the search button consistent in its implementation with the other buttons - adding the functionality inline via an `onclick` attribute.
> Fix search button in palette popover

- packages/node_modules/@node-red/editor-client/src/js/ui/editors/expression.js
Missed off an argument when updating `expr.evaluate(...)` to take a callback.
> Fix jsonata expression test ui

- packages/node_modules/@node-red/nodes/core/network/21-httprequest.js
- test/nodes/core/network/21-httprequest_spec.js
The HTTP request node supports digest authentication, but only for the `MD5` and `MD5-sess` algorithms. This PR adds the `SHA-256` and `SHA-512-256` algorithms (including the sess versions), following https://www.rfc-editor.org/rfc/rfc7616.html.
> Added SHA-256 and SHA-512-256 digest authentication

- packages/node_modules/@node-red/nodes/core/network/10-mqtt.html
- packages/node_modules/@node-red/nodes/core/network/10-mqtt.js
- packages/node_modules/@node-red/nodes/locales/de/messages.json
- packages/node_modules/@node-red/nodes/locales/en-US/messages.json
- test/nodes/core/network/21-mqtt_spec.js
I had an issue with QoS 1+ messages did not get delivered after re-connecting to the broker. After digging around I figured out that NodeRed automatically unsubscribes from topics before disconnecting. After searching for solutions I found the discussion in #3452. Unfortunately, there was no pull-request with the proposed changes attached to the issue. I figured to give it a try implementing it myself.
I am aware that I did not fulfill the `I have discussed this change on the forum/slack team` requirement and that this PR might be rejected, but since there was already an discussion on the issue going on, I thought to give it a shot.
The only thing I couldn't figure out how to check if the node itself was removed from a flow. As you mentioned in the issue, it would still have to …
> Option to disable MQTT topic unsubscribe on disconnect

- packages/node_modules/@node-red/editor-client/src/js/nodes.js
- packages/node_modules/@node-red/editor-client/src/js/ui/clipboard.js
For a node that has *just* been added to the editor with credentials, the editor still has its credentials in memory. If the node was exported in that state, the credentials were included.
This fix ensures credentials are never included in an export.
> Ensure no node credentials are included when exporting to clipboard

- README.md
I noticed that the build status icon of Travis CI is not available as the following screenshot.
Based on the following document about the GitHub Actions icon and I changed it.
https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/adding-a-workflow-status-badge
> Use build status icon of GitHub Actions

- packages/node_modules/@node-red/editor-client/src/js/settings.js
The approach reads the path from window.location in RED.settings.init(), removes the last character, replaces "/" with "-" and stores it a authTokensSuffix property. Whenever the key auth-tokens is read, set or removed this suffix is added to the localStorage key. This results i no api-changes and no changes when the editor runs in the root path and you may run as much instances as you like on a single host name.
The only, from my perspective minor, point of discussion is the the behavior, that the hole auth-tokens* "Namespace" for setting-keys gets "magic" while currently only the key auth-tokens itself has special meaning. I don't see a security issue because the sessions are initiated from the same operating system user, on the same browser, on the same computer. And as logout is still …
> Use editor path in generating localStorage keys

- packages/node_modules/@node-red/editor-client/src/sass/palette.scss
Makes the background color of the palette's filter box match the background color of the input field inside that box.
<table>
<tr><td>Now
<td>Then
<tr><td><img width="205" alt="SCR-20230417-jrmn" src="https://user-images.githubusercontent.com/29807944/232538165-2e098a58-fd7e-4e9d-906f-e795edaff0b8.png">
<td><img width="207" alt="SCR-20230417-jszf" src="https://user-images.githubusercontent.com/29807944/232538222-9cbc58bd-2a7b-47ba-b90e-b5851a74a0cf.png">
</table>
**NOTE**: *A white background was used here to better show the issue.*
This won't have any impact on the default theme because the variable used in this PR also points to the same value - `$secondary-background`.
https://github.com/node-red/node-red/blob/master/packages/node_modules/%40node-red/editor-client/src/sass/colors.scss#L …
> Fix palette filter background

- packages/node_modules/@node-red/editor-client/src/sass/search.scss
> Fix broken subflow icon and overflowed name in quick add dialog

- packages/node_modules/@node-red/editor-client/src/js/ui/subflow.js
> Add node width and height to boundingBox

- packages/node_modules/@node-red/editor-client/src/js/ui/view.js
When selecting a group via the lasso, the group object wasn't being added to the `movingSet`. This mean any action on the selection (delete, cut, copy etc) would not include the group.
This fix changes how the lasso selects a group to use the same code as clicking the group uses - rather than try to reinvent the wheel.
> Fix group selection when using lasso

- packages/node_modules/@node-red/editor-client/src/js/nodes.js
- packages/node_modules/@node-red/editor-client/src/js/ui/editor.js
- packages/node_modules/@node-red/runtime/lib/flows/util.js
In our application we use our own storage plugin to save the flows in a database.
Due to this way of saving data we sometimes run in the problem that the flows are retrieved without including the subflow.
This results in node-red not starting / opening at all without displaying an error.
The following changes result in node-red being able to open and display the subflow as a missing flow type
> Handle missing subflow when loading flows into the editor

- packages/node_modules/@node-red/editor-client/locales/en-US/editor.json
- packages/node_modules/@node-red/editor-client/src/js/ui/keyboard.js
Fixes #4140 
The keyboard shortcut dialog doesn't provide all of the available 'scopes' when setting custom keyboard shortcuts.
This makes it impossible to add a shortcut scoped to just the edit dialog - something that *can* be done via keymap.json as it can specify any scope it wants.
This PR adds 'edit dialog' as an option when setting the shortcut scope:
This then allows 'escape' to be set as the shortcut for closing the tray, without it clashing with the existing predefined escape handler for clearing the selection within the workspace.
> Add editor scope to keyboard shortcut scope select

- test/nodes/core/common/20-inject_spec.js
This test would sometimes run twice, causing the author to increase its catch count to 2 before considering the test complete. However even one pass proves the node is behaving as expected, and it always runs at least once. I have left the conditional statement in so it can be changed in future.
At least since October last year, this unit test has caused many PRs to be flagged as failing where most of their commits have nothing to do with the Inject node. This resolves the issue caused by this test and causes it to pass - since the Inject node does exhibit the correct behavior. The test did not accurately reflect this.
> Invalid JSONata Inject node test passing condition

- packages/node_modules/@node-red/editor-client/src/js/ui/env-var.js
The current code would create a `global-config` node whenever the settings dialog is closed, even if there was nothing to save in it. This cause the deploy button to become active unexpectedly.
This skips creating the config node if there's nothing to store in it.
> Avoid creating empty global-config node if not needed

- packages/node_modules/@node-red/editor-api/lib/editor/theme.js
Fixes #4170
This removes the Node-RED version from the `/theme` endpoint.
This endpoint is unsecured, so provides this information to all visitors to the page.
The same information is also available under the `/settings` endpoint - which is only accessible to logged-in users.
I can find nothing that uses `RED.settings.theme('version')` in the core of Node-RED, so I don't see a good reason to keep it there.
> Remove version info from theme endpoint

- packages/node_modules/@node-red/editor-client/locales/ja/editor.json
I added a Japanese translation for the update, https://github.com/node-red/node-red/pull/4154.
> Add Japanese translation for keyboard shortcut scope

- packages/node_modules/@node-red/editor-client/src/js/ui/view.js
Remove junction from groups node list if it is present.
Resolves Issue "Deleted junctions reappear on copy/paste #4164"
> Remove junctions from parent group when deleting

- packages/node_modules/@node-red/registry/lib/externalModules.js
Fixes #4168
This ensures only one module is installed at a time when using external modules. This avoids any race conditions with npm running in parallel with itself.
> Ensure external modules are installed synchronously

- packages/node_modules/@node-red/editor-client/src/js/ui/group.js
- packages/node_modules/@node-red/editor-client/src/js/ui/view.js
Closes #4101
This ensures that when two groups are merged (using the `core:merge-selection-to-group`), any existing env vars on those groups are maintained.
Whilst testing the initial fix I realised you couldn't control which group was considered the primary group from which any existing style is taken. It would always use the oldest group.
This PR fixes that as well by changing how group selection is tracked; keeping an ordered list of selected groups so we know which was selected first.
> Combine existing env vars when merging groups

- packages/node_modules/node-red/red.js
Fixes #4122 
There were two cases where we would `process.exit()` due to an error but not specify a non-zero exit code.
> Ensure non-zero exit codes for errors

- packages/node_modules/@node-red/editor-client/src/js/ui/subflow.js
- packages/node_modules/@node-red/editor-client/src/js/ui/view.js
Fixes #4111
When adding a new subflow input/output, the virtual node is now placed relative to the current view, rather than in the top left corner. This takes into account both scroll position and scale factor.
Also fixes the renumbering of output ports when one is deleted.
> Place subflow outputs/inputs relative to current view

- packages/node_modules/node-red/red.js
- packages/node_modules/node-red/settings.js
https://discourse.nodered.org/t/settings-js-httpstatic-feature-to-pass-options-to-express-static-non-breaking/76688
Allows an options object to be passed to express.static when using the httpStatic feature set in settings.js.
This enables customization to the various headers and other settings which can help to better integrate with a reverse proxy such as nginx. https://expressjs.com/en/api.html#express.static
> Allow options object on each httpStatic configuration

- packages/node_modules/@node-red/editor-client/src/js/red.js
- packages/node_modules/@node-red/editor-client/src/js/ui/view.js
Extends #4113 to tidy up the `RED.view.select` api to allow group selection by id.
> Enable RED.view.select to select group by id

- packages/node_modules/@node-red/editor-client/src/js/ui/editor.js
fixes #4198
Skip cloning the nodes array of a group node since they cannot be changed by the edit dialog and the nodes array is not used in the below comparison to determine if the node has changed anyway.
And while this fixes the stack overflow, I wam unsure why the demo flow presented in the issue causes this while other group nodes are fine.
I did chek the nodes object for any circular refrences but didnt spot them!
> Dont clone the group nodes `node` array when saving edits

- packages/node_modules/@node-red/nodes/core/function/89-delay.js
to close #4202
This fixes Issue #4202 in the delay not not flushing correctly when in rate limit mode.
> Fix delay node flush issue

- packages/node_modules/@node-red/editor-client/src/js/ui/keyboard.js
In function `resolveKeyEvent`, return `null`  immediately if both modifiers are pressed - allowing the browser to handle the shortcut.
This permits mac shortcuts like full screen CMD+CTRL+F to operate correctly.
> Dont handle shortcuts with both cmd+ctrl modifiers 

- packages/node_modules/@node-red/editor-client/src/types/node-red/func.d.ts
- packages/node_modules/@node-red/nodes/core/function/10-function.js
Adds optional callback to env.get in function node so that it can get jsonata properties in the future.
> Adds optional callback to env.get in function node

- packages/node_modules/@node-red/editor-client/src/types/node-red/func.d.ts
- packages/node_modules/@node-red/nodes/core/function/10-function.js
- packages/node_modules/@node-red/runtime/lib/flows/Flow.js
- packages/node_modules/@node-red/runtime/lib/flows/index.js
- packages/node_modules/@node-red/runtime/lib/flows/util.js
- packages/node_modules/@node-red/util/lib/util.js
- test/nodes/core/common/91-global-config_spec.js
- test/unit/@node-red/runtime/lib/flows/Flow_spec.js
- test/unit/@node-red/runtime/lib/storage/localfilesystem/index_spec.js
fixes #4196
Adds async callback to all the paths env-vars take when setup as JSONata values that need to be evaluated.
NOTE: Somehow an unrelated test "should handle flow file in random unc path and non-existent subfolder" in `test\unit\@node-red\runtime\lib\storage\localfilesystem\index_spec.js` was failing due to missing stub `getUserSettings`.  This may have been masked by [the stray `it.only`](https://github.com/node-red/node-red/issues/4224) preventing all the runtime unit tests running.
> Add callback to getSetting to support async jsonata access

- packages/node_modules/node-red/red.js
This is an alternative proposal to #4125 that appears to have stalled.
Rather than add `httpStaticMiddleware` as a top level property, this follows the lead of #4109 to support a `middleware` property on the `httpStatic` object:
```
httpStatic: [
{
path: '/opt/static/',
root: '/private/',
middleware: myCustomHttpMiddleware
}
]
```
> Add support for httpStatic middleware

- packages/node_modules/@node-red/nodes/locales/en-US/common/20-inject.html
The inject node doesn't create multiline strings as the help text explains. While there's indeed many ways to circumvent this, the Template node might be more "low-code" than the function node is.
> help: Template might be a better fit to create multiline strings

- packages/node_modules/@node-red/nodes/core/network/21-httprequest.js
Keep-Alive handling was broken when we moved to `got`. This fixes it. Need to apply custom http/https agents with the keepAlive flag set (`request` used to take care of that for you).
> Fix connection keep-alive in http request node

- packages/node_modules/@node-red/nodes/core/function/10-switch.html
Fixed #4241. In the switch node, the previous type is applied to the added text input. As of now, in the "is type of" rule, I think that only the number type should be copied to the second rule and others are string type. Could you check this handling?
> Fix broken text input in the switch node

- package.json
- packages/node_modules/@node-red/editor-client/src/types/node-red/func.d.ts
- packages/node_modules/@node-red/nodes/core/function/10-function.js
- packages/node_modules/@node-red/runtime/lib/flows/Flow.js
- packages/node_modules/@node-red/runtime/lib/flows/Group.js
- packages/node_modules/@node-red/runtime/lib/flows/Subflow.js
- packages/node_modules/@node-red/runtime/lib/flows/index.js
- packages/node_modules/@node-red/runtime/lib/flows/util.js
- packages/node_modules/@node-red/runtime/lib/nodes/index.js
- packages/node_modules/@node-red/util/lib/util.js
- test/node_modules/nr-test-utils/index.js
- test/nodes/core/common/20-inject_spec.js
- test/nodes/core/common/91-global-config_spec.js
- test/nodes/core/function/15-change_spec.js
- test/nodes/subflow/subflow_spec.js
- test/unit/@node-red/runtime/lib/flows/Flow_spec.js
- test/unit/@node-red/runtime/lib/flows/Group_spec.js
- test/unit/@node-red/runtime/lib/flows/Subflow_spec.js
- test/unit/@node-red/runtime/lib/flows/index_spec.js
- test/unit/@node-red/runtime/lib/flows/util_spec.js
- test/unit/@node-red/runtime/lib/storage/localfilesystem/index_spec.js
This is a major refactoring of some internals that simplifies how env vars are retrieved.
This PR reverts node-red/node-red#4225 - we want to keep the `getSetting` api synchronous.
To workaround the fact we support JSONata env types that need to become async when we get to NR4.0, this PR does all of the evaluation of the env var true values as part of the startup of the flows. To achieve this, the `Flow.start` function has been made async.
To further simplify the lookup logic, the way Groups are handled has been completely changed. We have now a `Group` object that has its own `getSetting()` function and can delegate up to its parent group or flow. This removes a bunch of code in Flow that didn't really respect the hierarchy of things.
One side effect of this change is that groups need to …
> Evaluate all env vars as part of async flow start

- packages/node_modules/@node-red/editor-client/locales/en-US/editor.json
- packages/node_modules/@node-red/editor-client/src/js/ui/palette-editor.js
- packages/node_modules/@node-red/editor-client/src/sass/palette-editor.scss
- packages/node_modules/@node-red/editor-client/src/sass/palette.scss
1. Add catalogue selector to the palette install tab
2. Filter search to each catalogue or "All Catalogs"
3. If "All Catalogs" is selected, show which catalog the node comes from in the meta data
Notes:
* Removed `absolute` styling and changed sort texts to icons (see justifications below)
* Scrolling now occurs on the editable list instead of the whole panel.  (compounded CSS issues around `absolute` positioning caused scrolling of node lists to reveal empty panel in the vertical tab list - see also: justifications below)
* Checked theming - ok
Justification:
Due to addition of filter and possibility of longish catalogue names (e.g. "Node-RED Community catalogue") pushing the sorting / refresh buttons down a row AND the editable list having `absolute` positioning, some restructuring was …
> Improve Catalogue visibility

- packages/node_modules/@node-red/runtime/lib/flows/Subflow.js
Closes #4239
Adds the following env vars that will be available to nodes within a subflow.
- `NR_SUBFLOW_NAME`
- `NR_SUBFLOW_ID`
- `NR_SUBFLOW_PATH`
They evaluate to the name/id/path of the subflow *instance*.
> Add NR_SUBFLOW_NAME/ID/PATH env vars

- packages/node_modules/@node-red/nodes/core/common/60-link.html
- packages/node_modules/@node-red/nodes/core/function/10-function.html
In my environment, `fa-clock` cannot display the time icon. Therefore, I changed it to the `fa-clock-o`.
And I also added the same icon to the link call node.
> Fix timeout icon in function and link call nodes

- packages/node_modules/@node-red/nodes/core/function/10-switch.html
I found that the previous fix in https://github.com/node-red/node-red/pull/4242 leads to another issue, https://github.com/node-red/node-red/issues/4272 because the current `vt` value is changed to `num` or `str`. Therefore, the code in this pull request changes the `vt` value when the second rule is added only.
I tested the following rules.
| Rule                   | 3.1.0-beta.3 | 3.1.0-beta.4 | This PR |
| ---------------------- | ------ | ------ | ----- |
| is of type 'string'    | OK     | Broken | OK    |
| is of type 'number'    | OK     | Broken | OK    |
| is of type 'undefined' | OK     | Broken | OK    |
| Rule                   | 3.1.0-beta.3 | 3.1.0-beta.4 | This PR |
| ---------------------- | ------ | ------ | ----- |
| is of type 'string'    | Broken | OK     | OK    |
| …
> Fix broken text input in the switch node (again)

- packages/node_modules/@node-red/nodes/core/network/21-httprequest.js
- test/nodes/core/network/21-httprequest_spec.js
If the http statusCode is 204 (Success, No Content) and the node return type is set to JSON this sets msg.payload as an empty json object so as to supress the JSON parse error
> Handle 204 in httprequest JSON

- packages/node_modules/@node-red/editor-client/src/js/ui/diff.js
While writing [my blog about the project feature](https://kazuhitoyokoi.medium.com/using-version-control-for-node-red-flows-ce8585df7870#:~:text=in%20the%20tree%20view%20of%20the%20template%20node%2C%20there%20is%20a%20button%20highlighted%20by%20the%20red%20rectangle%20above%20to%20show%20the%20details%20of%20the%20differentiation.%20after%20clicking%20the%20button%2C%20you%20can%20see%20the%20differentiation%20between%20the%20lines.), I thought that the text diff button should have a tooltip like the following screenshot.
With this tooltip, users can understand the function of the button before clicking and opening the text diff UI.
So, I submitted this pull request to add the tooltip.
> Add tooltip to text diff button

- test/nodes/core/parsers/70-JSON_spec.js
During development, the `npm test` command always fails in my Node.js v20 environment.
```
2444 passing (2m)
59 pending
2 failing
1) JSON node
should log an error if asked to parse an invalid json string:
AssertionError: expected 'Unexpected token \'o\', "foo" is not valid JSON' to start with 'Unexpected token o'
at Assertion.fail (node_modules/should/cjs/should.js:275:17)
at Assertion.value [as startWith] (node_modules/should/cjs/should.js:356:19)
at Timeout._onTimeout (test/nodes/core/parsers/70-JSON_spec.js:176:52)
at listOnTimeout (node:internal/timers:573:17)
at process.processTimers (node:internal/timers:514:7)
2) JSON node
should log an error if asked to parse an invalid json string in a buffer:
AssertionError: expected 'Unexpected token \'o\', "{"name":foo}" is not valid JSON' to …
```
> Fix test cases of JSON node

- packages/node_modules/@node-red/nodes/core/storage/10-file.js
- test/nodes/core/storage/10-file_spec.js
> Fix handling in file nodes when number is specified as file name

- packages/node_modules/@node-red/editor-client/src/js/ui/view.js
Fixes #4282
This ensures an undo of quick-add junction restores the correct workspace dirty state.
> Capture workspace dirty state when quick-adding junction

- packages/node_modules/@node-red/editor-client/locales/en-US/editor.json
- packages/node_modules/@node-red/editor-client/locales/ja/editor.json
- packages/node_modules/@node-red/editor-client/src/js/ui/palette-editor.js
In the user settings UI, the `a-z` and `recent` buttons have tooltips but the `relevance` button doesn't have it. In this pull request, I added the tooltip to the relevance button like following screenshot.
> Add tooltip to relevance sort button in user settings UI

- packages/node_modules/@node-red/editor-client/src/js/ui/tab-context.js
- test/unit/@node-red/editor-api/lib/admin/context_spec.js
Fixes #4295 
URL encode context key names when interacting via the context sidebar.
The server side already does the work to decode if necessary.
> Handle non-url-safe chars in context api

- packages/node_modules/@node-red/nodes/core/function/10-function.html
Fixes #4296 
Places the timeout/outputs options into a single row to make better use of the space.
> Fix function setup tab layout

- packages/node_modules/@node-red/runtime/lib/flows/Subflow.js
Fixes #4292
Wasn't coping with the fact `scope` might be an Array or now a String is group scoped.
> Handle group-scoped nodes inside subflow

- packages/node_modules/@node-red/nodes/core/network/10-mqtt.html
Fixes #4291 
I'm fairly sure the validation for a blank clientid doesn't need to check the autoUnsub flag. Using the clean session flag is enough for a check.
> Remove unnecessary check for clientid if autoUnsub set

- packages/node_modules/@node-red/editor-client/src/js/ui/view.js
Fixes #4206, #4205
Historically we have treated the Ctrl key and Mac's Cmd key as interchangeable when it comes to modifying mouse actions in the editor.
With the introduction of the Context Menu, this has lead to some unexpected user experiences - including the two issues linked above.
This PR modifies the logic is we better distinguish between the two when it matters. Essentially, we have the 'control' key modifier, which now maps to `ctrl` on Windows/Linux and `cmd` on Mac.
This keeps `ctrl` free for triggering the context menu - as per Apple's design guidelines.
> Better distinguish between ctrl and meta keys on mac

- packages/node_modules/@node-red/runtime/lib/storage/localfilesystem/util.js
- test/unit/@node-red/runtime/lib/storage/localfilesystem/util_spec.js
Fixes #4221 
This ensures concurrent calls to the `writeFile` utility function are serialised and handled in order. Due to the async nature of the work done, without this it was possible to hit errors (as per original issue) when multiple calls are made to update the same file.
> Ensure storage/util.writeFile handles concurrent write attempts

- packages/node_modules/@node-red/editor-client/src/js/ui/palette-editor.js
Fixes #4315 
This makes two changes to the Palette Manager:
- If there are multiple catalogues, the select box now defaults to 'All Catalogues' rather than the first in the list
- If there are fewer than 20 entries in a catalogue, they are listed even with no search term entered.
> Default filter to All Catalogues and show nodes for small lists

- packages/node_modules/@node-red/nodes/core/common/60-link.html
Reported on the forum, after upgrading to 3.1.0, an existing `link call` node was showing a validation error. This was because the validation expected `linkType` to be set. For old flows, that value could be `undefined` which ought to have been good enough to imply `static`.
This modifies the validation so it treats `undefined` as `static`.
One side-effect we'll live with is that on editing such a node and clicking 'done' without having made changes, will cause the value to get set to 'static' - and mark the node as dirty. This sometimes causes complaints in the community, but it's a fleeting moment to deal with it.
> Handle undefined linkType value for existing link-call nodes

- packages/node_modules/@node-red/runtime/lib/nodes/Node.js
- test/unit/@node-red/runtime/lib/nodes/Node_spec.js
Fixes #4330
Fixes the tracking of how many input handlers have the `(msg, send, done)` signature so we know to call complete at the right time.
> Handle nodes with multiple input handlers properly

- .github/PULL_REQUEST_TEMPLATE.md
Due to the way grunt is installed, `grunt` might not work for the user locally. However, `npm run test` will succeed for them, as NPM knows where `grunt` is located to execute.
- [-] For non-bugfix PRs, I have discussed this change on the forum/slack team.
- [ :) ] I have run `grunt` to verify the unit tests pass
- [-] I have added suitable unit tests to cover the new/changed functionality
> github: Request `npm run test` in PR template

- packages/node_modules/@node-red/nodes/core/function/89-delay.js
This is a fix for a regression introduced into the delay node in v3.1 where a msg.reset gets passed through to the output - to close Issue #4337
- [] For non-bugfix PRs, I have discussed this change on the forum/slack team.
> Fix regression in delay node to not pass on msg.reset

- packages/node_modules/@node-red/nodes/core/parsers/70-CSV.js
The change is to improve massively the problematic performance of the CSV node while exporting CSV from JS object
I consider this a bug fix due to the poor performance of the current implementation on fairly big payloads
I did not take the time to create an actual ticket before-hand and apologize for that.
By not using string.slice(0,-1) but rather joining smaller array that includes the separator only when required, the performance of the node is improved at by 2 to 3 order when handling big JS object
Since this PR is about improving the node performance, we need to understand the actual performance of the node, and how it now compares before/after the fix.
Here is the flow used for the following data :
```json
[[{"id":"f1d31f03.48da08","type":"inject","z":"4e2ac6b5.d48208","name":"","pro …
```
> Performance : make CSV export way faster by not re-allocating and handling huge string

- .github/workflows/release.yml
- .github/workflows/tests.yml
Github Actions are scripts based running on nodejs. They are also need updates and go regularly out of service and may break your CI. See [blog news](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/)
`peter-evans/create-pull-request@v2` was intentionally not updated, since I am not familiar with it and I want to avoid breaking the ongoing release of node-red 3.1.
Release notes:
https://github.com/actions/checkout/releases/tag/v4.0.0
> Update outdated Github Actions

- packages/node_modules/@node-red/editor-client/locales/en-US/editor.json
- packages/node_modules/@node-red/editor-client/locales/fr/editor.json
- packages/node_modules/@node-red/editor-client/locales/ja/editor.json
- packages/node_modules/@node-red/editor-client/locales/pt-BR/editor.json
- packages/node_modules/@node-red/editor-client/locales/zh-CN/editor.json
- packages/node_modules/@node-red/editor-client/src/js/ui/editor.js
- packages/node_modules/@node-red/editor-client/src/js/ui/utils.js
- packages/node_modules/@node-red/editor-client/src/js/validators.js
- packages/node_modules/@node-red/nodes/core/function/10-switch.html
- packages/node_modules/@node-red/nodes/core/function/15-change.html
Fixes #4340
This improves the validation of the Switch and Change node 'rules' property.
It now validates and reports up if there are any typing issues in any of the rules. The Change node already did this, but there was some code duplication. This PR adds `RED.utils.validateTypedProperty` that can be used to validate a typed property. It returns true if valid, and a String containing error details if invalid.
The validate function can now also return an array of error strings rather than just one - ensuring they are presented consistently along with any other node property errors.
> Improve validation of switch/change node rules

- packages/node_modules/@node-red/editor-client/src/js/ui/contextMenu.js
Fixes #4334
Some of the context menu entries didn't have explicit catalog entires for their action. This updates them to use the existing nls labels for the corresponding action.
> Add missing nls labels to context menu

- packages/node_modules/@node-red/runtime/lib/flows/util.js
Fixes #4342
When evaluating env vars in a Flow/Subflow/Group we defer evaluating `env` types to last as they might reference other env vars set at the same level.
However, when they are eventually evaluated, we're still in the call to evaluate the env vars - so the Flow/Subflow/Group object hasn't yet been updated with the evaluated values. So when the `env` evaluation is done and `flow.getSetting()` is called, it retrieves the unevaluated value... and if you can follow that then you get a 🥇 .
The fix is to hook into the `getSetting` call whilst evaluating the `env` property to return any just-evaluated values before delegating to the flow.
> Fix env evaluation when one env references another in the same object

- test/nodes/core/function/10-function_spec.js
(This is the result of my investigation into why the test "should delay handling messages until init completes" in `test/nodes/core/function/10-function_spec.js` fails occasionally.)
The library `node-red-node-test-helper` uses `process.nextTick` which might trigger executing callbacks slightly before normal, and thus causing the test to fail. The remedy is to add a tiny threshold margin of say 5ms, e.g. when the timeout period is 200ms then accept it being run for only 195ms. Through my testing I have never noticed a lower `msg.delta` value than 198.
The test makes use of `helper.load` whose implementation in the [`node-red-node-test-helper` library](node_modules/node-red-node-test-helper) contains the following:
```javascript
const self = this;
PROXY_METHODS.forEach(methodName => { …
```
> Timer testing fix

- packages/node_modules/@node-red/runtime/lib/flows/Flow.js
- packages/node_modules/@node-red/runtime/lib/flows/util.js
Reported in a [comment](https://github.com/node-red/node-red/issues/4342#issuecomment-1729516843), if an env var was of credential type, but no value set, an error was being hit.
This fixes that by ensuring the credentials object exists.
> Handle credential env var evaluation when no value set

- packages/node_modules/@node-red/editor-client/src/js/ui/editors/buffer.js
Currently if you use the enhanced buffer editor to enter buffer vales that contain binary style string literals it fails to display them corectly - but does handle hex 0x style ok.
This is because parseInt doesn't handle 0b automatically - but Number( does so in this case it should be a better bet.
> fix buffer viewer to handle 0b style binary

- packages/node_modules/@node-red/editor-client/src/js/ui/editors/code-editors/monaco.js
- [x ] Bugfix (non-breaking change which fixes an issue)
Address [issue 4377](https://github.com/node-red/node-red/issues/4377)
Where the Monaco code editor steals Ctrl-Enter, so that shortcut cannot instead be used to close the tray.
Code changed as per @Steve-Mcl suggestion.
> Ctrl-Enter does not close tray (Monaco) #4377

- packages/node_modules/@node-red/registry/lib/externalModules.js
- packages/node_modules/@node-red/registry/lib/installer.js
When installing packages the `--production` flag used to be added to the arguments that `npm` received. As npm wants developers to use the `--omit=dev` flag instead it warned users on STDERR. Standard error was captured by Node-RED and output to the logs as being an error. This caught users off-guard and they expected something to have gone wrong.
With this change the `--omit=dev` is used instead, to remove the warning.
This change works for NPM of version 8 and beyond[1], included in Node.JS 16. This change will not work on NPM version 6[2] which is included in Node.JS 14[3].
[1]: https://docs.npmjs.com/cli/v8/commands/npm-install#omit
[2]: https://docs.npmjs.com/cli/v6/commands/npm-install
[3]: https://nodejs.org/en/download/releases#looking-for-latest-release-of-a-version-branch
Note …
> npm: Remove production flag on npm invocation

- packages/node_modules/@node-red/editor-client/src/js/ui/common/typedInput.js
- packages/node_modules/@node-red/editor-client/src/js/ui/utils.js
Based on a [forum exchange](https://discourse.nodered.org/t/set-number-value-to-nan-in-change-inject-node/81589), this PR extends the validity checks for typedInput fields of type 'number'.
The following additional formats will pass the check:
- `NaN`
- Binary values, e.g.: `0b10101` or `0B11101`
- Octal values, e.g.: `0o1357` or `0O2468`
- Hex values, e.g.: 0x25aF or 0X69Cd
> Extend typedInput "num" type validity check to NaN, binary, octal & hex

- packages/node_modules/@node-red/runtime/lib/flows/Flow.js
- test/unit/@node-red/runtime/lib/flows/Flow_spec.js
Fixes #4396
The way `global-config` nodes store their credentials is slightly different to regular nodes - they get stored an extra level deep under a `map` propertry.
Rather than pick apart the logic of why that's the case, the fix here is to lookup under that key.
Also adds a test for same.
> Ensure global-config nodes lookup cred values properly

- packages/node_modules/@node-red/editor-client/src/js/red.js
Fixes #4392
We didn't originally add a close button to this notification because the user needs to take action pretty soon.
However, in response to #4392, this PR adds a close button. It is still considered a 'persistent' notification - causing the warning triangle to be shown in the header that can be clicked to reopen the notification.
> Add a close button to the restart-required notification

- packages/node_modules/@node-red/editor-client/src/js/nodes.js
Fixes #4044
The w/h properties of a group node were not being imported. That meant if a group was on a tab not visible in the editor, it would not get its w/h properties set before the next deploy happened.
This fix ensures any provided w/h values are set on the group when imported.
> Ensure group w/h are imported if present

- packages/node_modules/@node-red/editor-client/src/js/ui/typeSearch.js
Fixes #4415
The Quick Add dialog has a hard-coded list of common nodes - inject/change/switch etc. If any have been excluded, we need to make sure we don't try to show them in the list.
> Ensure typeSearch handles undefined node definitions

- packages/node_modules/@node-red/registry/lib/loader.js
Fixes #4381 
When loading nodes and plugins, the code was triggering a save to `.config.nodes.json` twice - the first time after the nodes are loaded, and again after plugins are loaded.
The code checks what is being written to see if it matches what's already there - to avoid needless file writing. However, due to the two-step process, the first call is missing the plugin info so will not match what is already in the file. The second call, with the full information, doesn't match the just-written partial update so triggers another file write.
The fix is to move the settings save to after both node and plugin loading is complete - so it is done just once with the full information that will match what is already there if nothing has changed.
> Only save settings once during node load process

- packages/node_modules/@node-red/nodes/core/common/20-inject.js
- packages/node_modules/@node-red/runtime/lib/flows/util.js
Fixes #4376 
This modifies how we handle falsey env var values.
From https://github.com/node-red/node-red/issues/4376#issuecomment-1789823618:
> This is one of the slightly historic mishandlings we have with env vars.
> 
> When working with 'normal' process env vars, we have always treated both `undefined` and a blank string to mean the env var isn't set. Otherwise we consider it is set.
> 
> As @dceejay highlights, we use a simple 'truthiness' test on this - which was fine for dealing with regular env vars that can only be strings.
> 
> When we introduced other types of value (boolean, number etc) we didn't consider their truthiness for this test.
> 
> We have two choices:
> 
> 1. modify the truthiness test to only look for `undefined`. This would mean a blank string env var would start …
> Handle false-like env vars properly

- packages/node_modules/@node-red/nodes/core/network/31-tcpin.js
- packages/node_modules/@node-red/nodes/locales/en-US/network/31-tcpin.html
This PR lets `msg.reset = true; ` (boolean)  reset the tcp-request node when it is set to remain connected. This allows the user to "kick" the connection if required so it forces a reconnect - or also allows them to send msg.host and/or msg.port to connect to a different server instead.
> Let msg.reset  reset Tcp request node connection when in stay connected mode

- packages/node_modules/@node-red/editor-api/lib/editor/theme.js
- packages/node_modules/@node-red/editor-client/src/js/ui/editors/mermaid.js
- packages/node_modules/@node-red/runtime/lib/api/settings.js
Fixes #4274
Allows a theme to specify which built-in theme mermaid should use.
via `settings.js`:
```
editorTheme: {
mermaid: {
theme: "forest"
}
}
```
via custom theme:
```
RED.plugins.registerPlugin("dark", {
type: "node-red-theme",
css: [
"themes/dark/theme.min.css",
"themes/dark/theme-customizations.min.css"
],
mermaid: {
theme: 'forest'
}
})
```
> Allow a theme to specifiy which theme mermaid should use

- packages/node_modules/@node-red/registry/lib/externalModules.js
Fixes #4446
This updates the module name parser to extract any possible subpath included so it gets imported properly.
For example:
- `fs/promises` - `fs` is the module name, `/promises` is the subpath
This correctly parses when there is a scoped module and/or a version string included:
- `@scope/module/subpath@1.2.3`
> Allow import of modules with subpath in specifier

- packages/node_modules/@node-red/nodes/core/network/10-mqtt.js
Fixes #4380
As the user can pass in a new value of `broker` without any validation, this ensures its a string before we try treating it as such.
> Guard against node.broker being undefined

- packages/node_modules/@node-red/editor-client/src/js/ui/projects/tab-versionControl.js
Prevents Node-RED from trying to load the parents of the first commit in Project History.
Fixes #3901
> Don't try to load the parents of the first commit

- packages/node_modules/@node-red/registry/lib/externalModules.js
This logs to the audit log whenever an external module is installed - similar to the existing `node.installed` event.
There is no sensible equivalent place for logging an uninstall.
This isn't done in the context of an http request, so we can't log who triggered it - that information can be derived from the preceding `flows.set` audit event that will contain the info.
> Add modules.install audit event when external module installed

- packages/node_modules/@node-red/editor-client/src/js/red.js
Fixes #4413
Debounces notifications so they don't flood the screen when uninstalling a module with lots of node sets in.
> Debounce node-removed notifications

- packages/node_modules/@node-red/editor-client/src/js/validators.js
- packages/node_modules/@node-red/nodes/core/function/16-range.html
- packages/node_modules/@node-red/nodes/core/function/90-exec.html
- packages/node_modules/@node-red/nodes/core/function/rbe.html
- packages/node_modules/@node-red/nodes/core/parsers/70-HTML.html
- packages/node_modules/@node-red/nodes/core/parsers/70-JSON.html
- packages/node_modules/@node-red/nodes/core/parsers/70-XML.html
- packages/node_modules/@node-red/nodes/core/parsers/70-YAML.html
- packages/node_modules/@node-red/nodes/core/sequence/17-split.html
- packages/node_modules/@node-red/nodes/core/storage/10-file.html
Fixes #4429
Adds proper validation to any core node with a typedInput with `msg.` type - mostly.
There are a couple that remain that need some more logic (as they support multiple types), eg `sort` node. But this handles the bulk of them.
> Add validators to any fields using msg-typed Input

- packages/node_modules/@node-red/editor-client/src/js/ui/editor.js
Fixes #4429
If no validator is provided in node property, the validation result is true which breaks the built-in validation of `typedInput`.
The solution that this PR adds is to check if the input is a `typedInput` and in this case call `typedInput("validate")`.
> Fix `validateNodeProperty` without validator provided

- packages/node_modules/@node-red/runtime/lib/flows/Subflow.js
Fixes #4456 
Subflows were not updating their internal record of their groups, meaning any attempt to lookup env vars would fail as they have to access the group objects.
> Ensure subflow instances keep track of their groups

- packages/node_modules/@node-red/runtime/lib/flows/Subflow.js
Fixes #4369
If a subflow module contains unrecognised node references (see #4369 for an example), we were logging an unhelpful error. This improves matters to identify the subflow and node at fault.
> Handle unknown node reference inside subflow module

- packages/node_modules/@node-red/nodes/core/function/10-switch.html
Fixes #4464
The typeof check in the switch node doesn't need to validate the configuration as they are hardcoded options. The way the rule stores its configuration was making the validator want to look for an actual json string in the config, whereas it is simply the string `json`.
> Fix switch validation of typeof field

- packages/node_modules/@node-red/editor-client/src/js/validators.js
- packages/node_modules/@node-red/nodes/core/function/16-range.html
- packages/node_modules/@node-red/nodes/core/function/rbe.html
- packages/node_modules/@node-red/nodes/core/parsers/70-HTML.html
- packages/node_modules/@node-red/nodes/core/parsers/70-JSON.html
- packages/node_modules/@node-red/nodes/core/parsers/70-XML.html
- packages/node_modules/@node-red/nodes/core/parsers/70-YAML.html
As a follow up to #4440, feedback from the community highlighted that the new validation was flagging errors with some existing nodes. Specifically, nodes that were deployed in an earlier version before a particular property was added to the node and not updated since.
We try to minimise disruption for users - so this PR relaxes the validation on these properties to allow their value to be undefined.
> Relax some node validators to allow undefined value

- packages/node_modules/@node-red/runtime/lib/flows/Subflow.js
When creating entities inside a subflow we generate new ids for each instance - including remapping any existing references to the modified ids.
We weren't doing that for groups - so nested groups didn't have the proper `g` property set , leading to the runtime getting stuck in a loop waiting for a non-existent group to appear.
This fixes that.
> Ensure nested groups inside subflows have their g props remapped

- packages/node_modules/@node-red/editor-client/src/js/events.js
This fixes an issue when RED.events.off(..) is called in a RED.events.on(..) callback:
```
let cb = () => {
RED.events.off("event-name", cb)
....
}
RED.events.on("event-name", cb)
```
This pattern emulates a once(..), i.e., execute a callback once-only for an event.
Discussed in [Forum](https://discourse.nodered.org/t/event-offing-an-on-event-to-perform-only-once/83726)
```
2451 passing (3m)
59 pending
Done.
=============================== Coverage summary ===============================
Statements   : 69.06% ( 11565/16746 )
Branches     : 61.9% ( 6382/10310 )
Functions    : 65.01% ( 1620/2492 )
Lines        : 69.19% ( 11215/16210 )
================================================================================
```
> Client/Editor Events: fix off-in-on pattern emulating once

- packages/node_modules/@node-red/editor-client/src/js/ui/common/typedInput.js
This adds auto-complete for `env` typedInputs:
It gathers valid completions from the node/group/flow/subflow/global-env-vars.
It's a bit inefficient currently as it has to re-gather that list of env vars each time it has to revaluate valid completions - but that's because we don't have a suitable point to do that initial gather at the start of an autoComplete session.
> Add auto-complete for env vars

- packages/node_modules/@node-red/editor-api/lib/editor/index.js
- packages/node_modules/@node-red/editor-api/lib/editor/ui.js
- packages/node_modules/@node-red/editor-client/templates/index.mst
- packages/node_modules/@node-red/runtime/lib/index.js
- test/unit/@node-red/editor-api/lib/editor/ui_spec.js
Fixes #4503
PR #4179 removed the `version` property due to security concerns about exposing it via unsecured end points. At the time I overlooked this property was also being injected into `index.mst` as the cache-busting query parameter value.
This PR restores the cache busting functionality, but uses a hash of the version. It isn't ideal in that there is still a 1:1 mapping between hash and version - so this just slightly obscures the value. .. but it's better than nothing.
> Restore caching busting functionality without using explict version number

- packages/node_modules/@node-red/editor-client/src/js/ui/view.js
In case a contrib node uses an oversized icon in non-`.svg` format, the size of this icon might change when pulling the node from the palette to the editor view:
This PR modifies the scaling algorithm - for that particular case - to ensure the size of the icon stays as it is in the palette:
Fix for #4490.
> Fix icon scaling for non .svg icons

- packages/node_modules/@node-red/editor-client/src/js/ui/editor.js
Fixes #4497
The issue was the loack of horizontal space to have both the 'X nodes uses this config' message and the scope select box.
Previously there was just enough room, but 3.1 added the help button which has taken up the spare space.
I've modified the 'X nodes uses this config' to be a more compact button that when clicked filters the info sidebar to show the users of the node. The original text is shown as a tool tip when the button is hovered.
> Modify node users info in config editor footer

- packages/node_modules/@node-red/editor-client/src/js/ui/env-var.js
- packages/node_modules/@node-red/runtime/lib/nodes/credentials.js
Fixes #4508
When deploying changes to a `global-config` node that included credential type properties, it was only sending changed values. This would cause any pre-existing value to be dropped.
This PR ensures the values are merged properly without losing anything.
> Ensure global-config credential env vars are merged on deploy

- packages/node_modules/@node-red/nodes/core/function/15-change.js
to fix #4372
As per Issue #4372 if asked to replace something with a boolean - currently if the search criteria is a regex then it returns as a string - (if the search is just a string then it returns a boolean correctly). This fix forces the replacement to be a boolean if requested.
As it is a slight change in behaviour I have left it on the 4.0 dev branch - but I think as it already half works then this is more of a bug fix tbh.
> Fix change node to return boolean if asked

- packages/node_modules/@node-red/runtime/lib/flows/Flow.js
- packages/node_modules/@node-red/runtime/lib/flows/Group.js
- packages/node_modules/@node-red/runtime/lib/flows/Subflow.js
- packages/node_modules/@node-red/runtime/lib/flows/util.js
Fixes #4479
With the work to pre-evaluate env values on start, we no longer re-evaluate JSON each time it is retrieved. The problem this has caused for the linked issue is that we are now returning the same object each time - an object that can be mutated by a flow.
Env values are intended to be immutable.
This PR fixes it by cloning the env value if needed. It only does this for object types (inc Arrays) - but not for string/number/boolean types that don't need it.
> Clone objects types when getting env values

- packages/node_modules/@node-red/editor-client/src/js/ui/tab-context.js
> Include top level property name when copying path from context

- packages/node_modules/@node-red/editor-client/src/js/nodes.js
Fixes #4545
When importing a flow that includes a pre-existing subflow definition *and* and instance of the subflow, the editor would correctly identify the existing subflow definition, however it was failing to re-associate the imported subflow instance with the existing subflow definition.
This fixes it be properly mapping the subflow instance's `type` to the existing subflow's type.
> Handle importing flow with existing subflow and instance node

- packages/node_modules/@node-red/runtime/lib/flows/Subflow.js
Fixes #4533 
If the instance node doesn't get its `g` property set, the `group` level scoping of catch/status/complete nodes won't work as expected.
> Ensure subflow instance node has g property set

- packages/node_modules/@node-red/editor-client/src/js/nodes.js
When `convertNode` receives a node with the `credentials` object, a loop checks for each credential whether it should be exported or not. If no credential is exported the function returns an empty object.
```js
// the node returned
{
id: "some-id",
type: "some-type",
credentials: {}, // <- empty creds object
...
}
```
Which is likely to overwrite unmodified credentials - the object should not be returned.
> (convertNode) Do not create the credentials object if there is nothing to export

- packages/node_modules/@node-red/nodes/core/function/10-function.js
Fixes #4536
If an ESM module doesn't define a `default` export, the Function wasn't exposing anything the module had to share.
This is a quick fix that if `default` is not defined it exposes the whole module to the Function node.
> Handle undefined default export when importing module

- packages/node_modules/@node-red/editor-client/locales/en-US/editor.json
- packages/node_modules/@node-red/editor-client/locales/fr/editor.json
- packages/node_modules/@node-red/editor-client/src/js/ui/clipboard.js
- packages/node_modules/@node-red/editor-client/src/sass/library.scss
Fixes #4549
The adds better feedback in the import conflict dialog to show which nodes already exist in the workspace.
The icon has a tooltip that says 'This node already exists'. I think there is more UX to improve, but this solves the original issue that the dialog lacked feedback on what already existed.
> Improve feedback in import dialog to show conflicted nodes

- packages/node_modules/@node-red/runtime/lib/nodes/credentials.js
Fixes #4560 
When adding the first credential value to `global-config`, it was hitting an undefined variables. All my local testing was with an existing flow that already had a global config object in the credential store.
> Ensure global creds object is initialised when adding first cred

- packages/node_modules/node-red/lib/red.js
The existing check for `>14` would break if the user had Node 15 as what we really wanted was Node 16 or later. This updates the version check to reflect that.
> Fix require of dns module

- packages/node_modules/@node-red/editor-client/src/js/ui/view.js
PR #4491 had a regression in it that caused node icons to go missing if they were oversized. This fixes it. Hurrah.
> Fix missing node icons in workspace

- packages/node_modules/@node-red/editor-client/src/js/ui/utils.js
- packages/node_modules/@node-red/editor-client/src/js/validators.js
- packages/node_modules/@node-red/nodes/core/common/20-inject.html
Fixes #3795 
Allows TypedInput number fields to include `${env var}` when validating the contents.
Also
- fixes up reporting multiple errors in the Inject node
- adds more number validation to inject node
- extends #4371 validation to built-in validator
> Do not flag env var in num typedInput as error

- packages/node_modules/@node-red/nodes/core/parsers/70-CSV.html
- packages/node_modules/@node-red/nodes/core/parsers/70-CSV.js
- packages/node_modules/@node-red/nodes/core/parsers/lib/csv/index.js
- packages/node_modules/@node-red/nodes/locales/en-US/messages.json
- packages/node_modules/@node-red/nodes/locales/en-US/parsers/70-CSV.html
- test/nodes/core/parsers/70-CSV_spec.js
Implements a new RFC compliant mode to the CSV node for NR V4
* Maintains legacy processing for backwards compatibility
* This is via the addition of a `Specification` drop down
* Includes a `form-tip` warning beneath when legacy mode is selected - the intention is to remove legacy mode at some future time, this tip is there to encourage users to update their flows.
* Always* outputs RFC compliant CSV
* \*we still permit line endings to be non-standard `\r` or `\n`
* Adds catchable error handling and node status (permitting user to intercept bad data)
* 13% faster or more in all cases tested so far
The CSV node in its current form can output non RFC compliant CSV strings and can in some cases, incorrectly parses RFC compliant CSV strings.  A simple but definitive test is: given any RFC …
> Add RFC4180 compliant mode to CSV node

- packages/node_modules/node-red/red.js
This change allows us to use our own authentication middleware in substitution for the built-in basic-auth middleware at the top level of RED.httpNode. The property httpNodeAuth in settings.js can receive a value that is a middleware function or array of middleware functions or fallback to using the built-in basic-auth. This change is backwards compatible. It was discussed on the forum @ https://discourse.nodered.org/t/httpnode-top-level-middleware-to-replace-basic-auth/85654/1
> let settings.httpNodeAuth accept single middleware or array of middlewares

- packages/node_modules/@node-red/nodes/core/parsers/70-HTML.html
- packages/node_modules/@node-red/nodes/core/parsers/70-HTML.js
- packages/node_modules/@node-red/nodes/locales/en-US/messages.json
Add a fourth option to the HTML node to collect attributes and html content together. At the moment, it is only possible to either have the attributes or the content of matching elements. This adds an option have both.
Discussed in the [forum](https://discourse.nodered.org/t/question-about-html-node/84298).
all passed but errored out on:
```
Running "nyc:all" (nyc) task
Fatal error: spawn nyc ENOENT
```
> HTML node: add option for collecting attributes and content

- packages/node_modules/@node-red/editor-client/src/js/ui/utils.js
- packages/node_modules/@node-red/nodes/core/common/lib/debug/debug-utils.js
As [discussed in the forum](https://discourse.nodered.org/t/fr-pr-click-on-id-in-debug-panel-highlights-node-or-flow/82988/20), this PR adds the feature to highlight a node or flow when clicking in the debug panel on a value `typeof string`, that is identified as a node / flow id. The term _node_ here comprises all node types returned by `RED.nodes.nodes(<id>)`.
This feature re-uses functionality already implemented and in use to highlight the emitting node of a debug message.
As the elements used to display debug messages are only created on demand (toplevel or when expanded), this feature is as well only injected on demand.
> Click on id in debug panel highlights node or flow

- packages/node_modules/@node-red/runtime/package.json
I realised seconds too late that #4352 added a dependency to the top-level package.json, but not to the inner package.json for the internal module that would depend on it.
This is one scenario our `scripts/verify-package-dependencies.js` tool doesn't spot - as it doesn't know the package is missing.
> Add rfdc to @node-red/runtime package.json

- package.json
- packages/node_modules/@node-red/runtime/lib/flows/Flow.js
- packages/node_modules/@node-red/runtime/lib/flows/Subflow.js
- packages/node_modules/@node-red/runtime/lib/flows/index.js
- packages/node_modules/@node-red/runtime/lib/flows/util.js
- packages/node_modules/@node-red/runtime/package.json
Reverts node-red/node-red#4352
Merged too quickly - breaking tests in `test/nodes/subflow/subflow_spec.js`
> Revert "changed cloning library to rfdc for runtime module"

- package.json
- packages/node_modules/@node-red/editor-client/src/js/ui/workspaces.js
- test/nodes/core/network/21-httprequest_spec.js
Fixes #4600
This is an alternative fix to #4601 - which resets the workspace index only when nodes are cleared. This event is triggered when switching projects - and a couple other scenarios where its probably sensible to reset the index.
> Reset workspace index when clearing nodes

- packages/node_modules/@node-red/editor-client/src/js/nodes.js
- packages/node_modules/@node-red/editor-client/src/js/ui/workspaces.js
Fixes #4626
Plumbs the `subflows:change` event up properly so we show the change indicator on subflow tabs
> Show change indicator on subflow tabs

- packages/node_modules/@node-red/editor-client/src/js/ui/contextMenu.js
Fixes #4617 
Ensures the context menu honours the `menu.menu-item-export-library` and `menu.menu-item-import-library` options that could be used to disable the import/export menu options.
> Hide import/export context menu if disabled in theme

- packages/node_modules/@node-red/editor-client/src/js/nodes.js
- packages/node_modules/@node-red/runtime/lib/flows/util.js
Fixes #4625 
This adds error handling in the runtime if a subflow instance has invalid properties - such as malformed JSON.
It also adds validation on the env vars with the editor itself. Note this only applies to the subflow instance node. If the parent subflow has errors, they don't get surfaced as cleanly... but they do get surfaced.
> Add validation and error handling on subflow instance properties

- packages/node_modules/@node-red/editor-api/lib/editor/comms.js
- packages/node_modules/@node-red/editor-client/src/js/comms.js
- packages/node_modules/@node-red/editor-client/src/js/ui/env-var.js
- packages/node_modules/@node-red/editor-client/src/js/user.js
- packages/node_modules/@node-red/editor-client/src/sass/header.scss
- packages/node_modules/@node-red/runtime/lib/api/comms.js
As part of the concurrent editing work, I've made some updates to the apis/events around the comms connection between runtime and editor.
I've pulled them into their own PR so they don't get lost amongst the concurrent editing work.
Summary:
- When logging into the editor, if a default user is enabled, the underlying comms connection retained the default user identity, rather than getting updated to identify as the newly logged in user. This wasn't an problem because nothing we have today relies on that identity... but we'll need that soon. So this PR updates the comms handling so when an anon user logs in and becomes identified, the comms connection also becomes identified.
- Added simple `on/off/emit` event handling to the editor-side comms component. This allows plugins to listen for …
> Comms API updates

- packages/node_modules/@node-red/editor-client/src/js/ui/palette.js
Addresses feedback from @GogoVega in #4634
- Ensures filter is properly applies on page reload
- Lazily removes any unrecognised categories from localStorage
> Ensure palette filter reapplies and clear up unknown categories

- packages/node_modules/@node-red/nodes/core/common/21-debug.html
Fixes #4641
Recent changes to display the full path to a node that logs to the debug sidebar didn't work for subflow modules - as the subflow definition isn't loaded into the editor.
This handle that
> Fix subflow module sending messages to debug sidebar

- packages/node_modules/@node-red/editor-client/src/js/ui/tab-help.js
Spotted an error in the console as a result of #4631 - where the import of flows happens before the help sidebar is populated with subflows. The newly emitted `subflows:change` event on import was triggering a refresh of help sidebar, which it wasn't ready for.
This fixes that.
> Guard refresh of unknown subflow

- Gruntfile.js
- packages/node_modules/@node-red/editor-api/lib/editor/theme.js
- packages/node_modules/@node-red/editor-client/src/js/multiplayer.js
- packages/node_modules/@node-red/editor-client/src/js/red.js
- packages/node_modules/@node-red/editor-client/src/js/ui/common/popover.js
- packages/node_modules/@node-red/editor-client/src/js/ui/tray.js
- packages/node_modules/@node-red/editor-client/src/sass/multiplayer.scss
- packages/node_modules/@node-red/editor-client/src/sass/style.scss
- packages/node_modules/@node-red/runtime/lib/index.js
- packages/node_modules/@node-red/runtime/lib/multiplayer/index.js
- packages/node_modules/node-red/settings.js
This is the first iteration of Node-RED Multiplayer mode - what we've called Concurrent Editing previously.
This lays a bunch of groundwork and adds basic 'presence awareness' in the editor that lets you know if someone else has the editor open at the same time.
When enabled, the header will show all of the other users who currently have the editor open:
If you click on them, **for this very initial version**, it lists which flow/subflow they have open and whether they are currently editing a node.
This example has `adminAuth` configured so we know who the users are. If also works without `adminAuth`, although everyone then gets a username like `Anon 123`.
This new feature is disabled by default. To enable it, users need to set `editorTheme.multiplayer.enabled = true` in their settings …
> Introduce multiplayer feature

- packages/node_modules/@node-red/nodes/core/function/90-exec.js
- packages/node_modules/@node-red/registry/lib/externalModules.js
- packages/node_modules/@node-red/registry/lib/installer.js
Following the 18.20.2/20.12.2 node.js releases, it is no longer valid to call `child_process.spawn` with a `.cmd` or `.bat` file *without* using the `shell: true` option.
This PR updates our usage to include the `shell` option when appropriate.
It's hard to know exactly what impact this could have given the many and varied ways the exec node is used - so will need some testing to verify.
> Fix use of spawn on windows with cmd files

- packages/node_modules/@node-red/nodes/locales/en-US/sequence/17-split.html
Minor change that only improves xpath parsing.
Parsing the doc broke due to xpath being strict. Now it doesn't fail as the opening `p` tag is closed.
> docs: Add closing paragraph tag

- packages/node_modules/@node-red/editor-client/src/js/ui/subflow.js
- packages/node_modules/@node-red/registry/lib/subflow.js
When a subflow was packaged as a module, and had a `conf-type` env property, the format used to save the value didn't match what the edit dialog expected - so it would always reset to the 'default' value on reopen.
Given the type does not need any special handling in the runtime we can store as just the string value.
> Fix saving of conf-type properties in module packaged subflows

- packages/node_modules/@node-red/editor-client/src/js/ui/deploy.js
- packages/node_modules/@node-red/editor-client/src/js/ui/editor.js
Undoing edits of subflow env properties was not working. This fixes that.
> Fix undo of subflow env property edits

- packages/node_modules/@node-red/editor-client/src/js/history.js
- packages/node_modules/@node-red/editor-client/src/js/ui/view.js
Applies two fixes to undo history:
1. if a node was moved multiple times, after a single undo, the change indicator was being cleared even through it was still 'dirty'.
2. after a deploy, doing an undo would revert the previous change, but not mark the item as changed
The first of these is fixed. The second is fixed for common cases (move/edit/delete), but not some of the edge-case history types.
> Fix undo history of moves and post-deploy handling

- packages/node_modules/@node-red/runtime/lib/flows/util.js
Fixes #4663
If an env var is a blank string (``FOO=""`), and is used in a property substitution (`${FOO}`), then we were not replacing it with a blank string, but leaving the `${FOO}` value in place.
This was a slightly intentional behaviour when we first introduced true env var support, but as they have expanded to be more widely used with subflow properties etc, then it makes sense to allow inserting a blank string if the env var is explicitly set to a blank string (rather than undefined).
Given this *might* be a change in behaviour for some obscure edge cases, I'm putting this in 4.0, rather than 3.x.
> Allow blank strings to be used for env var property substitutions

- packages/node_modules/@node-red/editor-client/locales/en-US/editor.json
- packages/node_modules/@node-red/editor-client/locales/ja/editor.json
- packages/node_modules/@node-red/editor-client/src/js/ui/palette-editor.js
- packages/node_modules/@node-red/editor-client/src/tours/welcome.js
- packages/node_modules/@node-red/runtime/locales/ja/runtime.json
> Add Japanese translations for 4.0.0-beta.2

- packages/node_modules/@node-red/editor-client/src/js/multiplayer.js
- packages/node_modules/@node-red/editor-client/src/js/red.js
- packages/node_modules/@node-red/editor-client/src/js/ui/common/popover.js
- packages/node_modules/@node-red/editor-client/src/js/ui/deploy.js
- packages/node_modules/@node-red/editor-client/src/js/ui/view-annotations.js
- packages/node_modules/@node-red/editor-client/src/js/ui/workspaces.js
- packages/node_modules/@node-red/editor-client/src/js/user.js
- packages/node_modules/@node-red/editor-client/src/sass/colors.scss
- packages/node_modules/@node-red/editor-client/src/sass/header.scss
- packages/node_modules/@node-red/editor-client/src/sass/multiplayer.scss
- packages/node_modules/@node-red/editor-client/src/sass/variables.scss
- packages/node_modules/@node-red/runtime/lib/multiplayer/index.js
Adds icons to the tabs/nodes to show where other users are in the editor:
Conscious of space, if there are more than two other users in one place, it only shows the first two, plus a count of how many more there are:
Hovering any user icon reveals their name, hovering over the count icon lists all of the users at that location:
Clicking on a user icon (including those in the top header) jumps to where they are in the editor.
> [multiplayer] Add user presence indicators

- packages/node_modules/@node-red/editor-api/lib/auth/index.js
Fixes #4363
When `autoLogin` was enabled, Node-RED will automatically redirect to the SSO login endpoint. If the login failed, we would reload the editor, and `autoLogin` would kick in again and fail to login - causing an endless loop.
There was already logic to break out of the loop if a `session_message` query parameter was provided - used in *some* SSO failure causes, but not the more common one described above. This PR adds that query param to other SSO handling routes so we do the right thing.
> Avoid login loops when autoLogin enabled but login fails

- packages/node_modules/@node-red/nodes/core/function/10-function.js
It seem's `vm.createScript` is deprecated, because it's not mentioned in the official docs. This PR replaces `vm.createScript` by `vm.Script`.
This was needed by myself to run node-red with [bun.sh](https://bun.sh). `vm.createScript` is not available in bun, because I think they missed it due of the missing documentation? Not sure.
The advantage of running node-red with bun is support of esm :)
I also opened a PR there to add support for `vm.createScript`: https://github.com/oven-sh/bun/issues/8312
> Replacing vm.createScript in favour of vm.Script

- packages/node_modules/@node-red/nodes/core/function/10-function.js
- packages/node_modules/@node-red/runtime/lib/flows/Flow.js
- test/nodes/core/function/10-function_spec.js
Fixes #4683
This does two things around error handling
1. preserves the `cause` property of any Error object passed to `node.error(...)`. This is a standard property of Error so reasonable to copy over.
2. updates Function node error handling to pass up the whole error object, not just the message string
The results of this will mean if an error thrown in a Function node includes a cause property it will be present on the message sent by a Catch node.
> Pass full error object in Function node and copy over cause property

- packages/node_modules/@node-red/runtime/locales/de/runtime.json
- packages/node_modules/@node-red/runtime/locales/en-US/runtime.json
- packages/node_modules/@node-red/runtime/locales/es-ES/runtime.json
- packages/node_modules/@node-red/runtime/locales/fr/runtime.json
- packages/node_modules/@node-red/runtime/locales/ja/runtime.json
- packages/node_modules/@node-red/runtime/locales/pt-BR/runtime.json
- packages/node_modules/@node-red/runtime/locales/ru/runtime.json
- packages/node_modules/node-red/red.js
Remove outdated NodeJS version checks because they are not supported anymore.
#4687
> fix: remove outdated Node 11+ check

- packages/node_modules/@node-red/editor-client/locales/en-US/editor.json
- packages/node_modules/@node-red/editor-client/src/js/ui/diff.js
This improves the flow diff view in two ways:
1. nodes that have only been moved are now highlighted differently to those that have had other changes applied. This makes it easier to scan through a list of changes to spot 'meaningful' changes rather than just moves.
2. If a node is moved between tabs, it now shows the flow name rather than id, making it easier to see where things have moved from/to
> Improve diff view display of nodes that have only moved

- packages/node_modules/@node-red/editor-client/locales/en-US/editor.json
- packages/node_modules/@node-red/editor-client/src/js/history.js
- packages/node_modules/@node-red/editor-client/src/js/ui/deploy.js
- packages/node_modules/@node-red/editor-client/src/js/ui/diff.js
- packages/node_modules/@node-red/editor-client/src/js/ui/notifications.js
This PR is a first iteration of improving the background conflict handling within the editor.
In Node-RED today, if another user deploys changes to the runtime whilst I have the editor open, it displays a modal notification and forces you to do something about it there and then. The choices being to merge, review or ignore the update.
If the other developer is being particular productive, they could be repeatedly deploying changes - causing this modal interruption every time.
The goal here is to remove this interruption, whilst still providing a way for a user to know there are upstream changes available for them to deal with at their time of choosing.
----
This PR updates the notification so that:
1. it is no longer modal - the user is not blocked from continuing what they were doing
2. …
> Improve background-deploy notification handling

- packages/node_modules/node-red/red.js
Closes #4569 
Adds `--version` cli arg that returns the node-red, node.js versions and OS info in one go:
```
$ node-red --version
Node-RED v4.0.0-beta.3-1
Node.js v18.18.2
Darwin 20.6.0 x64 LE
```
This is the same info we log on startup.
I know the original feature request wanted npm version as well, but that we can't get so easily without using child_process etc - and to be honest, npm version issues are much much rarer these days.
> Add --version cli args

- packages/node_modules/@node-red/editor-client/src/js/ui/editor.js
- packages/node_modules/@node-red/nodes/core/common/60-link.html
Fixes #4704 
Editing link nodes can have a side-effect on the configurations of other link nodes. The existing `oneditsave` mechanism does not provide any way for those side-effects to be automatically captured in the edit history.
This was the root cause of the linked issue - editing the link in node via the edit dialog, modified the link out nodes, but those modifications didn't get recorded in edit history
This PR fixes it by allowing `onEditSave` to return an object containing a history property. This should be an array of additional edit history events that will get merged with the node's own edit event into a single `multi` history event. This allows all of the node modifications to be undone in one.
> Allow nodes to return additional history entries in onEditSave

- packages/node_modules/@node-red/editor-client/src/js/ui/deploy.js
- packages/node_modules/@node-red/editor-client/src/sass/header.scss
To improve feedback when in the editor as a read-only user, with this PR, the deploy button now shows a lock icon and never becomes enabled. This is a clear indication that changes cannot be deployed.
If a user logs in, the lock icon is removed and the button restored to its expected state (depending if they had made changes or not).
> Show lock on deploy if user is read-only

- packages/node_modules/@node-red/editor-client/locales/en-US/editor.json
- packages/node_modules/@node-red/editor-client/locales/fr/editor.json
- packages/node_modules/@node-red/editor-client/src/js/ui/tab-config.js
- packages/node_modules/@node-red/editor-client/src/js/ui/tab-help.js
Add missing tooltips to Sidebar:
- `Collapse all` and `Expand all` are missing in **Config tab** (footer)
- `Show topics` button now displays a dynamic message (hide/show) in **Help tab**
@kazuhitoyokoi  I mention you so that it is easier for you to find the translations to do.
> Add missing tooltips to Sidebar

- packages/node_modules/@node-red/editor-client/locales/en-US/editor.json
- packages/node_modules/@node-red/editor-client/locales/fr/editor.json
- packages/node_modules/@node-red/editor-client/src/js/ui/common/typedInput.js
Translate the number of items selected in the options list (`typedInput`)
@kazuhitoyokoi 😉
> Translate the number of items selected in the options list

- packages/node_modules/@node-red/editor-api/lib/auth/permissions.js
- packages/node_modules/@node-red/editor-api/lib/auth/users.js
- packages/node_modules/@node-red/editor-api/lib/editor/theme.js
- packages/node_modules/@node-red/nodes/core/function/10-function.js
- packages/node_modules/@node-red/runtime/lib/api/settings.js
- packages/node_modules/@node-red/runtime/lib/nodes/Node.js
- packages/node_modules/@node-red/util/lib/util.js
Deprecated: Use Array.isArray() instead.
Source: https://nodejs.org/docs/latest-v18.x/api/util.html#utilisarrayobject
#4723
> chore: migrate deprecated `util.isArray`

- packages/node_modules/@node-red/editor-api/lib/auth/index.js
- packages/node_modules/node-red/settings.js
Closes #4717
This allows the session cookie used as part of adminAuth OAuth strategies to have its options customised.
The code applies the documented defaults, then allows `httpAdminCookieOptions` to override them.
> Add httpAdminCookieOptions

- packages/node_modules/@node-red/editor-client/src/js/ui/view.js
Without preventDefault, when you try to drag the canvas with middle mouse button on Windows (e.g. in Chrome), the cursor change to a "scroll cursor" and the canvas scrolls endlessly instead of being dragged accurately.
When you try to drag the canvas with middle mouse button on Windows (e.g. in Chrome), the cursor change to a "scroll cursor" and the canvas scrolls endlessly instead of being dragged accurately. (issue #4256 )
> Fix panning with middle mouse button on windows 10/11

- packages/node_modules/@node-red/editor-client/src/js/ui/common/typedInput.js
Fixes #4728 
Checkboxes are not updated when calling `typedInput("value", "")`
> Fix checkboxes are not updated when calling `typedInput("value", "")`

- packages/node_modules/@node-red/editor-client/src/js/ui/deploy.js
Fix the Sidebar Config is not refreshed after a deploy.
Issue described in the [Forum](https://discourse.nodered.org/t/should-the-double-exclamation-mark-for-imported-configuration-disapper-after-deploy/88348).
> Fix the Sidebar Config is not refreshed after a deploy

- packages/node_modules/@node-red/editor-client/templates/index.mst
Remove the trailing slash from meta (void) elements.
HTML5 has its own syntax and is not XHTML as is often mistaken.
For tags which do not allow child elements aka as void element, it is not allowed to use a trailing slash. In practice, however, this is not a problem due to the browser's excellent error tolerance.
Since different code styles are used in the head, this is a standardization to the formally “correct” style.
Validator to test: https://validator.w3.org/nu/
> fix(editor): remove trailing slash

- packages/node_modules/node-red/bin/node-red-pi
Script does not start node-red if space is in script path.
> fix(node-red-pi): node-red not started by path

- packages/node_modules/@node-red/editor-client/src/js/nodes.js
Fixes #4749.
Fixes `node_map` does not contain as key the new id of a copied node.
It's `new_nodes` which contains the new ids.
At the end of updating the new nodes, they are added to `node_map` which explains why they are in the image.
> Fix losing links when importing a copy of links into a subflow

- packages/node_modules/@node-red/runtime/lib/flows/index.js
Fixes #4752 
This adds 'rewired' nodes to the list that get stopped on Modified Flows type deploys.
When testing locally, I found some other odd behaviours caused by not including this list of nodes. For example:
Starting with:
```
[A] -> [B] -> [C]
```
then deleting the wire between B/C:
```
[A] -> [B]    [C]
```
Caused the runtime to restart nodes A and C, but *not* B (as B was considered 'rewired' whereas A and C were considered 'linked'). That's just wrong.
Makes sense to restart anything and everything that has been touched by a modification.
> Include rewired nodes when calculating Modified Flows stop list

- packages/node_modules/node-red/package.json
- packages/node_modules/node-red/red.js
- packages/node_modules/node-red/settings.js
Closes #4759 
Adds `httpStaticCors` to allow cors configuration to be applied to the `httpStatic` routes.
If `httpStatic` is provided as an array of configurations, they can each contain their own `cors` property, to allow for per-route configurations.
> Add `httpStaticCors`

- packages/node_modules/@node-red/nodes/core/network/21-httprequest.js
closes #4787
I suspect, given #4787 and #4789 the best course of action for the short term is to remove the default User-Agent
This PR removes default user-agent as per NR 3.x stream
> Remove default user agent

- packages/node_modules/@node-red/editor-client/src/js/ui/tab-info-outliner.js
I added tooltip for subflow instance button on info tab.
> Add tooltip for number of subflow instance on info tab

- packages/node_modules/@node-red/editor-client/src/js/ui/editor.js
Fix the config node select value assignment for "none":
- Remove old code in `updateConfigNodeSelect` that is supposed to assign the select value.
- Fix the value assignment of the select which used the label as value.
More informations on video [here](https://discourse.nodered.org/t/home-assistant-node-status-disabled/88858/9?u=gogovega).
> Fix the config node select value assignment

- packages/node_modules/@node-red/nodes/core/network/21-httprequest.js
- test/nodes/core/network/21-httprequest_spec.js
As UI for entering a proxy does not have a means for setting separate HTTP/HTTPS both agents should be set on the request
> UI proxy should setup agents for both http_proxy and https_proxy 

- packages/node_modules/@node-red/nodes/core/sequence/17-split.html
- packages/node_modules/@node-red/nodes/core/sequence/17-split.js
- packages/node_modules/@node-red/nodes/locales/en-US/messages.json
This is an alternative fix for #4781. Instead of PR #4795.
Instead of adding msg.complete on the join node - this optionally allows use of msg.parts in the join node when in manual mode. Default is not to use msg.parts. So is still breaking compared to Node-RED 3.x but is a cleaner fix in that it should also work with other nodes that create msg.parts.
> make using msg.parts optional in join node

- packages/node_modules/@node-red/editor-client/src/js/ui/editor.js
Use `_ADD_` value for both `add new...` and `none` options (introduced in #4627).
This resolves #4788, #4799 and a bunch of other bugs in the forum.
> Use `_ADD_` value for both `add new...` and `none` options

- packages/node_modules/@node-red/editor-client/src/js/ui/subflow.js
The subflow instance form wasn't setting a proper `id` on the credentials typedInput. This would lead to the value not being captured properly.
I'm slightly nervous of this fix as it's touching lines of code that haven't been touched for a long time - whic implies this has been broken for a long time. But I'm certain I've used this feature. I've tried all the usual scenarios and it appears to work okay.
> Ensure subflow instance credential property values are extracted

- packages/node_modules/@node-red/runtime/lib/flows/index.js
Fixes #4798 
The group nodes were not being included in the `/flow` response - as the runtime keeps them listed separately.
This ensures the groups nodes are included in the `nodes` property of the flow/subflow export.
> Ensure group nodes are properly exported in /flow api

- packages/node_modules/@node-red/editor-client/src/js/ui/editors/mermaid.js
By default `$.getScript` will append a timestamp-based query param to ensure the script doesn't get cached by the browser. This is entirely not what we want it to do.
We already have a cache-buster query param we use on all asserts loaded directly from the base html. This cache-buster value only changes when a new NR version is installed - which is when we want to ensure the browser loads the new version of the assets.
This PR updates the mermaid loading code to use our cache-buster value and not the timestamp one. This will save over 3Mb of traffic on each editor load (after the initial load).
> Ensure mermaid.min.js is cached properly between loads of the editor

- packages/node_modules/@node-red/runtime/lib/multiplayer/index.js
Fixes #4814 
Having stepped through the logic in the multiplayer code, I can't quite see how `session` can be undefined to cause the exception reported in #4814. However, the evidence shows it is possible to happen.
This PR adds a suitable guard to ensure we don't get an uncaught exception when it does.
Will need to revisit this as we progress the multiplayer features.
> Guard against undefined sessions in multiplayer

- packages/node_modules/@node-red/editor-api/lib/auth/index.js
In 4.0 we added support for customising the auth session cookie via `httpAdminCookieOptions`.
The session cookie still uses the default `connect.sid` name however. For reasons, we have a need to customise this cookie name - to avoid potential clashes.
I considered proposing hardcoding the cookie name to something different, but it feels much safer to make this customisable - hence this PR.
Whilst technically the cookie name isn't part of the cookie options object the underlying library uses, I don't see a good reason not to include it in the `httpAdminCookieOptions` object - we just have to extract it and pass it through to the right place.
---
Whilst investigating the original issue that has led to this PR, I also spotted our error handling around oauth authentication wasn't ideal.
We …
> Allow auth cookie name to be customised

- packages/node_modules/@node-red/editor-client/src/js/ui/editor.js
Fix node validation if the property is not required.
Issue described on the [Forum](https://discourse.nodered.org/t/node-edit-dialogue-json-input-complaining-about-being-null-version-4-0-0-18/88997).
> Fix node validation if the property is not required

- packages/node_modules/@node-red/editor-client/src/js/ui/editors/code-editors/monaco.js
closes #4820
1. call editor.dispose at end of destroy call
2. iterate any editors not in DOM and call dispose
> Clean up orphaned editors

- packages/node_modules/@node-red/editor-client/src/sass/colors.scss
As discussed [on the forum](https://discourse.nodered.org/t/can-we-have-a-more-subtle-border-on-the-header/89043), I'm proposing to use a color that makes the header border more subtle. I used the same red from the Deploy button.
Now:
Then:
It also works well with themes. Here's an example using the 'dark' theme.
Now:
Then:
> Use a more subtle border on the header

- packages/node_modules/@node-red/nodes/core/sequence/19-batch.html
- packages/node_modules/@node-red/nodes/core/sequence/19-batch.js
- packages/node_modules/@node-red/nodes/locales/en-US/messages.json
- test/nodes/core/sequence/19-batch_spec.js
(ie index = count -1). Useful to close at end of files etc.
This PR adds a option to the batch node to allow it to terminate/send the batch early if the msg.parts indicates the end of a sequence - ie if msg.parts.index = msg.parts.count - 1 
Useful if you want to chunk say a file into batches of lines - but also send the last few remaining lines at the end of the file... etc
See forum request here - https://discourse.nodered.org/t/feature-request-read-file-set-msg-complete-to-true-for-last-line/89225
> Let batch node terminate "early" if msg.parts set to end of sequence

- packages/node_modules/@node-red/editor-client/src/js/ui/contextMenu.js
Fixes #4827.
If the node in the selection is a group, must retrieve the nodes of that group.
> Fix menu to enable/disable selection when it's a group

- .github/workflows/tests.yml
Node 22.5 has a regression causing npm install to hang. This PR pins our Node 22 version to 22.4.x for the time being.
We'll revert this once the issue has been resolved.
> Back off node 22.5

- packages/node_modules/@node-red/editor-client/src/js/ui/view.js
When shift-moving link node wires, the old wire wasn't been removed.
This fixes that, and ensures the undo history replaces the wire.
> Fix moving link wires

- packages/node_modules/@node-red/nodes/core/network/10-mqtt.js
Fixes #4858
With MQTT, will payload must be a string. In my testing, this is the case for both v3.1.1 and v5.
This PR ensures that if it is set, then it is formatted as a string.
> Ensure will payload is a string

- packages/node_modules/@node-red/editor-client/src/js/ui/editor.js
The config node select box was reusing the id of the first env-defined config option - so that one would always be selected regardless of which actual env-defined option was picked.
> Fix env-var config select when multiple defined

- packages/node_modules/@node-red/editor-client/src/js/ui/actionList.js
- packages/node_modules/@node-red/editor-client/src/js/ui/contextMenu.js
- packages/node_modules/@node-red/editor-client/src/js/ui/workspaces.js
- packages/node_modules/@node-red/editor-client/src/sass/tabs.scss
Fixes #4864, #4870
- Ensures the context menu does not show flow-add/delete options if disabled in the editorTheme. (#4864)
- Ensures the context menu does not show action list option if disabled in the editorTheme. (#4870)
Also hides the 'add flow' button in the workspace tab bar and skips registering the corresponding actions.
> Hide add-flow options when disabled via editorTheme

- packages/node_modules/@node-red/nodes/core/network/10-mqtt.js
closes #4876
Call `setStatusDisconnected` whenever an mqtt nodes' 'close' handler is called.
NOTE: Any users depending on status events from the MQTT nodes should notice no _real_ difference since the change only acts upon deploying changes and shutting down Node-RED (i.e. when a nodes deconstructor is called via the `close` event) (and all bets are off)
NOTE2: I did consider "clearing" the status however it felt more sane to say "disconnected" when "no broker" was set.
> Set status of mqtt nodes to "disconnected" when deregistered from broker

- packages/node_modules/@node-red/util/lib/log.js
- test/unit/@node-red/util/lib/log_spec.js
`util.log` has long been deprecated and with Node 22, generates large warnings on first use.
This removes our use of that function by reimplementing it in our own code. The output format is identical so as not to break any lazy log parsers.
> Remove use of util.log

- packages/node_modules/@node-red/editor-client/src/js/ui/typeSearch.js
I noticed the quick-add dialog when adding a virtual link between link nodes was offering Junction as a valid option; we don't support junctions on virtual links.
This fixes how we apply the filter of the quick-add dialog to ensure Junction isn't included. The existing if statement had gotten a bit too complex; broken out into easier-to-understand checks.
> Do not include Junction type in quick-add for virtual links

- CITATION.cff
Recently I wanted to cite Node-RED for an academic work. Online search led me to https://discourse.nodered.org/t/citing-node-red-in-a-scientific-publication/52412/5 and https://nodered.org/about/#citing-node-red which I will use for my citation.
GitHub is able to show a "Cite this repository" if a citation file is added to the root of the repository as described in https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files. Even though there is information about citation in the node-red website, having a dedicated button in the GitHub repository is nice too (personally, it's the first place I look).
I made this PR to add the citation file required to enable this functionality in case you find this feature …
> GitHub: Add citation file to enable "Cite this repository" feature

- packages/node_modules/@node-red/editor-client/src/js/ui/view.js
Fixes #4881
When triggering the quick-add dialog via the context menu, we set state to QUICK_JOINING. Part of this includes setting up a key listener for when the user releases the cmd/ctrl key to exit QUICK_JOINING mode. However, when triggered via context menu, the keyboard isn't touched, so we are left in QUICK_JOINING mode. The user doesn't know to press/release cmd/ctrl to exit this mode.
This fix adds the escape key to the list of keys that will exit QUICK_JOINING mode.
It also updates the handling of clicking in the workspace when in QJ mode. Previously it was checking for the keyboard modifiers - but it should only do this when in default mode. When in QJ mode, it should just show the dialog.
> Stay in quick-add mode following context menu insert

- packages/node_modules/@node-red/editor-client/src/js/ui/workspaces.js
The page title should always be the name of the active workspace, but the name is not updated after changing tab and subflow name. To solve this problem, I added handling to update the page title.
> Refresh page title after changing tab name

- packages/node_modules/@node-red/editor-client/src/js/nodes.js
Fixes #4891.
#4857 ignores that `link call` node can call out of a subflow.
> Fix `link call` node can call out of a subflow

- packages/node_modules/@node-red/editor-client/src/js/ui/deploy.js
Fixes #4888.
In order to modify nodes, subflows/workspaces are temporarily unlocked.
An event is triggered for any subflow/workspace that has changed. This event will always contain an **unlocked** workspace because the re-locking only happens after all events have been triggered.
> Fix wrong unlock state when event is triggered after deployment

- scripts/generate-publish-script.js
The generate-publish-script needs to know what `latest` major version is so it generates the right tags. I always forget to bump this and end up doing it manually. Finally getting this update into the script.
> Bump generate-publish-script with latest

- packages/node_modules/@node-red/editor-client/src/js/nodes.js
Fixes #4891 again.
With #4892, if `otherNode` is not in a Subflow, the following check will deny the link because the `link call` node is in Subflow 🤦‍♂️ 🙄
> Refix link call node can call out of a subflow

- packages/node_modules/@node-red/editor-client/src/js/ui/view-tools.js
As discussed in the [forum](https://discourse.nodered.org/t/resetting-the-default-debug-node-name/92285), this PR improves the auto-generation of the node name to take the first available number.
So if existing numbers are 1,3 and 4. The new number is 2 instead of 5.
> Improve the node name auto-generated with the first available number

- packages/node_modules/@node-red/editor-client/src/js/ui/editors/envVarList.js
The `envVar` editable list should be sortable.
If the value is not `true`, the bar (`fa fa-bars`) is not added.
Resolves https://discourse.nodered.org/t/feature-request-rearrange-global-environment-variables/89502.
> Fix `envVar` editable list should be sortable

- packages/node_modules/@node-red/nodes/core/function/10-function.js
Resolves #4923.
Apply `envVarExcludes` setting to `RED.util.getSetting` into the function node.
> Apply `envVarExcludes` setting to `util.getSetting` into the function node

- packages/node_modules/@node-red/nodes/locales/en-US/network/10-mqtt.html
The mqtt node supports getSubscriptions and this is already implemented (See:
https://github.com/node-red/node-red/blob/master/packages/node_modules/%40node-red/nodes/core/network/10-mqtt.js#L1288), but it's missing in the docs. I was looking for this functionality, but I ended up discovering it accidentally in the code.
> Missing getSubscriptions in the docs while its implemented

- packages/node_modules/@node-red/editor-client/src/js/nodes.js
Fixes #4831.
`moduleList` does not contain the plugins, have to ask `RED.plugins`.
> Fix `setModulePendingUpdated` with plugins

- packages/node_modules/@node-red/editor-client/src/js/ui/palette-editor.js
Part of #4931.
This PR adds a queue to the Palette Manager so that the user can trigger multiple module installs/updates.
To support the future "Update all" button.
> Add a queue while installing or removing a module from the Palette Manager

- packages/node_modules/@node-red/editor-client/src/js/ui/typeSearch.js
Remove disabled node types from QuickAddDialog list.
> Remove disabled node types from QuickAddDialog list

- packages/node_modules/@node-red/editor-client/locales/en-US/editor.json
- packages/node_modules/@node-red/editor-client/src/js/ui/palette-editor.js
- packages/node_modules/@node-red/editor-client/src/js/ui/statusBar.js
- packages/node_modules/@node-red/editor-client/src/sass/palette-editor.scss
This is a continuation of #4935 that replaces that PR.
It refactors the palette manager code to allow us to reload the catalogues *without* generating the whole palette manager UI. This makes it more efficient to do background checks of updates so we can keep the status widget up to date.
> Add a new `update available` widget to statusBar

- packages/node_modules/@node-red/nodes/core/function/89-delay.js
- test/nodes/core/function/89-delay_spec.js
to fix #4830
This fix if for #4830 - it makes sending in a payload to the delay node in rate-limit mode, that has msg.reset set, not send any associated payload if the queue is empty.  (If the queue had anything in then nothing is sent.)
Note you can set msg.flush AND msg.reset - and if the queue does have contents it will flush that many - and if the msg has a payload that is added to the queue and then maybe flushed if appropriate. IE flush happens before reset.
> Make delay node rate limit reset consistent - not send on reset.

- packages/node_modules/@node-red/editor-client/src/js/nodes.js
- packages/node_modules/@node-red/editor-client/src/js/ui/clipboard.js
- packages/node_modules/@node-red/editor-client/src/js/ui/view.js
Fixes the following edge cases of #4599 :
- Do not save modules when deploying
- Do not import `global-config` if it does not contain environment variables
- If it contains, import the `global-config` or merge the environment variables if `global-config` exists
> Fix import of module list

- packages/node_modules/@node-red/editor-client/src/sass/palette.scss
Add the vertical marker to the palette hand.
See [preview in the Forum](https://discourse.nodered.org/t/wheres-my-sidebar-nodes/93091/5).
> Add the vertical marker to the palette hand

- packages/node_modules/@node-red/editor-client/src/js/ui/view.js
Fix wrong length attribute of Set
Fix wrong attributes were used.
https://github.com/node-red/node-red/blob/e48607c74317f047f09035872c9879816a3a0ed3/packages/node_modules/%40node-red/editor-client/src/js/ui/view.js#L291
> Change groups.length to groups.size

- packages/node_modules/@node-red/runtime/lib/flows/util.js
Fixes #4942.
If the value has the form `${CONF_NODE}`, it means that the sublow node is in a subflow.
Have to check if the env config node exists in the parent subflow.
> Get the env config node from the parent subflow

- packages/node_modules/@node-red/editor-client/src/js/ui/view.js
Whilst reviewing #4959 spotted we had a variable name reused in view.js that would have been caught if we applied linting... that's a topic for another day... so for now, just fixing the clash to avoid future confusion.
> Rename variable to avoid confusion in view.js

- packages/node_modules/@node-red/editor-client/src/js/nodes.js
Fix updating the Subflow name during a copy:
- If the Subflow is copied, updating the id before calling `addSubflow` causes `createNewIds` is false.
- Name update starts at 2 (instead of 1)
Related PR: #4757.
> Fix updating the Subflow name during a copy

- packages/node_modules/@node-red/editor-client/src/js/keymap.json
- packages/node_modules/@node-red/editor-client/src/js/nodes.js
[Forum](https://discourse.nodered.org/t/inject-node-trigger-via-hotkey/92154) request.
Triggers button action for selected nodes via a Hotkey (`ctrl-shift-t`).
> Trigger button action of the selected nodes with new Hotkey

- packages/node_modules/@node-red/editor-client/src/js/ui/editor.js
This PR adds the config node to `RED.history` to allow undo/redo changes.
It also fixes change handling (`node.changed`) - not all properties were checked.
Other changes:
- Remove an old duplicate save code with the panes system.
- Events triggering has been fixed - a `change` event should only be triggered if there are changes.
- Modify a users must trigger an `change` event.
- The logic which checks if users can continue to be associated with this config node has been modified: a user will be kept only if at least one property uses the config node in the correct scope. This allows to remove users who have nothing to do there (even if this case is not supposed to happen).
> Add config node to `RED.history` and handle `changed` prop

- packages/node_modules/@node-red/editor-client/src/js/ui/editors/panes/properties.js
- Add credentials to the history (`editState.changes`) so that they are reversible.
- Fix the handler that determines if a credential has changed.
> Fix save and history of credentials for panes

- packages/node_modules/@node-red/editor-client/src/js/nodes.js
Fix a node with an invalid number of outputs - isNaN check should be at the top.
Retrieve `nodeImported.outputs` only if the node definition allows it.
Related PR: #4757.
> Fix a node with an invalid number of outputs

- packages/node_modules/@node-red/editor-client/src/js/history.js
- packages/node_modules/@node-red/editor-client/src/js/nodes.js
- packages/node_modules/@node-red/editor-client/src/js/ui/editors/panes/envVarProperties.js
- packages/node_modules/@node-red/editor-client/src/js/ui/editors/panes/properties.js
- packages/node_modules/@node-red/editor-client/src/js/ui/subflow.js
Fixes https://github.com/FlowFuse/node-red-dashboard/issues/754.
#4587 introduced a feature that allows nodes in a subflow to choose a config node from the environment variables.
It's the subflow node that will define which "real" config node will be the environment variable. It is also this node that should be added to the users of the config node.
This PR therefore handles it:
- when adding/removing the subflow node
- when saving the subflow node config
- into the history (undo/redo subflow node changes)
This PR also fixes the node object added to the config node users, it must be the proxy object. Detected in #4807.
> Handle subflow node as user of config nodes

- packages/node_modules/@node-red/nodes/core/storage/10-file.js
In the same spirit as the previous [performance enhancement of the CSV node](https://github.com/node-red/node-red/pull/4349)
By using a simple array of buffer and using a Buffer.concat call, we skip alot of memory allocation - copy overhead that heavily reduce memory allocation and garbage collection on fairly "big" file sizes.
Those tests were run on a Linux machine with alot of memory and SSD storage, meaning the file can easily sits in the memory and this does not actually benchmark the disk itself, i've accessed the files multiple times to make sure they were cached.
Much like for the CSV nodes, the change is mostly to make "bigger files" works properly, starting with around 10MB files the time taken to read file as a unique Buffer starts skyrocketing.
Once more we're looking at time …
> Performance : make reading single buffer / string file faster by not re-allocating and handling huge buffers

- packages/node_modules/@node-red/editor-client/src/js/ui/contextMenu.js
- packages/node_modules/@node-red/editor-client/src/js/ui/view-tools.js
- packages/node_modules/@node-red/editor-client/src/js/ui/view.js
Fixes #4969 
When triggered via the context menu...
- Accounts for view zoom level when calculating junction/node insert position via context menu
- Inserts junction in a wire where the mouse was clicked
- Accounts for view zoom level when calculating junction insert position via slide action
> Fix junction insert position via context menu

- packages/node_modules/@node-red/editor-client/src/js/ui/clipboard.js
Fixes #4962
The import dialog already did some better validation of JSON pasted into the dialog before we tried to import it. This PR pulls out that logic into a reusable function, and applies it to the validation of JSON dropped into the workspace.
For the DND case, and errors are logged to the console, but not shown to the user as a notification.
The validation checks for:
1. An array
2. each array element is an object, with properties 'id' and 'type'
> Validate json dropped into editor to avoid unhelpful error messages

- packages/node_modules/@node-red/editor-client/src/js/history.js
- packages/node_modules/@node-red/editor-client/src/js/ui/editor.js
- packages/node_modules/@node-red/editor-client/src/js/ui/editors/panes/properties.js
Fixes undo history for credentials.
A lot of the code added in editor.js wasn't needed; the work to track changes in creds was already done in `packages/node_modules/@node-red/editor-client/src/js/ui/editors/panes/properties.js` - however it wasn't tracking the `has_XYZ` meta property needed to handle the full set of password change lifecycles.
> Rework saving of credentials to undo history

- packages/node_modules/@node-red/nodes/core/parsers/70-CSV.js
- packages/node_modules/@node-red/nodes/core/parsers/lib/csv/index.js
- test/nodes/core/parsers/70-CSV_spec.js
Fixes #4977
`node.sep` was not being honoured in lots of places when generating CSV. 
Given how many places had `,` hardcoded, I'm not 100% confident this won't have other side effects - so want to get more eyes on this (particularly from @Steve-Mcl) before merging.
> Ensure node.sep is honoured when generating CSV

- packages/node_modules/@node-red/registry/lib/installer.js
- test/unit/@node-red/registry/lib/installer_spec.js
The pull request is to fix an issue with installing local Tarball files that have spaces in the file path. When attempting to install a package with a file path containing spaces, such as "C:\ProgramData\Node-Red Installer\nodes\objectif-lune-node-red-contrib-package.tgz", the installation would fail with an error message indicating the path was trimmed, like this:
"ERR! path C:\ProgramData\Node-Red/package.json"
The root cause is that the npm install command was not properly handling the file path with spaces, and as a result, the path was being truncated. also in the logs it have this npm install command 
npm.cmd install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production --engine-strict C:\ProgramData\Node-Red …
>  Add qoutes when installing local tgz to fix spacing in the file path

- packages/node_modules/@node-red/editor-api/lib/auth/index.js
- packages/node_modules/@node-red/editor-api/lib/editor/theme.js
- packages/node_modules/@node-red/editor-client/src/js/user.js
If `adminAuth` is configured without a `type` (normally `credentials` or `strategy`) the login dialog is blank.
When `adminAuth` is also configured with `tokens` etc to support token based authentication, it would be useful to be able to provide a custom message and login prompt in the dialog.
This PR adds support for doing just that. The following properties can be added to the `editorTheme.login` property:
```
editorTheme: {
login: {
message: "Hi there Twitchers",
button: { url: "https://nodered.org", label: "Login via FlowFuse" }
}
}
```
> Support custom login message and button

- packages/node_modules/@node-red/editor-client/src/js/nodes.js
Fixes #4994.
#4807 removed some duplicate code that handles the user list. Unfortunately it was forgotten that config nodes can also use another config node.
During the import, the list of config nodes is sorted to ensure that nested nodes are created before updating the user list.
> Fix the user list of nested config node

- packages/node_modules/@node-red/editor-client/src/js/nodes.js
Fixes https://discourse.nodered.org/t/to-import-a-flow-without-dashboard-installed/93963.
Introduced by #4808.
`def` can be undefined. The default definition is added directly to the node, so `node._def` must be used instead.
> Fix def can be undefined if the type is missing

- packages/node_modules/@node-red/editor-client/src/js/nodes.js
Fixes #4999 
This PR changes how we sort config nodes when they are being imported to ensure that they are only added once anything they depend on has been added.
For example, given the graph:
```
A -> B -> C
D -/
```
We must ensure that `C` is added first, then `B` and `D` can be added, and then `A`.
> Fix config node sort order when importing

- packages/node_modules/@node-red/nodes/core/function/10-switch.js
Fixes #5013
When a switch node is configured to repair a message sequence, it can get into a recursive call stack when eventually sending the messages onwards.
This fixes by throwing a `setImmediate` in to break up the call stack.
> Avoid exceeding call stack when draining message group in Switch

- packages/node_modules/@node-red/editor-client/src/js/ui/library.js
Closes #5004
PR #5004 proposed a fix for the icons missing in the Function library browser. However the proposed fix would have then broken the icons in the Import/Export dialog.
If a library wants to use a font-awesome icon (eg `fa-foo`), its icon property is expected to be `font-awesome/fa-foo`. This was being handled properly by the Import/Export dialog, but not by the library browser.
The fix here is to apply the same parsing logic across both dialogs.
> Fix library icon handling within library browser component

- packages/node_modules/@node-red/runtime/lib/flows/Flow.js
- packages/node_modules/@node-red/runtime/lib/flows/Group.js
- packages/node_modules/@node-red/runtime/lib/flows/util.js
Fixes #5009 
This allows an env var definition to use `$global/flowContext()` lookups.
Using context in an env var definition isn't that useful, as the value is evaluated when the flow starts and doesn't update if context changes.
But that said, nor should trying to use it cause NR to crash as reported in #5009.
> Allow env var access to context

- packages/node_modules/@node-red/editor-client/src/js/ui/view.js
Fixes #5020 
When triggering quick-add within a group, the group was being selected. This left things in a bad state with both the added node and its group selected. This is not a state we should get into. The code that handles dragging something into a group was then getting tripped up because it was trying to add the parent group into the child group.
This fixes it by not getting into that bad state. Looking at the code, I think this was a remnant of the previous refactoring of group UX and should have been removed then.
> Do not select group when triggering quick-add within it

- packages/node_modules/@node-red/editor-client/src/js/ui/editor.js
Fixes #5010 
This updates the env vars of subflow instances when a subflow env var is removed - whilst also allowing it to be undone.
> Update sf instance env vars when removed from template

- packages/node_modules/@node-red/editor-client/src/js/ui/tab-context.js
- packages/node_modules/@node-red/editor-client/src/js/ui/utils.js
- packages/node_modules/@node-red/nodes/core/common/lib/debug/debug-utils.js
Closes #5008
This enables the context sidebar to remember its expanded state when refreshing.
There was some overlap with the existing functionality to pin properties in the debug sidebar, however we didn't want the user to have to explicitly pin things open in this case.
> Remember context sidebar tree state when refreshing

- packages/node_modules/@node-red/editor-client/src/js/multiplayer.js
- packages/node_modules/@node-red/editor-client/src/js/user.js
Fixes #5036
If `user.username` is not defined we can't use it to generate the two-letter user icon.
This fixes it by falling back to `user.email` if set, otherwise shows the default user icon.
> Handle undefined username when generating user icon

- packages/node_modules/@node-red/editor-client/src/js/ui/common/autoComplete.js
- packages/node_modules/@node-red/editor-client/src/js/ui/common/typedInput.js
- packages/node_modules/@node-red/editor-client/src/sass/ui/common/autoComplete.scss
- packages/node_modules/@node-red/runtime/lib/api/context.js
Fixes #5028
This improves our handling of auto-complete suggestions when the suggestions are bigger than the auto-complete drop-down window.
1. We now expand the drop-down to match the width of the corresponding TypedInput (keeping the 300px minimum width)
2. We show the end of the completion in favour of the beginning - so long completions don't get cut off when they get interesting
3. Updated backend API to return type hints along with the key names - scope to show type info in the autocomplete, but not as part of this PR
> Handle long auto-complete suggests

- packages/node_modules/@node-red/editor-client/src/js/ui/deploy.js
With [editorTheme.deployButton](https://nodered.org/docs/user-guide/runtime/configuration) is possible to customize the _Deploy_ button, but changes on _icon_ or _label_ will only take effect if the `type="simple"`.  
I would like to customize the _label_ and also keep the _default_ deploy drop-down options.
> feat: Add custom label for default deploy button in settings.editorTheme

- packages/node_modules/@node-red/runtime/lib/api/context.js
Currently there is no way to view the Flow level context of a subflow. This is because when viewing the subflow template, we aren't viewing a concrete instance of the subflow to show the information in the Flow section of the context sidebar.
With this PR, when a subflow instance node is selected in a regular flow, its flow level context will now be shown under the 'node' section of the context sidebar. This feels a sensible and pragmatic way to expose this level of context in the editor.
> Show subflow flow context under node section of sidebar

- packages/node_modules/@node-red/editor-client/src/js/ui/editors/code-editors/monaco.js
closes #5047 
Prevent monaco error complaining about symbols
> Prevent symbol usage warning in monaco

- packages/node_modules/@node-red/editor-client/src/js/ui/common/typedInput.js
If the `typedInput` is a list of options, the tooltip should snap to its label element.
```js
$("#node-input-example").typedInput({type:"fruit", types:[{
value: "fruit",
options: [
{ value: "apple", label: "Apple"},
{ value: "banana", label: "Banana"},
{ value: "cherry", label: "Cherry"},
],
validate: function (v) {...}
}]})
```
> Fix tooltip snapping based on `typedInput` type

- packages/node_modules/@node-red/editor-api/lib/editor/theme.js
Previously i introduced a change that allows to set the _label_ in the "Deploy" button in the UI editor([PR-5030](https://github.com/node-red/node-red/pull/5030)) despite of _deployButton.type_.
After the [v4.0.9](https://github.com/node-red/node-red/releases/tag/4.0.9) release, the change was not taking effect. The solution was not complete.
Hereby this PR. Deeper in the codebase, i found out that the _deployButton_ is only set in _themeSettings_ if `type=="simple"`. Values that will be fetched by the runtime. Therefore i made changes to set the _label_ before this condition.
> fix: set label in themeSettings.deployButton despite type attribute

- packages/node_modules/@node-red/editor-client/src/js/ui/deploy.js
Ref: https://discourse.nodered.org/t/deploy-with-improperly-configured-nodes/95464.
Ignore invalid nodes and unused config nodes if they are disabled or the parent flow is disabled.
> Ignore state of disabled nodes/flows during deployment

- packages/node_modules/@node-red/editor-client/src/js/ui/editors/markdown.js
Along with image drop, this change adds text drop into the editor. 
This is useful for highlighting text and then drag that text into the description of a node. Similar creating a mermaid diagram using a third-party tool and then drag the text into the description.
Also drop text files is also supported for longer texts.
Along with image drag&drop, this adds drop highlighted text and text files into the markdown editor.
Forum topic: https://discourse.nodered.org/t/text-and-text-file-drag-drop-into-the-description-editor/95532
> Support text drag & drop into markdown editor

- packages/node_modules/@node-red/editor-client/src/js/ui/tab-config.js
- packages/node_modules/@node-red/editor-client/src/sass/tab-config.scss
Work done in #4782 but rebased onto master.
Add the `changed` badge to the config node and the category.
> Add the `changed` badge to the config node

- .gitignore
I use [EditorConfig](https://editorconfig.org/) to adjust my editor settings for indentation.
My settings should probably be best ignored, unless there is a desire to have a project wide .editorconfig
Added a .editorconfig and it's probably best ignored. 
I don't know but perhaps it might also be helpful to have a project wide .editorconfig - if there is demand. It's designed to be editor agnostic so there is no vim v. emacs v. vscode debate involved.
> Add .editorconfig to .gitignore

- packages/node_modules/@node-red/editor-client/locales/en-US/editor.json
- packages/node_modules/@node-red/editor-client/locales/es-ES/editor.json
- packages/node_modules/@node-red/editor-client/locales/fr/editor.json
- packages/node_modules/@node-red/editor-client/locales/ja/editor.json
- packages/node_modules/@node-red/editor-client/src/js/ui/editors/code-editor.js
- packages/node_modules/@node-red/editor-client/src/js/ui/editors/markdown.js
- packages/node_modules/@node-red/editor-client/src/sass/dragdrop.scss
Follow on to #5056 
This updates the drop-target appearance for the markdown editor to be a bit more intuitive that it's handling the drop event into the markdown editor window.
Removes the text message (previously 'Drop Image here' - as it now handles images and text).
> Update markdown drop-target appearance

- packages/node_modules/@node-red/editor-client/src/js/ui/workspaces.js
Follow up to #5061 - ensures the config nodes sidebar is refreshed when locking/unlocking a flow via the built-in actions (rather than the edit dialog).
> Refresh config node sidebar when changing lock state of a flow

- packages/node_modules/@node-red/editor-client/src/js/history.js
- packages/node_modules/@node-red/editor-client/src/js/ui/editor.js
- packages/node_modules/@node-red/editor-client/src/js/ui/editors/panes/properties.js
- packages/node_modules/@node-red/editor-client/src/js/ui/palette.js
- Rewrite of `showEditSubflowDialog` (var replacement + prettier + camelCase)
- Change the prefix from `node-input` to `subflow-input`
The Subflow defaults definition contains only `name` and `env`. So we can directly use the right prefix to prepare the `Name` entry.
- Handle color change for instances:
- `redraw` need the flag `_colorChanged` to update the color (for instances)
- Palette uses the color defined in `sf.color` but this one can be undefined. In addition the color should respect the theme.
- Color change is now handled by `RED.history`.
> Fix undo of subflow color change not applying to instances

- packages/node_modules/@node-red/editor-client/src/js/ui/utils.js
- packages/node_modules/@node-red/util/lib/util.js
- test/nodes/core/common/21-debug_spec.js
- test/unit/@node-red/util/lib/util_spec.js
Improves display of error objects so it shows stack and other information.
Previously, it would display `<Name>: <message>` as a String. With this PR it now shows errors as objects with their common properties - name, message, stack and cause (if set). The type hint is also set to 'error' to be clear.
> Improve debug display of error objects

- packages/node_modules/@node-red/runtime/lib/flows/Flow.js
- packages/node_modules/@node-red/util/lib/util.js
Closes #5080 
Add `code` property to the error object emitted by the Catch node.
Also updates the changes from  #5079 to also include `code` if present in Error objects.
> Add code to error object sent by Catch node

- packages/node_modules/@node-red/editor-client/src/js/ui/palette.js
- packages/node_modules/@node-red/editor-client/src/js/ui/view.js
Fixes up the application of scale factor in FireFox when dealing with dragging a node from the palette over a link, as well as dragging an existing node over a link.
Also adds some padding to the bounding box used to detect collisions when its zero height - ie a horizontal link.
> Properly handle scale factor in getLinksAtPoint for firefox

- package.json
- packages/node_modules/@node-red/editor-client/src/js/i18n.js
- packages/node_modules/@node-red/util/lib/i18n.js
- packages/node_modules/@node-red/util/package.json
This updates i18next to latest to pickup upstream security fixes.
This major version bump drops support for their v3 message catalogue format. We can't drop support for that as it would break 3rd party nodes using that format.
Thankfully the mapping from v3 to v4 is fairly straight forward and relates primarily to how plurals are handled. I've added code to migrate between the formats automatically when the catalog is loaded.
> Bump i18next to 24.x and auto-migrate message catalog format

- packages/node_modules/@node-red/editor-client/src/js/ui/contextMenu.js
- packages/node_modules/@node-red/editor-client/src/js/ui/view-tools.js
Fixes #5090 
The code that determined whether to enable the show/hide label context menu items was not handling the link nodes properly.
If a node doesn't have an `l` property, we need to check if `showLabel` is set on its definition to see what the default value of `l` should be. We cannot assume that lack of an `l` property means the label is shown - as link nodes set `showLabel` to false.
Whilst verifying this fix, I also spotted the history handling of the show/hide action was also incorrect. It was also  it was setting the old value to the wrong default (without taking into account the `showLabel` value).
> Handle link nodes with show/hide label action

- packages/node_modules/@node-red/editor-client/locales/en-US/editor.json
- packages/node_modules/@node-red/editor-client/src/js/ui/palette-editor.js
- packages/node_modules/@node-red/editor-client/src/sass/palette-editor.scss
- Modifies the Palette search to prioritise downloads (in the past 7 days) first. This retuns far more appropriate results in an easier order to parse. The more popular a package is, the more likely it is that the person searching a given term is looking for that package.
> Default Palette Search: Sort by Downloads

- packages/node_modules/@node-red/editor-client/locales/en-US/editor.json
- packages/node_modules/@node-red/editor-client/src/js/ui/userSettings.js
- packages/node_modules/@node-red/editor-client/src/js/ui/view.js
- packages/node_modules/@node-red/editor-client/src/sass/flow.scss
Closes #4375 
Adds an annotation to any nodes that have a non-blank `info` property - ie the 'description' field.
Clicking on the annotation opens the edit dialog for the node with the description tab shown.
Not 100% about this, but wanted to get the code shared. 
Have also added a user option to toggle whether the setting is shown or not (consistent with the option we provide to show/hide status).
> Add a node annotation if the info property is set

- packages/node_modules/@node-red/editor-client/src/js/ui/palette-editor.js
Resolves #4865.
- Supports a module with nodes and plugins
- Supports plugins without part in the runtime (no .js file)
- Removes empty node/plugin set (lines 951 & 955)
> Support for a module with nodes and plugins in the palette

- packages/node_modules/@node-red/editor-client/src/js/ui/palette-editor.js
#4599 added the ability to pre-populate the filter list of the Palette Manager. This was applied to both the Node and Install tab, however just spotted, the filter didn't work on the Node tab. 4599 only needed it for the Install tab - so wasn't noticied there.
The Update Available notification relies on it working on the Node tab, which this PR fixes.
It also clears the filter when the dialog is closed - which feels a better behaviour than remembering the old filter.
> Fix node tab filtering

- packages/node_modules/@node-red/editor-client/src/js/ui/utils.js
- packages/node_modules/@node-red/editor-client/src/sass/debug.scss
As described [here](https://discourse.nodered.org/t/visually-truncate-long-strings-in-debug-side-bar/91294), truncates long topic and string messages from the Debug Sidebar with pure CSS solution.
Preview:
> Truncate long messages from the Debug Sidebar

- packages/node_modules/@node-red/editor-client/locales/en-US/editor.json
- packages/node_modules/@node-red/editor-client/src/js/ui/palette-editor.js
- packages/node_modules/@node-red/editor-client/src/sass/palette-editor.scss
Closes #5126 
If the catalogue.json has a `deprecated` flag, the palette manager will now show an indicated against the node in the Install tab
Note: for the purposes of this screenshot, I've hardcoded some values to get it to show up - as it stands the public catalogue doesn't yet include the deprecated flag. The module shown was a randomly picked. The `Do <b>not</b> use me` is custom text provided by the catalogue.json in place of a boolean for the `deprecated` field - as shown here, HTML is escaped so content cannot be injected into the editor via this field.
> Show deprecated message if module flagged

- packages/node_modules/@node-red/registry/lib/loader.js
Use the same approach for plugins, which I used for nodes in https://github.com/node-red/node-red/pull/3669
Basically: when a plugin is transpiled from es modules/typescript, import the default export.
Currently `export =` would need to be used, but that becomes the only export and so nothing else can be exported, which is quite unhandy. See the original PR for more detailed explanation.
> feat: import default export if plugin is a transpiled es module

- packages/node_modules/@node-red/runtime/lib/telemetry/index.js
- `console.log` is replaced by `debug`
- No need to import the `got` module every time `report` is called
> Import `got` module only once when sending metrics

- packages/node_modules/@node-red/editor-client/src/js/nodes.js
Fixes #5133.
If the node definition contains internal properties, they will be removed from the definition.
**NOTE**: `icon`, `info`, and `label` have special behavior.
> Exclude internal properties from node definition

- packages/node_modules/@node-red/editor-client/src/js/ui/common/typedInput.js
Closes #5153.
Allows filtering selectable nodes with typedInput's `node` mode.
Prototypes are:
```ts
filter: string;            // node type
filter: string[];          // list of node type
filter: (node) => boolean; // function that returns a boolean
```
Example:
```js
$(elm).typedInput({
default: "node",
types: ["node"],
node: {
filter: "debug"
//filter: ["debug", "inject"]
//filter: (node) => node.type === "debug"
}
})
```
> Node filter support for typedInput's builtin node

- packages/node_modules/@node-red/nodes/core/function/10-function.js
- packages/node_modules/node-red/settings.js
- test/nodes/core/function/10-function_spec.js
* added default timeout to function node
* added unit test to support defaultFunctionTimeout
---
Issue -> https://github.com/node-red/node-red/issues/4976
This PR introduces the `defaultFunctionTimeout` parameter for the Function node, defined in seconds. The primary purpose of this setting is to prevent blocking code within function blocks from indefinitely halting execution.  
**Key Details:**  
- **Default Value**: `0` (indicating no timeout).  
- **Functionality**:  
- Serves as a default safeguard against blocking operations, such as an infinite loop (`while(1){}`), which can block the main thread.  
- Ensures system stability by unblocking such scenarios after the specified timeout duration.  
- **Precedence**: If `functionTimeout` is specified in the settings file, it overrides …
> Add globalFunctionTimeout

- packages/node_modules/@node-red/nodes/core/common/24-complete.js
- packages/node_modules/@node-red/nodes/core/common/25-status.js
- test/nodes/core/common/24-complete_spec.js
This fix automatically filters out any nodes that are directly connected to the complete node that would otherwise feedback straight into the complete node... It DOES NOT filter nodes that are indirectly connected - but does fix the simple use case where someone connects a debug direct to the complete node to see what is returned but forgets to remove it from the scope of the complete node.
> Fix complete node to not feedback immediately connected nodes

- packages/node_modules/@node-red/nodes/core/network/10-mqtt.js
- test/nodes/core/network/21-mqtt_spec.js
This PR supersedes #4989
It includes the good work by @meeki007 from the original PR and adds the missing fix for the unit test.
> Ensure generated mqtt clientId uses only valid chars

- packages/node_modules/@node-red/nodes/core/function/90-exec.js
Fixes #5139 
Aligns how the node handles the encoding of stdout and stderr to match each other.
> Exec: Make encoding handling consistent between stdout and err

- packages/node_modules/@node-red/nodes/core/function/10-function.js
Closes #4927 
Adds `URL` and `URLSearchParams` as standard globals to the Function node. No reason to hold these out.
> Add URL/URLSearchParams to Function sandbox

- packages/node_modules/@node-red/nodes/core/network/21-httprequest.js
- packages/node_modules/@node-red/nodes/locales/en-US/messages.json
fixes #5171
If `msg.rejectUnauthorized` is a string allow "true", "false" (and upper case versions) otherwise show a warning and use default behaviour.
Boolean values used as is, any other types also ignored.
Targeting `dev` but may also want to back port to the 4.0.x branch
> Allow limited Strings for msg.rejectUnauthorized

- packages/node_modules/@node-red/editor-client/src/js/ui/event-log.js
- packages/node_modules/@node-red/util/lib/exec.js
Based on user feedback, if an install is taking a long time you may close the palette manager window at which point you have no indication that anything is happening. Sometimes the request can timeout, but the install still runs in the background.
This PR adds a spinner widget to the statusBar that is shown if there is ongoing activity in the event log. Clicking on it opens up the event log.
> Add event-log widget to status bar

- packages/node_modules/@node-red/editor-client/src/js/ui/editor.js
Closes #5115.
Prevent the editor to open the same dialog multiple times.
When closing the dialog box, `pop()` is used, so I don't suggest changing the stack order.
NOTE: I have a doubt about `showTypeEditor`.
> Prevent the editor to open the same dialog multiple times

- packages/node_modules/@node-red/editor-client/src/js/red.js
- packages/node_modules/@node-red/editor-client/src/js/ui/common/autoComplete.js
- packages/node_modules/@node-red/nodes/core/network/10-mqtt.html
Closes https://github.com/node-red/node-red/issues/5082
This adds the ability for 3rd party plugins to provide auto-complete suggestions for fields in the editor that have autoComplete enabled.
It updates the `topic` fields in the mqtt in/out nodes to make use of this - although no specific auto-complete plugin is included with this PR.
---
The `autoComplete` widget has been extended to allow the caller to specify a plugin type that should be used as a source of completions.
From the PR, the MQTT node `topic` fields are now setup with:
```
input.autoComplete({
minLength: 0,
completionPluginType: 'node-red-mqtt-topic-autocomplete-source',
context: {
node
}
})
```
- `completionPluginType` identifies the type of plugin to use
- `context` is passed in and will be passed to the plugin to …
> Add support for plugin sources of autoComplete fields

- .github/workflows/tests.yml
- packages/node_modules/@node-red/nodes/core/function/90-exec.js
- packages/node_modules/@node-red/registry/lib/installer.js
- packages/node_modules/@node-red/runtime/lib/storage/localfilesystem/projects/git/index.js
- packages/node_modules/@node-red/util/lib/exec.js
- packages/node_modules/node-red/red.js
Fixes some Node 24 issues:
- removes `util.log` use (which has been removed in Node 24)
- updates use of deprecated functions in child_process
- adds 24 to the test matrix
> Updates for Node 24

- packages/node_modules/@node-red/editor-client/src/js/ui/view.js
Fixes #5219 
When adding a node into a group, the history event is stacked into a multi-type event.
When that also includes a link splice, the multi event was being updated with the splice undo details - whereas it needs to be on the original 'add' event.
This fixes that.
> Add splice history events to original add event

- packages/node_modules/@node-red/nodes/core/sequence/17-split.js
fixes #5251
The code changed from 4.0.x to 4.1.x
This change to to prevent making changes to the orginial input `msg` object incase any values were stored in context (pass by reference).
The change meant that for every output message the whole original input `msg` was being cloned, which could be huge, causing a big performance regresion.
This fix ensures the clone of the orginial `msg` is only done once and the much smaller output message is then cloned again to update `msg.parts` object for each output. This results in lots of small clones rather than lots of very large clones.
> Speed up split node

- packages/node_modules/@node-red/editor-client/locales/en-US/editor.json
- packages/node_modules/@node-red/editor-client/locales/ja/editor.json
- packages/node_modules/@node-red/editor-client/src/js/ui/event-log.js
Users may want to know how the event log view works before clicking the button. Therefore, I added a tooltip to the button.
> Add tooltip for event log view

- packages/node_modules/@node-red/editor-client/src/js/ui/palette-editor.js
#5143 added the icon to the node documentation. To do this, when adding an element to the node list (`nodeList.editableList('addItem', element)`), the URL is looked up in the catalog list and added to the node entry.
The problematic is that elements can be added before all catalogs are loaded; the DOM is built without the icon because the catalog list is empty at that time.
When all catalogs are loaded, each element of the list is refreshed (with `refreshNodeModuleList`), except that the URL is not updated because not handled in `_refreshNodeModule`.
I only noticed this problem now because my connection is slow. Before that I thought that loading catalogs during initialization left enough time before the construction of node elements.
> Fix node documentation icon for long catalog loading
