- nodes/core/storage/66-mongodb.html
- nodes/core/storage/66-mongodb.js
To get pagination out of the find query we need both limit and skip, and skip was missing. This pull request is adding it.
> adding skip to the mongodb input node

- red/log.js
- red/nodes/Node.js
- red/nodes/flows.js
- test/nodes/core/core/58-debug_spec.js
- test/nodes/core/core/80-function_spec.js
- test/nodes/core/parsers/70-HTML_spec.js
- test/nodes/core/parsers/70-JSON_spec.js
- test/nodes/core/parsers/70-XML_spec.js
- test/red/nodes/Flow_spec.js
- test/red/nodes/Node_spec.js
This pull request adds the metric logging mechanism discussed over the last few days. Simply adds the concept of "metric" with various properties (nodeid, message uuid, event which triggered the metric and any other metrics thought useful by the caller). It adds calls when messages are sent and received.
Part of this work has been to remove the "emit" nature of logging, which has caused some test failures, purely because they were checking various things on this emit. This pull request comments out these failing tests (test case failures rather than actual failures) and I will work to fix the testcases but wanted the code up and available.
> Adding metric logging mechanism

- red/storage/localfilesystem.js
Handle 3 core failures on Windows due to library paths that look like "'C:\Users\" instead of "/home" or "./", which caused localfilesystem to create a path with the runtime dir append to the home dir.
> fix 3 localfilesystem tests failing on Windows

- red/i18n.js
I changed the i18n module to initialize its list of supported languages by scanning the locales directory instead of hardcoding an array.
> Initialize list of supported languages from locale directory

- editor/js/ui/library.js
- editor/js/ui/sidebar.js
- editor/js/ui/tab-config.js
- editor/js/ui/tab-info.js
- editor/js/ui/workspaces.js
- editor/templates/index.mst
- locales/en-US/editor.json
- nodes/core/core/58-debug.html
- nodes/core/locales/en-US/messages.json
- red/api/locales.js
- red/i18n.js
This PR converts the text in the sidebar titles and `index.mst` to use NLS. Also, it contains a fix for a typo that creates an error when the `Accept Language` header is not present or it contains a hyphenated locale that is not a supported language (in its hyphenated form or otherwise).
> Added NLS enablement to the sidebar and index

- README.md
A git link requires an SSH key with access to the repo, whilst an HTTPS link can be used by anybody
> https link (rather than git) in dev instructions

- package.json
Noted in https://nodesecurity.io/advisories/uglifyjs_incorrectly_handles_non-boolean_comparisons.
Closes #725 .
> Bump uglify to 2.4.24 to address security advisory

- .travis.yml
- nodes/core/core/89-trigger.js
- test/nodes/core/storage/50-file_spec.js
This pull request has several patches suggested by @dceejay that correct the two errors that were causing Node-RED not to build on Node 4.0.0. One was a bad test that failed when it should have succeeded (now fixed), and the other was a case where code set a value to a string when it was expecting a number.
The request also patches .travis.yml to test against Node 4.0.0 which includes setting up the Travis environment to use the gcc 4.8 compiler.
As it stands, the .travis.yml files allow failures on the 4.0.0 builds to not show up as failures of the main build. At some point that should be switched over, but there's still all of `node-red/node-red-nodes` to get tested under 4.0.0.
> Support for Node 4.0.0 and Travis CI testing for same

- nodes/core/io/21-httpin.js
- package.json
Setting UTF-8 as the default body encoding stops us sending binary
content, e.g. audio, which can be decoded into a Buffer.
Use "Content-Type" header to decide whether to decode as UTF-8 or a Buffer.
> Allow HTTP nodes to handle non-UTF8 content.

- .jshintrc
- red/runtime/nodes/registry/registry.js
- test/red/runtime/nodes/registry/registry_spec.js
Reopening https://github.com/node-red/node-red/pull/854 pointing to 0.14.0 branch
> Prevent RED.node.registerNode from overriding a constructor's prototype

- bin/node-red-pi
Hello,
The benefits of this change are:
- it allows process supervisors (like daemontools) to get the PID of the actual node-red process
- it leaves fewer process hanging around
nick.
> Added 'exec' to the command in the node-red-pi script

- editor/js/ui/keyboard.js
- red/api/locales/en-US/editor.json
Updated the Keyboard Shortcuts dialog to include most of the keyboard shortcuts registered during initialization.
The only keyboard shortcuts _not_ added were `[Ctrl]`+`[=]`, `[Ctrl]`+`[-]`, and `[Ctrl]`+`[0]` since those are overridden/owned by some browsers (like Firefox), and, hence, they don't always work.
PS. May need an update (possible merge conflict) if PR #922 is accepted.
> Keyboard shortcuts dialog update

- nodes/core/io/31-tcpin.js
In the TCP request node (TCPGet) if one uses a normal character (say A) as the the split character, it will currently fail because the chatacter is compared to the ascii value. This pull requests fixes this.
> Fix split character in TCP Request node

- editor/js/ui/palette.js
- editor/js/ui/tab-info.js
Due to jquery selector type, it can match a condition where the node type followed by a hyphen can also be matched. This moves to a stricter selector removing the hyphen condition.
From:
[https://api.jquery.com/attribute-contains-prefix-selector/](https://api.jquery.com/attribute-contains-prefix-selector/)
To:
[https://api.jquery.com/attribute-ends-with-selector/](https://api.jquery.com/attribute-ends-with-selector/)
Fixes #969
> Fix jquery selector, selecting more than one help pane/popover

- nodes/core/core/89-delay.html
- nodes/core/core/89-delay.js
- nodes/core/locales/en-US/messages.json
- test/nodes/core/core/89-delay_spec.js
Add possibility to set the value for the rate unit.
Backward compatible, if the new nbRateUnits is not set, default to 1. 
This way we can delay messages to 1 msg per X seconds/minutes/hours days instead of always 1. 
Useful when interacting with API that has an uncommon rate limiting like 1req per 2 seconds.
> Add number of units to the delay node (rate)

- nodes/core/core/89-delay.html
With the added nbRateUnits and the normal rules of validation, the editor was complaining about the rules not being met and blocking the deployment.
This resolve the problem by accepting empty string and any number.
see #994 
Solution discussed with @dceejay
> Fix migration of Delay Node

- editor/js/ui/palette.js
Added the 'containment:parent' option for draggable so that if you drag a node from the sidebar and pull it below the current window Y-axis border, it will be contained and will not cause the window to overflow.
> Added parent containment option for draggable.

- red/runtime/nodes/Node.js
> Fix node.error() not printing when passed false

- nodes/core/io/31-tcpin.js
The TCPget (TCP request) node wasn't able to handle multiple connections at the same time.  This fixes the issue by storing each client instance in an object based on the ip+port as the key.
Here's a test flow that can show the behavior:
```
[{"id":"52c260ec.62ee68","type":"tcp request","z":"2decd90d.7e3056","server":"","port":"","out":"time","splitc":"20","name":"","x":730,"y":100,"wires":[["4fead340.86692c"]]},{"id":"adbc7290.16b538","type":"function","z":"2decd90d.7e3056","name":"","func":"var hosts = [\n    {host: \"127.0.0.1\", port: 5000, payload: \"ping1\", topic: \"topic1\"},\n    {host: \"127.0.0.1\", port: 5001, payload: \"ping2\", topic: \"topic2\"},\n    {host: \"127.0.0.1\", port: 5002, payload: \"ping3\", topic: \"topic3\"},\n    {host: \"127.0.0.1\", port: 5003, payload: …
```
> TCPget can now handle concurrent sessions

- nodes/core/core/80-template.html
- nodes/core/core/80-template.js
- test/nodes/core/core/80-template_spec.js
This PR add ability to use `{{flow.*}}` and `{{global.*}}` variables inside Template node.
> Add support for flow and global context in Template node

- test/nodes/helper.js
I am using this file in another project to test nodes.
When running a test suite with gulp and jasmine-node the gulp process never ends as comms are still open.
This resolves the problem.
> Close comms on stopServer in test helper

- red/api/index.js
- settings.js
Add a setting to cause the redirection of insecure HTTP connections to editor to secure HTTPS connections.  Possibly only ever useful behind a proxy, like Bluemix.
> Add setting to cause insecure redirect

- editor/js/ui/view.js
`textContent` is supported all browsers expect for IE 8 and older. I couldn't find any documentation on supported browsers so apologies if IE 8 is to be supported.
Source: http://caniuse.com/#search=textContent
> Use textContent to avoid manual escaping

- nodes/core/core/75-exec.html
- nodes/core/core/75-exec.js
Otherwise, the status of the node is updated and the error code is send through the third output.
> exec node returns 0 on the third output if command ended without error.

- nodes/core/io/05-tls.html
- nodes/core/io/05-tls.js
- nodes/core/locales/en-US/messages.json
- red/api/info.js
- settings.js
Send certs and keys to node redin configuration properties to store them in credentials file
by default upload buttons will be shown unless a cert or key path is already set
added new settings flag called 'tlsDisableLocalFiles' to disable UI for local paths for cloud hosted NR
> UI to upload certificates and keys for TLS

- red/runtime/nodes/registry/loader.js
- test/red/runtime/nodes/registry/loader_spec.js
The commit should fix #1121 
As shown in the added test case, the new code loads an en-US file when `node.help['en-US']` is missing.
> Fix empty extra node help content issue

- red/api/locales/ja/editor.json
I modified Japanese translation mistake. Currently Japanese translation of "Selection to Subflow" is "サブフローの選択"("Select subflow"). "Selection to Subflow" should be "選択部分をサブフロー化"("Create subflow from selected flow").
> Modify Japanese translation file for editor

- red/api/locales.js
Currently only languages in the core are checked when
the editor requests a translation. This means that if
a node includes more translations they are not checked.
This change removes the check against that short list,
but it only checks the first language from the browser
supported list
>  Allow nodes to have translations not in core

- red/runtime/nodes/registry/localfilesystem.js
- test/red/runtime/nodes/registry/localfilesystem_spec.js
I added whitelist function to constrain nodes which correspond with operation policy.
(Opposite of blacklist function, nodeExcludes in settings.js)
This function uses nodesIncludes in settings.js.
I have already discussed the design of this function with Dave and Nick.
> Add node whitelist function

- nodes/core/io/21-httprequest.js
- red/runtime/nodes/registry/registry.js
- red/runtime/settings.js
- red/runtime/util.js
- test/red/runtime/settings_spec.js
- test/red/runtime/util_spec.js
Implement register/exportNodeSettings.
This implementation is the enhancement derived from the trello note below.
https://trello.com/c/jmFK6hAb/87-allow-a-node-to-declare-what-settings-should-be-made-available-to-the-editor
For example, change registerType of the core node "21-httprequest.js" to as follows.
```
RED.nodes.registerType("http request",HTTPRequest,{
credentials: {
user: {type:"text"},
password: {type: "password"}
},
settings: {
httpRequestColour: {
value: "red",
exportable: true
}
}
});
```
Then access to http://localhost:1880/settings, and you'll see the node setting.
> Allow a node to declare what settings should be made available to the editor.

- Gruntfile.js
- package.json
Istanbul command can be run with grunt to output a coverage report.
When you run "grunt mocha_istanbul", you'll see the coverage report in coverage/lcov-report/index.html.
> Add istanbul to Gruntfile.js

- test/red/runtime/nodes/registry/installer_spec.js
In my laptop, one test case almost always failed due to timeout.
My laptop environment is:
OS: 32bits Windows 7
CPU: Intel Core i5-5200U @ 2.2GHz
Memory: 4GB
In this environment, it takes about 4 seconds. So I want to extend the timeout to 10 seconds for margin.
> Extend timeout for the test case of installing non-existant path.

- red/runtime/nodes/registry/localfilesystem.js
- test/red/runtime/nodes/registry/localfilesystem_spec.js
The getLocalNodeFiles is called 3 times.  Each time it called, the callee needs to resolve the dir argument.
That was not done for several of calls, and local modules (specified in the "nodesDir" setting) were not returned to client because of that.
This fix will allow to make sure the dir is consistently resolved.
> Resolve dir argument of getLocalNodeFiles function

- editor/js/ui/tab-info.js
I noticed while developing a node that I was seeing the wrong data-help-name. My node type was 'timer' and I was seeing the help text for 'bigtimer'. I figured it had to be a substring match someplace.  It seems it's in the editor itself.
There may be a good reason there is a partial attribute match done. I couldnt really think of it, and tested a bit and everything seems ok. So if anything, this might help you think of other solutions to the problem.
> dont match only part of the node type

- red/runtime/nodes/flows/util.js
I've been using addFlow and removeFlow pragmatically.  Decided to update to latest-latest, and on removeFlow, NR went through the motions, and made the flow inaccessible, but in fact, re-started all the nodes in the flow (only seen because the flow was generating debug....).
I spent quite some time tracking down, and I believe that the new diffConfig does not mark flows themselves as being removed.  As such, all the nodes get 'removed', but they remain there in the underlying flow.  The flow itself then seems to disappear, but the modules are there running until another deploy-like action causes NR to realise it has nodes with no parent flow, and then removes them grumpily :).
Hope I found the right way of solving this...
> Add note of removed flows in diffConfig

- red/runtime/nodes/registry/loader.js
Hi all,
i have some private modifications and suffixed the version semver compliant (§9 http://semver.org/) with -mw. This breaks the loading of the dashboard with
[node-red-dashboard] Node module cannot be loaded on this version. Requires: >=0.14.0 
so i would like to have the line
!semver.satisfies(runtime.version().replace("-git",""), nodeFiles[module].redVersion)) {
in file red/runtime/nodes/registry/loader.js changed to
!semver.satisfies(runtime.version().replace(/(\-[1-9A-Za-z-][0-9A-Za-z-\.]*)?(\+[0-9A-Za-z-\.]+)?$/,""), nodeFiles[module].redVersion)) {
which would remove all metadata information bevor comparing the versions.
Tested with:
1.2.3-mw
1.2.3+240417
1.2.3+240417-mw
1.2.3-mw+240417
1.2.3-mw
1.2.3-m.w
1.2.3+24.04.17
1.2.3+24.04.17-m.w
1.2.3-m.w+24.04.17
The third is also …
> Version check no meta

- nodes/core/core/75-exec.js
The exec node did not support white spaces in the arguments of the payload, say if you needed to provide a path with spaces in a certain arguments with quotes around the path, eg:
```java -cp "folder name/myjar.jar" MyClass```
It did work with having whitespaces in the command part of the payload, eg: 
```"folder name/exec" -someflag```
It worked in the command part since previously there was a line 52 (added by [dceejay](https://github.com/dceejay) in a previous [issue](https://github.com/node-red/node-red/issues/1100))
```if (/^"."$/.test(cmd)) { cmd = cmd.slice(1,-1); }``` 
that removed the quotes of the command part. This is needed since [spawn()](https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options) from node.js does not support quotes …
> Bug fix in exec node. White spaces in arguments now works

- editor/js/nodes.js
I have flow with two sub-flows, the first sub-flow contains the second one.
When I'm trying to export and import the flow:
* It creates the sub-flow twice.
* It leaves the sub-flow empty.
* It makes the last copy of the sub-flow contains manipulating copies of the node's sequence.
> ![node red](https://user-images.githubusercontent.com/14214460/27134416-289cfd6c-511e-11e7-811c-56eff25ed1b6.png) </br>
> ![node red2](https://user-images.githubusercontent.com/14214460/27135132-6a033e22-5120-11e7-8021-9f0686a3c764.png)
This code change solved the problem.
> Fix bug: Export Subflows

- editor/js/ui/palette.js
Node-Red Version (last commit):
> commit e9c1216d5cde177428f73c1abd94fe97ce48d195
> 	Author: Nick O'Leary <nick.oleary@gmail.com>
> 	Date:   Mon Jun 26 10:49:06 2017 +0100
> 
> 	    Handle logging out and already logged-out editor
> 	    Fixes #1288
NodeJs Version:
> v6.10.2
* When I register a node which it's category has more that 1 word - I see it on the palette with `_` instead of ` 
`.
* When I register a node which it's category has more than 2 words - I can not see the category with the node on the palette.
This code change solved me the problems.
> Support category with more than one word

- red.js
- red/runtime/storage/localfilesystem.js
- test/red/runtime/storage/localfilesystem_spec.js
#1281
With this fix, process.env.USERPROFILE takes precedence over process.env.HOMEPATH.
For the users who upgrade from the older version to 0.17, if the file ".config.json" exists in process.env.HOMEPATH, Node-RED tries to keep using the folder.
I tested on Windows 7, Windows 10, Linux (Ubuntu), macOS (Sierra).  All worked fine.
> Fix creating userDir other than system drive on Windows

- red/runtime/nodes/registry/registry.js
- test/red/runtime/nodes/registry/registry_spec.js
#1318
If icons are missing for some nodes such as email and twitter, tries to check under public/icons.
> Fix missing icons for some nodes

- settings.js
The provided settings.js wrongly provide a commented function webSocketVerifyClient which doesn't have any effect.
The correct parameter is (according to the code of node websocket) webSocketNodeVerifyClient.
> Fix settings.js by using webSocketNodeVerifyClient

- nodes/core/logic/16-range.js
- test/nodes/core/logic/16-range_spec.js
> Fix boundary problem in range node

- test/red/runtime/storage/localfilesystem_spec.js
#1317 
Fix a problem when ".config.json" exists on the directory that runs a grunt command.
> Fix userDir test case when .config.json exists

- nodes/core/io/10-mqtt.html
This pull request add a name property to the mqtt broker node.
All the changes are only in the html file.
If the name property is set, the label for the broker node becomes the name... rather than as currently.
Rational:  
I have an unusual situation where I have multiple mqtt broker nodes which all have the same broker configured, but use different credentials.  Issue is that they all list by the same label... so i never know which one is actually in use.
Original label:
If ClientId is set: <clientid>@<broker server name> 
else <broker server name>
New label:
If Name is set: <name> 
else If ClientId is set: <clientid>@<broker server name>
else <broker server name>
The label is used in the general html to produce the lists used in the mqtt-in and mqtt-out nodes.  I did consider using name …
> mqtt: Add 'name' to mqtt-broker node, and label it by this if it is set.

- editor/sass/editor.scss
Problem
-----
I am a Japanese programmer.When I used node-red, I found a bug about ace editor.
The next image is a screenshot of a bug.There are two parts I want you to pay attention to in this image.
1. Is not a monospaced font.
2. The cursor is out of position.
This problem occurs on **Chrome** on the Mac.It does not occur in Safari.
Reproduction
-----
The environment I used is below.
- OS: macOS Sierra 10.12.5  (MacBook Pro (13-inch, 2017, Four Thunderbolt 3 Ports))
- Browser: Google Chrome version 60.0.3112.78 (Official Build) (64bit)
- npm version: 4.0.5
- node version: v7.4.0
To reproduce the bug, edit the setting "<img width="120" alt="2017-07-30 15 31 58" src="https://user-images.githubusercontent.com/7535743/28751196-440fdca8-753c-11e7-9202-d7efcf79bf8a.png">" on the flow editor. …
> Change font family

- editor/vendor/jsonata/formatter.js
- package.json
- red/api/locales/en-US/jsonata.json
[JSONata 1.3.0 was released on Sept. 4th.](https://github.com/jsonata-js/jsonata/releases/tag/v1.3)  This release includes three main additions: backticks can be used to preserve reserved tokens (in place of single– or double–quotes), two new functions have been added (including the highly useful `$merge`), and a new mode for more detailed error reporting has been added to the parser.
This merge request simply updates the npm dependency in package.json and defines additional help text for the two new functions added to JSONata 1.3.0
> Upgrade JSONata to v1.3.0

- nodes/core/logic/10-switch.html
Second input form of "is between" rule on switch node edit dialog is lacked.
1. Open edit dialog of switch node.
1. Change a rule to "is between".
> Fix the appearance of 'is between' rule on switch node edit dialog

- red.js
This pull request allows port zero to be set for the express port, so that the OS can auto-allocate a port number.
The allocated port number is written to settings.serverPort, from where it can be retrieved if required by the app.
> Allow port zero for Express

- nodes/core/core/80-template.js
- test/nodes/core/core/80-template_spec.js
I fixed #1376 .
This fix supports return code and other characters which need escape character.
> Handle escape characters in template node which uses Mustache format and JSON output mode

- nodes/core/logic/15-change.js
- test/nodes/core/logic/15-change_spec.js
The change node could not change a value of flow and global context, because it passed wrong argument to `get()` function.
I fix it and add test cases.
> Fix wrong argument in change node

- red/runtime/nodes/context.js
- test/nodes/core/core/80-function_spec.js
I fixed global.keys() bug which I found in pull request #1402.
Suggestion:
global.keys() method in my pull request doesn't support deprecated context.global in the function node document (https://nodered.org/docs/writing-functions). I think that it's better to change "deprecated" to "unsupported" in the document because global.keys() method needs to heavily handle both context.global and global.set()/get() if context.global is supported.
> Fix global.keys() bug in function node

- red/api/auth/index.js
Node-red routes for oauth are hard-coded to '/auth/strategy' when they should use the settings.httpAdminRoot + `/auth/strategy`. Without this fix, github oauth only works if the httpAdminRoot is left to the default value.
> [fix] github oauth strategy when Root is not /

- nodes/core/core/lib/debug/debug-utils.js
speed up debug sidebar window processing of messages by only handling up to the number of messages in the history depth (100) - dropping any older than that, as they won’t be in the scrollable window anyway.
This is part 1 of 2
(part 2 will batch up messages across the websocket)
> speed up debug window - only process required number of messages

- nodes/core/core/58-debug.js
- test/nodes/core/core/58-debug_spec.js
When an array of buffers is sent to the debug tab, the buffer size is displayed as `undefined` .
I fixed this and added a test case.
> Fix debug message format for Buffer

- editor/js/ui/utils.js
> Make it possible to save formatting choices separately by the type of object

- test/nodes/core/storage/50-file_spec.js
This is a pull request that was discussed on #1352.
The test script `50-file_spec.js` fails only on Windows environment.
On the Windows environment, the unlinked file won't be completely deleted until its file handle is closed.  Under this condition, to recreate the same file fails. So I explicitly call `close`.
> Fix a problem of file append test on Windows

- red/runtime/locales/en-US/runtime.json
- red/runtime/storage/localfilesystem.js
- test/nodes/core/core/75-exec_spec.js
- test/red/runtime/nodes/index_spec.js
- test/red/runtime/storage/localfilesystem_spec.js
Fixes #1478.
The proposed fix calls `stream.write()` rather than `stream.end()` to write the file's contents. Then it calls `fs.fsync()` and finally `stream.end()` to close the file.
On my test system and Travis CI, this affected some timings and revealed a few race conditions in the existing unit tests for nodes.
* The first was the Flows `startFlows()` function being incorrectly stubbed away in "test/red/runtime/nodes/index_spec.js". The wrong object was used in the stub, causing the `startFlows()` function to still be called, but there was no corresponding call to `stopFlows()`. 
* I don't know if Travis CI would have caught this or not, but I saw it on two different desktops and it was very consistent.
* The second was the Exec node. A test would pass if stderr only emitted one …
> Fix #1478 - Project files are not being flushed to disk after being written

- editor/js/ui/common/typedInput.js
So far, for typedInput "<input type=text>" fields, only custom width styles like "width:100%" or "width:75px" worked. Proposed change allows to use calc() as well, like in "width:calc(100% - 120px)"
Details here: …
> Updated regex so custom width using calc() work

- nodes/core/core/80-template.html
- nodes/core/core/80-template.js
- nodes/core/locales/en-US/messages.json
Added a parsed YAML option to the template node to parse YAML as an object.
> Added parsed YAML support for template node

- nodes/core/parsers/70-HTML.js
- test/nodes/core/parsers/70-HTML_spec.js
Make HTML node to produce parts property like split node.
This allows messages extracted by HTML node processed
as a group.
> add parts support for HTML node

- editor/js/nodes.js
- editor/js/ui/editor.js
ui-tab, ui-link, and ui-button nodes use `icon` property.  This conflicted with dynamic icon change feature.
So I made this feature disable if a node defines `icon` property in defaults array.
By the way, the diff result looks like currentDefaultIcon is replaced with icon at line 1072 in …
> Fixed name conflict of icon property for dashboard node

- nodes/core/core/89-trigger.js
- test/nodes/core/core/89-trigger_spec.js
currently to use msg.payload to reset a trigger that is in progress, it needs to match a string.
> let trigger node be reset by boolean message

- red/red.js
- red/runtime/nodes/registry/loader.js
Fixes Websockets not able to listen if httpAdminRoot is unset/false.
When creating 'red.server' for a node, use runtime.server rather than runtime.adminApi.server, and fill runtime.server at startup with the valid http server regardless of adminApi being available.
This resolves websockets not working when the adminApi (httpAdminRoot) is disabled in settings.
It MAY resolve similar issues with other nodes if any others rely on RED.server actuaklly being the http server.
The websockets node uses RED.server, which is only initialised to the http server object if the adminApi is enabled.
These changes add a new variable (runtime.server) which is valid when adminApi is enabled or disabled, then uses this reference to the http server to populate RED.server for nodes.
(tested in old 17.5 …
> Fix WebSockets not working when httpAdminRoot false

- editor/js/ui/editor.js
relax errors for missing semi-colons, [] syntax warnings, max errors.
And also ignore missing doctype error for html templates.
https://github.com/ajaxorg/ace-builds/releases/tag/v1.2.9
> Changes to ACE editor annotations

- editor/js/ui/projects/projects.js
- Condition: There are no projects under $HOME/.node-red/projects.
Even if a user creates a new project, `Open...` button in projects menu does not become clickable until Node-RED will be restarted.
This behavior is kept even if the user creates multiple projects.
> Enable the project open button when creating a first project

- red/api/editor/locales/ja/editor.json
I updated Japanese messages in editor.json because English messages were updated in their file.
> Update Japanese translations in editor.json

- nodes/core/parsers/70-JSON.html
I added icons into property UI of JSON node because other nodes in the same group (CSV, HTML, XML and YAML node) have icons at the text input on their property UI.
> Add icons into property UI of JSON node

- nodes/core/storage/50-file.js
- test/nodes/core/storage/50-file_spec.js
Current *FILE IN* node with "a msg per line" mode produces unexpected *parts* property for a file with empty line.
For example, for following input file
```
--
--
```
we expect following messages:
```
{ payload:"--", parts: { id:..., index:0 }},
{ payload:"", parts: {id:..., index:1 }},
{ payload:"-", …
```
> fix behavior of "a msg per line" mode of FILE IN node with empty line

- nodes/core/parsers/70-HTML.js
- test/nodes/core/parsers/70-HTML_spec.js
Current HTML node reuses message object when "as multiple messages, one for each element" mode is selected.  This causes following nodes see unexpected message property value.
This fix creates different objects for each output messages.
> fix HTML node not to reuse message object for multiple output messages

- editor/js/ui/library.js
- red/api/editor/library.js
- test/red/api/editor/library_spec.js
If nodes are installed from an npm package which has an [org-scoped name](https://www.npmjs.com/docs/orgs/publishing-an-org-scoped-package.html) &mdash; for example, `@myorg\node-red-contrib-mypackage` &mdash; the Node-RED UI does not …
> Allow at sign in module examples path

- nodes/core/logic/17-split.js
- test/nodes/core/logic/17-split_spec.js
When a JOIN node is configured with reduce expression of `$append($A, ...)` and initial value of `[]`, the node produces unexpected result with application of multiple input message streams.
For example, if reduce expression is `$append($A, [payload])`, initial value is `[]`, and input messages are `{ …
> fix reduce mode of JOIN node with JSONata $append function

- nodes/core/hardware/36-rpi-gpio.html
- nodes/core/io/21-httpin.html
- nodes/core/io/21-httprequest.html
- nodes/core/logic/10-switch.html
- nodes/core/logic/17-split.html
- nodes/core/logic/19-batch.html
- change backquoted string in HTML info text to <code>...</code>.
> Fix backquote in info text

- nodes/core/logic/19-batch.js
- test/nodes/core/logic/19-batch_spec.js
Concatenating the same message sequence using BATCH mode may corrupts `msg.parts` property because it shares same messages on output.
This PR fixes this by cloning concatenated messages before send.
> fixed message modificcation of concat mode of BATCH node

- editor/js/history.js
- editor/js/ui/editor.js
The followings are how to reproduce the problem.
Problem 1
1. Install a node that does not specify defaults object in html.
1. Deploy the node on workspace.
1. Open the edit dialog.
Problem 2
1. Install a node that does not specify defaults object in html.
1. Modify port labels or icon on the node settings tab.
1. Undo the modification by Ctrl+z
> Fixed the problems when using a node without defaults

- editor/js/ui/common/tabs.js
- editor/js/ui/workspaces.js
see #1613.
I checked all callers of `workspace_tabs.count()`.  It looks that all of them expect that the count does not include subflow tabs.
> Fix the problem that the last flow tab can be deleted

- nodes/core/logic/10-switch.html
#1663
As a switch node named the element of output port labels with mixing number and alphabet, I changed it to use only numbers.
> Fix the problem that output labels of switch node sometimes disappear

- editor/js/ui/deploy.js
- editor/js/ui/editor.js
- editor/js/ui/view.js
#1662
- Clear the changed flag for each subflow when deployed.
- Applying the code for node editing to subflow.
https://github.com/node-red/node-red/commit/879c0f41142aaafd1a3e8552024d81d5e40b012d#diff-22a7b0b89bfea2828bc49b86c7537fb7
- Set a default name value for a subflow.
> Don't mark a subflow changed when actually modified nothing

- editor/js/history.js
- editor/js/nodes.js
- editor/js/ui/editor.js
- editor/js/ui/palette.js
- editor/js/ui/utils.js
#1609
Supported user defined icon for subflow.  Once an icon is specified for a subflow, the default icon of its subflow node becomes the icon instead of subflow.png.
> Enable user defined icon for subflow

- nodes/core/io/10-mqtt.js
- package.json
Add proxy configuration for MQTT websocket connection. Proxy is set when an environment variable, e.g. HTTP_PROXY or http_proxy, is defined.
> Mqtt proxy configuration for websocket connection, #1651.

- editor/js/main.js
- red/api/editor/locales/en-US/editor.json
- red/runtime/nodes/flows/index.js
See issue #1689 
This pull request will revert pre 0.18 behaviour and not block the flow from starting when run time is unable to decrypt flow credentials using the `credentialSecret` supplied in `settings.js` or `.config.json`. It also adds a runtime state notification that will persist to inform the user that their credentials will be reset on the next deployment. Changes should not affect projects behaviour if it is enabled.
[Demo](https://i.imgur.com/bNUORg2.gif)
> Handle and display for invalid flow credentials when project is disabled #1689

- nodes/core/locales/en-US/messages.json
- nodes/core/parsers/70-HTML.html
- nodes/core/parsers/70-HTML.js
- test/nodes/core/parsers/70-HTML_spec.js
When parsing HTML documents it makes sense to let the output actually be on a different property than the input property - so that nodes can be chained more easily.
> add output property select to HTML parse node

- nodes/core/io/32-udp.html
- nodes/core/io/32-udp.js
- nodes/core/locales/en-US/messages.json
- nodes/core/locales/ja/messages.json
- nodes/core/locales/zh-CN/messages.json
to allow better re-use of ports. Currently in order to broadcast/multicast you have to bind to a port… - if not specified we were binding the local port to the remote port number. We should be binding locally to a random port if not otherwise specified.
> bind to correct port when doing udp broadcast/multicast

- red/runtime/storage/localfilesystem/util.js
This PR is related to an issue in master branch where NR attempts to backup the .config.json file before it's been written to disk. Changes backup to use `copySync` and moves it below the `fsync` to ensure file is present when backup is made.
> Fix ENOENT error on first start when no user dir

- bin/node-red-pi
For some reason the following will result
in an endless loop under bash-4.3.42:
```
while([ -h "${SCRIPT_PATH}" ])
```
Just remove the round brackets (parentheses) to fix the issue.
They're not needed anyway.
> node-red-pi: fix behavior with old bash version

- test/red/runtime/nodes/registry/registry_spec.js
On Windows system, *returns a registered icon* test of `test/red/runtime/nodes/registry/registry_spec.js` fail because of its use of `/` as separator.  This PR fixes this problem.
> Fix test failure of icon scan on Windows

- red/runtime/i18n.js
Currently, Node-RED runtime do not perform i18n translation because a target locale of the translation  is not specified.  This PR fixes the problem by using value of LC_*/LANG variables as the target locale.
> Allow i18n translation in runtime

- red/runtime/i18n.js
- red/runtime/locales/en-US/runtime.json
- red/runtime/locales/ja/runtime.json
- red/runtime/storage/localfilesystem/projects/Project.js
- red/runtime/storage/localfilesystem/projects/defaultFileSet.js
- test/red/runtime/storage/localfilesystem/projects/defaultFileSet_spec.js
Currently automatically generated files for a project such as README.md is written in English.
This PR add i18n support for the generated files and Japanese message catalogue.
> Add i18n support for default file set for a project

- editor/js/ui/diff.js
- red/api/editor/locales/en-US/editor.json
- red/api/editor/locales/ja/editor.json
This PR supports i18n for projects and adds Japanese translation.
> Add i18n support for project

- nodes/core/hardware/36-rpi-gpio.js
- nodes/core/locales/en-US/messages.json
- test/nodes/core/hardware/36-rpi-gpio_spec.js
Currently Pi GPIO nodes don't load into the editor on a non-Pi platform - there will  be occasions when this is actually required so for example a team can work on a Pi project without being next to the Pi... This change means the will be available in the palette and can be configured and edited - but will return Not Available / NA as their status.
> let Pi nodes be visible/editable on all platforms

- editor/js/ui/notifications.js
- editor/js/ui/projects/projects.js
- red/api/editor/locales/en-US/editor.json
- red/api/editor/locales/ja/editor.json
As described in [Issue #1768 ](https://github.com/node-red/node-red/issues/1768),
retry button of authentication management dialog appear as "[Object]".
This fixes it to apper as "Retry" with refresh icon.
> Fix appearance of retry button of remote branch management dialog

- editor/js/ui/common/typedInput.js
Rule editing UI of switch node in current 0.19 branch is not shown in expected mannar as shown in the following figure.
This problem is caused by `typeField` and `optionExpandButton` field reference with `undefined` value in `type`  function.
This PR resolves this issue.
> Fix typedInput error on initialization

- nodes/core/logic/17-split.js
When msgs get joined into objects currently the final msg to arrive is used as the base msg to add the newly joined payload to. If anyone has added extra top level properties to any of the other messages (maybe via a divergent path) they will be dropped.
This change make the the top level message be an accumulation of previous msg top level properties then with the new payload.
This should be transparent to users as the last msg in will still set all the same properties as previously… just there may now be a few more.
Fixes the Issue #1782
> join-node-keep-top-level-properties

- nodes/core/logic/15-change.html
Current *change* node implementation of 0.19 branch shows node label for flow/global context property reference in raw format (e.g. `flow.#:(abc):xyz`).
This PR fixes this to be shown in propetly formatted style (e.g. `flow.xyz`).
> Fix appearrence of change node label for flow/global ref

- nodes/core/logic/10-switch.html
Current switch node implementation of 0.19 branch shows port label for flow/global context property reference in raw format (e.g. flow.#:(abc)::xyz).
This PR fixes this to be shown in propetly formatted style (e.g. flow.xyz).
> Fix appearrence of switch node port label for flow/global ref.

- red/runtime/nodes/context/localfilesystem.js
When the cache is initialized in localfilesystem plugin, an error occurs if there is no context file.
For example, when using the plugin for the first time, there is no context file.
I fixed it to ignore `ENOENT` error.
> Fix an error when initializing the cache

- nodes/core/io/22-websocket.js
- nodes/core/locales/en-US/messages.json
- nodes/core/locales/ja/messages.json
I found that the status messages in websocket nodes are English. I fixed 22-websocket.js to support i18n.
> Support i18n in websocket node

- Gruntfile.js
- test/editor/wdio.conf.js
As @Kazuki-Nakanishi discussed before, I added headless option for UI test.
Using this option, users can choose whether to run UI test in GUI or CUI.
> Add headless option for UI test

- red/runtime/nodes/context/index.js
- test/red/runtime/nodes/context/index_spec.js
To minimise callback nesting, I added support for getting multiple values to `context.get ()`.
By passing an array of key, you can get the values of the keys at once.
```javascript
// Get multiple
flow.get(['foo', 'bar'], function(err, fooValue, barValue) {
});
```
And I added test cases.
> Make it possible to get multiple values

- red/runtime/nodes/context/localfilesystem.js
- test/red/runtime/nodes/context/localfilesystem_spec.js
I have fixed an error when initializing the cache in #1788.
But if the parent directory does not exist, the ENOENT error is thrown.
I fixed this to use `ensureDir()` instead of `mkdir()`.
And I added test cases.
> Fix the error that the parent directory of the context does not exist

- red/runtime/nodes/context/index.js
- test/red/runtime/nodes/context/index_spec.js
To minimise callback nesting, I added support for setting multiple values to `context.set ()`.
By passing arrays of key and value, you can set key/value pairs at once.
```javascript
// Set multiple
flow.set(['foo', 'bar'], [fooValue, barValue], function(err) {
});
```
And I added test cases.
> Make it possible to set multiple values

- test/nodes/core/logic/15-change_spec.js
Current unit test of **change** node lacks tests for accessing multiple persistable stores.
But adding test cases for multiple persistable context fails because initialization of persistable context in `beforeEach` is overridden by runtime initialization in `helper.load`.  
Previous tests for single persistable store succeeds because an access for unknown store fallbacks to default sore.
So this PR also fixes initialization sequence of persistable stores.
> Add multiple persistable store tests for change node

- nodes/core/core/20-inject.html
This PR fixes following problems in persistable context access  of inject node:
- target is always shown as `flow` even if it is `global`,
- notification message is show in raw format (e.g. `#:(store)::name`) without target information,
- parsing context storage access speficication do not use `RED.utils.parseContextKey`.
> Fix context access appearance of inject node in editor

- red/runtime/util.js
This PR fixes typo of function `evaluteEnvProperty` to `evaluateEnvProperty` in `red/runtime/util.js`.
> Fix typos in util.js

- nodes/core/logic/17-split.html
- nodes/core/logic/17-split.js
- test/nodes/core/logic/17-split_spec.js
`split` node implementation of current 0.19 branch do not support new environment variable input of `typedInput`.  
This PR add support for this.
> Allow environment variable as reduce init value in split node

- nodes/core/io/31-tcpin.js
- package.json
- settings.js
- test/nodes/core/io/31-tcprequest_spec.js
- queues messages on a per-client basis while waiting for TCP server connection
- add [`denque`](https://npm.im/denque) package for performance
- add tests
- remove a duplicate test in `31-tcp_request.spec.js`
This code uses ES6 conventions allowed in Node.js v4.x (the tests pass on this version).
> tcp node: queue pending messages while connecting to tcp server

- red/runtime/util.js
- test/nodes/core/logic/10-switch_spec.js
- test/nodes/core/logic/15-change_spec.js
- test/nodes/core/logic/17-split_spec.js
- test/nodes/core/logic/18-sort_spec.js
- test/red/runtime/util_spec.js
This PR adds context store support to the JSONata function.
```text
$flowContext(key [, store])
$globalContext(key [, store])
```
If the optional `store` parameter is supplied, then the function retrieves a context property from specified context store.
If it is not supplied, then the function retrieves a context property from `default` context store(e.g. existing memory).
>  Add context store support to JSONata functions 

- test/nodes/core/core/80-template_spec.js
Some test cases of template node for persistable context uses undefined store name.  These tests succeeds because of fallback to default store.
This PR fixes these tests and add default store for later detection of unexpected use of default store.
> Fix test for template node for persistable context

- nodes/core/core/89-trigger.html
- test/nodes/core/core/89-trigger_spec.js
Trigger node lacks support of binary buffer, timestamp, and environment variable for typedInput fields.
> Add support of bin, data, and env type to trigger node

- nodes/core/logic/10-switch.html
- nodes/core/logic/10-switch.js
- test/nodes/core/logic/10-switch_spec.js
I fixed bugs about followings in Switch node .
* Editor
* A typedInput is displayed when `isEmpty` or `isNotEmpty` rule is selected.
* `outputlavel` of  `isEmpty` or `isNotEmpty` displays unnecesarry typedInput value.
* `isEmpty` or `isNotEmpty` passes unnecesarry typedInput value to runtime.
* Runtime
* An error occurs when evaluating `null` on `isEmpty` or `isNotEmpty` rule.
* Test case
*  Evaluating `null` instead of `0` by mistake.
> Fix bugs about "isEmpty" rule in Switch node 

- test/nodes/core/storage/50-file_spec.js
Some unit tests for file node very occasionally fails.  In these test cases, order of output messages are incorrectly assumed to have the same order of input messages.  
This PR fixes these tests.
(I think that it is better if synchronization of input and output message order can be optionally specified.)
> Update file node test to cope with occasional failure

- editor/js/ui/common/typedInput.js
We found a problem by UI testing.
When TypedInput is displayed, some html elements are created as option.
Then close the edit dialog, typedInput option element remains as following.  
I fixed this.
> Fix to remove unnecessary typedInput option element

- red/runtime/nodes/context/index.js
- test/nodes/core/core/80-function_spec.js
- test/red/runtime/nodes/context/index_spec.js
Allow `context.get` and `context.keys` to be called without callback when `store` is specified.
You can call these as followings.
```javascript
context.get("key","store");
context.keys("store");
```
> Allow `get` and `keys` to be called without callback

- editor/js/ui/common/typedInput.js
`TypedInput` widget seems to support specification of `TypeDefinition` icon by HTML tag or CSS class.  But it fails to show when selecting from a type menu.
> Fix use of HTML tag or CSS class specification as icon of TypedInput

- nodes/core/io/10-mqtt.js
This change allows to subscribe to shared subscriptions in the MQTT-In core node.
Before the topic check would fail because subscribe topic and the topic in the message are not the same for shared subscriptions.
--> I created a topic on the [forum](https://discourse.nodered.org/t/core-mqtt-in-shared-subscriptions-for-core-node-mqtt-in-mqtt-v5/2475)
> Allows MQTT Shared Subscriptions for MQTT-In core node

- editor/js/ui/search.js
- editor/js/ui/tab-config.js
It would be useful (occasionally) to be able to find which nodes are using a particular config node. This PR does that by making the number field to the right of the node identifier in the config node window into a button that opens the search window with the result of the search for that config node id.
Also letting the search function  `RED.search.show()` accept an argument would potentially be useful to other integrations.
See - https://discourse.nodered.org/t/how-to-find-all-nodes-that-are-using-a-specific-configuration-node/2919 for original "issue" that prompted this PR.
> Config search

- packages/node_modules/@node-red/nodes/core/core/89-delay.html
- packages/node_modules/@node-red/nodes/core/core/89-delay.js
- test/nodes/core/core/89-delay_spec.js
Adds a flush option to the delay node as per Trello todo list item - sending a msg.flush property will cause any queued up messages to be delivered immediately (rather than msg.rest which wipes them).
Also adds tests for both reset and flush modes  (reset tests were missing)
> Delay node - add msg.flush option

- red/api/editor/library.js
- test/red/api/editor/library_spec.js
Previously, when trying to import an example into the flow editor on
Windows, the load attempt would fail with an HTTP 404 error in the
browser client, with the following error being written to the Node-RED
log:
> TypeError: path must be absolute or specify root to res.sendFile
This was due to the path being passed to the `res.sendFile` function
not being fully-qualified (for example, `\Users\myuser\...\example.json`).
With the changes in this commit, the path to the example file is
resolved to a fully-qualified path before being passed into the
`res.sendFile` call. For example, a path on Windows of
`\Users\myuser\...\example.json` would be transformed to
`C:\\Users\\myuser\\...\example.json` before being passed along to the
`sendFile` function. This change allows the file to be loaded …
> Resolve path when sending example file for Windows support

- packages/node_modules/@node-red/editor-api/lib/editor/locales/en-US/editor.json
While I translate English message catalog into Japanese, I found that the catalog lacks the necessary p tag. Therefore, I added it.
> Add necessary p tag into English message catalog

- packages/node_modules/@node-red/editor-client/src/js/ui/view.js
- packages/node_modules/@node-red/nodes/core/core/58-debug.html
- packages/node_modules/@node-red/nodes/core/core/58-debug.js
Add button.visible function to view.js
Make status independant of tosidebar setting
Adds a .visible(boolean) function to the button handler in view.js - default true. This allows the side button on a node to be hidden completely. This allows the debug node - when set to not send to the sidepanel to not have the button that toggles reporting or not - so is a visual indication of whether it reports to the sidebar or not.
> If debug set not to go to sidebar hide the button

- nodes/core/storage/50-file.js
- test/nodes/core/storage/50-file_spec.js
`File` node fails to crate files when a message arrives while processing a previous message.
This is caused by the use of `File` node property as global state.
This PR fixes this problem by serializing input message processing.
**Test case that reproduces the problem**
```
{"id":"1637d5d5.ef08ea","type":"tab","label":"フロー 2","disabled":false,"info":""},{"id":"1c48b6b5.c7b7b9","type":"inject","z":"1637d5d5.ef08ea","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":160,"y":180,"wires":[["c430d682.c32ae8"]]},{"id":"c430d682.c32ae8","type":"function","z":"1637d5d5.ef08ea","name":"","func":"var len = 1024*1024*100;\nvar data = new Buffer(len);\nfor(var i = 0; i < 5; i++) {\n    var path = \"/tmp/quux_\"+i;\n    var msg = { payload: …
```
> fix multiple input message processing of file node

- editor/js/ui/common/typedInput.js
When switching between `flow` and `global` on TypedInput several times, unnecessary TypedInput elements remain.
This is because the remove function has not been called.
I fixed it to call the function.
> Fix unnecessary TypedInput element

- packages/node_modules/@node-red/runtime/lib/nodes/context/index.js
- packages/node_modules/@node-red/runtime/locales/en-US/runtime.json
- packages/node_modules/@node-red/runtime/locales/ja/runtime.json
I found that there are duplicated key names ("install-failed-not-found" and "error-loading-module") in message catalog, runtime.json. Therefore, I deleted unnecessary "install-failed-not-found" and define new "error-loading-module" as "install-failed-not-found2". At the same time, I updated Japanese message catalog and fixed typo.
> Fix reference bug in message catalog

- packages/node_modules/@node-red/editor-client/src/js/ui/view.js
If a switch node with two or more ports uses a font-awesome icon, the icon is shown on the top of the node not the center.
This PR fixed the problem.
> Adjust the fa icon position for the node with height

- packages/node_modules/@node-red/editor-client/src/js/ui/diff.js
- packages/node_modules/@node-red/editor-client/src/js/ui/editor.js
- packages/node_modules/@node-red/editor-client/src/js/ui/palette.js
- packages/node_modules/@node-red/editor-client/src/js/ui/search.js
- packages/node_modules/@node-red/editor-client/src/js/ui/typeSearch.js
- packages/node_modules/@node-red/editor-client/src/js/ui/utils.js
If a flow with an invalid font-awesome icon name was imported, no icon was shown on edit dialog.
The way of reproducing it is as follows.
1. Deploy a node and set a font-awesome icon.
2. Export a flow.
3. Modify the flow and specify invalid font-awesome icon name.
4. Import the flow.
5. Open an edit dialog and check `Appearance` tab.
> Show default icon when invalid font-awesome icon was specified

- nodes/core/logic/19-batch.html
Because the minimum value for batch node property is not set, we can input invalid values, such as a negative number.
I fixed to set minimum values of properties and spinners to prevent invalid value.
> Prevent invalid value for batch node property

- nodes/core/hardware/36-rpi-gpio.js
Fix for `[warn] rpi-gpio : Cannot find Pi RPi.GPIO python library` when the library is installed with `pip` using the default prefix `/usr/local`, instead of a distro package manager.
> Recognize pip installs of RPi.GPIO

- packages/node_modules/@node-red/editor-api/package.json
Fix package name of editor-api of dev branch.
In package.json of editor-api, editor-api is named `@node-red/editor`.
```json
// packages/node_modules/@node-red/editor-api/package.json
{
"name": "@node-red/editor",
"version": "0.20.0-alpha.0",
```
But [Design: Runtime Editor Split](https://github.com/node-red/node-red/wiki/Design%3A-Runtime-Editor-Split#packaging) defines this name as `editor-api`. Also node-red package.json requires `@node-red/editor-api`.
```json
// packages/node_modules/node-red/package.json
"dependencies": {
"@node-red/editor-api": "0.20.0-alpha.0",
"@node-red/runtime": "0.20.0-alpha.0",
```
So I fix name property of package.json from `@node-red/editor` to `@node-red/editor-api`.
> fix typo of editor-api package name

- nodes/core/io/10-mqtt.html
- nodes/core/io/10-mqtt.js
- nodes/core/locales/en-US/messages.json
- nodes/core/locales/ja/messages.json
- nodes/core/locales/zh-CN/messages.json
This PR add output type to the `mqtt in` node so we can explicitly parse the message content. It is consistent with `udp in` and `http request`.
It fixes #1912 as parsing binary messages is problematic if it has a valid UTF-8 interpretation.
As discussed with @knolleary, the default behavior is to auto-detect the format to keep compatibility with existing flows.
> Add output type to mqtt node

- packages/node_modules/@node-red/editor-client/src/js/ui/editor.js
subflow edit dialog does not show an input port label correctly.  The reproduction procedure is as follows.
1. Create a subflow.
2. Change the number of input port from 0 to 1.
3. Click `edit properties`, and open `Appearance` tab.
> Show port label of subflow with input port

- packages/node_modules/@node-red/nodes/core/io/21-httprequest.html
- packages/node_modules/@node-red/nodes/core/io/21-httprequest.js
- packages/node_modules/@node-red/nodes/locales/en-US/messages.json
- test/nodes/core/io/21-httprequest_spec.js
This adds a `msg.requestTimeout` option to the http request node to override the global httpRequestTimeout parameter per message.
> http request: add msg.requestTimeout parameter

- packages/node_modules/@node-red/nodes/core/hardware/36-rpi-gpio.html
- packages/node_modules/@node-red/nodes/locales/ja/hardware/36-rpi-gpio.html
I found that `<p>` tag in html file of rpi-gpio out node are not closed.
They were in the section of the help text that gets displayed in the info sidebar tab.
It was the same  in Japanese language file.
So I fixed these html files.
> Fix html file of rpi-gpio out node

- packages/node_modules/@node-red/nodes/core/io/22-websocket.html
- packages/node_modules/@node-red/nodes/locales/ja/messages.json
This PR adds missing Japanese translation of message catalogue for nodes.
Also fixes missing label in settings UI of websocket config node.
> Update Japanese message catalog for nodes

- red.js
This is required by RFC 2617
I try to connect our node-red enpoint with a iOS application . The node-red instance is secured over Basic Auth . Problem right now is that node-red returns www-authenticate: Basic realm=Authorization Required … The std Apple API does not recognise the realm because it is not “quotated” .. The Standard says it must be in quotation marks (https://tools.ietf.org/html/rfc2617#page-4 chapter 2) .. The issue is in red.js (node-red/red.js) line 243
I changed the code and put the Realm into quotation marks like it is specified in the RFC 2617 doc
> Add quotation marks for basic auth challenge

- packages/node_modules/@node-red/editor-client/locales/en-US/editor.json
- packages/node_modules/@node-red/editor-client/locales/ja/editor.json
- packages/node_modules/@node-red/editor-client/src/js/ui/editor.js
Title part of new node setting tab is not i18n ready.
This PR fix this and adds Japanese message translation.
> add i18n & JP message for node config tab

- packages/node_modules/@node-red/editor-client/src/js/ui/diff.js
Speed up the display of the diff panel in the editor UI for large flows.
Currently the diff of a flow of 2500 nodes takes 3mins, 3300 nodes 5 mins...etc
This is because the DOM for the whole diff (all nodes, all properties of all nodes) is generated when the diff panel is opened.
By generating the DOM for node properties only if the user clicks on the node, the size of the flow has much less impact on the loading time of the panel.
This brings the appearance of the diff table down to a few seconds even for large flows.
> Speeding up display of diff for large flows

- packages/node_modules/@node-red/registry/lib/installer.js
- packages/node_modules/@node-red/runtime/locales/en-US/runtime.json
Currently we just check for the existence of npm. We should also refuse to enable the palette if the version of npm is too old (aka 1.4.2 from debian) as it will break users with bad installs.
This PR logs the fact in the log and suggests users update.
> refuse to enable palette if npm too old

- packages/node_modules/@node-red/nodes/core/parsers/70-JSON.js
- packages/node_modules/@node-red/nodes/locales/en-US/parsers/70-JSON.html
- test/nodes/core/parsers/70-JSON_spec.js
This deletes the msg.schema property before sending the msg to avoir conflicts with further JSON nodes.
> JSON node: delete msg.schema before sending msg to avoid conflicts

- packages/node_modules/@node-red/editor-client/locales/en-US/editor.json
- packages/node_modules/@node-red/editor-client/locales/ja/editor.json
- packages/node_modules/@node-red/editor-client/src/js/ui/editors/markdown.js
Tooltips in node's markdown editor are not i18n ready.
This PR adds i18n support of these tooltips and corresponding Japanese messages.
> i18 support for markdown editor tooltips

- test/editor/pageobjects/nodes/core/core/58-debug_page.js
- test/editor/pageobjects/nodes/core/core/80-function_page.js
- test/editor/pageobjects/nodes/core/core/80-template_page.js
- test/editor/pageobjects/util/key_page.js
- test/editor/specs/scenario/cookbook_endpoint_uispec.js
Several UI test cases failed on the mac OS.
1. The scenario of ` get a parsed JSON response` in cookbook_uispec.js failed.
Reason: When inputting a value into a text box, WebdriverIO fails to clear the default vaule.
Information: https://github.com/webdriverio/webdriverio/issues/1140
Workaround: Nothing (run the test on the OS other than mac OS)
2. All scenarios failed when running with WebdriverIO 4.14.1 and `--non-headless` option.
Reason: Maximizing a browser fails.
Information: https://github.com/webdriverio/webdriverio/issues/3043
Workaround: Run a UI test without `--non-headless` option, or run with WebdriverIO 4.13.1.
3. Most scenarios failed when running UI test simultaneously.
Reason: Concurrent connection to ChromeDriver fails.
Information: …
> Update UI test for mac OS

- packages/node_modules/@node-red/editor-client/src/js/ui/typeSearch.js
- packages/node_modules/@node-red/editor-client/src/js/ui/view.js
Adds the ability to add multiple nodes quickly via the keyboard. Use ctrl/cmd click to open the select menu - then start typing the name (eg inj) - then hit cmd/ctrl enter to place the node - the select then goes back to the fill list and you can repeat - the next node will be linked to the previous node. If you select a node that ends a flow (eg debug) it will complete the flow and close the select.
> add fast entry via keyboard for string of nodes

- packages/node_modules/@node-red/nodes/core/io/21-httprequest.js
- test/nodes/core/io/21-httprequest_spec.js
Fix #2025
Cookie values in http request node are always encoded and you cannot change encoding.
~~This PR allows http request node to change cookie value encoding.~~
This PR allows http request node to avoid encoding cookie.
```javascript
msg.cookies = { };
// Set encode option to `false` if you do not want to encode a cookie value
msg.cookies["demo-hello"] = {value:"hello+world", encode:false}; 
// Set it to true or nothing to use encodeURIComponent function
msg.cookies["demo-hello2"] = {value:"hello+world", encode:true};
msg.cookies["demo-hello2"] = {value:"hello+world"};
```
This PR also fixes encoding behavior in the dev branch in order to be same behavior as the master branch.
>  Allow http request node to avoid encoding cookie

- packages/node_modules/@node-red/nodes/core/io/21-httprequest.html
- packages/node_modules/@node-red/nodes/core/io/21-httprequest.js
- packages/node_modules/@node-red/nodes/locales/en-US/messages.json
- [x ] New feature (non-breaking change which adds functionality)
Add the ability to use payload properties as parameters on a GET request
- [x ] I have read the [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md)
- [x ] For non-bugfix PRs, I have discussed this change on the mailing list/slack team.
- [x ] I have added suitable unit tests to cover the new/changed functionality
> Use payload properties as parameters on a GET request

- packages/node_modules/@node-red/editor-client/locales/en-US/editor.json
- packages/node_modules/@node-red/editor-client/locales/ja/editor.json
- packages/node_modules/@node-red/editor-client/src/js/ui/editor.js
This PR changes `editor-tab.name` i18 tag to common label `common.label.name`.
> Fix use of i18n label

- packages/node_modules/@node-red/editor-client/locales/en-US/editor.json
- packages/node_modules/@node-red/editor-client/src/js/ui/editor.js
- packages/node_modules/@node-red/runtime/lib/nodes/flows/Subflow.js
- test/nodes/subflow/subflow_spec.js
When editing a subflow instance node, its env var table will now display the env vars defined in the parent subflow. This helps the user to know what variables could be customised in the subflow instance.
In the screenshot, the `HOST` env var has been defined in the parent subflow. It's name is not editable but its value is. The button to the right will revert the value back to the default value provided by the parent. (The button is only shown *if* the type or value has been changed in the instance).
The `POST` env var has been newly defined in this instance - it doesn't exist in the parent - so its name is editable and has the delete button to remove it entirely.
> Display parent subflow properties in subflow instance edit dialog

- packages/node_modules/@node-red/runtime/lib/nodes/context/index.js
- test/unit/@node-red/runtime/lib/nodes/context/index_spec.js
Currently, nodes in a subflow can not access flow context of enclosing flow/subflow.
New proposal to subflow enhancement 
(described at https://github.com/node-red/node-red/wiki/Design:-Subflow-Enhancements)
deals with this problem by introducing `$parent` to access enclosing flow context.
This PR implements this feature.
> Allow access of scope parent

- nodes/core/storage/50-file.js
- test/nodes/core/storage/50-file_spec.js
Outputting multi-byte string (e.g 試験) using File node creates unexpected file contents.
This is caused by specifying `binary` (not `utf8`) as encoding of output stream.
> Fix output of multi-byte string with file node

- packages/node_modules/@node-red/editor-client/src/js/ui/common/typedInput.js
Per https://github.com/node-red/node-red/issues/2059, this change addresses how the TypedInput should transfer the `type` and `placeholder` attributes from a normal configuration input field to a TypedInput field. 
Currently, the generated TypedInput can only be a text input and doesn't handle values like passwords that shouldn't be visible to the user. Additionally, the placeholder text of the original input field isn't used and presents an empty text input to the user.
> Transfer input attributes (placeholder, type) to generated TypedInput field

- packages/node_modules/@node-red/nodes/core/io/21-httprequest.html
Hi @knolleary, @dceejay,
Sorry for the last minute fix!!!
For the Digest/Bearer authentication pull request [#2061](https://github.com/node-red/node-red/pull/2061), I had executed a series of tests on existing flows.  However *at the end* we decided to replace two labels (*'password'* and *'token'*) by two spans inside a single label.
But it seems that the ```style="hide"``` (which worked fine on the labels) doesn't hide the token-span, so **both** the *'password'* **and** *'token'* text become visible at the same time.  This style is only required when - for an existing httprequest node without basic authentication - the authentication checkbox is now activated in the new version:
When I simply replace that style on the token-span by ```style="display:none"```, the token-span is …
> Fix hiding Bearer token

- packages/node_modules/@node-red/nodes/core/core/20-inject.html
- packages/node_modules/@node-red/nodes/core/core/75-exec.html
- packages/node_modules/@node-red/nodes/core/io/21-httprequest.html
- packages/node_modules/@node-red/nodes/core/storage/50-file.html
- packages/node_modules/@node-red/nodes/locales/en-US/messages.json
- packages/node_modules/@node-red/nodes/locales/ja/messages.json
Port label of inject, exec, httprequest, and file node is not i18n ready.
This PR makes them i18n ready and adds Japanese messages.
> Add i18n support for port label

- packages/node_modules/@node-red/editor-client/src/js/ui/palette.js
- packages/node_modules/@node-red/editor-client/src/js/ui/view.js
I added the functionality to changes the icon location according to input and output ports. Especially, it is for  subflow and function nodes which  always have icon on the left side.
> Automatic placing of node icon

- nodes/core/io/21-httprequest.html
- nodes/core/io/21-httprequest.js
This change would add support for `multipart/form-data` type data in `POST` requests with the standard `http request` node.
The payload structure has been reviewed on the forums at [this link](https://discourse.nodered.org/t/add-support-for-multipart-form-data-in-request-node/8111) and I've added some documentation to the node's info panel to indicate this.
The change also incorporates a check for payload type, to ensure that won't attempt this with headers that are mistakenly set to `multipart/form-data` but come with a `msg.payload` of Buffer or String (only accepts type `Object`).
> add multipart/form-data support to http request node

- packages/node_modules/@node-red/nodes/core/storage/50-file.html
As reported [here](https://github.com/node-red/node-red/issues/2086), encoding list of file in/out node are not shown correctly with Firefox.
This PR adds workaround on this issue.
> Fix problem on displaying option label on Firefox

- test/unit/@node-red/editor-api/lib/admin/context_spec.js
- test/unit/@node-red/editor-api/lib/admin/index_spec.js
- test/unit/@node-red/runtime/lib/api/context_spec.js
Currently, the test cases of admin API for context are skipped.
This PR adds test cases to cover the context API.
> Add tests for context API 

- packages/node_modules/@node-red/nodes/core/storage/50-file.html
- packages/node_modules/@node-red/nodes/locales/en-US/messages.json
- packages/node_modules/@node-red/nodes/locales/ja/messages.json
Current encoding menu in file-in and file-out nodes doesn't have title, "Encoding" because message catalog doesn't contain the message. Therefore, I added the messages into the catalogs.
Simultaneously, I added visible/hidden handling in encoding menu when Node-RED user selects "delete file" in Action menu.
> Fix encoding menu in file node

- packages/node_modules/@node-red/editor-client/src/js/ui/palette.js
After dragging and dropping a node from the palette into the central workspace on Node-RED flow editor, we can see a very short animation, the node returns to the palette. When the node is moved to the correct area, this animation is not needed in general draggable setting. And I found that the node returns to the incorrect position when the node is moved to the incorrect area because the position is hardcoded. Therefore, I changed the draggable setting in the code.
Simultaneously, I adjusted animation speed because I think that it's too fast.
> Fix node drag and drop animation

- packages/node_modules/@node-red/nodes/core/core/lib/debug/debug-utils.js
With current master branch of Node-RED, continuously outputting message to debug sidebar causes rapid increase in memory usage of node-red editor tab of Chrome client.  The increased memory is not reclaimed by garbage collector.
This seems to be caused by mixing jQuery with native DOM manipulation as discussed in:
https://makandracards.com/makandra/31325-how-to-create-memory-leaks-in-jquery
This PR replaces raw JavaScript DOM manipulation code by jQuery code.
Sample flow:
```
[{"id":"de885be9.b10fc8","type":"tab","label":"Flow 1","disabled":false,"info":""},{"id":"d14b1b7a.231358","type":"inject","z":"de885be9.b10fc8","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":120,"y":120,"wires":[["271411aa.bb864e"]]},{"id":"f49bed2d.de …
```
> Fix possible memory leak of debug sidebar output

- packages/node_modules/@node-red/nodes/core/io/21-httprequest.js
- test/nodes/core/io/21-httprequest_spec.js
When passing`msg.requestTimeout` with a value of 0 to the http request node it would be ignored and do the request with the default timeout.  This warns the user if he attempts to pass 0.
> http request node: warn user if msg.requestTimeout == 0

- packages/node_modules/@node-red/editor-client/locales/en-US/editor.json
- packages/node_modules/@node-red/editor-client/locales/ja/editor.json
- packages/node_modules/@node-red/editor-client/src/js/ui/library.js
This PR make new library folder creation interface i18n ready.
> Update I18n support for library ui

- packages/node_modules/@node-red/editor-client/locales/en-US/editor.json
- packages/node_modules/@node-red/editor-client/locales/ja/editor.json
- packages/node_modules/@node-red/editor-client/src/js/ui/userSettings.js
This PR make list of editor languages in settings displayed in i18n text instead of raw locale name.
English & Japanese language names are supported.
> update editor language selection UI for i18n

- packages/node_modules/@node-red/editor-client/src/js/ui/common/typedInput.js
In some cases, type selection part of typedInput field is displayed in truncated manner as shown below.
This seems to be resolved by adding `white-space: nowrap` to the calculated html elements as discussed in: https://stackoverflow.com/questions/118241/calculate-text-width-with-javascript
> Fix typedinput width calculation

- Gruntfile.js
- packages/node_modules/@node-red/editor-client/locales/en-US/editor.json
- packages/node_modules/@node-red/editor-client/src/js/keymap.json
- packages/node_modules/@node-red/editor-client/src/js/red.js
- packages/node_modules/@node-red/editor-client/src/js/ui/actionList.js
- packages/node_modules/@node-red/editor-client/src/js/ui/clipboard.js
- packages/node_modules/@node-red/editor-client/src/js/ui/commandPrompt.js
- packages/node_modules/@node-red/editor-client/src/js/ui/common/editableList.js
- packages/node_modules/@node-red/editor-client/src/js/ui/search.js
- packages/node_modules/@node-red/editor-client/src/sass/search.scss
This adds a new command-prompt dialog that lists all available actions and triggers the action when it is selected.
This will help the user discover what actions are available and what keyboard shortcuts are defined. It also allows the user to trigger any action from the keyboard even if a shortcut has not been defined for it. For example, adding a new flow tab can be done via the sequence: `Alt-Shift-P  Down-Arrow Enter` - as that action happens to be the top of the list currently.
The prompt is shown via the action `core:show-command-prompt` which the default keymap maps to `Alt-Shift-P`. I have not yet added a menu item for it - but wanted to gauge feedback before doing that.
The displayed names of the actions are derived from the id of the action. Further work will be needed to …
> Add Command prompt dialog

- packages/node_modules/@node-red/editor-client/src/js/nodes.js
- packages/node_modules/@node-red/editor-client/src/js/ui/common/toggleButton.js
- packages/node_modules/@node-red/editor-client/src/js/ui/editor.js
- packages/node_modules/@node-red/editor-client/src/js/ui/tab-config.js
- packages/node_modules/@node-red/editor-client/src/js/ui/view.js
- packages/node_modules/@node-red/editor-client/src/js/ui/workspaces.js
- packages/node_modules/@node-red/editor-client/src/sass/colors.scss
- packages/node_modules/@node-red/editor-client/src/sass/editor.scss
- packages/node_modules/@node-red/editor-client/src/sass/flow.scss
- packages/node_modules/@node-red/editor-client/src/sass/mixins.scss
- packages/node_modules/@node-red/editor-client/src/sass/tab-config.scss
- packages/node_modules/@node-red/runtime/lib/nodes/flows/Flow.js
- test/unit/@node-red/runtime/lib/nodes/flows/Flow_spec.js
This feature allows individual flow nodes to be disabled.
If disabled, the runtime ignores the node. Messages do *not* pass through a disabled node.
Currently Configuration nodes cannot be disabled. This would need more work to support - for example, we wouldn't want to remove it from the Config Node select boxes (because that would break flows if a user disabled then enabled a config node). But we would perhaps need some indication in the select box that the node has been disabled so the user doesn't inadvertently select it.
A node is disabled by toggling a button in the footer of the edit dialog. I'm not 100% sure about the placement of this button. Some other options I considered:
- in the header next to the Delete button - but that doesn't work so well for Subflow Instance nodes as we …
> WIP: Enable individual flow nodes to be disabled

- packages/node_modules/@node-red/editor-client/src/js/keymap.json
This adds a shortcut for deploy (ctrl-s).
> Add default shortcut (ctrl-d) for deploy

- packages/node_modules/@node-red/registry/lib/library.js
When looking at the Examples import list it currently shows nodes that have an examples directory even if they have nothing in it (eg if they were copied from another node as a template file structure). We may as well not show them in the list.
> Ignore empty examples directories (don't add to import menu)

- package.json
- packages/node_modules/@node-red/util/package.json
Update JSONata to 1.6.5 to fix #2183
> Update jsonata to 1.6.5 which should fix #2183

- packages/node_modules/@node-red/editor-client/src/js/ui/palette.js
I fixed #2243. I removed chartOffset because it is not needed. Only paletteWidth and paletteTop are enough for all nodes.
> Fix inserting new subflow node to existing wire

- CHANGELOG.md
- packages/node_modules/node-red/settings.js
Switch, join, sort and batch nodes use `nodeMessageBufferMaxLength` as a variable name to limit internal queue size but `nodeMaxMessageBufferLength` is used in settings.js and CHANGELOG.md. Therefore, I changed `nodeMaxMessageBufferLength` to `nodeMessageBufferMaxLength`  in the files.
> Fix wrong variable name

- packages/node_modules/@node-red/editor-client/src/js/history.js
- packages/node_modules/@node-red/editor-client/src/js/nodes.js
- packages/node_modules/@node-red/editor-client/src/js/ui/subflow.js
- Problem
With current dev branch, when we convert `function` node to subflow in the following flow,
`function` node remain in original tab as follows.
This is caused by not maintaining the newly introduced `nodeTabMap` when converting to SUBFLOW.
> Fix error on converting selection to subflow

- packages/node_modules/@node-red/editor-client/src/js/nodes.js
Current dev branch causes following reference error on deleting workspace tab.
This PR intended to fixe this problem.
```
red.min.js:16 Uncaught ReferenceError: ws is not defined
at Object.removeWorkspace (red.min.js:16)
at o (red.min.js:16)
at click (red.min.js:16)
at HTMLButtonElement.<anonymous> (red.min.js:16)
at HTMLButtonElement.dispatch (vendor.js:2)
at HTMLButtonElement.v.handle (vendor.js:2)
```
> fix reference error on deleting tab

- packages/node_modules/@node-red/nodes/core/logic/10-switch.html
- packages/node_modules/@node-red/nodes/core/logic/10-switch.js
- packages/node_modules/@node-red/nodes/locales/en-US/messages.json
- test/nodes/core/logic/10-switch_spec.js
Adds a "Has key" option to the switch node so users can route messages based on if a property of their msg exists, as requested on mailing list- https://discourse.nodered.org/t/switch-node-jsonata-magic/12943/4
> Add "has key" rule to  switch node + tests

- .github/ISSUE_TEMPLATE.md
- .github/ISSUE_TEMPLATE/--bug_report.md
- CONTRIBUTING.md
- packages/node_modules/@node-red/runtime/lib/index.js
- packages/node_modules/node-red/lib/red.js
- packages/node_modules/node-red/red.js
Node.js v6 users tend to encounter some problems because current Node-RED doesn't support Node.js v6. To know that Node.js v6 is unsupported when starting Node-RED, I added the appropriate version for handling to check the version of Node.js. And I replaced node.js with Node.js and removed handling for unused error code which is used in starting Node-RED.
> Use appropriate version of Node.js

- packages/node_modules/@node-red/editor-client/locales/ja/editor.json
- packages/node_modules/@node-red/nodes/locales/ja/messages.json
I updated Japanese translation for Node-RED flow editor.
> Update Japanese message catalog

- packages/node_modules/@node-red/editor-client/src/js/ui/tab-context.js
- packages/node_modules/@node-red/nodes/core/core/lib/debug/debug-utils.js
Buttons on the debug tab have the same duplicated tooltips. Therefore, I removed the tooltip created by the `title` attribute.
> Fix duplicated tooltips

- packages/node_modules/@node-red/nodes/core/logic/17-split.js
I added "g" into the end of regular expressions to handle escape characters repeatedly in separator of the split node. Because join node handles escape characters repeatedly but split node doesn't do the same handle, for example, the following flow cannot split table data which uses "¥t|¥t" as a separator.
```
[{"id":"74dad08f.907508","type":"inject","z":"6c707c87.f66fe","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":150,"y":120,"wires":[["1c96485.4128a38"]]},{"id":"e05591e4.c7bd38","type":"split","z":"6c707c87.f66fe","name":"split by \"<tab>|<tab>\"","splt":"\\t|\\t","spltType":"str","arraySplt":1,"arraySpltType":"len","stream":false,"addname":"","x":170,"y":260,"wires":[["59d4206c.cf9358","1f98c665.fcaaaa"]]},{"id":"59d420 …
```
> Fix escape character handling for separator in split node

- packages/node_modules/@node-red/editor-client/src/js/ui/editor.js
Node property UI for general nodes has only buttons to select a tab (Property, Description, Appearance tabs) and has no menu. On the other hand, the configuration node and subflow node have the menu to select a tab in addition to buttons. To make them the same user experience, I removed the menu from the configuration node and subflow node.
> Remove tab menu from node property UI for subflow and configuration nodes

- packages/node_modules/@node-red/editor-client/src/js/ui/palette.js
With current dev branch, subflow category change is not immediately reflected in the palette.
This PR will fix this problem.
> fix subflow category change on palette

- packages/node_modules/@node-red/editor-client/locales/en-US/editor.json
- packages/node_modules/@node-red/editor-client/locales/ja/editor.json
- packages/node_modules/@node-red/editor-client/src/js/nodes.js
- packages/node_modules/@node-red/editor-client/src/js/ui/editor.js
- packages/node_modules/@node-red/editor-client/src/js/ui/palette.js
- packages/node_modules/@node-red/editor-client/src/js/ui/utils.js
- packages/node_modules/@node-red/editor-client/src/sass/editor.scss
This PR add support for specifying SUBFLOW color.
Color is specified for SUBFLOW template (not instance) by its appearance tab.
Change of SUBFLOW color take effect after reloading editor.
> Add support for specifying subflow template color

- packages/node_modules/@node-red/editor-client/locales/en-US/editor.json
- packages/node_modules/@node-red/editor-client/locales/ja/editor.json
- packages/node_modules/@node-red/editor-client/src/js/ui/subflow.js
Some string of new subflow UI feature are not i18n ready.
This PR make them i18n ready.  
It also adds Japanese message catalogue items and remove unused catalogue items.
> Fix i18n of new subflow feature

- packages/node_modules/@node-red/editor-client/src/js/nodes.js
- packages/node_modules/@node-red/nodes/core/core/25-complete.html
- packages/node_modules/@node-red/nodes/core/core/25-complete.js
- packages/node_modules/@node-red/nodes/core/core/58-debug.js
- packages/node_modules/@node-red/nodes/core/core/75-exec.js
- packages/node_modules/@node-red/nodes/core/core/80-function.js
- packages/node_modules/@node-red/nodes/core/io/10-mqtt.js
- packages/node_modules/@node-red/nodes/core/io/21-httprequest.js
- packages/node_modules/@node-red/nodes/core/io/22-websocket.js
- packages/node_modules/@node-red/nodes/core/io/31-tcpin.js
- packages/node_modules/@node-red/nodes/core/io/32-udp.js
- packages/node_modules/@node-red/nodes/core/logic/15-change.js
- packages/node_modules/@node-red/nodes/core/storage/50-file.js
- packages/node_modules/@node-red/nodes/locales/en-US/core/25-complete.html
- packages/node_modules/@node-red/nodes/locales/en-US/messages.json
- packages/node_modules/@node-red/runtime/lib/nodes/Node.js
- packages/node_modules/@node-red/runtime/lib/nodes/flows/Flow.js
- packages/node_modules/@node-red/runtime/lib/nodes/flows/index.js
- test/nodes/core/core/80-function_spec.js
- test/nodes/core/logic/18-sort_spec.js
- test/nodes/core/parsers/70-HTML_spec.js
- test/nodes/core/parsers/70-JSON_spec.js
- test/nodes/core/parsers/70-YAML_spec.js
- test/unit/@node-red/runtime/lib/nodes/Node_spec.js
- test/unit/@node-red/runtime/lib/nodes/flows/Flow_spec.js
- test/unit/@node-red/runtime/lib/nodes/flows/Subflow_spec.js
- adds an option 'done' parameter to the Node's `input` event handler. This allows the node to notify the runtime is has finished processing a message
- introduces the Complete node that is triggered by these notifications and can be used to start a second flow when another one finished
- **MAYBE BREAKING CHANGE**: The messaging passing between nodes is now asynchronous rather than synchronous. This will cause a change in the apparent order nodes are evaluated as messages pass through branches in a flow. Rather than depth-first, it will now be breadth-first.
- To restore the synchronous message passing, `runtimeSyncDelivery` can be set to `true` in the settings file. This is a temporary measure to help users keep their flows running until they are read to embrace async mode.
> Adds Done callback to Input event handler

- packages/node_modules/@node-red/editor-client/src/js/ui/view.js
- packages/node_modules/@node-red/nodes/core/io/21-httprequest.html
- packages/node_modules/@node-red/nodes/core/io/21-httprequest.js
- packages/node_modules/@node-red/nodes/locales/en-US/messages.json
- packages/node_modules/@node-red/runtime/lib/storage/localfilesystem/projects/ssh/keygen.js
With this update, now the HTTP Request node can support persistent HTTP connection (HTTP session reuse). This is very useful in some cases, for instance, an API that requires subsequent communications through the first initial TCP session.
> Add HTTP Persistent (session reuse) capability

- packages/node_modules/@node-red/editor-client/src/js/ui/subflow.js
In the SUBFLOW UI definition, if the row type is `none` (label definition), the environment variable name is not needed.  
> Allow subflow label row without environment variable name

- packages/node_modules/@node-red/editor-client/src/js/ui/subflow.js
When no icon is defined for SUBFLOW UI row, there is a small padding on the left side of the label.
This PR removes this.
> Remove padding for label for SUBFLOW UI row without icon

- packages/node_modules/@node-red/editor-client/src/js/ui/subflow.js
For `select` type SUBFLOW UI definition with no menu item definition, following operation causes reference of undefined value:
1. load a flow with `select` type SUBFLOW UI definition with no menu item definition,
2. open instance of the SUBFLOW,
3. open edit SUBFLOW template,
4. open environment variable definition panel,
5. open menu definition 
This is caused by initialization of internal ui options for `select` item without required field.
Sample Flow:
```
[{"id":"e8d2465c.e012c8","type":"tab","label":"Flow 1","disabled":false,"info":""},{"id":"e07ed459.72e398","type":"subflow","name":"Subflow 1","info":"","category":"","in":[],"out":[],"env":[{"name":"V","type":"str","value":"","ui":{"type":"select"}}],"color":"#da9"},{"id":"15e42ee8.649301","type":"function","z":"e07ed459.72e398","nam …
```
> Fix subflow UI for select

- packages/node_modules/@node-red/editor-client/src/js/ui/editor.js
- packages/node_modules/@node-red/editor-client/src/js/ui/editors/markdown.js
- packages/node_modules/@node-red/editor-client/src/js/ui/library.js
Current Markdown editor has two troubles. When the Node-RED user expands the editor,  the user cannot utilize the large resolution of the display effectively because the maximum size of the editor is 1000px. Therefore, I removed the definition of the max size. After fixing it, the user experience will be the same as JavaScript editor in the function node.
And there's an unknown vertical gray line (I found that it is a print margin while fixing it.) on the editors. I added ace editor option to remove it.
> Fix Markdown editor

- packages/node_modules/@node-red/editor-client/src/js/ui/palette.js
Node/Subflow name with long words displayed incorrectly on palette as follows.
This PR allow breaking long words to make node name displayed appropriately.
Example Flow:
```
[{"id":"2ea254e1.57525c","type":"tab","label":"Flow 1","disabled":false,"info":""},{"id":"bb38aeb.bd5705","type":"subflow","name":"あいうえおかきくけこさしすせそ","info":"","category":"","in":[],"out":[],"env":[],"color":"#da9"},{"id":"f985a78b.017a88","type":"subflow","name":"ABCDEFGHIJKLMNOPQRSTUVWXYZ","info":"","category":"","in":[],"out":[],"env":[],"color":"#da9"},{"id":"a4068e80.92d37","type":"subflow","name":"ABC DEF GHI JKL MNO PQR STU VWX YZ","info":"","category":"","in":[],"out":[],"env":[],"color":"#da9"},{"id":"2dd42cc4.5050d4","type":"subflow","name":"ABCDEF GHIJKL MNO …
```
> allow word breaking of node name with long word

- packages/node_modules/@node-red/editor-client/src/js/ui/palette.js
There's a draggable handling problem in the 1.0-beta version of Node-RED. When users drag a node to the outside central workspace, the node will return to the incorrect location (left edge of the palette) because `$('#' + e.target.id).offset().left;` always has 0 as the value currently. Therefore, I replaced the code with `getPaletteNode(nt)` to get the appropriate location.
> Fix draggable handling in palette

- packages/node_modules/@node-red/editor-client/src/js/red.js
According to the [configuration document](https://nodered.org/docs/user-guide/runtime/configuration#editor-themes), the following options in settings.js are supported to hide the unwanted items in the menu of Node-RED flow editor.
editorTheme: {
menu: {
"menu-item-import-library": false,
"menu-item-export-library": false,
"menu-item-keyboard-shortcuts": false,
}
}
But these options are not valid in the current implementation. Therefore, I added the handling to support them.
> Fix menu hiding function for flow editor

- packages/node_modules/@node-red/editor-client/src/js/ui/editor.js
This PR fixes #2298.  I investigated the issue and the reproduction steps are much simpler than originally described in the ticket.  This bug seems to occur when a subflow color is changed from the initial load and the subflow node does not exist on any flows.  
I'm guessing when the `RED.nodes.eachNode` loop happens and the subflow exists on a flow it gets updated (but I'm not sure).  
From my logging it seems like if the subflow doesn't exist on a flow the registry's `nodeDefinitions` contains a stale version of the subflow with the old color.
This PR adds some logic to update the nodeDefinition of the subflow with the new color when there is a color change.
Repro:
Add a new subflow
Change the color of it
Drag it onto a flow tab and observe the color
Not sure if this is the best way to …
> Fix issue where subflow color did not update when not on a flow

- packages/node_modules/node-red/red.js
This PR introduces two new environment variables that can be used to modify Node-RED behaviour.
- `NODE_RED_ENABLE_SAFE_MODE` : enables safe mode. Equivalent to `--safe` argument
- `NODE_RED_ENABLE_PROJECTS` : enables projects. Equivalent to `editorTheme.projects.enabled=true`
The benefit of adding these env vars is it makes it easier to enable these features in the docker container for two reasons:
1. you don't have to change the start command to add `--safe`
2. you don't have to edit the settings file to enable projects
Rather than add these things as docker specific features, it seems sensible to add them to the core of node-red as I'm sure they will be useful in other scenarios.
> Add env vars to enable safe mode and projects

- packages/node_modules/@node-red/nodes/core/common/20-inject.html
On the inject node property UI, the pull-down menu and checkboxes are wider than specified values. This problem seemed to occur because the order of the styles to apply was changed in Node-RED  v1.0.0. Therefore, I added `!important` to set higher priority.
> Fix width on inject node property

- packages/node_modules/@node-red/editor-client/locales/de/editor.json
- packages/node_modules/@node-red/editor-client/locales/en-US/editor.json
- packages/node_modules/@node-red/editor-client/locales/ja/editor.json
- packages/node_modules/@node-red/editor-client/locales/ko/editor.json
- packages/node_modules/@node-red/editor-client/locales/zh-CN/editor.json
- packages/node_modules/@node-red/editor-client/src/js/ui/editor.js
- packages/node_modules/@node-red/editor-client/src/js/ui/tab-config.js
Because some tooltips don't support i18n, I modified them to support i18n.
> i18n support in tooltips

- packages/node_modules/@node-red/editor-client/src/js/ui/userSettings.js
After a user opens and closes the user settings UI, the grid and snapping settings are cleared. Because this problem occurred from no default values in the grid setting, I added them.
> Fix grid setting in flow editor

- packages/node_modules/@node-red/nodes/locales/en-US/messages.json
Changed tip of inject node dialog.
Interval of inject node should be "596 hours or less", not "less than 596 hours".
> Interval of inject node should be 596 hours or less.

- packages/node_modules/@node-red/nodes/locales/de/function/80-template.html
- packages/node_modules/@node-red/nodes/locales/en-US/function/80-template.html
- packages/node_modules/@node-red/nodes/locales/ja/function/80-template.html
- packages/node_modules/@node-red/nodes/locales/ko/function/80-template.html
Current examples in the information tab of the template node don't work correctly because the JSON is not valid. Therefore, I fixed them in this pull request.
> Fix invalid JSON data in template node

- packages/node_modules/@node-red/util/lib/util.js
The API docs for `RED.util` do not match the full function signature for a number of functions, specifically `getMessageProperty`, `getObjectProperty` and `parseContextStore`. Over time, the name of a parameter in those functions got changed, but the jsdoc didn't get updated. This PR fixes the JSDoc.
> Fixed docstrings to have them match the function signature 

- packages/node_modules/@node-red/editor-client/src/js/ui/editors/json.js
Current "Collapse items" element in the menu on visual JSON editor collapses child JSON objects only. I think that it is natural to collapse both parent and child JSON objects (It is opposite handling of "Expand items"). Therefore, I added the handling to collapse the parent JSON object.
> Fix menu in visual JSON editor

- packages/node_modules/@node-red/editor-client/src/js/ui/subflow.js
The current subflow cannot show messages in the node property according to language which is specified in user settings UI. The language used is the language that was specified in custom subflow UI. This problem occurred because custom subflow property UI overwrites the `currentLocale` value. Therefore, I changed the value name to avoid the conflict.
> Fix language handling in subflow node

- packages/node_modules/@node-red/editor-client/src/js/ui/subflow.js
Because the tooltip language in customUI of subflow was "en-US","ja","de"...,
I modified them to become "English", "Japanese", "German".
I also changed the width 50px to 120px, because "Chinese(Simplified)" overwrapped with Label area.
> fix tooltip language in subflow

- packages/node_modules/@node-red/nodes/core/network/21-httprequest.html
When opening the config screen of a http-request node, the authentication type (digest, basic, bearer) will determine which fields (username, passworde, token) needs to be visible.  Since that ```change``` handler wasn't called, the incorrect authentication fields became visible.
I simply call the ```change()``` method of the authentication-type dropdown, to trigger the handler...
I have discussed the change (incl. animations) in this Discourse [post](https://discourse.nodered.org/t/odd-problem-with-bearer-authentication/12422/16?u=bartbutenaers).
> Check auth type on opening

- packages/node_modules/@node-red/nodes/core/storage/10-file.js
When using the file-in node and ‘a msg per line’ the last line does not get msg.topic passed. 
In the  
.on(‘end’, function() { 
code (starting at line 334) the msg is created but no msg.topic is set. Adding 
topic:msg.topic, 
after line 343 (var m = { payload: spare,) fixes the issue.
> Using the ‘a msg per line’ the last line does not get msg.topic passed

- packages/node_modules/@node-red/editor-client/src/js/nodes.js
On the latest Node-RED flow editor, users can mistakenly create a nested subflow using keyboard shortcuts.
To avoid the nested subflow, there's the handling to show an error in the current implementation but it doesn't work correctly because `getSubflow(newNodes[i].z || activeWorkspace)` returns `null`. I think that `getSubflow(activeWorkspace)` is enough to the handling. Because I cannot imagine the situation to use `newNodes[i].z`, I tried to submit this pull request as a draft pull request.
> Fix handling to avoid invalid nested subflow

- packages/node_modules/@node-red/editor-client/src/js/ui/subflow.js
- packages/node_modules/@node-red/editor-client/src/js/ui/workspaces.js
- packages/node_modules/@node-red/nodes/99-sample.html.demo
- packages/node_modules/@node-red/nodes/core/common/90-comment.html
Because I found that there are name fields which have no placeholders in subflow node, tab, comment node, and 99-sample node, I added them.
> Add placeholders to name fields

- packages/node_modules/@node-red/editor-client/src/js/ui/editors/expression.js
Function help text of JSONata expression editor is initially blank.
This PR fixes it to be shown initially.
> Make JSONata help initially shown

- packages/node_modules/@node-red/editor-client/src/sass/ui/common/typedInput.scss
For typedInput with long list of types, unexpected line break is inserted after menu icon of type items as shown below:
- Change node[Japanese]
- Change node[English with narrow browser window]
This PR prohibits insertion of line break in menu items.
> Prohibit line break in type menu of typedInput

- packages/node_modules/@node-red/editor-client/src/js/ui/common/tabs.js
Quick wiring supports both meta and ctrl keys but selecting tab supports meta key only. It is difficult for Windows users to select tabs using the meta key (Windows key) because the Windows taskbar is opened when the key is used. I think that the ctrl key is needed for Windows users.
> Support ctrl key to select tabs for Windows

- packages/node_modules/@node-red/editor-client/locales/en-US/editor.json
- packages/node_modules/@node-red/editor-client/locales/ja/editor.json
- packages/node_modules/@node-red/editor-client/src/js/ui/editor.js
I added a tooltip to the expand button in the markdown editor.
> Add tooltip to the expand button in markdown editor

- scripts/install-ui-test-dependencies.sh
- test/editor/wdio.conf.js
Currently, UI testing doesn't work because the handling of the latest Google Chrome seems to have been changed. To work correctly, I updated the modules and modified the settings of the Webdriver IO.
> Fix UI testing on the latest Google Chrome

- packages/node_modules/@node-red/editor-client/locales/en-US/editor.json
- packages/node_modules/@node-red/editor-client/locales/ja/editor.json
- packages/node_modules/@node-red/nodes/core/function/10-switch.html
- packages/node_modules/@node-red/nodes/core/sequence/17-split.html
- packages/node_modules/@node-red/nodes/locales/en-US/messages.json
- packages/node_modules/@node-red/nodes/locales/ja/messages.json
I found that there're typedInput menus that don't support i18n in join and switch nodes. Therefore, I modified the code.
> Support i18n for typedInput in join and switch nodes

- packages/node_modules/@node-red/util/lib/log.js
- packages/node_modules/@node-red/util/lib/util.js
- test/unit/@node-red/util/lib/log_spec.js
- test/unit/@node-red/util/lib/util_spec.js
Catches bad objects being encoded, returning instead the error.
Symptom- Observed that global context would not display in front end, the call returning 400.
Traced to an object in global which cause encodeObject to except.
This push catches that, and now global will display, but the object in question display as an error.
I considered catching around the call to encodeObject, but inside seems more appropriate as it fixes the issue globally.  However, please consider how this could impact any other code which uses encodeObject.
I assume this change will also affect all places where objects are converted for display on the UI.
e.g. 'bad things' in messages will display the result as an error.
> Catches bad objects being encoded, returning instead the error.

- packages/node_modules/@node-red/runtime/lib/nodes/flows/Subflow.js
For all those nodes thaht don't specify it.
So that subflow status then works ok
the subflow seems to need the correct `node-red:` context for i18n of status message to work correctly - other wise they just show the untranslated version (eg common.status.OK) 
This fix checks to see if the text starts with `common` and if so prepends the `node-red:` context.
About 80% of core nodes do NOT have the context set - so we either need to do something like this or fix all the nodes - (and then the 3rd party ones)
> let subflow add node-red context to status so i18n works

- packages/node_modules/@node-red/util/lib/i18n.js
As discussed in the [forum](https://discourse.nodered.org/t/i18n-language-fallback-behaviour/13039):
The i18n language fallback behaviour is currently not following the [fallback principles](https://www.i18next.com/principles/fallback) of the i18next framework.
E. g. if the browser language is set to "de-DE" and there are no "de-DE" files, it should(!) look for "de" files first. Instead Node-RED falls back to "en-US" immediately.
This PR should fix that issue.
> I18n - language fallback behaviour

- packages/node_modules/@node-red/nodes/core/network/10-mqtt.js
- packages/node_modules/@node-red/nodes/core/network/21-httprequest.js
- packages/node_modules/@node-red/nodes/core/network/22-websocket.js
Bugfix: Fixes comparison of proxy and noproxy against null, now just looks for non-falsy.
1/ The existing comparison encourages people to set the env variable to null, which ends up with it equalling the string 'null'.
2/ if (process.env.no_proxy === undefined), then process.env.no_proxy.split will fail.
Extends proxy use in mqtt by adding noproxy support.
Adds proxy/noproxy support to websocket.
ToDo:
really, proxy configuration node selection should also be added to mqtt and websocket?
> noproxy support in mqtt, Proxy & noproxy support in websocket

- packages/node_modules/@node-red/editor-client/src/js/red.js
Installing new node from editor *Manage Palette* interface causes following error:
```
Uncaught TypeError: RED.library.loadFlowLibrary is not a function
```
It seems that  the `loadFlowLibrary` function become useless in current Node-RED version.  Thus, this PR removes call of the `loadFlowLibrary` call.
> Remove undefined loadFlowLibrary call

- packages/node_modules/@node-red/editor-client/src/sass/ace.scss
- packages/node_modules/@node-red/editor-client/src/sass/forms.scss
When Japanese users input Japanese words on the ace editor, an unknown horizontal object which interferes with reading input text emerges.
Discussion: https://discourse.nodered.org/t/since-version-1-0-japanese-inline-input-has-become-difficult-to-use/19009
I found that this problem came from CSS restructuring. Therefore, I modified it (I checked it on the latest Chrome and Firefox on both Windows 10 and macOS in addition to IE and Safari).
> Fix IME bug in text editor

- packages/node_modules/@node-red/editor-client/src/js/ui/editors/json.js
I found that there're menus that don't support internationalization and have no icons in JSON editor. Therefore, I fixed them.
> Add icons and support i18n in typedInput of JSON editor

- Gruntfile.js
- scripts/install-ui-test-dependencies.sh
- test/editor/pageobjects/util/key_page.js
- test/editor/wdio.conf.js
In this pull request, I added code to execute UI testing on BrowserStack.
The discussion slides about the BrowserStack support are as follows (page 12-17). 
https://github.com/node-red-hitachi/node-red-notes/blob/master/Meeting/20200127/02-Testing.pdf
[Procedures to execute UI testing]
(1) Set BrowserStack credentials to environment variables 
BROWSERSTACK_USERNAME=\<user name\>
BROWSERSTACK_ACCESS_KEY=\<accesss key\>
(2) npm install
(3) scripts/install-ui-test-dependencies.sh
(4) grunt --browserstack
> Support BrowserStack in UI testing

- packages/node_modules/@node-red/editor-client/locales/en-US/editor.json
- packages/node_modules/@node-red/editor-client/locales/ja/editor.json
- packages/node_modules/@node-red/editor-client/locales/ja/jsonata.json
I added translations for the JSONata expression editor and language menu. At the same time, I fixed typos.
> Add Japanese translations for i18n

- packages/node_modules/@node-red/editor-client/locales/ja/editor.json
- packages/node_modules/@node-red/nodes/core/parsers/70-HTML.html
- packages/node_modules/@node-red/nodes/core/parsers/70-XML.html
- packages/node_modules/@node-red/nodes/core/parsers/70-YAML.html
- packages/node_modules/@node-red/nodes/core/sequence/18-sort.html
- packages/node_modules/@node-red/nodes/core/sequence/19-batch.html
While checking the messages catalog, I found that some node files have unnecessary namespaces for i18n. To match namespace rules with other nodes, I removed the namespaces.
> Remove unnecessary namespaces for i18n

- packages/node_modules/@node-red/editor-client/locales/zh-CN/editor.json
- packages/node_modules/@node-red/editor-client/locales/zh-CN/jsonata.json
- packages/node_modules/@node-red/nodes/locales/zh-CN/messages.json
- packages/node_modules/@node-red/runtime/locales/zh-CN/runtime.json
1. Add zh-CN translation for runtime.json
2. Update zh-CN translation for editor-client
3. Update zh-CN translation for nodes messages.json
> Complete zh-CN translation for Editor-client/Nodes/Runtime

- packages/node_modules/@node-red/editor-client/locales/en-US/editor.json
- packages/node_modules/@node-red/editor-client/src/js/ui/common/typedInput.js
- packages/node_modules/@node-red/editor-client/src/sass/ui/common/typedInput.scss
Introduces a new `cred` built-in type for the TypedInput widget.
This is intended as an alternative to the plain `<input type="password">` element, providing a more intuitive user experience for the way the editor already handles credentials.
When a node is edited, the editor doesn't know the true value of any password-credential properties. It only knows if the runtime has a value or not.
With a plain password input, we use the placeholder `__PWRD__` so we can tell if the user has edited the value or not. But that can lead to confusion:
1. the placeholder dots for `__PWRD__` may be a different length to the value a user knows they have set. That makes the user uncertain if the value has been stored properly or truncated.
2. if the user knows what value they entered previously and wants …
> Add credential type to TypedInput

- packages/node_modules/@node-red/runtime/lib/nodes/Node.js
Fixes #2444
Moves the point where we log the `receive` metric event so it is *after* the async break. This will mean the gap between the `receive` and subsequent `send` metric events better reflect the actual processing time.
@HiroyasuNishiyama this is a very simple change, but would appreciate if you could verify the metrics look better with this change in place.
> Move receive metric position to better reflect async changes

- package.json
- packages/node_modules/@node-red/nodes/package.json
fixes #2469
this is a major version bump of https-proxy-agent, because they set engine to >6 and did some refactoring, which is ok for node-red.
version bump, because dependency has bug
> bump https-proxy-agent

- packages/node_modules/@node-red/runtime/lib/api/flows.js
- packages/node_modules/@node-red/runtime/lib/nodes/flows/index.js
- test/unit/@node-red/runtime/lib/api/flows_spec.js
- test/unit/@node-red/runtime/lib/nodes/flows/index_spec.js
This PR allows credentials to be included as part of the `/flows` end point.
For example:
```
curl --header "Node-RED-API-Version: v2" \
--header "Content-Type: application/json" \
--request POST \
--data '{"flows":[{"id":"12e1febf.0d0201","type":"tab","label":"Flow 1","disabled":false,"info":""},{"id":"6a4f931.ab6016c","type":"http request","z":"12e1febf.0d0201","name":"","method":"GET","ret":"txt","paytoqs":false,"url":"","tls":"","persist":false,"proxy":"","authType":"basic","x":430,"y":120,"wires":[[]]}],"credentials":{"6a4f931.ab6016c":{"user":"foo","password":"bar"}}}' http://localhost:1880/flows
```
This does a complete replacement of the credentials in the runtime - it cannot be used to incrementally update only some of the credentials. That will come in a future update.
This is …
> Allow credentials to be provided as part of /flows api

- packages/node_modules/@node-red/editor-client/src/js/ui/view.js
This PR adds a 'line break' function of label on nodes.
Users can separate the words on different lines by inserting '\n' in the name field.
Support a line break at workspace and properties editor.
> Add a 'line break' function

- test/editor/pageobjects/nodes/core/function/15-change_page.js
- test/editor/pageobjects/nodes/core/parsers/70-JSON_page.js
- test/editor/pageobjects/nodes/core/parsers/70-XML_page.js
- test/editor/pageobjects/nodes/core/parsers/70-YAML_page.js
Because XPath was changed in the commit(https://github.com/node-red/node-red/commit/cc5fdd984459f74bb022bfc4f34d7a4f95eb8b7a),  the UI test fails. Therefore, I fixed the XPath in the page objects.
> Fix XPath in page objects for UI tests

- packages/node_modules/node-red/settings.js
Fix paletteCategories order to match the order in the "Version 1.0 released" [blog post](https://nodered.org/blog/2019/09/30/version-1-0-released#reorganised-palette).
> Fix paletteCategories order

- packages/node_modules/@node-red/nodes/locales/ja/storage/10-file.html
- packages/node_modules/@node-red/nodes/locales/zh-CN/storage/10-file.html
- packages/node_modules/@node-red/nodes/locales/zh-TW/storage/10-file.html
I applied updates (https://github.com/node-red/node-red/commit/b165129388f37f2f8b873016c1cc346b9aaf0185 and https://github.com/node-red/node-red/commit/09d55a0cbdff545f59138c232163283dfe0fde65) of English messages on file node property to Japanese and Chinese ones.
> Remove old leagcy wording from file node info (Japanese and Chinese)

- packages/node_modules/@node-red/util/lib/util.js
The function prepareJSONataExpression() does not take context store into account.
This causes problems when using typedInput fields and getting the value of a property based on its type using evaluateNodeProperty()
The function `prepareJSONataExpression()` does not take context store into account.
This causes problems when using `typedInput` fields and getting the value of a property based on its type using`evaluateNodeProperty()`. 
So far the only option was to check first if the type of the property is `"jsonata"`, then call `prepareJSONataExpression()` and then `evaluateJSONataExpression()` with a callback so that the context stores are taken into account.
> Support for context stores using JSONata and evaluateNodeProperty()

- packages/node_modules/@node-red/editor-api/lib/auth/index.js
- packages/node_modules/@node-red/editor-api/lib/auth/strategies.js
- packages/node_modules/@node-red/editor-api/lib/auth/users.js
- test/unit/@node-red/editor-api/lib/auth/strategies_spec.js
- test/unit/@node-red/editor-api/lib/auth/users_spec.js
This PR proposes a feature that enables the execution of the Admin API even in the 'strategy' scheme by adding a customizable token-based authentication function.
Details are written in [design note](https://github.com/node-red/designs/blob/master/designs/admin-api-authentication.md).
> Add admin api authentication function

- packages/node_modules/@node-red/nodes/locales/ja/messages.json
- packages/node_modules/@node-red/nodes/locales/ja/sequence/17-split.html
Because English messages of the join node was updated in the commit, https://github.com/node-red/node-red/commit/85a1f59a93664e317934b3beac7f9de60f00b1c9, I added translation of that in this commit.
> Add Japanese translation for join node

- packages/node_modules/@node-red/nodes/core/network/22-websocket.html
- packages/node_modules/@node-red/nodes/locales/de/messages.json
- packages/node_modules/@node-red/nodes/locales/de/network/22-websocket.html
- packages/node_modules/@node-red/nodes/locales/en-US/messages.json
- packages/node_modules/@node-red/nodes/locales/ja/messages.json
- packages/node_modules/@node-red/nodes/locales/ko/messages.json
- packages/node_modules/@node-red/nodes/locales/zh-CN/messages.json
- packages/node_modules/@node-red/nodes/locales/zh-TW/messages.json
Because I found that the English message remains on the WebSocket node property in my Japanese browser environment, I added Japanese translations. To support the same change in other languages, I also modified other message catalogs.
> Add Japanese translation to node property of websocket node

- packages/node_modules/@node-red/editor-client/src/js/ui/editor.js
Subflow template editing panel has three configuration tabs.  But, when opening the panel, only one icon is shown as below.
After clicking the appearance icon, properties icon is shown.
Then after clicking icon, descriptions icon is shown.
This seems to be caused by a move of tab construction code into callback function.
> fix tab appearance of subflow template panel

- packages/node_modules/@node-red/editor-client/src/js/events.js
- packages/node_modules/@node-red/editor-client/src/js/history.js
- packages/node_modules/@node-red/editor-client/src/js/nodes.js
- packages/node_modules/@node-red/editor-client/src/js/ui/deploy.js
- packages/node_modules/@node-red/editor-client/src/js/ui/editor.js
- packages/node_modules/@node-red/editor-client/src/js/ui/group.js
- packages/node_modules/@node-red/editor-client/src/js/ui/palette.js
- packages/node_modules/@node-red/editor-client/src/js/ui/subflow.js
- packages/node_modules/@node-red/editor-client/src/js/ui/view.js
- packages/node_modules/@node-red/editor-client/src/js/ui/workspaces.js
This introduces a much more consistent set of events within the editor for whenever an element is added, removed or modified.
The events emitted on the `RED.events` event system. The event names take the form: `"<thing>:<action>"`.
`<thing>` can be one of:
- nodes
- flows
- subflows
- groups
- links
`<action>` can be one of:
- add
- remove
- change
The payload of the events is the object in question.
There is also:
- flows:reorder    - when tabs are reordered. Payload is array of flow ids.
- workspace:clear  - when the workspace is emptied - part of switching projects
The `nodes:change` event was already used by RED.nodes.dirty() to cause the Deploy button to become active. This PR renames that event to:
- workspace:dirty  - Payload is boolean flag for the dirty state
This commit also …
> Add more consistent events in the editor

- test/editor/specs/scenario/cookbook_dataformats_uispec.js
Currently, the UI testing fails in 'convert to/from YAML' case because the indent of output data from the YAML node seems to be changed. I fixed the indent to run without the failing.
> Fix test cases for UI testing

- packages/node_modules/@node-red/nodes/core/network/21-httpin.js
There is a deprecation warning during http requests when metrics enabled:
`(node:87599) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated`
> Fix: Remove nodejs deprecation warning in 21-httpin node

- packages/node_modules/@node-red/nodes/core/common/20-inject.html
- packages/node_modules/@node-red/nodes/core/common/20-inject.js
- packages/node_modules/@node-red/nodes/locales/en-US/messages.json
This change is to allow users to inject whatever properties they want to `msg`. This allows you to inject directly to an http-request node for example.
This change is intended to be 100% backward compatible with existing flows.
ToDo:
- Info panel needs to be updated
- Unit tests need to be created
> Adding user definable properties to inject node

- packages/node_modules/@node-red/editor-client/src/js/ui/projects/projects.js
In the `Projects` menu, the `Open` and `Project Settings` are disabled after enabling project feature and initial cloning of a project from a remote repository.
> Activate project menu after initial clone

- packages/node_modules/@node-red/nodes/core/network/31-tcpin.js
The rationale is to collect (via status changes) own list of active sessions for particular tcp-in nodes to allow to pass an external message to those sessions only.
Proposed as a workaround for https://discourse.nodered.org/t/tcp-connection-pool-better-separation/19432.
Please consider applying.
> Allow to know particular session from status node

- packages/node_modules/@node-red/nodes/core/common/20-inject.js
- packages/node_modules/@node-red/nodes/locales/en-US/messages.json
- packages/node_modules/@node-red/nodes/locales/ja/messages.json
- test/nodes/core/common/20-inject_spec.js
New properties definition interface of inject node allow use of JSONata expression that is useful for creating values using logics.  
However, in the current implementation, if an error occurs in a JSONata expression, the node's error output become "[object Object]" at runtime.  On the other hand, in change node, an error of JSONata expression is reported at deployment time.
This fix ensures that the message is output correctly and change the behavior in line with the current change node.
> Update inject node error handling

- packages/node_modules/@node-red/editor-client/locales/en-US/editor.json
- packages/node_modules/@node-red/editor-client/locales/ja/editor.json
- packages/node_modules/@node-red/editor-client/src/js/ui/group.js
- packages/node_modules/@node-red/nodes/locales/ja/messages.json
While I tried the functionality of grouping nodes, I translated English messages to Japanese.
> Add Japanese translations for grouping nodes

- packages/node_modules/@node-red/editor-client/locales/en-US/editor.json
- packages/node_modules/@node-red/editor-client/src/js/red.js
- packages/node_modules/@node-red/editor-client/src/js/ui/projects/projects.js
- packages/node_modules/@node-red/editor-client/src/sass/workspace.scss
Adds a progress bar show when the editor is loading (or project is being changed).
- gives feedback on progress loading elements
- hides the editor until it is fully populated
**Note** - this PR is based on the `outliner` branch. We should get #2556 merged first, then this becomes a 1-commit PR to just add the progress bar on top.
> Add a loading progress bar

- packages/node_modules/@node-red/editor-api/lib/index.js
- packages/node_modules/node-red/settings.js
Adds `httpAdminMiddleware` as a new optional setting that works in the same way as the existing `httpNodeMiddleware` setting, but is applied to the HTTP Admin routes.
This will allow, for example, for custom http headers to be added to all admin routes. 
The example in the settings file does this:
```
httpAdminMiddleware: function(req,res,next) {
// Set the X-Frame-Options header to limit where the editor
// can be embedded
res.set('X-Frame-Options', 'sameorigin');
next();
},
```
which can be used to restrict how the editor is iframed into other pages.
> Add httpAdminMiddleware to allow custom headers on admin routes

- packages/node_modules/@node-red/editor-client/src/js/ui/editor.js
The current dev version of the Node-RED flow editor doesn't show the description about a group on the info tab after users input the description. To show the description, they need to unselect the group and select it again.
Therefore, I added the code to reflect the description on the info tab immediately after inputting the text.
> Fix description of grouping nodes

- packages/node_modules/@node-red/editor-client/src/js/ui/tab-info-outliner.js
After creating subflow from `Subflows > Selections to Subflow` menu,  outliner leaves *empty* item in tree list as shown below: 
This PR tries to fixe this problem.
> Fix outliner display of newly created subflow

- packages/node_modules/@node-red/editor-client/src/js/ui/workspaces.js
Deleting tab (workspace) from following tab information edit panel causes 
`Uncaught TypeError: Cannot read property 'label' of undefined` error.
This seems to be caused by refreshing sidebar of deleted tab on closing panel.
> Fix error on deleting tab

- packages/node_modules/@node-red/nodes/core/common/21-debug.html
- packages/node_modules/@node-red/nodes/core/common/21-debug.js
- packages/node_modules/@node-red/nodes/locales/en-US/messages.json
The PR lets the Debug node set it's status (under the node) independent of the main side bar and console outputs. It can select a msg.property or use a JSONata expression
> Let debug node show status indpendent of main output

- packages/node_modules/@node-red/editor-client/src/js/ui/view-tools.js
Adds a pair of actions to toggle the node label visibility in the editor.
- `core:show-selected-node-labels`
- `core:hide-selected-node-labels`
Created live on twitch!
> Add action to toggle node label visiblity

- packages/node_modules/@node-red/editor-client/src/js/ui/view.js
When a group name contains line breaks (\n), the label and surrounding boxes of the group are node displayed correctly as follows:
This PR tries to fix this problem to make the group displayed as follows:
> fix line break of group label

- packages/node_modules/@node-red/nodes/locales/de/parsers/70-XML.html
- packages/node_modules/@node-red/nodes/locales/en-US/parsers/70-XML.html
- packages/node_modules/@node-red/nodes/locales/ja/parsers/70-XML.html
- packages/node_modules/@node-red/nodes/locales/ko/parsers/70-XML.html
- packages/node_modules/@node-red/nodes/locales/zh-CN/parsers/70-XML.html
- packages/node_modules/@node-red/nodes/locales/zh-TW/parsers/70-XML.html
The XML node help docs include the property `options` in the Outputs when it should be listed under Inputs. 
Old docs:
Fixed:
Also restored the property name (which was translated) in the German version.
> Moved options property from Outputs to Inputs section

- packages/node_modules/@node-red/editor-client/src/js/ui/editor.js
- packages/node_modules/@node-red/editor-client/src/js/ui/library.js
- packages/node_modules/@node-red/nodes/core/function/10-function.html
To reuse node description in function node via the library, I added the function which saves the node description with other metadata and JavaScript code in a function node.
> Saving node description property to the library

- packages/node_modules/@node-red/editor-client/src/sass/ace.scss
As reported on #2104, on some systems (mainly Linux), the underscore character is not visible in Node-RED editor without zooming in or out. The issue seems to be related to DejaVu Sans font rendering [as pointed out on the forum](https://discourse.nodered.org/t/cant-see-my-underline-char/26957/23?u=ristomatti) by @Steve-Mcl.
Change of `line-height` to '1' on ACE editor lines seems to fix the issue at least on my system (Linux Mint / latest Chrome) without actually affecting the actual height of the editor lines.
Before:
After:
> Fix editor underscore visibility on Linux systems

- packages/node_modules/@node-red/editor-client/src/js/polyfills.js
Node-RED editor fails to load on IE11.
This is because the code for IE11 fails to check that `Array.from` is defined in JSONata.
`Array.from` is no longer defined from JSONata 1.8.3, so this PR removes the check code.
> remove JSONata Array.from check for IE11

- packages/node_modules/@node-red/editor-client/src/js/ui/tab-info-outliner.js
- packages/node_modules/@node-red/editor-client/src/js/ui/view.js
A browser error occurs when deleting a group in the following steps (sample flow is included below).
1. select candidate group
2. press `DELETE` key
Then error occurs in a browser: `TypeError: Cannot read property 'remove' of undefined`
- Sample Flow
```
[{"id":"5bcefa6.e5ffb04","type":"tab","label":"Flow 1","disabled":false,"info":""},{"id":"d2cc1f36.9502d","type":"group","z":"5bcefa6.e5ffb04","style":{"stroke":"#999999","stroke-opacity":"1","fill":"none","fill-opacity":"1"},"nodes":["7c362d0f.e25f24"],"x":170,"y":95,"w":220,"h":130},{"id":"7c362d0f.e25f24","type":"group","z":"5bcefa6.e5ffb04","g":"d2cc1f36.9502d","style":{"stroke":"#999999","stroke-opacity":"1","fill":"none","fill-opacity":"1"},"nodes":["7ce34a04.2777cc"],"x":195,"y":120,"w":170,"h":80},{"id":"7ce34a04.2777cc","type":"co …
```
> fix deletion of group

- packages/node_modules/@node-red/editor-client/src/js/ui/common/typedInput.js
A small enhancement to the typedInput widget - permitting a node to set the tooltip of an option or checkbox item in the typed input.
Re: [Forum discussion](https://discourse.nodered.org/t/typedinput-option-tooltip/27607/2)
> Support setting title on typedInput option/ check

- packages/node_modules/@node-red/nodes/locales/ja/messages.json
- packages/node_modules/@node-red/runtime/locales/ja/runtime.json
I added Japanese transaltions for http-request node, change node and https refresh logic.
> Add Japanese transaltions for http-request node, change node and https refresh logic

- package.json
- packages/node_modules/node-red/package.json
- packages/node_modules/node-red/red.js
Adds `node-red-admin` as a dependency of the main node-red module.
Exposes it via the `admin` argument to the main `node-red` executable.
So to generate a password hash, users will be able to run:
```
node-red admin hash-pw
```
`admin` *must* be the first argument to the `node-red` command. If that is detected, all of the remaining arguments are passed to `node-red-admin` as-is. Any comments on the style or behaviour of the command should be directed at `node-red-admin`.
- `node-red -? admin` will give you help for `node-red`.
- `node-red admin -?` will give you help for `node-red-admin`.
> Add node-red admin support

- packages/node_modules/@node-red/editor-client/src/js/ui/view.js
An empty group with multi-line label moves upward when workspace is redrawn.
- Example flow:
```
[{"id":"e8f2e3bc.c68f8","type":"tab","label":"Flow 1","disabled":false,"info":""},{"id":"768e1e6b.b2306","type":"group","z":"e8f2e3bc.c68f8","name":"A\\nB","style":{"stroke":"#999999","fill":"none","label":true,"label-position":"nw","color":"#a4a4a4"},"nodes":[],"x":155,"y":148,"w":40,"h":56}]
```
> Fix group position of empty group with multi-line label

- packages/node_modules/@node-red/editor-client/src/js/ui/tab-info-outliner.js
If the last element is removed from a group, an empty placeholder for the group is not shown on outliner tree.
Following steps can reproduce this:
1. import the following flow
```
[{"id":"e14b8c7f.8eac5","type":"tab","label":"Flow 1","disabled":false,"info":""},{"id":"d49ec8fc.6158c8","type":"group","z":"e14b8c7f.8eac5","style":{"stroke":"#999999","stroke-opacity":"1","fill":"none","fill-opacity":"1"},"nodes":["6b15a0dc.9f785"],"x":175,"y":80,"w":80,"h":80},{"id":"6b15a0dc.9f785","type":"comment","z":"e14b8c7f.8eac5","g":"d49ec8fc.6158c8","name":"","info":"","x":215,"y":120,"wires":[],"l":false}]
```
2. select comment node
3. Select menu item: Groups > Remove from group
4. *empty* placeholder for the outer group is not shown on outliner as follows:
> fix empty placeholder not shown on remove from group

- packages/node_modules/@node-red/nodes/core/network/22-websocket.html
Opening `websocket-listner` settings panel causes following editor error:
```
Definition error: websocket-listener.label TypeError: Cannot read property 'charAt' of undefined
at Object.label (<anonymous>:113:27)
at Object.getNodeLabel (red.min.js:16)
at Object.p [as refresh] (red.min.js:16)
at Object.show (red.min.js:16)
at red.min.js:16
```
> Fix char at error on undefined when opening websocket-listner

- packages/node_modules/@node-red/editor-client/src/js/ui/group.js
`Groups > Merge selection` menu do not merge group for single element or non-group items.  
The operation for these items is the same as for `Groups > Group selection`. 
Therefore, This PR try to disable the `Group selection` menu for these cases.
> Disable group merge for single item or non-group items

- packages/node_modules/@node-red/editor-client/src/js/ui/view.js
As reported by https://github.com/node-red/node-red/issues/2614, the Node-RED editor causes the following error if a multi-line node label is used for a node with multiple ports.
```
red.min.js:16 Uncaught TypeError: Cannot set property 'textContent' of null
at SVGGElement.<anonymous> (red.min.js:16)
at vendor.js:37
at Tn (vendor.js:35)
at Array.Ma.each (vendor.js:37)
at Rt (red.min.js:16)
```
This is due to an error in the calculation of the number of rows before the node change.
This PR try to fix this problem.
Also contains a commit to fix indentation of `view.js`.
> Fix multi-line node label handling

- packages/node_modules/@node-red/editor-client/locales/ja/editor.json
- packages/node_modules/@node-red/editor-client/locales/ja/jsonata.json
- packages/node_modules/@node-red/editor-client/src/js/ui/tab-info-outliner.js
- packages/node_modules/@node-red/runtime/locales/ja/runtime.json
I found that the enable/disable button in the outliner is always "enable". I fixed the i18n problem in this commit. And I added Japanese translations for outliner, jsonata, and runtime.
> Fix i18n bug in outliner

- packages/node_modules/@node-red/nodes/core/function/90-exec.js
This relates to:
https://github.com/node-red/node-red/issues/2604
and
https://discourse.nodered.org/t/exec-node-timeout-not-working-in-exec-mode/28040
and is a possible workaround for most issues related to kill described there.
This has only been tested on linux where this change applies so it would most definitely need more testing on windows/mac and maybe linux distributions where there is no bash(?).
> use bash as shell for exec command if on linux

- packages/node_modules/@node-red/editor-client/src/js/ui/subflow.js
Editor causes following error if no selection on subflow input types is made.
```
Uncaught TypeError: Cannot read property 'value' of undefined
at red.min.js:16
at Array.map (<anonymous>)
at t.<computed>.<computed>.types (red.min.js:16)
at t.<computed>.<computed>.types (vendor.js:10)
at HTMLInputElement.<anonymous> (vendor.js:10)
at Function.each (vendor.js:2)
at s.fn.init.each (vendor.js:2)
at s.fn.init.t.fn.<computed> [as typedInput] (vendor.js:10)
at HTMLInputElement.<anonymous> (red.min.js:16)
at HTMLInputElement.dispatch (vendor.js:2)
```
This may be due to specifying an empty string as input type. 
In the proposed fix, use `str` type in such cases.
> Fix error on empty subflow input types

- Gruntfile.js
- package.json
Add developer options
* permits npm run build-dev.  skips minification & doesnt launch nodemon
* permits npm run dev for those without grunt installed globally
In summary...
* Adds `"build-dev": "grunt build-dev"` to `package.json` scripts
* this permits `npm run build-dev`
* skips minification & doesnt launch dev server - ideal for VSCode / Atom F5 step debugging in IDE
* Adds `"dev": "grunt dev"` to `package.json` scripts
* this permits `npm run dev` for those without grunt installed globally
REF: https://discourse.nodered.org/t/live-streaming-some-node-red-development-work/26856/10
<br>
Additional info (for adding to [developer docs](https://nodered.org/docs/developing/)?)
```
{
"version": "0.2.0",
"configurations": [
{
"type": "node",
"request": "launch",
"name": "Debug node-red", …
```
> Add developer options

- packages/node_modules/@node-red/nodes/core/common/21-debug.html
- packages/node_modules/@node-red/nodes/core/common/21-debug.js
- packages/node_modules/@node-red/nodes/locales/en-US/messages.json
This is a fix/update/improvement to #2564
Removes the extra status label that confused some users. 
Renamed "auto" mode to "show Output" to reflect that is just trying to show the default output as before. 
Tidied up loop detection logic so if a status node was set to pick up the status from all nodes (the default) - then fed into a debug set to show status - the debug would recognise the message had come from itself and not update (so breaking a spin loop).
Also only send status if it had actually changed from last status set ( also helps to break loops )
It also now checks the property it is set to and if that is an object containing a shape, fill and text then it uses those as if it were a real status message (rather than just printing the object.)
Finally - it improves the migration …
> fix debug status to not loop, make migration more seamless, detect status type objects

- packages/node_modules/@node-red/nodes/locales/en-US/function/10-switch.html
Clarify switch help regarding booleans for the is empty / is not empty rules.
> Clarify empty rules in switch node documentation

- packages/node_modules/@node-red/nodes/locales/ja/function/10-switch.html
Because documentation about empty rules in the switch node is updated in #2649, I also updated the Japanese translation for it.
> Update Japanese translation for switch node

- packages/node_modules/@node-red/runtime/lib/nodes/Node.js
To enable precise tracing of each message, we propose to make the runtime emit log message whenever the message processing is finished. 
By this PR, nodes which use Messaging API (i.e., call done() at end of message processing) emit "done" event on metric log.
Example log output:
```
18 Aug 09:11:09 - [metric] {"level":99,"nodeid":"f748808a.a2b39","event":"node.http response.done","msgid":"59bf7151.69477","timestamp":1597709469150}
```
Further details are on the design note of [Message Tracing by metric log](https://github.com/node-red/designs/pull/34).
> Add 'done' metric log for message tracing

- packages/node_modules/@node-red/editor-client/src/js/ui/common/tabs.js
- packages/node_modules/@node-red/editor-client/src/js/ui/sidebar.js
This allows the sidebar tabs to be reordered by dragging their buttons around.
The order of the buttons is stored in user settings, so it can be persisted across reloads of the editor. Regardless of order, the Info tab is still displayed by default. There's a separate possible change to make to remember the last tab a user was on - but the async nature of loading sidebar tabs makes that a bit trickier to handle.
The existing 'pinned' tab behaviour has been changed - it will only influence the order of the tabs if the user has not set a preferred order. So a user with Dashboard installed will still see it as the 5th tab (4th if they don't have projects enabled). However if a user reorders their tabs, then installs Dashboard, it will end up at the end of the list - but at least they can …
> Reorderable sidebar tabs

- Gruntfile.js
- packages/node_modules/@node-red/registry/lib/loader.js
- test/unit/@node-red/registry/lib/loader_spec.js
This change modifies how nodes are loaded so that if `disableEditor` is set, we now skip loading the node html into memory.
This shaves a small amount off the startup time - not as much as I'd hoped. But it will save a bit of memory usage.
It still loads the locales files as a node may have runtime messages in its catalog.
> Avoid loading node html if disableEditor set

- packages/node_modules/@node-red/runtime/lib/nodes/Node.js
- test/unit/@node-red/runtime/lib/nodes/Node_spec.js
> Fix `this` context when calling multiple event listeners (fixes #2692).

- packages/node_modules/@node-red/editor-client/locales/en-US/editor.json
- packages/node_modules/@node-red/editor-client/src/js/nodes.js
- packages/node_modules/@node-red/editor-client/src/js/ui/clipboard.js
- packages/node_modules/@node-red/editor-client/src/js/ui/view.js
Closes #2170
We have seen rare occasions where a node ends up with its `z` property set to `0`. This is invalid and should not be possible - yet it does happen.
This PR adds the code to detect when we import such nodes, and creates a new workspace to put them on. The user is notified with the following message:
> Recover nodes with invalid z property

- packages/node_modules/@node-red/editor-client/locales/en-US/editor.json
- packages/node_modules/@node-red/editor-client/src/js/history.js
- packages/node_modules/@node-red/editor-client/src/js/nodes.js
- packages/node_modules/@node-red/editor-client/src/js/ui/clipboard.js
- packages/node_modules/@node-red/editor-client/src/js/ui/common/checkboxSet.js
- packages/node_modules/@node-red/editor-client/src/js/ui/common/editableList.js
- packages/node_modules/@node-red/editor-client/src/js/ui/common/toggleButton.js
- packages/node_modules/@node-red/editor-client/src/js/ui/common/treeList.js
- packages/node_modules/@node-red/editor-client/src/js/ui/subflow.js
- packages/node_modules/@node-red/editor-client/src/js/ui/tab-info-outliner.js
- packages/node_modules/@node-red/editor-client/src/js/ui/view.js
- packages/node_modules/@node-red/editor-client/src/sass/library.scss
- packages/node_modules/@node-red/editor-client/src/sass/tab-info.scss
- packages/node_modules/@node-red/editor-client/src/sass/ui/common/checkboxSet.scss
This PR changes how the editor imports flows.
In the existing code, when importing a flow (`Ctrl-I` dialog) the editor would:
- assign new ids to all nodes
- identify subflow definitions that already exist and not import a duplicate
- identify config nodes that already exist and not import a duplicate
This is the right thing to do for 90% of cases. However there is a scenario it doesn't handle: where I want to import an update to an existing subflow I already have.
This PR changes the workflow to support this use case. When importing it now does:
- it does *not* assign new ids to all nodes at first
- it then identifies if any of those ids clash with nodes/subflows/tabs/etc that already exist
- it prompts the user that there are conflicts:
- If the user clicks "Import copy" it does the …
> Improved handling of importing duplicate subflow/config nodes

- packages/node_modules/@node-red/registry/lib/localfilesystem.js
1. Prepare a new Node-RED environment.
2. Install two nodes.
- node-red-dashboard
- node-red-contrib-ui-led
3. Insert "led" node to Flow, then group and tab setup, and deploy.
The following message is displayed on the terminal.
And the node in error doesn't work.
```
While constructing LEDNode widget: Error: Cannot find module 'node-red-dashboard'
at Object.requireModule [as require] (D:\heroku\node-red-sample\local_packages\@node-red\registry\lib\util.js:48:19)
at new LEDNode (D:\heroku\node-red-sample\data\node_modules\node-red-contrib-ui-led\led.js:13:26)
at Object.createNode (D:\heroku\node-red-sample\local_packages\@node-red\runtime\lib\nodes\flows\util.js:493:31)
at Flow.start (D:\heroku\node-red-sample\local_packages\@node-red\runtime\lib\nodes\flows\Flow.js:193:48)
at start …
```
> fix getModuleFiles function

- packages/node_modules/@node-red/runtime/lib/storage/localfilesystem/index.js
- packages/node_modules/@node-red/runtime/lib/storage/localfilesystem/settings.js
- packages/node_modules/@node-red/runtime/lib/storage/localfilesystem/util.js
- test/unit/@node-red/runtime/lib/storage/localfilesystem/settings_spec.js
The runtime settings are currently stored in `~/.node-red/.config.json`. This contains:
- the list of nodes discovered by the runtime
- user settings (eg editor settings such as 'show grid' etc)
- project settings (active project, list of available projects etc)
- other things - notable `_credentialSecret`.
Putting all of these things in one place is not ideal - a consequence of the Storage API only having a simple read/write API for the whole settings object.
This PR changes the default LocalFileSystem storage plugin to split the settings into 4 files:
- `.config.nodes.json` - the node registry
- `.config.users.json` - user specific settings (eg editor settings)
- `.config.projects.json` - project settings, including the active project
- `.config.runtime.json` - everything else - most …
> Split .config.json into separate files

- packages/node_modules/@node-red/nodes/core/function/10-function.js
Starting with v1.1 the function node has a setup and close handler.
However, compared to the main function body that is executed each time a message arrives, the setup handler (and the close handler) does only expose a subset of the functionality of the main function body.
This PR exposes `send, status, log, warn, error, debug, trace, name, id` in the setup handler.
See also https://discourse.nodered.org/t/setup-and-close-of-new-function-node-discussion-about-use-cases-extensions/29570
> expose send, status, log, warn, error, debug, trace, name, id in setup code of function node

- packages/node_modules/@node-red/nodes/core/function/89-trigger.html
- packages/node_modules/@node-red/nodes/core/function/89-trigger.js
- packages/node_modules/@node-red/nodes/locales/en-US/function/89-trigger.html
- packages/node_modules/@node-red/nodes/locales/en-US/messages.json
- test/nodes/core/function/89-trigger_spec.js
Allow the delay between first and second messages sent by Trigger node to be set per-message using `msg.delay`.
This does not apply to the looping mode.
> Allow trigger node delay to be overridden with msg.delay

- packages/node_modules/@node-red/editor-client/locales/en-US/editor.json
- packages/node_modules/@node-red/editor-client/locales/ja/editor.json
- packages/node_modules/@node-red/editor-client/src/js/ui/palette-editor.js
Tooltip for module list refresh is not i18n-ed.
This PR makes it i18n-ed and adds Japanese translation.
> i18n module refresh tooltip

- packages/node_modules/@node-red/editor-client/src/js/ui/common/popover.js
In some cases, popover of sidebar tab is displayed in two line as follows.
> Fix unexpected line break of sidebar tab name popover

- packages/node_modules/@node-red/editor-client/src/js/ui/palette-editor.js
- packages/node_modules/@node-red/editor-client/src/sass/palette-editor.scss
NPM moduloe upload button is shown widely on Safari as follows.
This PR try to fix this problem.
> Fix upload button width on Safari

- packages/node_modules/@node-red/runtime/lib/storage/index.js
Fixes #2736
When disabling (or enabling) a module that contains lots of individual node sets (ie .js files), the code disables each one in turn - but without any locking to ensure one is done before the next is disabled. Each call to disable causes the settings file to be updated to record the set as being disabled.
This would cause multiple calls to `saveSettings` that overlap, leading to the error reported in #2736 
This fix is to add a mutex lock on `saveSettings` to ensure it can only have one active call at a time. Applying the fix here will ensure the same symptom can't crop up through other parts of the API that drive rapid changes to the settings file.
There is a separate item to consider - that disabling a whole module causes so many calls to update settings. It would be nice if …
> Add mutex lock to saveSettings storage call

- packages/node_modules/node-red/settings.js
This PR modifies the comment at the start of the default settings file.
- Removes the Apache2 License. This file is intended to be owned by the end user. They are free to use it however they want
- Adds comments about the format of the file and where to find more information about it
> Modify default settings comment

- packages/node_modules/@node-red/nodes/locales/ja/messages.json
I translated "Docs" button in the http-in node to be the same as documentation of the node-red-node-swagger node.
https://github.com/node-red/node-red-node-swagger/pull/76
> Add Japanese translation for http-in node

- packages/node_modules/@node-red/runtime/lib/storage/localfilesystem/library.js
This small fix allows the library to scan symbolic links inside lib/flows and lib/function folders.
> Library: properly handle symlinked folders

- packages/node_modules/@node-red/editor-client/src/js/ui/common/typedInput.js
- packages/node_modules/@node-red/editor-client/src/sass/ui/common/typedInput.scss
As discussed on [Discourse](https://discourse.nodered.org/t/readonly-typedinput/35358/4?u=bartbutenaers), it would be nice if a TypedInput could be disabled.
Via this PR a TypedInput can easily be disabled like this:
```
$("#my_typedinput_id").typedInput("disable", true);
```
To get this result:
This allows values to be displayed, without allowing the user to change those values ...
All credits for this solution go to @Steve-Mcl!
> Allow TypedInput to be disabled

- packages/node_modules/@node-red/nodes/core/sequence/17-split.js
- test/nodes/core/sequence/17-split_spec.js
Update Split/Join nodes so that you can capture completion event of the node.
- `done()` for receiving message is deferred until the message is joined and sent to next node.
-  if buffer overflow is occurred while message is accumulating, `done(error)` is called only for last message, and `done()` is called for other messages in buffer to prevent flood of error messages.
> Messaging API support in Split/Join nodes

- packages/node_modules/@node-red/runtime/lib/flows/Flow.js
Fix bug: Crash & quit while handling exception with undefine msg.error. i.e. flow with 3 nodes, http-in, delay 5-10s, http-out; client with 3s timeout request the flow; TypeError: Cannot read property 'hasOwnProperty' of undefined\r at Flow.handleError (/usr/src/node-red/node_modules/@node-red/runtime/lib/flows/Flow.js:474:27)
> Fix bug: Crash & quit while handling exception with undefine msg.error

- packages/node_modules/@node-red/editor-client/src/js/user.js
- test/unit/@node-red/editor-api/lib/editor/theme_spec.js
Allow using `userMenu` explicitly in the theme configuration by enabling to set to true or false and have the expected behavior of show and hide the user menu.
> Allow to explicit use userMenu in the theme configuration

- packages/node_modules/@node-red/editor-api/lib/admin/index.js
- packages/node_modules/@node-red/editor-client/src/js/red.js
- packages/node_modules/@node-red/editor-client/src/js/settings.js
- packages/node_modules/@node-red/editor-client/src/js/ui/palette-editor.js
- packages/node_modules/@node-red/editor-client/src/js/ui/projects/projectSettings.js
- packages/node_modules/@node-red/registry/lib/index.js
- packages/node_modules/@node-red/registry/lib/installer.js
- packages/node_modules/@node-red/registry/lib/localfilesystem.js
- packages/node_modules/@node-red/registry/lib/util.js
- packages/node_modules/@node-red/runtime/lib/api/nodes.js
- packages/node_modules/@node-red/runtime/lib/api/settings.js
- packages/node_modules/@node-red/runtime/lib/index.js
- packages/node_modules/@node-red/runtime/locales/en-US/runtime.json
- test/unit/@node-red/registry/lib/util_spec.js
- test/unit/@node-red/runtime/lib/api/settings_spec.js
This PR adds support for the `externalModules` setting that can be used to provide a allow/deny list of modules to control what a user is allowed to install.
The full discussion around the design of the setting is here: https://github.com/node-red/designs/discussions/40
In summary, it adds the setting:
```
externalModules: {
autoInstall: true/false,
autoInstallRetry: 30,
palette: {
allowInstall: true/false,
allowUpload: true/false,
allowList: [],
denyList: []
}
}
```
This deprecates some existing settings:
- `editorTheme.palette.editable` for `externalModules.palette.allowInstall`
- `autoInstallModules` for `externalModules.palette.allowInstall = true` and `externalModules.autoInstall = true`
- `autoInstallModulesRetry` for `externalModules.autoInstallRetry`
- `editorTheme.palette.upload` …
> Add support for settings.externalModules

- packages/node_modules/@node-red/util/index.js
- packages/node_modules/@node-red/util/lib/i18n.js
- packages/node_modules/node-red/settings.js
Adds an option to change the language regardless of the operating systems language. 
This is a suggestion, briefly discussed with @dceejay. Sometimes administrators want to run an English server but might want to provide node-red (and the dashboard) in another language.
> add optional lang select

- packages/node_modules/@node-red/editor-client/src/js/ui/projects/projectUserSettings.js
- packages/node_modules/@node-red/editor-client/src/js/ui/projects/tab-versionControl.js
- packages/node_modules/@node-red/runtime/lib/storage/localfilesystem/projects/Project.js
- packages/node_modules/@node-red/runtime/lib/storage/localfilesystem/projects/index.js
- packages/node_modules/node-red/settings.js
We introduced the option of an automatic git workflow in the 1.2 release. This auto-commits changes whenever they are made from the editor.
This PR allows the choice of workflow to be made via the settings file. This acts as the default choice until the user goes into the User Settings dialog and changes it.
The default settings file has been updated to include the default `manual` setting:
```
editorTheme: {
projects: {
// To enable the Projects feature, set this value to true
enabled: false,
workflow: {
// Set the default projects workflow mode.
//  - manual - you must manually commit changes
//  - auto - changes are automatically committed
// This can be overridden per-user from the 'Git config'
// section of 'User Settings' within the editor
mode: "manual"
}
}
}
```
> Allow project workflow to be configured via settings file

- packages/node_modules/@node-red/editor-client/src/js/history.js
- packages/node_modules/@node-red/editor-client/src/js/nodes.js
- packages/node_modules/@node-red/editor-client/src/js/red.js
- packages/node_modules/@node-red/editor-client/src/js/ui/editor.js
- packages/node_modules/@node-red/editor-client/src/js/ui/tab-info.js
- packages/node_modules/@node-red/editor-client/src/sass/palette.scss
- packages/node_modules/@node-red/nodes/core/common/24-complete.html
- packages/node_modules/@node-red/nodes/core/common/25-catch.html
- packages/node_modules/@node-red/nodes/core/common/25-status.html
- packages/node_modules/@node-red/nodes/core/common/60-link.html
This implements initial support for node property typing as described in the design note: https://github.com/node-red/designs/pull/37
From the design note:
> A node's `defaults` object in its HTML definition provides a list of its properties
with some metadata associated with them.
> If a property is intended to be a reference to a configuration node, its entry
in the defaults object will include the `type` property that identifies the type
of config node it should point to.
> This allows the editor to automatically generate the Config Node select box UI
and manage the relationship between the nodes.
This PR implements support for nodes to declare properties that hold references to other nodes that may or may not be configuration nodes. The editor is then able to ensure those properties …
> Support node property typing

- packages/node_modules/@node-red/nodes/core/function/90-exec.html
- packages/node_modules/@node-red/nodes/core/function/90-exec.js
This PR does ~~two~~one things... 
- 1) It changes the default from "append msg.payload" - to be not appended. - Quite often we get users saying a simple command like `ls` doesn't work - which is because the default is to append a payload which again by default is often the timestamp from an inject node - so the command fails. Making the default to not be appended should fix this - and indeed it should be more obvious that if you want to append the payload you need to tick it...
- ~~2)~~ It adds `msg.complete = true` to the 3rd output of the node when in spawn mode. This is the output that returns the return code - but by adding msg.complete = true it can also be used to feed a join node to rejoin all the output from the spawned command. (However it still needs a change node to delete the …
> Exec node - don't append msg.payload to command by default

- packages/node_modules/@node-red/nodes/core/function/90-exec.js
- packages/node_modules/node-red/settings.js
This adds a execMaxBufferSize settings to allow  the user to customize the maximum buffer size for the output of the exec node.
> Add settings.execMaxBufferSize to control buffer size of exec node

- packages/node_modules/@node-red/nodes/core/network/31-tcpin.html
`splitc` input field of **tcp request** node has no meaning for `sit` and `immed` output option.
This PR hides the field for these options.
> Hide unused input field of tcp request node

- packages/node_modules/@node-red/editor-client/src/js/ui/clipboard.js
- packages/node_modules/@node-red/editor-client/src/sass/library.scss
- packages/node_modules/@node-red/editor-client/src/sass/tab-info.scss
Adds a preview list of the nodes/flows/subflows that will be exported to the Export Dialog.
The new tabbed view has the preview as the default view, but the underlying JSON can be viewed by clicking the JSON tab.
The rationale for not showing the JSON by default is that the preview list will give the user confidence over what they are about to export - there is no particular need to see the JSON.
> Add preview to Export Dialog

- packages/node_modules/@node-red/nodes/core/network/21-httprequest.js
- packages/node_modules/@node-red/registry/lib/library.js
This checks if the coreNodesDir is empty before trying to iterate over the files in that directory.
> Prevent crash when coreNodesDir is empty

- packages/node_modules/@node-red/editor-client/src/js/ui/palette.js
- packages/node_modules/@node-red/editor-client/src/js/ui/view.js
If the label of a SUBFLOW contains a line break (`\n `), the label may be displayed outside of the SUBFLOW as shown below. 
This PR attempts to fix this.
> Fix line break of subflow label on palette

- packages/node_modules/@node-red/editor-client/src/js/ui/utils.js
- packages/node_modules/@node-red/nodes/core/function/15-change.js
- packages/node_modules/@node-red/util/lib/util.js
- test/nodes/core/function/10-switch_spec.js
- test/nodes/core/function/15-change_spec.js
- test/unit/@node-red/util/lib/util_spec.js
See https://github.com/node-red/designs/discussions/43
This adds support for nesting `msg.` property references in a `msg`, `flow` and `global` expression.
For example, `msg.payload[msg.topic]` or `flow.rooms[msg.topic]`.
The Change and Switch nodes have been updated to make use of this.
Any node that uses `RED.util.getMessageProperty(...)` to resolve `msg` expressions will gain this ability without any changes.
Similarly, any node that uses `RED.util.evaluateNodeProperty(...)` to resolve `flow` and `global` expressions will also benefit.
> Allow nested msg properties in msg/flow/global expressions

- packages/node_modules/@node-red/editor-api/lib/admin/plugins.js
- packages/node_modules/@node-red/editor-api/lib/editor/index.js
- packages/node_modules/@node-red/editor-api/lib/editor/theme.js
- packages/node_modules/@node-red/editor-api/lib/editor/ui.js
- packages/node_modules/@node-red/editor-client/src/js/red.js
- packages/node_modules/@node-red/editor-client/src/js/ui/userSettings.js
- packages/node_modules/@node-red/registry/lib/plugins.js
- packages/node_modules/@node-red/runtime/lib/api/plugins.js
- test/unit/@node-red/editor-api/lib/editor/theme_spec.js
This PR builds on top of the Plugins PR (#2779) to define a new type of plugin that provide custom editor themes.
This allows a theme to be published to npm and allows an end-user to install the module and activate it by setting `editorTheme.theme` to the name of the theme.
To create a theme plugin, its package.json must have a `node-red` section that lists the plugins in the package:
```
"node-red": {
"plugins": {
"my-theme": "my-theme.js"
}
}
```
`my-theme.js` will then look like this:
```
module.exports = function(RED) {
RED.plugins.registerPlugin("my-theme", {
type: "node-red-theme",
css: "theme.css"
})
}
```
Key points:
- this will register a plugin called `my-theme`
- it has a type of `node-red-theme` - this is used to identify this plugin as containing a theme
- the `css` property …
> Add support for Theme Plugins

- packages/node_modules/@node-red/editor-client/src/js/nodes.js
Normally, the Config node is referenced by the node.
Since createExportableNodeSet() targets the nodes that belong to the subflow, the Config node that has the reference is also exported.
However, the Config nodes of ui_subgroup_t and ui_subgroup_i defined in the currently proposed UI Module do not have references from the nodes.
Only the "z" property*1 of the subflow is designed to be the key for node reference.
Therefore, by adding the Config node that belongs to the subflow to the export target, the ui_subgroup_t and ui_subgroup_i Config nodes are targeted.
*1 In the latest version of Node-RED, the "z" property of the Config node is now preserved when importing a flow.
For this reason, the "subgroup" key of ui_subgroup_t, which had the same meaning, has been abolished and "z" has been …
> Add config node to refer to when exporting subflow

- packages/node_modules/@node-red/editor-client/src/js/ui/palette.js
- packages/node_modules/@node-red/editor-client/src/js/ui/tab-info-outliner.js
Feedback from the forum highlighted the fact it is quite hard to find all instances of a given subflow. To do that with the search today, you need to know the subflow's id - which is non-trivial to discover as we hide it quite well.
This PR adds two new mechanisms for finding instances of subflows.
1. The palette tooltip now has a button that sets the info sidebar search to reveal all nodes of the given type. This button is on all node tooltips, not just subflows.
2. The outline view now has an instance count next to each subflow - in the same way we already do for configuration nodes. Clicking on the number opens the search dialog to list the instances.
> Add easier ways to find subflow instances

- packages/node_modules/@node-red/editor-client/locales/en-US/editor.json
- packages/node_modules/@node-red/editor-client/src/js/ui/editor.js
Fixes #2840
When opening an node/subflow editor dialog that includes credentials, the editor makes a call back to the runtime to get the credential information. If that call takes a long time for some reason, the edit dialog doesn't appear and there is no feedback to the user. The user may get bored and double-click on the node again - kicking off another request to load the credentials.
When the request(s) finally timeout or complete, you then get multiple edit dialogs open.
This PR fixes two aspects of this:
1. If a node edit dialog is still being built, a second dbl click on a node is ignored. This stops you from getting multiple dialogs open for the same node.
2. There is now timeout handling for loading credentials.
For the timeout handling, there are two stages to this.
1. If the …
> Handle timeouts when trying to load node credentials in editor

- packages/node_modules/@node-red/editor-client/src/js/ui/tab-info-outliner.js
The Info outliner provides a button to toggle the enabled/disabled state of nodes and flows. This PR adds the button to Group nodes as well - although the behaviour is slightly different.
When you disable a Flow, the nodes within it are not individually disabled, but are implicitly disabled.
A Group doesn't have the same concept of being disabled - and this PR doesn't change that fact. The button this PR adds will toggle the enable/disable state of all nodes within the group. More specifically, it swaps the state of the *first* node in the group, and ensures all of the others match. This means if you have a group with a mixture of states, they will all get aligned to the same state.
This also fixes the Undo history handling of the existing button.
> Add enable/disable toggle button for groups in info-outliner

- packages/node_modules/@node-red/editor-client/locales/en-US/editor.json
- packages/node_modules/@node-red/editor-client/src/js/ui/subflow.js
Based on feedback from the forum, this PR adds a confirmation dialog if the user clicks the 'delete subflow' button when there are instances of the subflow within the flows.
> Add confirm dialog when deleting subflow with instances in use

- packages/node_modules/@node-red/editor-client/src/js/polyfills.js
- packages/node_modules/@node-red/editor-client/src/js/ui/clipboard.js
As described in this [issue](https://github.com/node-red/node-red/issues/2755), exporting flow do not work on IE11.
This is caused by use of data uri scheme for downloading.
This PR try to fix this problem by adding polyfill for supporting this feature.
> add IE11 polyfill to support URI download scheme

- packages/node_modules/@node-red/editor-client/locales/en-US/editor.json
- packages/node_modules/@node-red/editor-client/locales/ja/editor.json
- packages/node_modules/@node-red/editor-client/src/js/ui/subflow.js
- packages/node_modules/@node-red/runtime/locales/ja/runtime.json
I added Japanese translations for Node-RED v1.3.0. Because my acquaintance kindly pointed out the mistranslations of the configuration node, I also changed them to the correct translations.
> Add Japanese translations for Node-RED v1.3.0

- packages/node_modules/@node-red/runtime/lib/flows/index.js
- packages/node_modules/@node-red/runtime/lib/flows/util.js
As described in this [issue](https://github.com/node-red/node-red/issues/2835), changing node's group make the node restarted on deploy regardless of node deployment mode.  
This PR tries to prevent nodes that only change groups from restarting.
> Fix deploy of node in group

- packages/node_modules/@node-red/runtime/lib/flows/Flow.js
ensures text status is actually a string so that it will be displayed.
> fix numeric status not displaying by ensuring it's a string

- packages/node_modules/@node-red/editor-client/src/js/ui/clipboard.js
With current dev branch, exporting nodes to clipboard causes line breaks lost when pasting it.
> fix line break of exporting nodes to clipboard

- packages/node_modules/@node-red/nodes/core/common/lib/debug/debug-utils.js
As described in this [issue](https://github.com/node-red/node-red/issues/2745), filtering of debug node output do not work debug nodes contained within subflow.
This PR try to fix this problem.
> Allow filtering of debug node output within subflow

- packages/node_modules/@node-red/editor-client/src/js/ui/palette-editor.js
PR #2821 could not be completed due to different email addresses used for it's commits.
This new branch is meant to be used as a new PR to replace the failed one
The palette editor only checks the first three numbers of a module version. When using pre-release additions, the editor does not correctly shows updated modules.
> New attempt for PR #2821

- packages/node_modules/@node-red/editor-client/locales/en-US/editor.json
- packages/node_modules/@node-red/editor-client/src/js/ui/common/editableList.js
- [ X ] New feature (non-breaking change which adds functionality)
See [discussion](https://discourse.nodered.org/t/custom-button-for-editablelist/41342) on Discourse.
This PR allows developers to show custom buttons at the bottom of an EditableList, next to the "Add" button, by filling the `buttons` property of the options.  For example:
```
$("ol.list").editableList({
addItem: function(container, i, clickableShape) {
//...
},
removable: true,
sortable: true,
buttons: [{
label: "with icon",
icon: "fa fa-star",
title: "my custom button",
click: function(evt) { 
alert("button clicked");
}
}]
});
```
- [ X ] I have read the [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md)
- [ X ] For non-bugfix PRs, I have discussed this change on the forum/slack …
> EditableList custom buttons

- packages/node_modules/@node-red/runtime/lib/flows/Flow.js
- packages/node_modules/@node-red/runtime/lib/flows/index.js
- test/unit/@node-red/runtime/lib/flows/Flow_spec.js
Fixes #2876
When Node-RED starts up flows we make sure to start config nodes before flow nodes as that is typically the right thing to do - flow nodes want their config nodes to already be available.
However we weren't doing anything special when it comes to stopping the flows.
This PR changes how we stop flows. It does two things:
1. it stops the `global` flow *last* - where previously it would be stopped first. This means any global config nodes are stopped *after* any flows are stopped
2. within a flow, it stops all flow nodes before config nodes
A very important point - this just changes the order the calls to stop are made. It doesn't do anything to wait until the flow nodes have stopped before stopping config nodes. 
If nodes need to do anything with the config nodes as part of the …
> Stop config nodes after flow nodes

- packages/node_modules/@node-red/editor-client/src/js/keymap.json
- packages/node_modules/@node-red/editor-client/src/js/nodes.js
- packages/node_modules/@node-red/editor-client/src/js/ui/view-tools.js
- packages/node_modules/@node-red/editor-client/src/js/ui/view.js
This adds three new actions to the editor (along with default key bindings)
- `core:select-connected-nodes` - `alt-s c` - selects all nodes connected to the current selected node(s).
- `core:select-upstream-nodes` - `alt-s u` - selects all nodes reachable from the input of any currently selected node
- `core:select-downstream-nodes` `alt-s d` - selects all nodes reachable from the outputs of any currently selected node
The `select-connected-nodes` action is equivalent to the shift-click behaviour we've long had.
The up/down stream actions are useful where you want to add an extra node into the middle of an existing flow and need to move everything on one side to make room.
There is a suggestion (not yet implemented) that we could adapted the shift-click behaviour so that depending where …
> Add new select-* actions to editor

- packages/node_modules/@node-red/nodes/core/sequence/17-split.js
- test/nodes/core/sequence/17-split_spec.js
this PR allows joining incoming messages into an array 
a) in manual mode if msg.parts is there then the index is now honoured - so if two array parts arrive with same index the later will replace the former - and not increase the number of parts arrived - ie you need a complete set on indices in order to complete the array.
b) in auto mode - if you send a msg.reset -  but without any msg.parts set - it will now reset all inflight messages rather than complaining about missing parts.
to close #2866
> Fix join node array index and reset

- packages/node_modules/@node-red/nodes/core/parsers/70-CSV.js
- test/nodes/core/parsers/70-CSV_spec.js
and add tests
to close #2853
This fix ensures the template is reset once complete (either an array or msg with .parts or a single message) - such that a subsequent msg with msg.columns defined will then use that new definition.
> fix csv node template reset when array complete

- packages/node_modules/@node-red/editor-api/lib/editor/index.js
- packages/node_modules/@node-red/editor-api/lib/editor/library.js
- packages/node_modules/@node-red/editor-client/src/js/ui/clipboard.js
- packages/node_modules/@node-red/editor-client/src/js/ui/library.js
- packages/node_modules/@node-red/editor-client/src/sass/library.scss
- packages/node_modules/@node-red/editor-client/src/sass/projects.scss
- packages/node_modules/@node-red/registry/lib/index.js
- packages/node_modules/@node-red/registry/lib/plugins.js
- packages/node_modules/@node-red/runtime/lib/api/library.js
- packages/node_modules/@node-red/runtime/lib/api/settings.js
- packages/node_modules/@node-red/runtime/lib/index.js
- packages/node_modules/@node-red/runtime/lib/library/examples.js
- packages/node_modules/@node-red/runtime/lib/library/index.js
- packages/node_modules/@node-red/runtime/lib/library/local.js
- packages/node_modules/@node-red/runtime/lib/plugins.js
- packages/node_modules/@node-red/runtime/locales/en-US/runtime.json
- test/resources/plugin/test-plugin/library-filestore.html
- test/resources/plugin/test-plugin/library-filestore.js
- test/resources/plugin/test-plugin/locales/en-US/library-filestore.json
- test/resources/plugin/test-plugin/package.json
- test/unit/@node-red/runtime/lib/api/settings_spec.js
- test/unit/@node-red/runtime/lib/library/index_spec.js
This is an initial implementation of Library source plugins as outlined in the design note: https://github.com/node-red/designs/pull/41
This PR is against the `plugins` branch (see #2779).
It adds support for custom library plugins that add new sources to the import/export library dialog in the editor.
This PR includes a stubbed out library plugin (although the fine details of the API is still evolving). See the design note linked above for more details.
This is a draft PR as there is a lot more work to be done. I'm working on this in parallel to the plugins PR as it helps to have a real use case for plugins as it helps flush out requirements for the base functionality.
> Library plugins

- packages/node_modules/@node-red/editor-api/lib/editor/theme.js
- packages/node_modules/@node-red/editor-client/src/js/ui/keyboard.js
This has been on the trello backlog for a while. Node-RED provides a set of default keyboard shortcuts in the editor and a user is able to customise those shortcuts manually in the editor.
This PR allows a custom set of default keyboard shortcuts to be provided in the settings file.
Under the `editorTheme` property, the new `keymap` setting can be used:
```
keymap: {
"core:add-flow": {
"key": "shift-ctrl-a"
},
"core:new-project": {}
}
```
In this example, it sets the shortcut for `core-add-flow` to `shift-ctrl-a`, and it *removes* the built-in shortcut for `core:new-project`. The format of this property is the same as we store under `.config.users.json` - this means a user can customise their shortcuts in the editor, and then copy/paste the configuration from the .config file into their …
> Allow default keymap to be overridden in settings file

- packages/node_modules/@node-red/editor-client/src/js/red.js
- packages/node_modules/@node-red/editor-client/src/js/ui/sidebar.js
We added the ability to reorder the sidebar tabs in a recent release. However, when the editor loads, whilst the order of tabs would be restored, you'd still get the Info sidebar tab show regardless of where in the order it was. This is because the sidebar would always show the first tab **added**.
This PR fixes the behaviour so that the first tab is always the one shown when the editor loads.
> Ensure the first sidebar tab is shown when editor loads

- packages/node_modules/@node-red/editor-client/src/js/ui/palette-editor.js
In Node.js v8, variable names in the regular expression seem not to be supported. To solve the situation, I changed it to an array instead of that.
> Fix regular expression for Node.js v8

- packages/node_modules/@node-red/editor-client/src/js/nodes.js
After creating a SUBFLOW using `Subflow` → `Selection to Subflow` menu, link from input port and link to output port of the SUBFLOW template are vanished as follows but internally connected.
> fix vanishing link in subflow

- packages/node_modules/@node-red/registry/lib/loader.js
If an error occurs while loading a node, the line number where the error occurred is not reported.
- Current
```
9 Mar 10:16:35 - [warn] [node-red-contrib-subflow2node/subflow2node] SyntaxError: Unexpected token ':'
```
- Expected
```
9 Mar 10:16:35 - [warn] [node-red-contrib-subflow2node/subflow2node] SyntaxError: Unexpected token ':' (line:47)
```
This PR attempts to fix the following two problems:
- Line number in error object is not recognized correctly,
- If the path contains a symbolic link, error number is not detected.
> Fix error report on  node load

- packages/node_modules/@node-red/editor-client/src/js/nodes.js
When exporting nodes that point to same config node, config node reference become empty except first reference.
(Eg. Multiple widgets belonging to the same Dashboard group)
> fix exporting config node

- packages/node_modules/@node-red/editor-api/lib/editor/index.js
- packages/node_modules/@node-red/editor-api/lib/editor/ui.js
- packages/node_modules/@node-red/registry/lib/index.js
- packages/node_modules/@node-red/registry/lib/localfilesystem.js
- packages/node_modules/@node-red/registry/lib/registry.js
- packages/node_modules/@node-red/runtime/lib/api/nodes.js
- packages/node_modules/@node-red/runtime/lib/nodes/index.js
- test/resources/plugin/test-plugin/test.html
If a Plugin or Node module has a top-level directory called `resources`, the runtime will now automatically expose it over the http admin route handler using the path:
`/resources/<name-of-module>/<path-to-resource>`
This removes the need for the plugin/node to manually setup route handlers to do the same.
> Allow module to provide resources and automatically expose them

- packages/node_modules/@node-red/nodes/core/function/90-exec.html
- packages/node_modules/@node-red/nodes/core/function/90-exec.js
- test/nodes/core/function/90-exec_spec.js
I think that exec node needs the ability to handle not only `msg.payload` but also other variables like `msg.filename`.
As we discussed in the following forum, I added `typedInput` for `msg.payload` to support changing the variable name.
https://discourse.nodered.org/t/suggestion-to-support-jsonata-in-exec-node/42794
Image: (the `typedInput` has msg. only)
> Support typedInput in msg.payload field of exec node

- packages/node_modules/@node-red/nodes/core/function/10-function.js
- test/nodes/core/function/10-function_spec.js
Adds `node.outputCount` property inside function node executors.
Briefly discussed here: https://discourse.nodered.org/t/expose-configured-output-count-to-function-node-i-can-pr/43848/5
Along the way, consistent testing of `node.id` and `node.name` across `init`, `func` and `finalize` functions were also added (previously only `init` method was tested).
> Function node: add `node.outputCount` property to sandbox

- packages/node_modules/@node-red/nodes/core/network/21-httpin.js
Fix for #2935 
This is a quick fix, but it feels wrong to just start to build a list of `application/*` that should be binary.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types#types
This sort of implies that `application/*` should be considered binary unless otherwise known
Add x-protobuf to the list of tested subtypes
> Fix for #2935

- packages/node_modules/@node-red/nodes/core/sequence/17-split.html
Changes the default manual mode of the Join node to be key/value Object rather than String.
In our experience, users tend to want to use the Object mode to join streams of messages. Having that as the default option makes sense.
> Join: change default manual mode to object

- packages/node_modules/@node-red/runtime/lib/storage/localfilesystem/projects/index.js
- packages/node_modules/@node-red/runtime/locales/en-US/runtime.json
- packages/node_modules/node-red/settings.js
This PR presets the flow file name to flows.json in the settings.js file  - thus it will only apply to new installs unless people update their settings file.  It also adds a warning if it is not set - so say that the hostname is being used. 
This should make things more obvious for people moving flows from one machine to another in that the flow should just work without having to be renamed. Will also make running on some other platforms (like docker) easier as then the default settings can be used.
> fix flowfile name to flows.json in settings

- packages/node_modules/@node-red/runtime/lib/index.js
- packages/node_modules/@node-red/runtime/locales/en-US/runtime.json
- packages/node_modules/node-red/settings.js
(no change is actual behaviour yet - just warning)
Should we remove option from settings ? or just label it ?
This PR - deprecates the usage of httpRoot in settings .js - having overlapping options can cause confusion - Cleaner just to be explicit about httpNodeRoot and httpAdminRoot.  This PR only adds a warning - and does not actually change functionality yet.
> Deprecate usage of httpRoot and add warning

- packages/node_modules/@node-red/runtime/lib/storage/localfilesystem/projects/index.js
When `editorTheme.projects.enabled=true` and `editorTheme.projects.workflow.mode="auto"`,  
1. add a node to workspace
2. remove the node added by (1)
3. press deploy button
causes following error:
```
Apr 09:02:42 - [warn] Error saving flows:
26 Apr 09:02:42 - [warn] Error
at /Users/nisiyama/src/Curry/Git/node-red-hitachi/packages/node_modules/@node-red/runtime/lib/storage/localfilesystem/projects/git/index.js:35:19
at processTicksAndRejections (internal/process/task_queues.js:97:5)
26 Apr 09:02:42 - [error] Error
```
The reason for this is that editor is trying to commit in the case where there is no change in the flow.
This PR try to fix the problem.
> fix error on auto commit for no flow change

- package.json
- packages/node_modules/@node-red/nodes/core/common/20-inject.js
- packages/node_modules/@node-red/nodes/package.json
Moves the Inject node over to the `CronosJS` module.
The previous module `cron` has a growing number of issues against it on the latest version - one we had to revert upgrading to last year.
`CronosJS` is the module used by the cron-plus node and is actively maintained.
This will open up some options for improving what the Inject node can offer - although that's a separate discussion for another day.
> Move Inject node to CronosJS module

- packages/node_modules/@node-red/nodes/core/storage/10-file.js
- packages/node_modules/node-red/settings.js
- test/nodes/core/storage/10-file_spec.js
Currently if a relative path is used in the File nodes, it is resolved relative to the working directory of the Node-RED process. 
That is non-obvious to new users and they don't necessarily know what the cwd is.
This change introduces `RED.settings.fileWorkingDirectory` that allows the user to set a specific directory to be used to resolve relative paths.
This PR only touches the File nodes. We should review other nodes that handle local paths and update them to honour this setting.
> File node: Add fileWorkingDirectory to customise how relative paths are resolved

- packages/node_modules/@node-red/registry/lib/externalModules.js
- packages/node_modules/@node-red/registry/lib/installer.js
- packages/node_modules/@node-red/runtime/lib/flows/Flow.js
- packages/node_modules/@node-red/runtime/lib/index.js
- packages/node_modules/@node-red/runtime/lib/nodes/Node.js
- packages/node_modules/@node-red/runtime/locales/en-US/runtime.json
- packages/node_modules/@node-red/util/index.js
- packages/node_modules/@node-red/util/lib/hooks.js
- test/unit/@node-red/registry/lib/externalModules_spec.js
- test/unit/@node-red/registry/lib/installer_spec.js
- test/unit/@node-red/runtime/lib/flows/Flow_spec.js
- test/unit/@node-red/runtime/lib/nodes/Node_spec.js
- test/unit/@node-red/util/lib/hooks_spec.js
Introduces a set of new API hooks that can be used to add code before and after `npm install` is run. This applies to both installing new nodes and Function node external modules.
There are four new hooks:
- `preInstall`
- `postInstall`
- `preUninstall`
- `postUninstall`
The `*Install` hooks are passed the following event object:
```json
{
"module": "<npm module name>",
"version": "<version to be installed>",
"url": "<optional url to install from>",
"dir": "<directory to run the install in>",
"isExisting": "<boolean> this is a module we already know about",
"isUpgrade": "<boolean> this is an upgrade rather than new install"
}
```
The `*Uninstall` hooks are passed the following event object:
```json
{
"module": "<npm module name>",
"dir": "<directory to run the uninstall in>",
}
```
``` …
```
> Add pre/postInstall hooks to npm install handling

- packages/node_modules/@node-red/nodes/core/common/20-inject.html
This just reorganises the typedinput list to move the context options to the bottom of the list to de-emphasise them - in particular msg. that has no real meaning here as there is no msg (though it could be used to duplicate a previous entry I suppose) - see https://github.com/orgs/node-red/projects/8#card-56046423
> Re-order inject typedinput to de-emphasise context options

- packages/node_modules/@node-red/registry/lib/externalModules.js
- packages/node_modules/@node-red/registry/lib/installer.js
This PR adds [`--engine-strict`](https://docs.npmjs.com/cli/v7/using-npm/config#engine-strict) flag to the npm install command for installing custom nodes. This flag ensures that if a specific nodejs version is included under *engines* section in `package.json` the npm install command will fail if it does not satisfy the nodejs version requirements rather than only generate a warning message.
to use this feature , a node developer adds an [engines](https://docs.npmjs.com/cli/v6/configuring-npm/package-json#engines) section in `package.json` and specify the version requirements such as 
```{ "engines" : { "node" : ">=0.11.15" } }```
This is tested to check for a specific nodejs version. This could possibly be extended to also stipulate a minimum node-red version which will be very useful …
> add engine-strict flag to npm install args

- packages/node_modules/@node-red/editor-client/src/js/ui/common/treeList.js
1. Currently it is not possible to remove an level 0 item from the treeList widget.
```
var item = myList.treeList('get', 'deleted');
item.treeList.remove();
myList.treeList('get', 'deleted');
-> works as expected
myList.treeList('data')
.filter(item => item.id == 'deleted')
.map(item => item.label);
-> it does not work as expected, the deleted item returns anyway
```
2. Currently if you remove a child element from the list, and then insert it again the gutter width is calculated incorrectly
> Fixed remove item when depth=0 and wrong gutter calc treeList widget

- packages/node_modules/@node-red/editor-client/src/js/ui/tab-info.js
I fixed #2975. Because shortcut keys in the info tips message contain '[' and ']', the regular expression recognized them as special words between '[' and ']'. To avoid the situation, I changed the regular expression to detect special words only which have alphabetical characters.
> Fix incorrect shortcut keys in info tips

- packages/node_modules/@node-red/nodes/core/network/21-httprequest.js
Get proxy support working with the Got http client
Also a couple of fixes for redirects (especially http to https)
A bunch of the http-request proxy authentication tests are failing, but the node works with a local squid instance. Will keep looking at those
> Get got working with proxies

- packages/node_modules/@node-red/editor-client/src/sass/base.scss
- packages/node_modules/@node-red/editor-client/src/sass/colors.scss
- packages/node_modules/@node-red/editor-client/src/sass/diff.scss
- packages/node_modules/@node-red/editor-client/src/sass/editor.scss
- packages/node_modules/@node-red/editor-client/src/sass/forms.scss
- packages/node_modules/@node-red/editor-client/src/sass/palette-editor.scss
- packages/node_modules/@node-red/editor-client/src/sass/palette.scss
- packages/node_modules/@node-red/editor-client/src/sass/style.scss
- packages/node_modules/@node-red/editor-client/src/sass/tab-info.scss
- packages/node_modules/@node-red/editor-client/src/sass/variables.scss
This introduces a set of named CSS variables for certain key colours to allow plugins/nodes to use them rather than hardcode colours that won't honour custom themes.
I've done a little bit of rationalisation of the CSS colours as well to remove some misuse of certain named properties.
I haven't added vars for all the Sass variables - just the ones I think will be useful.
We will eventually need a style guide in the docs for the css classes we provide.
> Add css named variables for certain key colours

- packages/node_modules/@node-red/nodes/core/function/10-switch.js
- test/nodes/core/function/10-switch_spec.js
Switch node with empty rules causes following error:
```
23 May 10:15:13 - [error] [switch:a4bcdee3.4848d] TypeError: Cannot read property 'vt' of undefined
```
> fix handling of empty switch rules

- packages/node_modules/@node-red/editor-client/src/js/nodes.js
- packages/node_modules/@node-red/nodes/core/network/10-mqtt.js
- packages/node_modules/@node-red/nodes/core/network/22-websocket.js
- packages/node_modules/@node-red/nodes/core/network/31-tcpin.js
- packages/node_modules/@node-red/util/lib/util.js
This PR changes the algorithm used to generate ids in the editor and runtime.
The existing code could produce variable length ids and had a `.` in the middle - which was accidental rather than intentional because all those years ago, I forgot to include `Math.floor()` in the code. eg `bfc71766.923608`
The new algorithm creates 8-byte fixed length ids without the `.` - eg `4ab59dd6503989b6`. This gives us a range of 2^64 − 1 values - which is suitably random to avoid collisions within individual NR instances.
> Change node id generation to give fixed length values without '.'

- packages/node_modules/@node-red/runtime/lib/nodes/context/index.js
- test/unit/@node-red/runtime/lib/nodes/context/index_spec.js
As discussed [here](https://discourse.nodered.org/t/typeerror-cannot-read-property-startswith-of-undefined/46212/8?u=steve-mcl)
Ensure `key` is a string when getting and setting context. 
At first i used the error string `"key must be a string"` 
... but once i tested it, i felt it was net clear enough to the user where this error was coming from. 
I eventually settled on `"context set() requires 'key' to be a valid string"` and `"context set() requires 'key' to be a valid string"`
Any thoughts on a better error string?
<br>
This is the result of my test...
```
[{"id":"95d47f9e.765ca","type":"function","z":"c559743c.82b088","name":"context.set(undefined, 1) ERROR","func":"context.set(undefined, 1);\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":1580,"y":200 …
```
> ensure context get/set key is a string

- packages/node_modules/@node-red/runtime/lib/flows/Flow.js
Thank you for considering the [Add get subflow information #2898](https://github.com/node-red/node-red/pull/2898) pull request.
Regarding the correction added in [the comment](https://github.com/node-red/node-red/pull/2898#issuecomment-811501640) of this request, there was a problem that the node could not be acquired, so I considered the correction.
Subflow instance node acquisition on line 380 does not work and the expected value is not obtained.
Instead, this.activeNodes [id] on line 375 returns null.
By excluding the subflow instance node in line 372, the expected value of the node can be obtained.
> Fix allow Flow.getNode to return subflowInstance nodes

- package.json
- packages/node_modules/@node-red/nodes/core/parsers/70-HTML.js
- packages/node_modules/@node-red/nodes/package.json
- test/nodes/core/parsers/70-HTML_spec.js
Bumping cheerio to their latest version which is a major version bump with api changes.
This PR does the work to handles those changes. The unit tests pass without any changes (although I have fixed the error handling in the tests so failures are properly reported rather than timedout).
There *may* be edge cases our unit tests don't catch, so this needs highlighting in release notes as something for users to check after upgrading.
> HTML node: cheerio update to 1.x

- packages/node_modules/node-red/settings.js
The list of settings has inevitably grown over time and they have become a bit of a muddle. This PR attempts to fix that.
The settings are have been reordered into clearly labelled sections:
*  Flow File and User Directory Settings
*  Security
*  Server Settings
*  Runtime Settings
*  Editor Settings
*  Node Settings
I have removed `paletteCategories` as that was deprecated some time ago and should be `editorTheme.palette.categories` - the code has handled both for some time now. The docs need to be updated to match.
The diff provided by this PR doesn't necessarily make it easy to appreciate the overall structure of the new file. You can see the new file in its entirety here: https://github.com/node-red/node-red/blob/reorganise-settings/packages/node_modules/node-red/settings.js
> Restructure default settings.js to be more organised

- packages/node_modules/@node-red/nodes/core/network/21-httprequest.js
- test/nodes/core/network/21-httprequest_spec.js
Manually build the Authentication header to work round URL encoding problem
Also add support for user/password in URL e.g.
http://user:pass@www.example.com
> Fix for basic auth with @ in username

- packages/node_modules/@node-red/nodes/core/network/05-tls.html
- packages/node_modules/@node-red/nodes/locales/ja/messages.json
I added additional Japanese translations to the message catalog in Node-RED 2.0.
To show the message in one line, I adjusted the width of some fields in the TLS config node.
> Add additional Japanese translations for Node-RED 2.0 beta-1

- packages/node_modules/@node-red/editor-api/lib/editor/comms.js
Currently, the Comms layer in the runtime will batch up events to send to the editor in a 50ms timer and then send the whole lot in one go. That helps to reduce the work done by not sending each event as its own packet over the websocket.
With the Flow Debugger, it is now possible to get a huge storm of events all queued up to send which get sent in one go. This has the problem of dumping a huge workload on the editor in a single message.
This PR modifies the runtime side of comms to send no more than 50 events per message, with the 50ms pause between message. This should give the editor some breathing space when such storms occur.
> Batch messages sent over Comms link

- packages/node_modules/@node-red/nodes/core/storage/10-file.html
- packages/node_modules/@node-red/nodes/core/storage/10-file.js
- packages/node_modules/@node-red/nodes/locales/en-US/messages.json
- test/nodes/core/storage/10-file_spec.js
and add test
Add option to file-in node so when in per line or per chunk mode it will add all existing properties to the msg rather than creating a new one.. As this is a new feature it is targeted to dev.
To close Issue #3034
> Add option for file-in node to include all properties (default off)

- packages/node_modules/@node-red/nodes/core/storage/10-file.html
- packages/node_modules/@node-red/nodes/locales/en-US/messages.json
- packages/node_modules/@node-red/nodes/locales/ja/messages.json
In the Japanese environment, I found that there is "s" in the output labels of the file-in node.
This problem is caused by a hardcode to describe plural words in the English environment. To solve the problem, I added new entries for plural words to be the same as other entries to distinguish singular and plural words.
> Fix output label in file-in node

- CHANGELOG.md
On GitHub, the CHANGELOG.md shows correctly. But the changelog is currently corrupted in the help tab.
- Unintended code blocks
- Unintended links
To show them on both GitHub and the help tab, I changed the Markdown.
> Fix change log in help tab

- Gruntfile.js
- packages/node_modules/@node-red/editor-client/src/js/ui/common/popover.js
- packages/node_modules/@node-red/editor-client/src/js/ui/view-annotations.js
- packages/node_modules/@node-red/editor-client/src/js/ui/view.js
- packages/node_modules/@node-red/editor-client/src/sass/variables.scss
This PR introduces a new api that can be used to add custom annotations to nodes.
This initial implementation provides support for one type of annotation - 'badges'.
Badges are ~10px square icons shown in the top-right corner of the node. The existing node-changed (blue dot) and node-warning (orange triangle) indicators have been reimplemented using this new API.
The flow debugger will use this api to add a badge to indicate if a node is currently paused or not.
The flow linter will use this api to highlight nodes that have linter errors.
This is how the node-changed badge is defined:
```
RED.view.annotations.register("red-ui-flow-node-changed",{
type: "badge",
class: "red-ui-flow-node-changed",
element: function(node) {
var changeBadge = …
```
> Add RED.view.annotations api

- packages/node_modules/@node-red/editor-client/src/js/ui/clipboard.js
When exporting a whole flow, it selects the flow nodes and pulls in any referenced config nodes.
However some config nodes (such as `ui_spacer`) can be scoped to a flow without any references. These nodes have `hasUser` set to false in their definition.
This fix ensures those config nodes get included in an export.
> Include `hasUser=false` config nodes when exporting whole flow

- packages/node_modules/@node-red/editor-client/src/js/nodes.js
An alternative fix for #3043.
When deleting/adding a node that points at a config node, we were correctly updating the config node's `users` array, but we weren't emitting the `nodes:change` event for the config node.
That was letting the Outliner display of a config node's user count to get out of sync.
> Emit `nodes:change` for any updated config node when node deleted/added

- packages/node_modules/@node-red/nodes/core/function/90-exec.html
- packages/node_modules/@node-red/nodes/core/function/90-exec.js
- packages/node_modules/@node-red/nodes/locales/en-US/function/90-exec.html
- packages/node_modules/@node-red/nodes/locales/en-US/messages.json
- test/nodes/core/function/90-exec_spec.js
This adds a `Hide windows` checkbox to the exec node to allow hiding shell windows under windows. Without this, the windowsHide option of exec and spawn defaults to false and shell windows will appear briefly when running commands.
> exec node: add windowsHide option

- packages/node_modules/@node-red/util/package.json
When I tried [the electron Node-RED](https://github.com/node-red/node-red-desktop/pull/1) using Node-RED v2.0 beta 2, I encountered a startup error.
I found that this problem came from a lack of dependencies in the `@node-red/util` module. Therefore, I added the `fs-extra` module as dependencies in the `@node-red/util` module. (Strangely, this problem didn't occur using Node-RED v1.3.5).
> Add fs-extra module to dependencies in @node-red/util module

- packages/node_modules/@node-red/nodes/core/network/22-websocket.html
- packages/node_modules/@node-red/nodes/core/network/22-websocket.js
- packages/node_modules/@node-red/nodes/locales/en-US/messages.json
This adds a new option to the Websocket Client config node to enable automatic sending of ping messages as-per the websocket spec.
If enabled, the client will send ping messages each interval. If the previous ping has not been acknowledged by a pong, the client terminates the connection (triggering status node etc) and attempts to reconnect.
> Allow websocket client node to send pings

- packages/node_modules/@node-red/nodes/core/function/89-delay.html
- packages/node_modules/@node-red/nodes/core/function/89-delay.js
- packages/node_modules/@node-red/nodes/locales/en-US/function/89-delay.html
- test/nodes/core/function/89-delay_spec.js
This PR allows `msg.flush` to accept a numeric parameter. If set to a numeric then up to that many messages will be released from the queue immediately. If any other type then all will be flushed (as per current behaviour).
Also the node status messages have now been changed to reflect the depth of the queue so you can inspect how many are left.... Note: as per today - for delay mode there is no status for delays set to < 1 sec , and in rate mode the status is updated every 500mS - both in order to save websocket bandwidth to the browser in the case of fast moving data.
> Delay node updates to added numeric flush control for releasing things from queue

- packages/node_modules/@node-red/nodes/core/function/10-function.html
- packages/node_modules/@node-red/nodes/core/function/10-function.js
- packages/node_modules/@node-red/nodes/locales/en-US/messages.json
- packages/node_modules/@node-red/registry/lib/externalModules.js
- packages/node_modules/@node-red/registry/lib/util.js
- packages/node_modules/@node-red/runtime/lib/storage/localfilesystem/settings.js
- packages/node_modules/@node-red/runtime/locales/en-US/runtime.json
- test/unit/@node-red/registry/lib/externalModules_spec.js
In 1.3 we introduced the ability for the Function node to specify additional modules via the UI.
For various reasons, we decided to install those extra modules under `~/.node-red/externalModules`. This was whilst trying to solve various issues around the full lifecycle management of those modules.
However we never released support for removing modules via the UI - that has to be done on the command line. So none of the issues that were addressed by having a separate directory actually apply.
Feedback from the community was not overly positive on having a separate directory. Users want a single package.json for their application that covers everything - rather than having one for the app and one for the external modules.
**This PR changes the behaviour to install and load external modules …
> Move externalModules back into the user dir

- packages/node_modules/@node-red/nodes/core/function/10-function.html
- packages/node_modules/@node-red/nodes/core/function/10-function.js
- packages/node_modules/node-red/settings.js
- test/nodes/core/function/10-function_spec.js
Enable `functionExternalModules` by default for new installs.
> Enable functionExternalModules by default

- packages/node_modules/@node-red/nodes/core/network/21-httprequest.js
Fixes #3072
Attempt to detect if an old agent-base instance has been required that has patched the core https.request function, and undo the patching if found.
Not ideal, but will keep the core working and quickly identify nodes that need updating.
> Detect if agent-base has patch https.request and undo it

- packages/node_modules/@node-red/editor-client/src/sass/tabs.scss
Fixes the tab fade CSS for when themes are used
Current state
With the proposed fix
> Fix tab fade CSS for when using themes

- packages/node_modules/@node-red/nodes/core/network/21-httprequest.js
- test/nodes/core/network/21-httprequest_spec.js
Copy tls.cert to tls.certificate for GOT module
> Copy tls.cert to tls.certificate for GOT

- packages/node_modules/node-red/red.js
+ In the current settings.js template the following code snippet is provided:
```
https: function() {
return {
key: require("fs").readFileSync('/home/pi/.node-red/certs/privkey.pem'),
cert: require("fs").readFileSync('/home/pi/.node-red/certs/fullchain.pem')
}
},
```
Since no encoding parameter is specified, the readFileSync will return a ***raw buffer***.
+ However it is also possible to read the keypair like this:
```
https: function() {
return {
key: require("fs").readFileSync('/home/pi/.node-red/certs/privkey.pem', 'utf8'),
cert: require("fs").readFileSync('/home/pi/.node-red/certs/fullchain.pem', 'utf8')
}
},
```
Since an encoding parameter is specified, the readFileSync will return a ***string***.
However in the case of a string, the current code will fail (as discussed on …
> Key and certificate as string or buffer

- packages/node_modules/@node-red/editor-client/src/js/ui/common/tabs.js
- packages/node_modules/@node-red/editor-client/src/sass/tabs.scss
When hovering over an inactive tab, the fade becomes visible due to the background color change. A similar issue happens in subflow tabs.
This PR fixes the issues by changing the fade colors of inactive tabs when hovering and bringing the close tab link to the front.
> Fix fade colors when hovering over tabs

- packages/node_modules/@node-red/editor-api/lib/auth/index.js
… passed in via options
This sets the arity of the node-red verify callback wrapper function to the arity of the verify callback provided via options.
This is useful when the passport strategy inspects the arity to determine which data is passed to the function, like this one e.g.:
https://github.com/jaredhanson/passport-openidconnect/blob/master/lib/strategy.js#L220
> Give passport verfiy callback wrapper the same arity as the original callback

- packages/node_modules/@node-red/editor-client/locales/en-US/editor.json
- packages/node_modules/@node-red/editor-client/src/js/history.js
- packages/node_modules/@node-red/editor-client/src/js/keymap.json
- packages/node_modules/@node-red/editor-client/src/js/red.js
- packages/node_modules/@node-red/editor-client/src/js/ui/common/menu.js
- packages/node_modules/@node-red/editor-client/src/js/ui/common/tabs.js
- packages/node_modules/@node-red/editor-client/src/js/ui/group.js
- packages/node_modules/@node-red/editor-client/src/js/ui/keyboard.js
- packages/node_modules/@node-red/editor-client/src/js/ui/view-tools.js
- packages/node_modules/@node-red/editor-client/src/js/ui/view.js
- packages/node_modules/@node-red/editor-client/src/sass/dropdownMenu.scss
- packages/node_modules/@node-red/editor-client/src/sass/header.scss
- packages/node_modules/@node-red/editor-client/src/sass/tabs.scss
- packages/node_modules/node-red/red.js
Adds align actions to the editor:
- `core:align-selection-to-left`  - `alt-a l`
- `core:align-selection-to-center`  - `alt-a c`
- `core:align-selection-to-right`  - `alt-a r`
- `core:align-selection-to-top`  - `alt-a t`
- `core:align-selection-to-middle`  - `alt-a m`
- `core:align-selection-to-bottom`  - `alt-a b`
- `core:distribute-selection-horizontally` - `alt-a h`
- `core:distribute-selection-vertically` - `alt-a v`
ToDo:
https://trello.com/c/iYmbLYT1
> Add align actions to editor

- packages/node_modules/@node-red/editor-client/locales/en-US/editor.json
- packages/node_modules/@node-red/editor-client/src/js/history.js
- packages/node_modules/@node-red/editor-client/src/js/nodes.js
- packages/node_modules/@node-red/editor-client/src/js/red.js
- packages/node_modules/@node-red/editor-client/src/js/ui/tab-info-outliner.js
- packages/node_modules/@node-red/editor-client/src/js/ui/view-tools.js
- packages/node_modules/@node-red/editor-client/src/js/ui/view.js
- packages/node_modules/@node-red/editor-client/src/js/ui/workspaces.js
This PR adds a set of actions that can reorder the nodes in the workspace.
- `core:move-selection-forwards`
- `core:move-selection-backwards`
- `core:move-selection-to-front`
- `core:move-selection-to-back`
A consequence of this change is that flow nodes are now added to the flow json sorted by tab and then order on that tab.
But there's more work to do when it comes to groups. These do *not* currently apply to groups - only to the nodes.
The order of nodes in the outline sidebar does not change - there is some commented-out code that almost does the job, but it gets confusing when it comes to groups.
In fact, the whole handling of groups needs looking at in general. They exist on a different plane to nodes - nodes are *always* drawn over the top of groups.
> Allow nodes to be raised/lowered in the workspace

- packages/node_modules/@node-red/editor-client/src/js/nodes.js
- packages/node_modules/@node-red/editor-client/src/js/ui/editor.js
- packages/node_modules/@node-red/editor-client/src/js/ui/group.js
- packages/node_modules/@node-red/editor-client/src/js/ui/subflow.js
- packages/node_modules/@node-red/editor-client/src/js/ui/workspaces.js
- packages/node_modules/@node-red/runtime/lib/api/flows.js
- packages/node_modules/@node-red/runtime/lib/flows/Flow.js
- packages/node_modules/@node-red/runtime/lib/flows/Subflow.js
- packages/node_modules/@node-red/runtime/lib/flows/index.js
- packages/node_modules/@node-red/runtime/lib/flows/util.js
- packages/node_modules/@node-red/runtime/lib/nodes/Node.js
- packages/node_modules/@node-red/runtime/lib/nodes/index.js
- packages/node_modules/@node-red/util/lib/util.js
- test/nodes/core/function/15-change_spec.js
- test/nodes/subflow/subflow_spec.js
- test/unit/@node-red/runtime/lib/flows/Flow_spec.js
This draft PR adds support of environment variable definition feature to tabs and groups.
(design note: https://github.com/node-red/designs/pull/56)
[test Flow]
```
[{"id":"f7ca862bdab6753c","type":"subflow","name":"Subflow 1","info":"","in":[{"x":40,"y":80,"wires":[{"id":"4252d927624bb8c7"}]}],"out":[{"x":360,"y":80,"wires":[{"id":"4252d927624bb8c7","port":0}]}]},{"id":"4252d927624bb8c7","type":"change","z":"f7ca862bdab6753c","name":"","rules":[{"t":"set","p":"payload","pt":"msg","to":"V0","tot":"env"}],"action":"","property":"","from":"","to":"","reg":false,"x":200,"y":80,"wires":[[]]},{"id":"24c1d7451d6b49db","type":"tab","label":"フロー 1","disabled":false,"info":"","env":[{"name":"V0","value":"tv0","type":"str"}]},{"id":"091be52d71e62cd2","type":"group","z":"24c1d7451d6b49db","name":""," …
```
> Add support of environment variable for tab & group

- packages/node_modules/@node-red/editor-api/lib/editor/theme.js
- packages/node_modules/@node-red/editor-client/templates/index.mst
- test/unit/@node-red/editor-api/lib/editor/theme_spec.js
I came across an issue where it was possible to change the browser tab icon on safari, but not the colour used to render the svg.
I've therefore made a very small enhancement which allows you to adjust this in the `settings.js`.
> Allow colouring of tab icon svg

- packages/node_modules/node-red/lib/red.js
Allows `coreNodesDir` in settings to be set to `false` to disable core nodes
> Allow coreNodesDir to be set to false

- packages/node_modules/@node-red/editor-client/src/js/ui/palette-editor.js
- packages/node_modules/@node-red/registry/lib/installer.js
- test/unit/@node-red/registry/lib/installer_spec.js
As described in https://github.com/node-red/node-red/pull/3131 adds a new set of flags to `externalModules.palette` to allow finer control over what can be upgraded via the admin API and palette manager.
(renamed to `allowUpdate` from the original proposed `allowUpgrade`)
```
externalModules: {
autoInstall: true/false,
autoInstallRetry: 30,
palette: {
allowInstall: true/false,
allowUpload: true/false,
allowUpdate: true/false,  // NEW, default: true
allowList: [],
denyList: [],
allowUpdateList: [],  // NEW, default: '*' (allow all)
denyUpdateList: []   // NEW, default: null (do not deny any)
}
}
```
Works in the same way as the install allow/deny lists. Blocks upgrades to denied modules on the admin api and hides the 'update' button in the palette manager.
### TODO:
> Add allowUpdate feature to externalModules.palette

- packages/node_modules/@node-red/registry/lib/library.js
- packages/node_modules/@node-red/util/lib/i18n.js
This replaces fs-extra with fs and uses the fs.promises versions for the async calls
This fixes the issue that causes electron to fail to run complaining about Unhandled promise rejection. 
In draft as tests now fail... need to discuss if it's the tests that need fixing or the code...
> Fixes to fs promises so that an electron built version runs

- packages/node_modules/@node-red/nodes/core/network/21-httprequest.js
The current HTTP request node output the time spent on HTTP requests as a metric log(`node.http request.duration.mills`), but it does not provide a breakdown of the time spent on HTTP request, such as DNS resolution, and TCP connection establishment, which hinders failure analysis.
The got package, used in HTTP request node, [can obtain these detailed timing information as a result of HTTP requests](https://www.npmjs.com/package/got#timings).  This PR use this feature to add a function to output the detailed timing information as a metric log.
An example of metric log is shown below: 
```
23 Aug 11:52:27 - [metric] {"level":99,"nodeid":"15576e5393f5cb94","event":"node.http request.duration.millis","msgid":"11c38881d7cf926f","value":"215.305","timestamp":1629687147857}
23 Aug 11:52:27 - …
```
> Extend HTTP request node to log detailed timing information

- Gruntfile.js
- packages/node_modules/@node-red/editor-client/locales/en-US/editor.json
- packages/node_modules/@node-red/editor-client/src/js/red.js
- packages/node_modules/@node-red/editor-client/src/js/settings.js
- packages/node_modules/@node-red/editor-client/src/js/ui/common/popover.js
- packages/node_modules/@node-red/editor-client/src/js/ui/editor.js
- packages/node_modules/@node-red/editor-client/src/js/ui/tab-help.js
- packages/node_modules/@node-red/editor-client/src/js/ui/tour/tourGuide.js
- packages/node_modules/@node-red/editor-client/src/js/ui/userSettings.js
- packages/node_modules/@node-red/editor-client/src/sass/colors.scss
- packages/node_modules/@node-red/editor-client/src/sass/dropdownMenu.scss
- packages/node_modules/@node-red/editor-client/src/sass/header.scss
- packages/node_modules/@node-red/editor-client/src/sass/popover.scss
- packages/node_modules/@node-red/editor-client/src/sass/style.scss
- packages/node_modules/@node-red/editor-client/src/sass/tourGuide.scss
- packages/node_modules/@node-red/editor-client/src/sass/variables.scss
- packages/node_modules/@node-red/editor-client/src/tours/first-flow.js
- packages/node_modules/@node-red/editor-client/src/tours/welcome-2-1.js
- packages/node_modules/@node-red/editor-client/src/tours/welcome.js
This introduces a new component - `RED.tourGuide` that can be used to provide interactive guided tours within the Node-RED UI.
You can see a demo of the feature here: https://www.youtube.com/watch?v=MmkkiEc3ITs (correct at the time of raising this PR... things may change...)
There are a few different use cases for this feature:
- A 'what's new' tour that is displayed the first time the editor is opened at a new version (not maintenance releases)
- Interactive tutorials for specific features in the editor (eg, "how to use subflows") that could get triggered the first time a user does an action.
- Interactive tutorials for building flows (eg, "lets build a chat-bot together")
This is very much a work in progress and will continue to evolve to meet the needs of the tours/tutorials we choose …
> Add Tour Guide component

- packages/node_modules/@node-red/editor-client/src/js/ui/diff.js
Restore tab selection when merging flows that have changed on the server. Right now the user will be send to the first tab.
> Restore tab selection after merging conflicts

- packages/node_modules/@node-red/editor-client/src/js/ui/editor.js
Fixes #3001
The config node select UI is due an overhaul - replacing it with a TypedInput possibly that could provide better search/filter options if the list of candidate nodes is long.
But for now, just fix the width calculation to properly inherit the width of the input element it's replacing. The code didn't know about `calc()` style widths due to an overly aggressive regex.
> Ensure config-node select inherits width properly from input

- packages/node_modules/@node-red/nodes/core/function/89-delay.js
- packages/node_modules/@node-red/nodes/locales/en-US/function/89-delay.html
- test/nodes/core/function/89-delay_spec.js
(moved random delay to top to group with other delay types.
Tests and docs to follow
This adds (allows) a `msg.lifo` property . If it exists on a msg for a rate limited queue then it adds it to the front of the queue (unshift) rather than the end so it will be first out (Last In First Out). 
This  allow building a stack type queue if required - or a push back in case of failure retry type queue.
> Add push to front of rate limit queue.

- packages/node_modules/@node-red/editor-client/src/js/ui/common/typedInput.js
- packages/node_modules/@node-red/editor-client/src/sass/ui/common/typedInput.scss
When you have a TypedInput with multiple types, we didn't do a good job of remembering previous values whilst switching types.
For example, if you had an input with two types:
1. 'none' with hasValue=false
2. 'select' with multiple options
Then if you picked the 'select' option and chose some options, then switched to 'none' and back to 'select' - all of your previous choices were cleared.
There were also issues with that combination with it not setting the 'select' label properly.
With this PR, the TypedInput now remembers the value when switching between types and restores the previous value when you go back to a previous type.... in some cases.
For this change, there are 3 'classes' of type to consider:
1. types with a value (where the user types in) - `str` `num` `msg` etc
2. types …
> Do better remembering TypedInput values whilst switching types

- packages/node_modules/@node-red/editor-client/src/js/ui/tour/tourGuide.js
- packages/node_modules/@node-red/editor-client/src/sass/colors.scss
- packages/node_modules/@node-red/editor-client/src/sass/tourGuide.scss
- packages/node_modules/@node-red/editor-client/src/sass/variables.scss
As highlighted [here](https://github.com/node-red/node-red/pull/3136#issuecomment-932729662) the Tour theme doesn't work well on dark themes that have not been rebuilt for 2.1.
Whilst the tour component is theme-aware, some restructuring on how the popover component applies its style means existing styles won't quite do the right thing until they get rebuilt for 2.1.
I've no doubt themes will get updated and rebuilt for 2.1, but if a user updates NR to 2.1 without updating their theme as well, then they will be greeted with the new welcome tour not looking good.
This PR tweeks how the styles are applied so they look semi-decent on dark themes that haven't bene rebuilt for 2.1.
> Improve themeing of tourGuide

- packages/node_modules/@node-red/nodes/core/function/15-change.html
- packages/node_modules/@node-red/nodes/core/function/15-change.js
- packages/node_modules/@node-red/nodes/locales/en-US/messages.json
- test/nodes/core/function/15-change_spec.js
A common gotcha with the Change node is that when setting object properties it doesn't clone the value - so you end up with a reference to the original property. Any modifications to the 'new' property also applies to the original one. This happens with  both setting from a msg property and context property.
This PR adds an option to the 'set' action of the Change node to make a 'deep copy' of the value. 
The option is only shown for the 'set' rule when the 'source' is `msg` `flow` `global` or `env` - as those are the ones that can set a value that could be referenced elsewhere.
I have also changed the text of the `set` rule - where it used to just say `to` it now says `to the value` which hopefully helps make it clearer the 'direction' of the action.
This will also help address #3144
> Add option to deep-clone properties in Change node

- packages/node_modules/@node-red/editor-client/locales/en-US/editor.json
- packages/node_modules/@node-red/editor-client/src/js/nodes.js
- packages/node_modules/@node-red/registry/lib/installer.js
Improves the error reporting if a 'bad' node module is installed. This is specifically if the module is installed via the Palette Manager, rather than just loaded at startup.
In this instance, 'bad' means the node's .js file throws an error whilst being required. If that error is thrown before any node types are registered, we would log the following:
```
30 Sep 15:25:38 - [info] Installing module: broken-node, version: 1.0.0
30 Sep 15:25:41 - [info] Installed module: broken-node
30 Sep 15:25:41 - [info] Adding node types:
```
With this PR, we now log the following:
```
30 Sep 15:25:38 - [info] Installing module: broken-node, version: 1.0.0
30 Sep 15:25:41 - [info] Installed module: broken-node
30 Sep 15:25:41 - [warn] [broken-node/index] Error: Bish bash bosh(line:3)
```
In this …
> Improve node install error reporting

- packages/node_modules/@node-red/nodes/core/storage/10-file.html
- packages/node_modules/@node-red/nodes/locales/en-US/messages.json
Changes the palette labels of the file nodes to `read file` and `write file` to make it clearer which is which.
> Add paletteLabel to file nodes to make read/write more obvious

- packages/node_modules/@node-red/editor-client/src/js/ui/editor.js
When a node depends on a config node it does so by specifying the `type` property in its `defaults` object:
```
broker: {type:"mqtt-broker", required:true},
```
There was a requirement raised some time ago to be able to provide a filter for what config nodes the user is able to pick from  - rather than listing all of them.
This PR adds support for that.
I will admit it is a bit of an edge case, but it is one that is hard to work around if we don't so something like this.
So, for example, if the select box should only show broker nodes configured to use port 1883:
```
broker: {type:"mqtt-broker", required:true, filter: function(n) { return n.port == 1883 } },
```
The `filter` function is called for each config node of the given type. It should return `true` if the config node should be …
> Allow a node to specify a filter for the config nodes it can pick from

- packages/node_modules/@node-red/nodes/locales/en-US/function/80-template.html
Added note about changing template characters to the help text
- [] Bugfix (non-breaking change which fixes an issue)
- [ x] I have read the [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md)
> change template characters

- packages/node_modules/@node-red/nodes/core/network/21-httprequest.html
- packages/node_modules/@node-red/nodes/core/network/21-httprequest.js
- packages/node_modules/@node-red/nodes/locales/en-US/messages.json
The legacy behaviour of the HTTP Request node is, in the case of a non-2xx response, to both trigger any Catch nodes (`node.error(...)`) and send on the response (`node.send(...)`).
This double counting of the response isn't helpful, but is the long held behaviour of the node.
This PR adds an option to the HTTP Request node to send non-2xx responses *only* to the Catch node. Without that option selected, the legacy behaviour remains - the message is passed to both Catch and Send.
In 3.0 we should change the default to be Catch-only.
> Add option to only send http response errors to Catch node

- packages/node_modules/@node-red/editor-client/src/js/ui/utils.js
- packages/node_modules/@node-red/editor-client/src/sass/tab-info.scss
* Add a custom marked extension to convert markup from markdown text to generate HTML that adheres to the [Node help style guide](https://nodered.org/docs/creating-nodes/help-style-guide)
* markup kept simple to leave un-rendered markdown human readable
As discussed in the [design note](https://github.com/node-red/designs/discussions/60) and in forum [here](https://discourse.nodered.org/t/using-markdown-directly-to-document-the-nodes/49592/12?u=steve-mcl)
> Render node documentation to node-red style guide when written in markdown.

- packages/node_modules/@node-red/editor-client/src/js/ui/common/typedInput.js
- packages/node_modules/@node-red/nodes/core/function/10-switch.html
- packages/node_modules/@node-red/nodes/core/function/15-change.html
It is a common scenario that when adding rules to a Switch node, you want the compared values to all be the same type.
Currently, the Switch node defaults each rule to String type. If you're comparing against a numbers, its a pain to have to change the type field every time.
With this PR, the node will copy the previous rule's type when adding a new rule. It also focusses the input so the user can enter a value straight away without having to click on the input again (if they have just added a rule, they probably want to enter the value)
> Copy previous rule type when adding rule to switch node

- Gruntfile.js
- packages/node_modules/@node-red/editor-client/src/js/ui/common/autoComplete.js
- packages/node_modules/@node-red/editor-client/src/js/ui/common/popover.js
- packages/node_modules/@node-red/editor-client/src/js/ui/common/typedInput.js
- packages/node_modules/@node-red/editor-client/src/sass/style.scss
- packages/node_modules/@node-red/editor-client/src/sass/ui/common/autoComplete.scss
This adds a new `autoComplete` widget that can be applied to any `<input type="text">` that gives an auto-complete dropdown whilst typing in the input.
This is applies that to the `msg.` type of the `TypedInput`, with a (for now) hardcoded list of all message properties that core nodes use.
Even with the hardcoded list, this is already really useful.
But I plan to follow up with a design proposal for how nodes can provide a list of the properties they care about - distinguishing those they receive vs those they send. It would then be feasible for contrib nodes to add to the auto-complete list and it would also be able to sort the suggested completions based on whether a given type exists in the upstream or downstream flow. In that scenario, it would still show valid completions across the …
> Add autoComplete widget and add to TypedInput for msg. props

- packages/node_modules/@node-red/editor-client/src/js/ui/view.js
If the target of the Link node exists in another tab, selecting the virtual node will move to the tab of target node, but not the target node is not shown.
This fix show the target node after moving tab if there is only one target node in target tab.
> fix to show link target when selected

- packages/node_modules/@node-red/editor-client/src/sass/colors.scss
- packages/node_modules/@node-red/editor-client/src/sass/flow.scss
The selector `.red-ui-flow-port-label` currently uses `$secondary-text-color` to define its text color, but that variable usually has its value changed by the themes.
I noticed this issue with the Dracula theme. Here's how it looks when using that variable.
And here's how it looks with the proposed change.
This uses the same color value defined for `$secondary-text-color` in the default vanilla theme.
It's like Nick said on Slack some time ago.
This PR tries to fix that.
> Don't let themes change flow port label color

- packages/node_modules/@node-red/editor-client/src/js/ui/common/typedInput.js
[Reported on the forum](https://discourse.nodered.org/t/typefield-problems-in-2-1-3/53832), if a TypedInput is initialised with a list of types where the first type in the list has no value (eg, timestamp), but the node property is a different type with value (eg `str`), then the TI gets the right type, but the value is blank.
This is happening because when the TI is initialised, it first sets the types, which causes the type to be primed as the first in the list (`timestamp`). It then applies the actual type (`str`), which is seen as a change in type from no-value to value - and it restores the 'old' value which is blank - overwriting the right value that was already there.
The fix is to not set the `type` when setting the `types` list if its part of the initialisation of the whole …
> Avoid redundant initialisation of TypedInput type

- packages/node_modules/@node-red/nodes/core/function/89-delay.js
- [ x] Bugfix (non-breaking change which fixes an issue)
to fix issue found in #3260
When in rate limit per topic mode nothing gets sent to the 2nd output if that is selected.
The way those mode work is that if a new msg arrives on a topic then the new one replaces the old one in the queue (so only the most recent gets sent) - so the old one gets discarded... This fix sends the one that would have been be discarded to the 2nd output if that is enabled.
> fix 2nd output when in rate limit per topic modes

- packages/node_modules/@node-red/editor-api/lib/auth/index.js
- packages/node_modules/@node-red/editor-api/lib/auth/strategies.js
The audit log events for when a user logs in to the editor included the `username` of the user, but not their full profile object - which other audit events have.
This brings these events into line with the others.
> Include full user object on login audit events

- packages/node_modules/@node-red/editor-client/src/js/nodes.js
- packages/node_modules/@node-red/editor-client/src/js/ui/diff.js
- packages/node_modules/@node-red/editor-client/src/js/ui/editors/panes/envVarProperties.js
This fixes a few things with Groups and the diff view.
- when editing flow/group env vars, this fixes undoing changes
- if a flow/group has no env vars, we do not include an empty `env` property on the node
- the diff view of a group now includes `env` and `w`/`h` properties
Related to #3232
> Group diff fix

- packages/node_modules/@node-red/nodes/core/common/21-debug.js
This avoids internal errors from being returned to the caller
> Add proper error handling for 404 errors when serving debug files

- packages/node_modules/@node-red/editor-client/src/js/nodes.js
Following editor operation causes node conflict on importing flow:
1. detele flow tab,
2. import a flow with nodes that was contained in the flow tab of (1)
This is because the tab information is deleted too early, so the deletion is delayed in this PR.
> fix removed tab not to cause node conflict

- packages/node_modules/@node-red/runtime/lib/flows/Flow.js
- packages/node_modules/@node-red/runtime/lib/flows/Subflow.js
- packages/node_modules/@node-red/util/lib/util.js
- test/unit/@node-red/runtime/lib/flows/Flow_spec.js
If an environment variable reference is made using `$parent` in a group, the location of the variable reference in the outer environment may become incorrect.  
This is because the `$parent` reference within the group is not reflected in the outside environment.
> fix env var access using $parent for groups

- packages/node_modules/@node-red/editor-client/src/js/i18n.js
- packages/node_modules/@node-red/util/lib/i18n.js
i18next recently added a 'natural language detection' feature that, whilst the details are irrelevant, broken the ability to have message catalog namespaces that contain a space.
This was introduced in a major version change on their part, but unfortunately their migration guide did little to highlight the impact of this feature. It did at least, once the dots were joined, point to the config options needed to disable the behaviour and get back to how it used to work.
> Fix i18n handling of namespaces with spaces in

- packages/node_modules/@node-red/editor-client/locales/en-US/editor.json
- packages/node_modules/@node-red/editor-client/src/js/ui/common/tabs.js
- packages/node_modules/@node-red/editor-client/src/js/ui/search.js
- packages/node_modules/@node-red/editor-client/src/js/ui/tab-info-outliner.js
- packages/node_modules/@node-red/editor-client/src/js/ui/workspaces.js
- packages/node_modules/@node-red/editor-client/src/sass/tabs.scss
This is technically a new feature that addresses a usability concern with the hide-tabs feature. I propose to include this in 2.1.4 rather than wait two months for 2.2.0.
As such, want to get sign-off from @dceejay as this is an exception to our normal way of working.
This PR improves the workflow around hiding tabs a bit. Specifically:
- the icon is changed from the `x`to by the eye icon. Repeated feedback told us users felt the `x` implied they were deleting the tab rather than hiding. Changing the icon to the more benign eye is less alarming and more related to visibility rather than deletion.
- moreso, when you hover on the tab the icon is the open eye. When you hover over the eye it closes. This also helps reinforce the purpose of the button.
- The tab dropdown menu has a new option …
> Change tab hide button icon to an eye and add search option

- packages/node_modules/@node-red/editor-client/src/tours/welcome.js
In the pull request, https://github.com/node-red/node-red/pull/3282, the hide icon was changed from `x` to the eye icon. But the tour guide still uses the `x` icon. 
Therefore, I changed it to the eye icon by the pull request.
> Fix hide icon in tour guide

- packages/node_modules/@node-red/nodes/core/function/10-function.js
Fixes #3299
The Function node was not using the right utility function to access env vars - so the group level env vars were being ignored.
> Update Function to use correct api to access env vars

- packages/node_modules/@node-red/editor-client/src/js/ui/editors/panes/envVarProperties.js
> Avoid adding empty env properties to tabs/groups

- packages/node_modules/@node-red/editor-client/src/js/ui/clipboard.js
Can not delete selected nodes by delete key after following operations:
1. select nodes,
2. open import/export dialog from menu,
3. close the dialog,
4. press `DEL` key.
This is because focus is lost after opening the dialog.  This PR tries to resolve this issue.
> resume focus after import/export dialog close

- packages/node_modules/@node-red/nodes/examples/storage/read file/01 - Read string from a file.json
- packages/node_modules/@node-red/nodes/examples/storage/read file/02 - Read data in specified encoding.json
- packages/node_modules/@node-red/nodes/examples/storage/read file/03 - Read data breaking lines into messages.json
- packages/node_modules/@node-red/nodes/examples/storage/read file/04 - Create a message stream.json
- packages/node_modules/@node-red/nodes/examples/storage/write file/01 - Write string to a file.json
- packages/node_modules/@node-red/nodes/examples/storage/write file/02 - Write string to a file specified by property.json
- packages/node_modules/@node-red/nodes/examples/storage/write file/03 - Delete a file.json
- packages/node_modules/@node-red/nodes/examples/storage/write file/04 - Specify encoding of written data.json
In recent Node-RED release, name of `file` and `file-in` node changed to `read file` and `write file`.  But examples of these nodes uses old name.  This PR fixes these node names.
This PR also fixes minor typo in examples.
> Update file node examples according to node name change

- packages/node_modules/@node-red/editor-client/src/js/ui/editors/js.js
- packages/node_modules/@node-red/nodes/core/function/10-function.html
Ensure extra libs are declared in monaco to prevent red error underline on libraries declared in setup tab.
See issue #3319
> load extralibs when expanding monaco. fixes #3319

- packages/node_modules/@node-red/nodes/core/network/21-httprequest.js
fixes #3324
Add check for `undefined` values and replace with empty string
> Fix basic auth with empty username or password

- packages/node_modules/@node-red/editor-client/src/js/ui/deploy.js
When importing and deploying a flow, a warning will be displayed if there are undefined nodes.
However, in the case of a config node, no warning is displayed.  So if you deploy a flow containing undefined config node, the flow will stop unintentionally.
To solve this problem, I added a check to see if the config node is an undefined node at the time of deployment.
> Check availability of type of config node on deploy

- packages/node_modules/@node-red/editor-client/src/js/ui/view-tools.js
Adds a pair of new actions for wiring nodes.
- `core:wire-series-of-nodes` - for a selection of nodes, add a wire (if necessary) between each node pair in the order they exist in the selection
- `core:wire-node-to-multiple` - for a selection of nodes, wires the *first* node (the source) in the selection to all of the remaining nodes. If the source node has multiple outputs, they are wired in turn.
No default keyboard shortcut assigned to them (yet)... something to consider adding.
> Wiring shortcut

- packages/node_modules/@node-red/nodes/core/network/22-websocket.html
- packages/node_modules/@node-red/nodes/core/network/22-websocket.js
- packages/node_modules/@node-red/nodes/locales/de/messages.json
- packages/node_modules/@node-red/nodes/locales/en-US/messages.json
- packages/node_modules/@node-red/nodes/locales/ja/messages.json
- packages/node_modules/@node-red/nodes/locales/ko/messages.json
- packages/node_modules/@node-red/nodes/locales/ru/messages.json
- packages/node_modules/@node-red/nodes/locales/zh-CN/messages.json
- packages/node_modules/@node-red/nodes/locales/zh-TW/messages.json
- test/nodes/core/network/22-websocket_spec.js
Implemented support for Websocket Subprotocols [RFC 6455 section 1.9](https://datatracker.ietf.org/doc/html/rfc6455#section-1.9) in the Websocket Client node.
This change is largely based upon PR #1938 by @dpslwk, which was abandoned a couple of years ago. The main changes to the original PR are (based on the orig PR comments):
- Consequently named the var and displayed label 'subprotocol' (conforming to the RFC naming)
- Implemented a test that validates the client functionality by reading out the ws-serverside received subprotocol
This PR was also discussed at https://discourse.nodered.org/t/feature-request-websocket-sub-protocol-support/56315/4.
> Implemented support for Websocket Subprotocols in WS Client Node.

- packages/node_modules/@node-red/runtime/lib/flows/util.js
- packages/node_modules/@node-red/runtime/lib/nodes/Node.js
This adds some comprehensive logging if a call to `Node.log` itself throws an error.
That should not happen - but we have #3327 telling us it *can* happen. This logging should capture more information about the state of the node and its flow object. It will also tell us the type/id/module of the node that hit the error.
A side-effect of this PR is nodes now have a `_module` property that is information about the module that provided the node - including name and version.
> Add log logging

- packages/node_modules/@node-red/nodes/core/network/31-tcpin.html
- packages/node_modules/@node-red/nodes/core/network/31-tcpin.js
- packages/node_modules/@node-red/nodes/locales/en-US/messages.json
- test/nodes/core/network/31-tcprequest_spec.js
This PR add the TLS config option panel (used in HTTP request nodes) to the TCP nodes in both client and server modes.
It also  makes the TCP request node match the existing TCP in node capability of splitting the input when in receive Strings mode... existing is just the received Buffer or String. This now also allows to split that string on a char or sequence of chars. This then holds any remaining input until the next packet arrives and then tries to split again.
> Add TLS option to tcp client nodes

- packages/node_modules/@node-red/nodes/core/common/20-inject.js
- packages/node_modules/@node-red/nodes/core/function/90-exec.js
- packages/node_modules/@node-red/nodes/core/storage/10-file.js
This PR - tidies up the core exec, file and inject nodes to use node.debug rather than the old -v / verbose flag from settings or command line.
> Remove use of verbose flag in core nodes - and use node.debug level instead

- packages/node_modules/@node-red/editor-client/locales/en-US/editor.json
- packages/node_modules/@node-red/editor-client/src/js/ui/search.js
- packages/node_modules/@node-red/editor-client/src/sass/search.scss
Adds a history of search terms to the main search dialog. This history entries are shown if the search field is empty:
- A search term is only added to the history if one of its results is selected
- The terms are listed with most-recent at the top
- If an older term is reused, it is brought to the top of the list, rather than being duplicated
- Hovering over any entry reviews a remove button
> Add search history to main search box

- packages/node_modules/@node-red/editor-client/src/js/nodes.js
- packages/node_modules/@node-red/editor-client/src/js/ui/view.js
Note this PR builds on top of PR #3294 so shows as including that PR's commits.
With PR #3294 allowing multiple links to be selected, this PR causes links to get selected if the nodes on both ends are selected.
By highlighting the link, it can be easier to visually follow a selected flow amongst other, unconnected nodes - and also to see the full extent of the selection. This is particularly useful when using the shift-click on a node to select all of the connected nodes.
It also fixes the behaviour of shift-clicking on a node whilst ctrl/cmd is also pressed:
- Currently, ctrl/cmd-click on a node will toggle if it is selected or not - adding/removing to the existing selection
- Shift-Click selects all nodes connected to the clicked-on node - but it clears the existing selection first
- …
> Highlight links when selecting nodes

- packages/node_modules/@node-red/editor-client/src/js/ui/view.js
This PR addresses the whole 'cannot align link nodes properly' issue.
The existing logic is this:
- The existing snap-to-grid behaviour aligns the left-hand edge of nodes to the grid.
- Node widths (if the is label shown) are rounded to the nearest 20
- For the default grid size, this means regular nodes span an exact number of grid cells, so the fact the left-hand edge snaps to the grid means the right-hand edge snaps for 'free'.
- For non-default grid sizes however, it means the right-hand edge is always 'off' the grid.
- It also means for Link nodes (hidden label), where the width is not a multiple of 20, the RH edge is off grid.
With this PR, the snap-to-grid logic has been updated to snap to the nearest grid line, whether that is left or right hand edge.
This means nodes that are not …
> Snap nodes on grid using either edge as reference

- packages/node_modules/@node-red/nodes/core/parsers/70-JSON.js
- test/nodes/core/parsers/70-JSON_spec.js
Currently the JSON parse node ignores (and drops) any buffers it sees - This PR changes that behaviour to attempt to parse them as if they contain a string... (and then fails if not).
Another option is to only do this when set in always "convert to javascript object" mode. Though if we don't make that clear I'm sure someone will trip up and wonder why the difference at some point.
> Let JSON node attempt to parse buffer if it contains a valid string

- packages/node_modules/@node-red/editor-client/src/js/ui/workspaces.js
Fixes #3295
The logic around generating the name of a newly added tab was broken a while ago so you could end up with multiple tabs called `Flow 1`.
This PR fixes the logic around detecting if a candidate name already exists.
> Fix generating flow name with incrementing number

- packages/node_modules/@node-red/nodes/core/network/22-websocket.js
Fixes #3264
The WebSocket Client heartbeat interval was being setup before the socket's `open` event fired - meaning it could try to send a ping before the client connected.
This fix moves the setup of the heartbeat to the `open` event handler and adds error handling around the `ping()` call to ensure it can't error if it hits a timing window of triggering whilst the socket is closing.
> Only setup ws client heartbeat once it is connected

- packages/node_modules/@node-red/editor-client/src/js/ui/editors/expression.js
- packages/node_modules/@node-red/util/lib/util.js
Fixes #3290
The current regex used to spot if `msg` is used in a JSONata expression has been updated to ignore case where it appears as `.msg`. For example, if `msg.payload` had a property called `msg` - `msg.payload.msg`.
> Improve jsonata legacy mode detection regex

- packages/node_modules/@node-red/util/lib/events.js
Fixes #3292
If someone is running node with the `--stack_trace_limit` parameter to limit stack trace lengths, then this fix removes an assumption that the stack is at least a certain length.
It does mean we aren't able to report the location of code making a deprecated call - but nothing we can do about that if the user has chosen to limit stack sizes.
> Handle reporting error location when stack is truncated

- packages/node_modules/@node-red/editor-client/src/js/ui/clipboard.js
- packages/node_modules/@node-red/editor-client/src/sass/editor.scss
As I mentioned in #3329, the `document.execCommand("copy")` is deprecated. So, in this pull request, I used the `navigator.clipboard.writeText(value)` instead of that. Could you select #3329 or this pull request to merge?
> Fix copy buttons on the debug window (another method)

- packages/node_modules/@node-red/editor-client/src/js/ui/view.js
If a node has multiple property validation errors, the start positions of the first and remaining properties in the tooltip are not aligned as follows:
This PR try to align the beginning of the message lines.
> fix to make start of property error tooltip messages aligned

- packages/node_modules/@node-red/nodes/core/network/21-httprequest.js
Currently grunt test fails on HTTP Request node test.
This is because asynchronous API is used without specifying a callback in the process of setting a cookie.
This PR changes them to use synchronous API.
> Fix http request set cookie to use sync API

- packages/node_modules/@node-red/editor-client/locales/en-US/editor.json
- packages/node_modules/@node-red/editor-client/src/js/red.js
- packages/node_modules/@node-red/editor-client/src/js/ui/sidebar.js
- packages/node_modules/@node-red/editor-client/src/js/ui/userSettings.js
- packages/node_modules/@node-red/editor-client/src/js/ui/view.js
This PR causes the zoom level of the editor to be stored in localStorage and restored when the editor is reloaded.
It also fixes remember if the sidebar had been closed or not, and also restores the view to the last sidebar tab the user had selected.
> Remember Zoom level and Sidebar tab selection between sessions

- packages/node_modules/@node-red/editor-client/src/js/ui/common/tabs.js
Fixes #3364 
As discussed, for now, remove the close animation causing the UI glitch
The async nature of `li.one("transitionend", function(evt) {` was causing the problem.
> bug: merge issue. fixes #3364

- packages/node_modules/@node-red/editor-client/src/types/node-red/func.d.ts
- packages/node_modules/@node-red/nodes/core/function/10-function.js
- packages/node_modules/@node-red/runtime/lib/flows/util.js
- packages/node_modules/@node-red/runtime/lib/nodes/Node.js
This PR exposes a new property on the Node object - `node._path`.
This can be used to describe a node's location in the flow - in terms of what Flow/Subflow it is on.
If `node-1` is on `flow-1`, it will have a `_path` of `flow-1/node-1`
That isn't very interesting. Where it does get interesting is when subflows are involved.
Given the following configuration:
- ​`node-1` is in `subflow-1`,
- an instance of `subflow-1` has id `subflow-instance-1` and is on `flow-1`
When the runtime starts that flow, it will create `subflow-instance-1` and create an instance of `node-1` and assigned a random id - `node-instance-49876`
When debugging that node instance, having the id `node-instance-49876` isn't very useful as a user cannot relate it back to `node-1`. This is where the `_alias` property comes …
> Add _path property to nodes and expose as node.path in Function node

- packages/node_modules/@node-red/editor-api/lib/editor/projects.js
- packages/node_modules/@node-red/editor-client/locales/en-US/editor.json
- packages/node_modules/@node-red/editor-client/src/js/ui/projects/projects.js
- packages/node_modules/@node-red/runtime/lib/api/projects.js
- packages/node_modules/@node-red/runtime/lib/nodes/context/index.js
- packages/node_modules/@node-red/runtime/lib/nodes/index.js
- packages/node_modules/@node-red/runtime/lib/storage/localfilesystem/projects/index.js
- test/unit/@node-red/runtime/lib/nodes/context/index_spec.js
Whilst originally treated as a bug fix, the ongoing conversation in #3240 has made the valid point that clearing context across project switches is not always desirable.
This needs to be an optional behaviour.
> Clear context contents when switching projects

- packages/node_modules/@node-red/editor-client/src/js/ui/search.js
fixes #3297
As the file node and file in node now have different palette label to type name, the search does not reveal them.
this modification adds the palletLabel (when different to  type name) to the search index.
> Pallet Label (if different to type) should be indexed for search

- packages/node_modules/@node-red/editor-client/src/js/ui/editors/panes/appearance.js
Simply opening and closing subflow template causes subflow instances modified.
This is caused by changing icon property value from `undefined` to `""` when no icon is specified.
This PR try to fix the problem.
> fix opening/closing subflow template not to make subflow changed
