node-red/node-red

nodes/core/storage/66-mongodb.js
=> Fixed check for array in MongoDB aggregate function

nodes/core/io/22-websocket.js, test/nodes/core/io/22-websocket_spec.js
Added some unit tests for the websocket node, also fixed a bug in the current websocket node causing it not to send messages properly.
=> Websocket unit tests

nodes/core/core/89-delay.js, test/nodes/core/core/89-delay_spec.js
Found these while writing flows using the random mode of the delay node.
-Mark
=> Random delay fixes

test/nodes/core/io/22-websocket_spec.js
=> added tests for websocket-client

test/red/nodes/Node_spec.js
The test was written so that the message was never sent to n3. Also there were duplicate done() statements. The way the wires were configured in the test did not match that in practice.
=> Fixing test where part wasn't exercised

public/red/comms.js
=> Fixes bug that prevented unsubscribe from WebSockets, browser side. Fixes node-red/node-red/#562

nodes/core/core/25-catch.html, nodes/core/core/25-catch.js, red/nodes/Flow.js, red/nodes/Node.js, red/nodes/flows.js, test/red/nodes/Flow_spec.js, test/red/nodes/Node_spec.js
=> Add Catch node

nodes/core/core/58-debug.html, nodes/core/core/80-function.html, nodes/core/core/80-function.js, test/nodes/core/core/80-function_spec.js
Hello,
After reading the mailing-list : https://groups.google.com/forum/#!topic/node-red/aVeNk4SJik4
I thought of a simple way to add a Logger to the sandbox to let the user using the Logging system of Node-RED instead of the console/util.
=> Adding an Object Node to the sandbox of a function node

nodes/core/core/89-trigger.js, nodes/core/parsers/70-CSV.js, test/nodes/core/analysis/72-sentiment_spec.js, test/nodes/core/core/25-catch_spec.js, test/nodes/core/core/89-trigger_spec.js, test/nodes/core/core/98-unknown_spec.js, test/nodes/core/parsers/70-CSV_spec.js, test/nodes/core/storage/50-file_spec.js
(includes a bugfix for csv :-)
=> new tests for sentiment, file and csv nodes

Gruntfile.js, editor/index.html, editor/js/main.js, editor/js/settings.js, editor/js/ui/clipboard.js, editor/js/ui/deploy.js, editor/js/ui/editor.js, editor/js/ui/keyboard.js, editor/js/ui/library.js, editor/js/ui/menu.js, editor/js/ui/sidebar.js, editor/js/ui/subflow.js, editor/js/ui/view.js, editor/js/ui/workspaces.js, editor/js/user.js, editor/sass/header.scss, editor/sass/palette.scss, editor/sass/sidebar.scss, editor/sass/workspace.scss, editor/templates/index.mst, red/api/auth/index.js, red/api/index.js, red/api/info.js, red/api/theme.js, red/api/ui.js, test/red/api/info_spec.js, test/red/api/theme_spec.js
=> Editor Themes

nodes/core/io/21-httpin.html, nodes/core/io/21-httpin.js
Adds support to HTTP In nodes in coordination with the pull request on the node-red/node-red-node-swagger repo.
=> Added support for swagger doc to HTTP-In

red/log.js, test/red/log_spec.js
Hi Nick (and/or other guys),
I have made changes for Issue #626.  Please review.  Thanks!
=> Added the capability to register custom loggers (for Issue #626)

editor/js/comms.js, editor/js/main.js, editor/js/nodes.js, editor/js/ui/clipboard.js, editor/js/ui/deploy.js, editor/js/ui/editor.js, editor/js/ui/keyboard.js, editor/js/ui/library.js, editor/js/ui/palette.js, editor/js/ui/subflow.js, editor/js/ui/tab-info.js, editor/js/ui/view.js, editor/js/ui/workspaces.js, editor/js/user.js, locales/en-US/editor.json, locales/zz-ZZ/editor.json, locales/zz-ZZ/runtime.json
I updated the files in the editor directory (including subfolders) to remove hardcoded strings and replace with calls to RED._() using keys stored in locales/en-US/editor.json. I also added pseudo-strings in the zz-ZZ locale.
=> Updated editor code with NLS strings

editor/js/main.js, editor/js/ui/clipboard.js, editor/js/ui/editor.js, editor/js/ui/workspaces.js
For each affected module I moved the code run at module load time into a function that is then called in the module's init function to ensure that RED._ is already initialized when needed.
=> Fixed the problem where RED._ was unavailable in the module code

editor/js/ui/palette.js
Added support for custom user nodes' categories to be translated in the palette.
=> Custom nodes category NLS

nodes/core/core/20-inject.html
=> Updated Inject node info with instructions for flow and global options

Gruntfile.js, editor/js/bidi.js, editor/js/history.js, editor/js/main.js, editor/js/ui/editor.js, editor/js/ui/palette.js, editor/js/ui/tab-info.js, editor/js/ui/tabs.js, editor/js/ui/view.js, editor/js/ui/workspaces.js, red/api/locales/en-US/editor.json
Hello @knolleary,
I created a this new pull request. 
I don't know why happened with the old one #827 (it is closed now)
Anyway I think I am done with the changes now :-)
Thank you for your review
=> Enforcing Base Text Direction

Gruntfile.js, editor/js/format.js, editor/js/ui/editor.js, editor/sass/editor.scss, editor/sass/forms.scss, editor/sass/jquery.scss, nodes/core/io/23-watch.html
Hello @knolleary ,
I added support for so called Structured Text Expression or STT.
In a few words STT is a special expression (FilePath, email, URL) where Bidi engine rendering is not sufficent.
Let's assume we have a file path like C:\ABC\DEF\file.txt
where capital letters stand for Hebrew letters. 
Without special treatment the display of this path would be C:\DEF\ABC\file.txt (the deeper directory would be displayed immediately after the C:\)
These changes ensure a right display
Please not that I only tested on Firefox for now
I know there are some problems for Chrome
But before moving forward I'd like to get your feedback
Thank you very much for your review
=> Handling Structured Text expression.

nodes/core/core/80-template.html
This can be useful when using the template node to create frontends, see this post:
https://groups.google.com/d/msg/node-red/q4DKaX87Ano/Xa1mLpOdAwAJ
Thanks !
=> Add CSS hilighting to the template node

Gruntfile.js, editor/js/bidi.js, editor/js/format.js, editor/js/history.js, editor/js/main.js, editor/js/ui/editor.js, editor/js/ui/palette.js, editor/js/ui/tab-info.js, editor/js/ui/tabs.js, editor/js/ui/view.js, editor/js/ui/workspaces.js, editor/sass/editor.scss, editor/sass/forms.scss, editor/sass/jquery.scss, nodes/core/io/23-watch.html, red/api/locales/en-US/editor.json
Signed-off-by: Moshe Wajnberg <wajnberg@il.ibm.com>
=> Bidi support for Text Direction and Structured Text

editor/js/ui/editor.js, editor/sass/forms.scss, nodes/core/io/21-httpin.html, nodes/core/io/21-httprequest.html, nodes/core/io/22-websocket.html, nodes/core/storage/28-tail.html, nodes/core/storage/50-file.html
Signed-off-by: Moshe Wajnberg <wajnberg@il.ibm.com>
=> Completing STT support

editor/js/text/format.js, editor/sass/editor.scss, editor/sass/forms.scss
Signed-off-by: Moshe Wajnberg <wajnberg@il.ibm.com>
=> Fixing issue 989

editor/js/text/format.js, nodes/core/io/21-httpin.html, nodes/core/io/22-websocket.html, nodes/core/io/23-watch.html, nodes/core/storage/28-tail.html, nodes/core/storage/50-file.html
Signed-off-by: Moshe Wajnberg <wajnberg@il.ibm.com>
=> Fixing issue 1024

editor/js/ui/palette-editor.js, red/runtime/nodes/registry/localfilesystem.js
=> Palette editor fixes

nodes/core/io/31-tcpin.js
Been testing this all night with 30+ devices and it seems pretty stable now !
=> TCPGet: Last property check (hopefully)

red/runtime/index.js
so it can be turned off/on if required
=> update welcome message to use logger

red/runtime/storage/localfilesystem.js, test/red/runtime/storage/localfilesystem_spec.js
'settings' is passed in to 'savesettings', but conflicts with the closure 'settings'.  So have renamed the version passed in to newsettings.
Re-created pull request as cla signature not correct first time :(.
=> fix bug where savesettings did not honor local settings variables

red/api/locales/ja/editor.json
I created Japanese translation file(editor.json) for Node-RED Flow Editor.
=> Add Japanese translation file(editor.json)

editor/js/ui/view.js
The same calculations are computed just a few lines above, lets reuse the result :)
=> Use pre-calculated values for connection path

test/red/runtime/storage/localfilesystem_spec.js
Add a setTime between writing and reading a library entry.
Fixes #1178.
=> Add wait for writing a library entry into a file.

nodes/core/io/05-tls.js, red/runtime/settings.js, test/red/runtime/settings_spec.js
Add the node setting tlsConfigDisableLocalFiles for tls node.
Since this branch does not have tlsDisableLocalFiles setting yet (only in 0.17 branch), I just modified tls node.
=> Add the node setting tlsConfigDisableLocalFiles for tls node.

nodes/core/hardware/36-rpi-gpio.html, nodes/core/hardware/36-rpi-gpio.js, nodes/core/hardware/nrgpio.py, nodes/core/locales/en-US/messages.json
as per discussion here: 
https://groups.google.com/forum/#!topic/node-red/lLUTszA-3HQ
=> adding frequency configuration to pwm output

editor/js/nodes.js, editor/js/ui/tab-info.js, editor/js/ui/workspaces.js, red/api/locales/en-US/editor.json, red/api/locales/ja/editor.json
This is the PR for #1194
I finally chose "2" because the output is similar to subflow.
If look and feel is weird, please let me know.
(sorry, I closed the previous PR, and sent this again.)
=> Add description to flow same as subflow

editor/templates/index.mst, red/api/theme.js, test/red/api/theme_spec.js
- Look for the field 'customScript' in editorTheme (settings.js)
- Add it to mustach context
- Load list on template side (index.mst)
=> Make theme able to load custom javascript

test/nodes/core/core/75-exec_spec.js
#1178
There were mainly three problems.
1. Windows does not have "sleep" command.
1. Windows echo command cannot be spawned.
1. Windows mkdir command automatically creates non-existent directories.
I fixed those problems according to the existing test cases as much as possible.
=> Exec node for windows environment

test/nodes/core/core/89-delay_spec.js, test/nodes/core/core/89-trigger_spec.js, test/red/runtime/storage/localfilesystem_spec.js
#1226
With regard to tail node, I reconsidered how to fix but could not find out the root cause although I looked into the source code.
I have no confidence whether adding a delay fix the problem or not.  So let me skip at this time.
=> Fix the test cases which sometimes fails due to timing.

test/nodes/core/core/75-exec_spec.js
Hi @dceejay,
I fixed several error tests which occurred only on Windows environment.
I also noticed that there are two results that the payload length becomes 6 or 8 on the following test case.
"exec node calling spawn should spawn a simple command and return binary buffer"
I'm not sure the exact condition but in my environment, the payload length is 6 on Windows 7, and the one is 8 on Windows 10.
So I fixed to accept both of them.
=> Fix exec node error tests on Windows

red/api/locales/en-US/jsonata.json
I found and modified typo in English jsonata.json file while I translated it into Japanese.
=> Modify typo in jsonata.json

nodes/core/locales/en-US/messages.json, red/api/locales/en-US/jsonata.json
I modified typo and added some messages which are easy for users to understand. Could you add these messages if they are acceptable?
=> Improve editor messages (jsonata.json and messages.json)

red/api/locales/zh-CN/editor.json
My Chinese co-workers translated English messages of Node-RED editor into Chinese. This translation file will be useful for a lot of Node-RED users because Chinese is one of the most popular language in the world.
=> Add Chinese translation file (editor.json)

red/api/index.js, red/api/ui.js
=>  Fix Bug: Can not display node icon when npm package has scope (#1305)

red/runtime/storage/index.js
=> Support period characters as flow name in flow library menu

nodes/core/core/60-link.html, nodes/core/locales/en-US/messages.json
I fixed #1329 . It is needed for Chinese and Japanese support of Node-RED editor.
=> Fix column name in link nodes to refer language file

red/runtime/storage/localfilesystem.js, test/red/runtime/storage/localfilesystem_spec.js
I fixed #1324 . To test flow export case, I separated object test case into functions case and flows case.
=> Add file extension into flow name of library automatically

nodes/core/io/21-httprequest.js
=> Fix bug: Allow false and 0 in payload for httprequest (#1333)

nodes/core/core/20-inject.html, nodes/core/core/75-exec.html, nodes/core/core/80-template.html, nodes/core/core/89-delay.html, nodes/core/core/lib/debug/debug-utils.js, nodes/core/io/10-mqtt.html, nodes/core/io/21-httpin.html, nodes/core/io/31-tcpin.html, nodes/core/locales/en-US/messages.json, nodes/core/locales/ja/messages.json
Some messages in node properties don't refer to language files because English messages are in their codes. To refer to the language files, I changed the messages to variables and updated language files. Some layouts were adjusted to fit Japanese messages.
=> Modify messages in node properties to refer to messages.json

editor/js/main.js, editor/js/ui/deploy.js, editor/js/ui/diff.js, editor/js/ui/editor.js, editor/js/ui/keyboard.js, editor/js/ui/palette-editor.js, editor/js/ui/search.js, editor/js/ui/tab-info.js, editor/js/ui/userSettings.js, editor/js/user.js, nodes/core/locales/ja/messages.json, red/api/auth/index.js, red/api/locales/en-US/editor.json, red/api/locales/ja/editor.json
In Japanese and Chinese environment, Node-RED editor shows some English messages because the English  messages are hard-coded in the source code. So I changed the messages into variables to refer to language files. And some Japanese messages were improved.
=> Modify messages to refer to language files

nodes/core/core/20-inject.html, nodes/core/core/80-function.html, nodes/core/core/89-delay.html
Proposed changes to function node, inject and delay. All of which have spinners. The function node is more serious as leaving the invalid value freezes the editor - so the fix forces the number to be valid. The others just add red triangles.
To fix #1370
=> Spinner fixes

red/runtime/storage/localfilesystem.js
I fixed #1390.
When loading a library entry, getFileMeta() and getFileBody() read the file contents into a Buffer and
decode Buffer to String by toString() method.
getFileMeta()
https://github.com/node-red/node-red/blob/85392496e77050092ac2109738635968df5a8153/red/runtime/storage/localfilesystem.js#L51-L52
getFileBody() 
https://github.com/node-red/node-red/blob/85392496e77050092ac2109738635968df5a8153/red/runtime/storage/localfilesystem.js#L80-L83
If toString() method decode a buffer containing a part of multi-byte character, it can not decode correctly to String.
By executing toString() method after reading one line into a Buffer,I fixed it.
=> Fix problem with multi-byte character(#1390)

editor/js/ui/palette.js
=> Auto hide empty palette categories

nodes/core/logic/17-split.js, test/nodes/core/logic/17-split_spec.js
I fixed #1411 and added test case.
=> Fix circular reference in join node

test/nodes/core/logic/10-switch_spec.js
I added test cases for switch node to improve  the coverage.
=> Add test cases for switch node

nodes/core/core/89-trigger.html, nodes/core/logic/15-change.html, nodes/core/logic/17-split.html
Found unmatched HTML tags in node informations.
=> fixed unmatched HTML tags

test/nodes/core/core/58-debug_spec.js
Add test cases for debug node to improve the code coverage.
=> Add test cases for debug node

test/nodes/core/core/80-function_spec.js
I created test cases for function node to improve the code coverage.
In the test cases, keys() in [node context](https://github.com/kazuhitoyokoi/node-red/commit/8c6a270e80c667412844a3b2c2c51f8b68a63471#diff-9a05b775cd70a3070353c2c4bee12db0R312) and [flow context](https://github.com/kazuhitoyokoi/node-red/commit/8c6a270e80c667412844a3b2c2c51f8b68a63471#diff-9a05b775cd70a3070353c2c4bee12db0R376) return their method names only. But keys() in [global context](https://github.com/kazuhitoyokoi/node-red/commit/8c6a270e80c667412844a3b2c2c51f8b68a63471#diff-9a05b775cd70a3070353c2c4bee12db0R440) returns get, set, keys and their method names. Could you confirm if it is correct specification?
=> Add test cases for function node

nodes/core/logic/15-change.js, test/nodes/core/logic/15-change_spec.js
I fixed #1441 and added test cases for it.
I modified conditions to read global/flow context value.
=> Fix invalid from property error in change node

editor/js/ui/typeSearch.js
I fixed #1447.
I added a condition to avoid adding nodes which the blacklist constraints.
=> Fix problem in node pull-down menu when using node blacklist

red/api/locales/zh-CN/editor.json
=> clean up naming for chinese software naming convention

red/api/locales/zh-CN/infotips.json
=> Add Chinese infotips.json

nodes/core/locales/zh-CN/messages.json, red/api/locales/zh-CN/editor.json
added chinese messages.json locale file for most core nodes
=> added chinese messages.json locale file

test/nodes/core/logic/15-change_spec.js
I removed the unused variables, "var rule" in test cases of change node.
I found it while adding new test cases for change node.
=> Remove unused variables in test cases of change node

test/nodes/core/io/31-tcprequest_spec.js
There is no test script for `http request` node.
- add test script for `http request` node.
=> add test script for "tcp request" node

test/nodes/core/io/32-udpout_spec.js
There is no test script for `udp out` node.
- add test script for `udp out` node.
=> add test script for "udp out" node

test/nodes/core/io/32-udpin_spec.js
There is no test script for `udp in` node.
- add test script for `udp in` node.
=> add test script for "udp in" node

nodes/core/parsers/70-CSV.js, test/nodes/core/parsers/70-CSV_spec.js
=> Fix css template with spaces , and add test

nodes/core/core/75-exec.html, nodes/core/core/75-exec.js, test/nodes/core/core/75-exec_spec.js
=> Add rc property to exec node outputs 1 and 2

test/nodes/core/logic/15-change_spec.js
I added test cases for change node to improve the code coverage.
=> Add test cases for change node

nodes/core/core/89-trigger.js
and accept floats for delay interval.
=> clone messages before delayed send

nodes/core/core/89-trigger.html, nodes/core/core/89-trigger.js, nodes/core/locales/en-US/messages.json, test/nodes/core/core/89-trigger_spec.js
lets the trigger node treat individual topics separately - so a single node can handle multiple triggers from various topics.
=> Let trigger node support per topic mode

editor/js/main.js, editor/js/nodes.js, editor/js/ui/editor.js, editor/js/ui/utils.js, editor/sass/editor.scss, red/api/index.js, red/api/locales/en-US/editor.json, red/api/locales/ja/editor.json, red/api/nodes.js, red/api/ui.js, red/runtime/nodes/index.js, red/runtime/nodes/registry/index.js, red/runtime/nodes/registry/localfilesystem.js, red/runtime/nodes/registry/registry.js, test/red/api/nodes_spec.js, test/red/runtime/nodes/registry/localfilesystem_spec.js, test/red/runtime/nodes/registry/registry_spec.js
Issue: #1385
Trello: https://trello.com/c/PkIhjRHx/126-allow-a-nodes-icon-to-be-set-dynamically
Design memo: https://github.com/node-red/node-red/wiki/Design:-Dynamic-node's-icon
=> allow a node's icon to be set dynamically

README.md
No code change.  Make install command in README.md consistent with install instructions by adding npm --unsafe-perm option
=> add —unsafe-perm option to npm install to match documentation

test/nodes/core/io/23-watch_spec.js
Add test script for WATCH node.
=> add test for WATCH node

Gruntfile.js, package.json, test/editor/editor_helper.js, test/editor/specs/editor_spec.js, test/editor/wdio.conf.js
Add ui test automation for Node-RED.
`grunt test-ui` runs the basic ui test.
Although I wanted to switch between headless and non-headless browser with Gruntfile setting, need more investigation.
Please let me pass it to a later task.
=> first step of ui test automation

nodes/core/core/80-template.html, nodes/core/core/80-template.js, red/api/auth/index.js, test/nodes/core/core/80-template_spec.js
=> enable template config via msg.template for stored or generated templates

nodes/core/parsers/70-CSV.js, test/nodes/core/parsers/70-CSV_spec.js
Make CSV node to produce parts property like split node.
This allows messages extracted by CSV node processed
as a group.
=> add parts support for CSV node

red/api/locales/zh-CN/jsonata.json
Add Chinese translation of jsonata.json.
The translation has been peer reviewed and revised.
=> Add Chinese translation of jsonata.json

test/red/api/editor/index_spec.js
=> Fix the error occuring during permission check

red/runtime/nodes/credentials.js
=> Fix the errors in credentials test cases

red/runtime/settings.js
=> Fix the property "users" access error in runtime.start test caces

test/red/runtime/storage/localfilesystem/library_spec.js
=> Fix the error that "otherwise is not a function"

nodes/core/core/80-function.html, nodes/core/core/80-template.html, nodes/core/logic/10-switch.html
add italic style to labels when using names - function, template and  switch node
=> ensure core node labels are italic when named

editor/js/main.js, editor/js/ui/projects.js, red/api/editor/projects/index.js, red/runtime/storage/localfilesystem/projects/Project.js, red/runtime/storage/localfilesystem/projects/index.js
=> Support to delete project feature

test/editor/pageobjects/workspace/debugTab_page.js, test/editor/pageobjects/workspace/editWindow_page.js, test/editor/pageobjects/workspace/node_page.js, test/editor/pageobjects/workspace/workspace_page.js, test/editor/specs/editor_spec.js, test/editor/wdio.conf.js
I created page objects so that a developer does not need to use browser object directly.
A developer can write a test script as one line for one action.
=> [UI test] Split test script into scenario and browser operation

editor/js/ui/projectUserSettings.js, editor/js/ui/projects.js, editor/sass/projects.scss, package.json, red/api/editor/index.js, red/api/editor/sshkeys.js, red/runtime/storage/index.js, red/runtime/storage/localfilesystem/index.js, red/runtime/storage/localfilesystem/projects/Project.js, red/runtime/storage/localfilesystem/projects/git/authServer.js, red/runtime/storage/localfilesystem/projects/git/index.js, red/runtime/storage/localfilesystem/projects/index.js, red/runtime/storage/localfilesystem/sshkeys.js, test/red/api/editor/sshkeys_spec.js, test/red/runtime/storage/localfilesystem/sshkeys_spec.js
=> SSH key management & Git access via SSH

editor/sass/editor.scss, editor/sass/notifications.scss
=> Open Project: prompt if workspace is dirty

nodes/core/io/21-httprequest.js
- [x ] New feature (non-breaking change which adds functionality)
This small change allows the HTTP Request node to work with WebDav by allowing PROPFIND and PROPPATCH methods to include the payload. …
=> HTTP REQUEST: Adding PROPPATCH and PROPFIND http methods

package.json, red/runtime/storage/localfilesystem/projects/index.js, red/runtime/storage/localfilesystem/projects/ssh.js, red/runtime/storage/localfilesystem/sshkeys.js, test/red/runtime/storage/localfilesystem/sshkeys_spec.js
=> Refactoring ssh-keygen function

editor/js/ui/projects.js, nodes/core/core/58-debug.html, nodes/core/core/lib/debug/debug-utils.js, nodes/core/core/lib/debug/debug.js
=> Clear debug message when switching projects

nodes/core/core/20-inject.html, nodes/core/core/20-inject.js, nodes/core/locales/en-US/messages.json, test/nodes/core/core/20-inject_spec.js
as we discussed in slack here is the PR with unit tests
=> Inject node - let once delay be editable

nodes/core/parsers/70-CSV.html, nodes/core/parsers/70-CSV.js, test/nodes/core/parsers/70-CSV_spec.js
Also fixes up msg.parts appropriately
=> Add skip first n lines capability to csv node

nodes/core/io/32-udp.js
=> tag UDP ports in use properly so they get closed correctly

package.json, red/api/auth/index.js
Addressing `express-session` memory leak #1434
=> add express-session memorystore without leaks

nodes/core/core/75-exec.html
The exec node info tab is missing a description of the Timeout field. The PR adds that.
=> Add description of Timeout field in exec node info tab

nodes/core/locales/en-US/messages.json
Add missing CSV node messages for new skip lines option
=> add missing CSV node messages

nodes/core/locales/en-US/messages.json, nodes/core/logic/18-sort.html, nodes/core/logic/18-sort.js, settings.js, test/nodes/core/logic/18-sort_spec.js
change UI of SORT node to make configuration more easily understood.
```
[{"id":"a695ff46.aa8be","type":"tab","label":"Sort Property","disabled":false,"info":""},{"id":"56fe41c.46feec","type":"tab","label":"Sort …
```
=> update UI for SORT node

nodes/core/logic/10-switch.html
An useless logging code was left in `10-switch.html`.
Removed it.
(I'm sorry for leaving the code.)
=> remove useless logging code

editor/js/ui/editor.js
I added a button to reset a user defined icon which exists on node settings tab in an edit node window.
=> Add a button to reset user defined icon

nodes/core/logic/10-switch.html, nodes/core/logic/10-switch.js, nodes/core/logic/17-split.html, nodes/core/logic/17-split.js, nodes/core/logic/18-sort.html, nodes/core/logic/18-sort.js, nodes/core/logic/19-batch.html, nodes/core/logic/19-batch.js, settings.js, test/nodes/core/logic/10-switch_spec.js, test/nodes/core/logic/17-split_spec.js, test/nodes/core/logic/18-sort_spec.js, test/nodes/core/logic/19-batch_spec.js
reduce `{switch,join,sort,batch}MaxKeptMsgsCount` property of `settings.js` to one `maxKeptMsgsCount`.
=> reduce *MaxKeptMsgsCount to one maxKeptMsgsCount

nodes/core/analysis/72-sentiment.html, nodes/core/analysis/72-sentiment.js, nodes/core/locales/en-US/messages.json, nodes/core/logic/16-range.html, nodes/core/logic/16-range.js, nodes/core/parsers/70-JSON.html, nodes/core/parsers/70-XML.html, nodes/core/parsers/70-XML.js, nodes/core/parsers/70-YAML.html, nodes/core/parsers/70-YAML.js, test/nodes/core/analysis/72-sentiment_spec.js, test/nodes/core/parsers/70-XML_spec.js, test/nodes/core/parsers/70-YAML_spec.js
Add select for msg property for several core nodes, 
yaml, xml, range, sentiment
add tests
=> Add property select to various core nodes

editor/js/ui/projects/projects.js
A user cannot go forward on the introduction page of projects if the user does not set git account.
=> Fix the problem when using projects feature without git setting

nodes/core/core/20-inject.html, nodes/core/core/20-inject.js, nodes/core/locales/en-US/messages.json
to close #1406
perform better validation / truncation of input for crontab,
adjust spacing on page to be less cramped/more aligned
=> remove inject node at specific time spinner

nodes/core/logic/10-switch.js, test/nodes/core/logic/10-switch_spec.js
While adding test cases for SWITCH updates, found some bugs in updates.
- application of *repair sequence* flag,
- *parts* property reconstruction.
=> fix bugs in SWITCH updates

editor/js/ui/projects/projects.js
On the `Create Project` dialog, even if I set `Encryption key`, the project does not encrypt a credential file.
This does not occur at the first time (on the introduction dialog).
=> Fix the problem that does not encrypt credential file

red/api/editor/locales/en-US/jsonata.json, red/api/editor/locales/ja/jsonata.json
I updated both English and Japanese messages in jsonata.json as follows.
- Add quotation marks for variables in English jsonata.json
- Remove unnecessary empty line in English jsonata.json
- Add Japanese translations
=> Update messages in jsonata.json

nodes/core/core/89-delay.html, nodes/core/logic/19-batch.html
This PR fixes small typos in info text of DELAY node and BATCH node.
=> Fix typo in info text

nodes/core/locales/ja/messages.json
This PR corrects a minor typo in Japanese message catalog.
=> fix typo in Japanese message catalog

editor/js/ui/editor.js
=> Disable user defined icon for subflow

red/runtime/nodes/index.js
Installation of a new node fails with following errror:
```
3 Mar 15:10:33 - [info] Installing module: null, version: 2.8.2
3 Mar 15:10:35 - [warn] Installation of module null failed:
3 Mar 15:10:35 - [warn] ------------------------------------------
3 Mar 15:10:35 - [warn] npm ERR! code ETARGET
npm ERR! notarget No matching version found for null@2.8.2
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xyz/.npm/_logs/2018-03-03T06_10_35_281Z-debug.log
3 Mar 15:10:35 - [warn] ------------------------------------------
```
=> fix failure of node installation

nodes/core/locales/ja/hardware/36-rpi-gpio.html
Translate RPI gpio nodes into Japanese.
Please merge this pull request after merging #1657.
=> Translate rpi-gpio node

nodes/core/locales/zh-CN/messages.json, red/api/editor/locales/zh-CN/editor.json
Full Chinese translations, maching the en-US, for the core nodes.
=> Chinese translations for core nodes

nodes/core/core/80-function.js, test/nodes/core/core/80-function_spec.js
- [ x] New feature (non-breaking change which adds functionality)
Adds node.deb and node.trace to function node so they can be called if needed.
- [ x] I have read the [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md)
- [ x] For non-bugfix PRs, I have discussed this change on the mailing list/slack team.
- [x ] I have run `grunt` to verify the unit tests pass
- [ x] I have added suitable unit tests to cover the new/changed functionality
=> add-debug-and-trace-to-function

nodes/core/io/21-httprequest.html, nodes/core/io/21-httprequest.js
Prevent Following Redirect #615
=>  Prevent Following Redirect (#615)

red.js, settings.js
=> update settings comments to describe how to setup for ipv6

nodes/core/core/80-function.js
Also pass the error in msg so that it can be handled in flows.handleError
=> better script error handling.

nodes/core/locales/ja/messages.json
This PR update Japanese message catalogue of core nodes in order to adapt node changes.
=> Japanese message catalogue update

nodes/core/core/80-function.html, nodes/core/core/80-function.js, test/nodes/core/core/80-function_spec.js
This PR adds a feature that allows function node code to access id and name of the node.
=> Allow id and name reference in function node code

nodes/core/io/10-mqtt.html
=> typo fix *hierarchy

editor/js/ui/projects/projectUserSettings.js, red/api/editor/locales/en-US/editor.json, red/api/editor/locales/ja/editor.json
I translated a project user setting function into Japanease.
=> add translate-user-settings

test/editor/pageobjects/workspace/debugTab_page.js
The id of tab interface was changed with this commit (red-ui-tab-link-buttons).  So I followed the change for UI test.
https://github.com/node-red/node-red/commit/a4eb8e11c3df0805ef347eb14ba4c77674638b47
=> Follow the change of tab interface for UI test

test/editor/pageobjects/nodes/core/core/20-inject_page.js
Fixed UI test to follow the change of typed input interface.
https://github.com/node-red/node-red/commit/461e6562ca4309937e9de5083d8ea736adfba93a
=> Follow the change of typedinput interface for UI test

nodes/core/logic/15-change.js, red/runtime/util.js, test/nodes/core/logic/15-change_spec.js
Switch node of current 0.19 branch fails to set/get values to/from persistable store.
=> Fix persistable context handling of switch node

red/api/editor/locales/en-US/editor.json, red/api/editor/locales/ja/editor.json
I updated Japanese language file, editor.json.
Simultaneously, I removed unnecessary lines and changed order in both files to be same.
=> Update Japanese language file (editor.json)

test/editor/pageobjects/nodes/core/core/20-inject_page.js, test/editor/pageobjects/util/spec_util_page.js, test/editor/pageobjects/workspace/workspace_page.js, test/editor/specs/scenario/cookbook_uispec.js, test/editor/wdio.conf.js
I created ui test cases for flow control on cookbook.
Changed the target branch of previous PR from master to 0.19.
=> Added test cases of flow control on cookbook

test/nodes/core/core/20-inject_spec.js, test/nodes/core/logic/15-change_spec.js
I added test cases of persistable context for inject node.
Because I found that there is wrong name in change node, I modified the name in the same pull request.
=> Add test cases of persistable context for inject node

red/runtime/nodes/context/memory.js, test/red/runtime/nodes/context/memory_spec.js
When an error occurred in accessing memory, the callback is called twice.
I fixed it and added test cases.
=>  Prevent the callback to be called twice

nodes/core/locales/ja/messages.json, red/api/editor/locales/ja/jsonata.json
I updated Japanese language files, messages.json and jsonata.json.
=> Update Japanese language files (messages.json and jsonata.json)

test/nodes/core/core/20-inject_spec.js, test/nodes/core/core/89-trigger_spec.js, test/nodes/core/logic/15-change_spec.js
I added test case of persistable context for trigger node.
And I changed order of initialization and closing procedures in test cases for inject and change nodes because I think that error sometimes occurs because of async functions.
=> Add test cases of persistable context for trigger node

test/nodes/core/core/20-inject_spec.js
This PR add test cases for accessing multiple persistable stores.
(see https://github.com/node-red/node-red/pull/1807 for details)
=> Add multiple persistable store tests for inject node

test/nodes/core/core/89-trigger_spec.js
This PR add test cases for accessing multiple persistable stores.
(see https://github.com/node-red/node-red/pull/1807 for details)
=> Add multiple persistable store tests for trigger node

nodes/core/core/80-template.html, nodes/core/core/80-template.js, test/nodes/core/core/80-template_spec.js
This PR add support of new persistable context support (e.g. `{{flow[store].name}}`) to **template** node.
=> Add support of persistable context to template node

test/nodes/core/core/80-function_spec.js
Current unit test for function node does not include tests for new persistable context.
This PR add tests for persistable context.
=> Add persistable context tests for function node

test/nodes/core/core/20-inject_spec.js
Current unit test of `inject` node lacks support of some input types (e.g. num, env, ...).
This PR add tests for these typese.
=> Add test cases for inject node

nodes/core/logic/15-change.js, test/nodes/core/logic/15-change_spec.js
I fixed the ReferenceError that occurs when getting invalid `fromValue` in change node.
And added a test case
=> Fix the ReferenceError in change node

test/red/runtime/nodes/context/index_spec.js
This PR covers several test cases for index.js of context.
=> Add test cases for index.js of context

test/editor/pageobjects/nodes/core/core/20-inject_page.js, test/editor/pageobjects/nodes/core/core/80-function_page.js, test/editor/pageobjects/nodes/core/core/80-template_page.js, test/editor/pageobjects/nodes/core/io/21-httpin_page.js, test/editor/pageobjects/nodes/core/io/21-httprequest_page.js, test/editor/pageobjects/nodes/core/io/21-httpresponse_page.js, test/editor/pageobjects/nodes/core/logic/15-change_page.js, test/editor/pageobjects/nodes/core/parsers/70-HTML_page.js, test/editor/pageobjects/nodes/nodefactory_page.js, test/editor/specs/scenario/cookbook_uispec.js
I created ui test cases for `HTTP requests` on cookbook.
=> Add UItest for http request

test/red/runtime/nodes/context/memory_spec.js
Add test cases for memory context.
=> Add test cases for memory context

red/api/editor/locales/ja/editor.json
We updated Japanese language files(editor.json).
=>  Update Japanese translation (editor.json)

red/runtime/nodes/context/localfilesystem.js, test/red/runtime/nodes/context/localfilesystem_spec.js
This PR covers several test cases for localfilesystem.js of context.
=> Add test cases for localfilesystem context

nodes/core/locales/ja/io/21-httprequest.html, nodes/core/locales/ja/parsers/70-JSON.html
I updated Japanese info of JSON and HTTP Request node.
=>  Update Japanese info text of JSON and HTTP Request node

test/nodes/core/storage/50-file_spec.js
Current unit test for file node does not check output message.
This PR add check of output messages.
=> Update test for file node for new output port

test/nodes/core/logic/10-switch_spec.js, test/nodes/core/logic/15-change_spec.js
We fixed and added test cases of switch and change node for persistable context.
=> Fix and add test cases for persistable context

red/runtime/locales/ja/runtime.json
This PR update Japanese message catalogue of runtime.json.
=> Update Japanese message catalogue of runtime.json

red/runtime/util.js, test/red/runtime/util_spec.js
Deleted unnecessary condition.
Added tests for runtime util.
=> Add tests for runtime util

test/nodes/core/io/21-httprequest_spec.js, test/nodes/core/storage/50-file_spec.js, test/red/runtime/nodes/registry/installer_spec.js, test/red/runtime/storage/localfilesystem/projects/ssh/index_spec.js
Fixed test cases on windows and under proxy environment.
1. In some environment, when sending a request to localhost, proxy server blocked the connection.  Using no_proxy can avoid this problem.
2. One test case for file node failed only on windows.  So skipped it.
3. It takes much time to test several test cases on windows than linux.  So extended the time limit.
=> Fix test cases on windows and under proxy

test/editor/pageobjects/nodes/core/core/20-inject_page.js, test/editor/pageobjects/nodes/core/storage/50-filein_page.js, test/editor/pageobjects/nodes/nodefactory_page.js, test/editor/pageobjects/workspace/palette_page.js, test/editor/specs/scenario/cookbook_endpoint_uispec.js, test/editor/specs/scenario/cookbook_uispec.js, test/resources/file-in-node/test.txt
Added tests for http endpoints on cookbook.
This PR depends on the PR of #1846.  After merged #1846, all tests will be passed.
=> Add UItest for http endpoints

nodes/core/io/31-tcpin.js, test/nodes/core/io/31-tcprequest_spec.js
- Added some more checks around this.
- We're choosing to only use the latest message when sending, which is
effectively what was happening before the queue implementation.
Fixes issue reported in #1863.
=> fix lost messages / properties in TCPRequest Node; closes #1863

nodes/core/core/80-function.js
* added some semicolons
* removed double parsing of ```err.stack``` into ```var stack```
* JavaScript linting improvement
* removed double split on ```var stack = err.stack.split```
=> fixed some linting issues

package.json, test/editor/pageobjects/editor/palette_page.js, test/editor/pageobjects/nodes/core/io/10-mqttconfig_page.js, test/editor/pageobjects/nodes/core/io/10-mqttin_page.js, test/editor/pageobjects/nodes/core/io/10-mqttout_page.js, test/editor/pageobjects/nodes/core/parsers/70-JSON_page.js, test/editor/pageobjects/nodes/nodefactory_page.js, test/editor/specs/scenario/cookbook_mqtt_uispec.js
Added UI testing code for MQTT scenarios on cookbook.
This scenario runs MQTT broker using mosca package to communicate between mqtt-out node and mqtt-in node.
=> Add UI testing code for MQTT node

editor/js/ui/projects/tab-versionControl.js, red/api/editor/locales/en-US/editor.json, red/api/editor/locales/ja/editor.json
This PR replaces remaining raw string reference in projects feature by message catalogue reference.
=> Fix message catalogue for projects 

nodes/core/hardware/nrgpio.py
* __raw_input()__ was removed in Python 3 in favor of __input()__
* Fix __sleep()__ to match the import on line 22
[flake8](http://flake8.pycqa.org) testing of https://github.com/node-red/node-red on Python 3.7.0
$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./nodes/core/hardware/nrgpio.py:45:24: F821 undefined name 'raw_input'
data = raw_input()
^
./nodes/core/hardware/nrgpio.py:63:24: F821 undefined name 'raw_input'
data = raw_input()
^
./nodes/core/hardware/nrgpio.py:85:24: F821 undefined name 'raw_input'
data = raw_input()
^
./nodes/core/hardware/nrgpio.py:120:24: F821 undefined name 'raw_input'
data = raw_input()
^
./nodes/core/hardware/nrgpio.py:134:24: F821 undefined name 'raw_input'
data = raw_input()
^ …
```
=> Define raw_input() in Python 3 & fix time.sleep()

editor/js/ui/utils.js, editor/js/ui/view.js, nodes/99-sample.html.demo
=> Fix node color bug

red/runtime/nodes/context/localfilesystem.js
This PR is work in progress.
This fixes following problems of #1888 :
=> Prevent race condition

nodes/core/io/21-httprequest.js, test/nodes/core/io/21-httprequest_spec.js
As we discussed, we prohibit http-request node from sending cookies to the different domain when redirected using cookiejar.
=> Prohibit http-request node from sending cookies to the different domain when redirected

test/red/api/editor/settings_spec.js
To improve code coverage, I added test cases for red/api/editor/settings.js.
=> Add test cases for red/api/editor/settings.js

packages/node_modules/@node-red/nodes/core/io/22-websocket.js, packages/node_modules/@node-red/nodes/core/io/23-watch.html, packages/node_modules/@node-red/nodes/core/io/23-watch.js, packages/node_modules/@node-red/nodes/core/logic/17-split.html, packages/node_modules/@node-red/nodes/core/logic/17-split.js, packages/node_modules/@node-red/nodes/core/storage/50-file.js, test/nodes/core/io/22-websocket_spec.js, test/nodes/core/storage/50-file_spec.js
A few small node tidy ups 
- watch node - also pass filename out as msg.filename - so can feed direct into file in node
- file in node - remove \n \r from any passed in filename - (often occurs if using exec node to ls a bunch of files)
- join node - don't send on reset of array (thought was already fixed... but not in dev)
- websocket out - don't send out "hidden" _session property when sending whole msg (like we don't send out _msgid). 
Done as separate commits so can be cherry picked if required.
=> Tidy core nodes

settings.js
=> Add missing comma

test/unit/@node-red/editor-api/lib/editor/theme_spec.js
To improve code coverage, I updated test cases in theme_spec.js.
=> Update test cases in theme_spec.js

packages/node_modules/@node-red/editor-client/locales/ja/editor.json
I added Japanese messages into editor.json and fixed typo.
=> Update Japanese message catalog

package.json, test/editor/editor_helper.js, test/editor/pageobjects/editor/workspace_page.js, test/editor/pageobjects/nodes/core/core/58-debug_page.js, test/editor/pageobjects/nodes/core/logic/15-change_page.js, test/editor/specs/scenario/cookbook_endpoint_uispec.js
As UI test did not run correctly after runtime and editor were split, I fixed the problem.
Somehow mosca in devDependencies was removed from package.json, I added it again.
=> Followed runtime-editor split for UI test

test/editor/pageobjects/editor/workspace_page.js, test/editor/specs/editor/workspace_uispec.js, test/editor/specs/scenario/cookbook_endpoint_uispec.js, test/editor/specs/scenario/cookbook_mqtt_uispec.js, test/editor/specs/scenario/cookbook_uispec.js
In the UI testing, nodes can be automatically deployed when omitting the coordinate.  Now you can simply call `workspace.addNode` again and again without specifying the coordinate.
We will update design notes after merged this PR.
=> Automatically adjust node deployment

packages/node_modules/@node-red/nodes/core/io/32-udp.js
Re-arranges the udp node to bind the socket more appropriately, and then share it between in and out sides. Should make sending and receiving multicast more reliable. (before one side may have grabbed the port and then either not shared it (not made messages available)  - or would bind the wrong port (but report it bound the correct one).
Also added some status so when using bind to interface it reports the ip used on that interface so you can check it's correct.
=> Udp node socket binding fixes

test/editor/editor_helper.js, test/editor/pageobjects/editor/debugTab_page.js, test/editor/pageobjects/editor/workspace_page.js, test/editor/pageobjects/nodes/core/core/80-function_page.js, test/editor/pageobjects/nodes/core/core/80-template_page.js, test/editor/pageobjects/nodes/node_page.js, test/editor/pageobjects/util/util_page.js, test/editor/specs/editor/workspace_uispec.js, test/editor/specs/scenario/cookbook_endpoint_uispec.js, test/editor/specs/scenario/cookbook_mqtt_uispec.js, test/editor/specs/scenario/cookbook_uispec.js, test/editor/wdio.conf.js
Fixed UI test problems caused by timing.
=> Fixed UI test problems caused by timing

packages/node_modules/@node-red/editor-client/locales/en-US/editor.json, packages/node_modules/@node-red/editor-client/locales/ja/editor.json, packages/node_modules/@node-red/editor-client/src/js/red.js
This PR updates Japanese message catalogue for Node-RED editor of current dev code.
Also adds support of i18n for projects menu of Node-RED editor.
=> Update message catalog for Node-RED editor

packages/node_modules/@node-red/editor-client/locales/ja/editor.json, packages/node_modules/@node-red/nodes/locales/ja/messages.json
With recent changes to dev branch, some Japanese message text are missing in the catalogue according to i18n page.  Added translation of these texts.
=> Update Japanese message catalogue

packages/node_modules/@node-red/nodes/core/io/21-httprequest.js, packages/node_modules/@node-red/nodes/locales/en-US/io/21-httprequest.html, packages/node_modules/@node-red/nodes/locales/ja/io/21-httprequest.html, test/nodes/core/io/21-httprequest_spec.js
I added `redirectList` property in msg of http-request node.
The data looks as follows.  In this example, host2 does not return any cookies.
```
[
{
"location":"http://host1/redirectTo1",
"cookies":{
"key1-1":{"Path":"/","value":"value1-1"},
"key1-2":{"Path":"/","value":"value1-2"}
}
},
{
"location":"http://host2/redirectTo2"
},
{
"location":"http://host3/return",
"cookies":{
"key3-1":{"Path":"/","value":"value3-1"},
"key3-2":{"Path":"/","value":"value3-2"}
}
}
]
```
=>  Add redirectList property in msg of http-request node

editor/js/ui/library.js
=> Export to library produces empty folder when name has a trailing slash

packages/node_modules/@node-red/editor-client/locales/en-US/editor.json, packages/node_modules/@node-red/editor-client/locales/en-US/jsonata.json, packages/node_modules/@node-red/editor-client/locales/ja/editor.json, packages/node_modules/@node-red/runtime/locales/ja/runtime.json
I added Japanese translation and fixed typo in the Japanese message catalog.
I also removed unnecessary lines from English message catalog.
=> Update message catalog

packages/node_modules/@node-red/registry/lib/util.js
`RED.require` fails with following error:
```
ReferenceError: registry is not defined
```
=> Fix RED.require

packages/node_modules/@node-red/nodes/core/io/22-websocket.html, packages/node_modules/@node-red/nodes/locales/en-US/io/22-websocket.html
=> Fix bug in WebSocket configuration node

Gruntfile.js, package.json
#1629
Remove chromedriver package from devDependencies, and instruct how to install it when running `grunt test-ui`.
I will update a related design note once this PR was merged.
By the way, as I had to freeze my previous account, I will contribute with this account from now.
=> Remove chromedriver from devDependencies

packages/node_modules/@node-red/editor-client/locales/en-US/editor.json, packages/node_modules/@node-red/editor-client/locales/ja/editor.json, packages/node_modules/@node-red/editor-client/src/js/nodes.js, packages/node_modules/@node-red/editor-client/src/js/ui/editor.js, packages/node_modules/@node-red/editor-client/src/js/ui/subflow.js, packages/node_modules/@node-red/nodes/core/core/80-function.js, packages/node_modules/@node-red/nodes/core/logic/15-change.js, packages/node_modules/@node-red/runtime/lib/nodes/Node.js, packages/node_modules/@node-red/runtime/lib/nodes/flows/Flow.js, packages/node_modules/@node-red/runtime/lib/nodes/flows/Subflow.js, packages/node_modules/@node-red/util/lib/util.js, test/nodes/subflow/subflow_spec.js, test/unit/@node-red/runtime/lib/nodes/flows/Subflow_spec.js
This PR add support of *SUBFLOW environment variable* support described in *SUBFLOW Enhancements* design note (https://github.com/node-red/node-red/wiki/Design%3A-Subflow-Enhancements).
=> Add support of subflow env var

packages/node_modules/@node-red/editor-client/src/js/ui/subflow.js
=>  Fix direction value of subflow output

packages/node_modules/@node-red/nodes/locales/ja/messages.json
This PR updates Japanese message catalogue of nodes.
=> Update Japanese message catalogue of core nodes

packages/node_modules/@node-red/editor-client/src/js/ui/library.js
=> Fix module name bug in import menu

packages/node_modules/@node-red/nodes/locales/en-US/io/21-httprequest.html, packages/node_modules/@node-red/nodes/locales/ja/io/21-httprequest.html
This PR updates Japanese info text of `httprequest` node in order to follow recent update of English info text.
Also fixed unmatched HTML tag.
=> Update info text of httprequest node

packages/node_modules/@node-red/nodes/locales/ja/io/21-httprequest.html
This PR fixes a minor typo in Japanese info text of `httprequest` node.
=> Fix typo in Japanese info text of httprequest node

packages/node_modules/@node-red/nodes/core/core/80-function.html
Removes unnecessary ternary operation.
=> Remove unnecessary ternary

packages/node_modules/@node-red/nodes/locales/ja/messages.json
This PR update Japanese message catalogue for nodes.
=> update Japanese message for nodes

packages/node_modules/@node-red/editor-client/locales/ja/editor.json
This PR update Japanese message catalogue for Node-RED editor.
=> Update Japanese message catalogue for editor

packages/node_modules/@node-red/editor-client/src/js/ui/editor.js, packages/node_modules/@node-red/editor-client/src/js/ui/subflow.js
This PR rearranges location of some UI items (category setting and instance count
message) of SUBFLOW template properties tab according to discussion on https://github.com/node-red/node-red/pull/2196 .
=> Rearrange subflow tab items

packages/node_modules/@node-red/editor-client/src/js/ui/editor.js
Fixed undefined node._def error when using a custom type editor.
=> Handle undefined node._def in edit stack title.

packages/node_modules/@node-red/nodes/core/logic/10-switch.html, packages/node_modules/@node-red/nodes/core/logic/15-change.html
The variable, `ruleset` in both switch and change node seems not to be used. Therefore, I removed it.
=> Remove unused variable

packages/node_modules/@node-red/editor-client/locales/ko/editor.json, packages/node_modules/@node-red/nodes/locales/ko/messages.json
There are some unused entries in KO message catalogue.
This PR removes them from the message catalogue.
=> remove unused entries in KO message catalogue

packages/node_modules/@node-red/editor-client/locales/ja/editor.json, packages/node_modules/@node-red/nodes/locales/ja/messages.json
This PR update Japanese message catalogue for missing entries.
=> Update JP message catalogue

packages/node_modules/@node-red/editor-client/src/js/user.js
Add css class `red-ui-button` to login submit button (Issue #2275)
=> Add css class to login submit button

packages/node_modules/@node-red/editor-client/locales/en-US/editor.json, packages/node_modules/@node-red/editor-client/locales/ja/editor.json, packages/node_modules/@node-red/editor-client/src/js/ui/projects/projectSettings.js, packages/node_modules/@node-red/editor-client/src/js/ui/tab-info.js
I updated i18n support for project feature.
=> Update i18n for project feature

packages/node_modules/@node-red/nodes/locales/ja/function/16-range.html
This PR updates Japanese info text of range node in response to original English info text.
=> update Japanese info text of range node

packages/node_modules/@node-red/nodes/locales/en-US/function/80-template.html
Response JSON has invalid comma, so I removed it.
=> Remove unnecessary comma.

packages/node_modules/@node-red/editor-client/src/js/ui/palette-editor.js
Fixes the overlap (shown in the screenshots) of the search box in `Palette Editor > Install` by the div below it.
=> Fix palette editor search visualization

packages/node_modules/@node-red/editor-api/lib/index.js, packages/node_modules/@node-red/editor-client/src/js/ui/editor.js
=> Fixed jsdoc descriptions

packages/node_modules/@node-red/nodes/core/parsers/70-CSV.js
=> Fixed the code format of 70-CSV.js from Tab to Space. try again.

packages/node_modules/@node-red/nodes/core/network/31-tcpin.js
=> Removed unused variable "remoteDetails"

packages/node_modules/@node-red/runtime/lib/nodes/Node.js
=> Remove msg

packages/node_modules/@node-red/editor-client/locales/ja/jsonata.json
This PR update Japanese message catalogue for JSONata following recent update of JSONata (https://github.com/node-red/node-red/pull/2340).
=> Update Japanese JSONata message catalogue

packages/node_modules/@node-red/editor-api/lib/admin/nodes.js, packages/node_modules/@node-red/editor-client/src/js/ui/palette-editor.js, packages/node_modules/@node-red/registry/lib/installer.js, packages/node_modules/@node-red/runtime/lib/api/nodes.js, packages/node_modules/@node-red/runtime/lib/nodes/index.js, test/unit/@node-red/editor-api/lib/admin/nodes_spec.js, test/unit/@node-red/registry/lib/installer_spec.js
This PR proposes the addition of more convenient and simple functions for node installation from other than public site.
Details are written in [design note](https://github.com/node-red/designs/blob/master/designs/node-installation/node-installation.md).
=> Add node installation from other than public site

packages/node_modules/@node-red/runtime/lib/storage/localfilesystem/projects/index.js, packages/node_modules/@node-red/runtime/lib/storage/localfilesystem/util.js, test/unit/@node-red/runtime/lib/storage/localfilesystem/index_spec.js
Allows flowFile to be specified as a UNC path in windows.
In localstorage, calls fs.ensureDir before writing a file, avoiding errors where a folder does not exist.
=> flows file absolute path plus non-existent folder creation.

packages/node_modules/@node-red/nodes/locales/ja/network/10-mqtt.html
This PR updates Japanese info text of MQTT out node according to changes on original English info text(https://github.com/node-red/node-red/commit/aa6c0b9d6e8b5601b22d543c700ead9166f10903).
Also fixes some typos.
=> Update Japanese info text of mqtt out node

test/editor/editor_helper.js, test/editor/pageobjects/editor/palette_page.js, test/editor/pageobjects/editor/workspace_page.js, test/editor/pageobjects/nodes/core/core/20-inject_page.js, test/editor/pageobjects/nodes/core/core/58-debug_page.js, test/editor/pageobjects/nodes/core/io/10-mqttconfig_page.js, test/editor/pageobjects/nodes/core/io/21-httpin_page.js, test/editor/pageobjects/nodes/core/logic/15-change_page.js, test/editor/pageobjects/nodes/core/storage/50-filein_page.js, test/editor/pageobjects/nodes/node_page.js, test/editor/pageobjects/nodes/nodefactory_page.js, test/editor/specs/editor/workspace_uispec.js, test/editor/specs/scenario/cookbook_endpoint_uispec.js, test/editor/specs/scenario/cookbook_uispec.js, test/editor/wdio.conf.js
I fixed test cases that fail in UI testing. And I added some adjustments for them.
=> Fix test cases for UI

packages/node_modules/@node-red/editor-api/lib/editor/index.js
Implements the proposed fix described in #2418.
=> Fixes the routes described in #2418

test/editor/pageobjects/editor/workspace_page.js
fix Issue #2407 "UI-test: memory leak. runtime-deploy event in deploy() "
when call event. remove runtime event.
=> UI-test: fix memory leak. runtime-deploy event in deploy()

packages/node_modules/@node-red/nodes/core/network/21-httprequest.html
HEAD should be selectable as method. Discussion was going on here:
https://discourse.nodered.org/t/http-head-request/21136/4
=> Add HEAD as Method

packages/node_modules/@node-red/editor-client/src/js/nodes.js, packages/node_modules/@node-red/editor-client/src/js/ui/editor.js, packages/node_modules/@node-red/editor-client/src/js/ui/subflow.js, packages/node_modules/@node-red/runtime/lib/api/flows.js, packages/node_modules/@node-red/runtime/lib/nodes/credentials.js, packages/node_modules/@node-red/runtime/lib/nodes/flows/Subflow.js
This introduces the ability to identify any subflow env property as a credential type. This will cause its value to be stored in flow credentials.
This uses the new cred typedInput proposed in #2367 
**Note**: credentials never get exported from the editor, so these property values will be left behind if copied to the clipboard.
=> Add credential-type to subflow env properties

test/editor/pageobjects/editor/palette_page.js, test/editor/pageobjects/nodes/core/common/21-debug_page.js, test/editor/pageobjects/nodes/core/common/24-complete_page.js, test/editor/pageobjects/nodes/core/common/25-catch_page.js, test/editor/pageobjects/nodes/core/common/25-status_page.js, test/editor/pageobjects/nodes/core/common/90-comment_page.js, test/editor/pageobjects/nodes/core/function/89-delay_page.js, test/editor/pageobjects/nodes/core/sequence/17-split_page.js, test/editor/pageobjects/nodes/core/sequence/19-batch_page.js, test/editor/pageobjects/nodes/nodefactory_page.js, test/editor/specs/scenario/cookbook_errorhandling_uispec.js, test/editor/specs/scenario/cookbook_httprequests_uispec.js
I created UI test case for the error handling flow which is introduced in cookbook website. In the pull request, I also fixed the page object for split node.
=> Add UI test case for error handling

packages/node_modules/@node-red/editor-client/src/sass/ace.scss
Consolidate duplicate CSS selectors.
=> Consolidate duplicate selectors

packages/node_modules/@node-red/editor-client/src/sass/workspace.scss
Fixes the syntax of two CSS properties.
=> Fix workspace CSS properties syntax

packages/node_modules/@node-red/editor-client/locales/en-US/editor.json
Just removes a duplicate object key.
=> Remove duplicate

packages/node_modules/@node-red/nodes/core/parsers/70-CSV.js
To properly parse CSV data, example below.
```
[{"id":"8600e861.0f1b88","type":"function","z":"6f1994e.e60de6c","name":"See if proper output","func":"msg.payload = encodeURIComponent(msg.payload[0].text);\nreturn msg;","outputs":1,"noerr":0,"x":620,"y":3680,"wires":[["a8326a2d.d93a98"]]},{"id":"4453cdcf.149ed4","type":"csv","z":"6f1994e.e60de6c","name":"","sep":",","hdrin":true,"hdrout":"","multi":"mult","ret":"\\n","temp":"","skip":"0","strings":true,"include_empty_strings":true,"include_null_values":true,"x":430,"y":3680,"wires":[["8600e861.0f1b88","58f20d10.5f7a84"]]},{"id":"a8326a2d.d93a98","type":"debug","z":"6f1994e.e60de6c","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":810,"y":3680,"wires":[]},{"id":"59deab16.5f75 …
```
=> Fix: Allow CR and LF control chars to be a part of the value

packages/node_modules/@node-red/runtime/lib/nodes/flows/index.js
Set `.disabled` on the flow object in /flow/:id API when `.disabled` is false
=> Set flow.disabled when disabled property is false

packages/node_modules/@node-red/editor-client/src/js/nodes.js
Running `grunt` on current dev branch causes jshint task error.
This is caused by lack of variable declaration.
This PR tries to fixes this.
=> add variable declaration to prohibit jshint error

packages/node_modules/node-red/red.js
This PR adds support of new command-line option for verwriting values in `settings.js`
described in https://github.com/node-red/designs/pull/23 .
=> Add option support for overwriting settiings.js

packages/node_modules/@node-red/nodes/core/network/21-httprequest.html, packages/node_modules/@node-red/nodes/core/network/21-httprequest.js, packages/node_modules/@node-red/nodes/locales/en-US/messages.json
with a body
First pass at a fix for #2476 
I'm working on some unit tests, but just want to check if everybody thinks my approach to this is right (also probably need to get the translations updated)
- [ x ] New feature (non-breaking change which adds functionality)
Adds support for optionally sending `msg.payload` as a body of a GET request
- [ x ] I have read the [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md)
- [ x ] For non-bugfix PRs, I have discussed this change on the mailing list/slack team.
- [ x ] I have run `grunt` to verify the unit tests pass
=> First pass at adding support for GET requests

.travis.yml, scripts/install-ui-test-dependencies.sh
As we had discussions on the issue, #2591, I added the code to enable automated UI testing on Travis CI.
=> Enable automated UI testing on Travis CI

test/editor/pageobjects/nodes/core/common/20-inject_page.js
I updated the page object of the inject node to improve failures in UI testing.
=> Fix page object of inject node

test/editor/pageobjects/nodes/core/common/21-debug_page.js, test/editor/specs/scenario/cookbook_dataformats_uispec.js
To improve failures in UI testing, I updated the page object of the debug node.
=> Fix page object of debug node

packages/node_modules/@node-red/editor-client/locales/ja/editor.json
This PR update Japanese message catalogue in response to English message catalogue update for subflow input UI.
=> Update subflow message jp

packages/node_modules/@node-red/nodes/locales/ja/messages.json
I updated the Japanese message for the debug node.
=> Update Japanese message for debug node

packages/node_modules/@node-red/nodes/locales/zh-CN/messages.json, packages/node_modules/@node-red/nodes/locales/zh-TW/messages.json
=> Update Chinese message for debug node

packages/node_modules/@node-red/nodes/core/common/20-inject.js, packages/node_modules/@node-red/nodes/core/common/24-complete.js, packages/node_modules/@node-red/nodes/core/common/25-catch.js, packages/node_modules/@node-red/nodes/core/common/25-status.js, packages/node_modules/@node-red/nodes/core/common/60-link.js, packages/node_modules/@node-red/nodes/core/function/16-range.js, packages/node_modules/@node-red/nodes/core/function/80-template.js, packages/node_modules/@node-red/nodes/core/network/21-httpin.js, packages/node_modules/@node-red/nodes/core/parsers/70-HTML.js, packages/node_modules/@node-red/nodes/core/parsers/70-JSON.js, packages/node_modules/@node-red/nodes/core/parsers/70-XML.js, packages/node_modules/@node-red/nodes/core/parsers/70-YAML.js
Update core nodes to support new Node Messaging API.
This is cherry-picked PR of #2402 .
For ease of review, I cherrypicked commits which are already reviewed
(Inject, Complete, Catch, Status, Link, Range, Template, HTTP in, HTML, JSON, XML, YAML; see https://github.com/node-red/node-red/pull/2402#issuecomment-575566897 ).
=> Messaging API support of core nodes (cherrypicked)

packages/node_modules/@node-red/nodes/locales/de/messages.json
=> german translation, wording (#2660)

package.json, packages/node_modules/@node-red/runtime/lib/api/flows.js, packages/node_modules/@node-red/runtime/package.json
=> Updated flow modification methods to support mutex serialization

packages/node_modules/@node-red/editor-client/src/js/ui/view.js
Selecting link node not existing within current active workspace from outliner causes editor error or unexpected node display as follows.
- Example flow: show *Flow 3*, then select link node or group in *Flow 1* or *Flow 2* from outliner
```
[{"id":"a82601c.3ed04","type":"tab","label":"Flow 1","disabled":false,"info":""},{"id":"b19dd4c9.92bd08","type":"tab","label":"Flow 2","disabled":false,"info":""},{"id":"5331fed3.c62c5","type":"tab","label":"Flow 3","disabled":false,"info":""},{"id":"f9ad954e.bb5028","type":"group","z":"a82601c.3ed04","style":{"stroke":"#999999","stroke-opacity":"1","fill":"none","fill-opacity":"1","label":true,"label-position":"nw","color":"#a4a4a4"},"nodes":["af01d39.8c7553"],"x":214,"y":139},{"id":"f6bab400.583b88","type":"group","z":"b19dd4c9.92bd08","style":{"stro …
```
=> fix selection of link node not existing within active workspace

packages/node_modules/@node-red/editor-client/locales/ja/editor.json
This PR add Japanese translation of message catalogue for changes in this PR(https://github.com/node-red/node-red/commit/2c6cda1f27b5b5bab538f2f605209768e2d6b3ef).
=> update Japanese message catalogue for 1.2.3 release

packages/node_modules/@node-red/nodes/core/sequence/19-batch.js, test/nodes/core/sequence/19-batch_spec.js
Update Batch node so that you can capture completion event of the node.
=> Messaging API support in Batch node

packages/node_modules/@node-red/nodes/core/parsers/70-CSV.js, test/nodes/core/parsers/70-CSV_spec.js
Update CSV node so that you can capture completion event of the node.
=> Messaging API support in CSV node

packages/node_modules/@node-red/nodes/core/sequence/18-sort.js, test/nodes/core/sequence/18-sort_spec.js
Update Sort node so that you can capture completion event of the node.
=> Messaging API support in Sort node

packages/node_modules/@node-red/nodes/core/function/89-delay.js, test/nodes/core/function/89-delay_spec.js
Support Messaging APIs in Delay node.
By this update, you can capture a completion event of delay node by complete node.
=> Messaging API support in Delay node

packages/node_modules/@node-red/nodes/core/function/89-trigger.js, test/nodes/core/function/89-trigger_spec.js
Update Trigger node so that you can capture completion event of the node.
- It calls done when the message has been received and:
- the 'first' message has been sent, 
- any timer has been set up for the second message
- But it does not wait for the second message to be sent before calling done.
- (from discussion in https://github.com/node-red/node-red/pull/2402#discussion_r432741748)
=> Messaging API support in Trigger node

packages/node_modules/@node-red/nodes/examples/parser/csv/01 - Parse CSV with default column name as message sequence.json, packages/node_modules/@node-red/nodes/examples/parser/csv/02 - Parse CSV with default column name as array.json, packages/node_modules/@node-red/nodes/examples/parser/csv/03 - Parse CSV with specified column name as message sequence.json, packages/node_modules/@node-red/nodes/examples/parser/csv/04 - Parse CSV with column name in first row as message sequence.json, packages/node_modules/@node-red/nodes/examples/parser/csv/05 - Convert JavaScript object to CSV.json, packages/node_modules/@node-red/nodes/examples/parser/csv/06 - Convert JavaScript object to CSV.json, packages/node_modules/@node-red/nodes/examples/parser/csv/07 - Convert array of JavaScript objects to CSV with column name header.json, packages/node_modules/@node-red/nodes/examples/parser/csv/08 - Specify column names in input message.json, packages/node_modules/@node-red/nodes/examples/parser/csv/09 - Send column name when reset property set.json, packages/node_modules/@node-red/nodes/examples/parser/csv/10 - Join parsed CSV message sequence using join node.json, packages/node_modules/@node-red/nodes/examples/parser/html/01 - Extract array of HTML element by CSS selector.json, packages/node_modules/@node-red/nodes/examples/parser/html/02 - Extract sequence of HTML element by CSS selector.json, packages/node_modules/@node-red/nodes/examples/parser/html/03 - Extract array of HTML element by CSS selector specified in message.json, packages/node_modules/@node-red/nodes/examples/parser/html/04 - Join extracedt  sequence of HTML element using join node.json, packages/node_modules/@node-red/nodes/examples/parser/json/01 - Convert JSON string to JavaScript object.json, packages/node_modules/@node-red/nodes/examples/parser/json/02 - Convert JavaScript object to JSON string.json, packages/node_modules/@node-red/nodes/examples/parser/json/03 - Validate input JSON string.json, packages/node_modules/@node-red/nodes/examples/parser/xml/01 - Convert JavaScript object to XML.json, packages/node_modules/@node-red/nodes/examples/parser/xml/02 - Convert XML to JavaScript object.json, packages/node_modules/@node-red/nodes/examples/parser/xml/03 - Control conversion using options property.json, packages/node_modules/@node-red/nodes/examples/parser/yaml/01 - Convert JavaScript object to YAML.json, packages/node_modules/@node-red/nodes/examples/parser/yaml/02 - Convert YAML to JavaScript object.json
This PR add examples for parser category core nodes.
=> add examples for parser category nodes

packages/node_modules/@node-red/editor-client/locales/de/editor.json, packages/node_modules/@node-red/nodes/locales/de/messages.json
Inconsistency and an error in the german translation.
Gitter -> Raster (it was called Raster in every other section and is, as far as I can tell, called raster in other applications)
Festlegen - bis -> Setzen - auf
As "festlegen bis" makes no sense at all in the context of a change node.
=> Improvements to DE translation

test/unit/@node-red/editor-api/lib/index_spec.js
- [ x ] Bugfix (non-breaking change which fixes an issue)
A start on improving code coverage within the project. (@knolleary often comments it needs work in his streams!)
- [ x ] I have read the [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md)
- [ x ] I have run `grunt` to verify the unit tests pass
- [ x ] I have added suitable unit tests to cover the new/changed functionality
P.s. This was a short effort to get my hands dirty. Looking advice regarding the way forward, how best to structure tests, general do's and do not's when working with tests on node-red. I'll wrap up the remaining test coverage over the weekend.
=> Improve editor api index test coverage

packages/node_modules/@node-red/editor-api/lib/index.js, packages/node_modules/@node-red/nodes/core/network/21-httpin.js
allow for adding an array of middleware functions
discussed @ https://discourse.nodered.org/t/feature-request-middleware-integration/37890
=> middleware integration

packages/node_modules/@node-red/editor-client/src/js/ui/tab-info-outliner.js
Current dev branch fails to run grant because of following jshint error:
```
Running "jshint:editor" (jshint) task
packages/node_modules/@node-red/editor-client/src/js/ui/tab-info-outliner.js
178 |                            if (!!n.d !== targetState) {
^ Confusing use of '!'.
>> 1 error in 70 files
Warning: Task "jshint:editor" failed.^G Use --force to continue.
```
=> fix jshint failure

packages/node_modules/@node-red/nodes/locales/de/sequence/19-batch.html
=> fixing minor typo in node's documentation

packages/node_modules/@node-red/nodes/examples/network/http/01 - Create HTTP endpoint.json, packages/node_modules/@node-red/nodes/examples/network/http/02 - Handle query parameters.json, packages/node_modules/@node-red/nodes/examples/network/http/03 - Handle URL parameters.json, packages/node_modules/@node-red/nodes/examples/network/http/04 - Access HTTP request headers.json, packages/node_modules/@node-red/nodes/examples/network/http/05 - Post data to a flow.json, packages/node_modules/@node-red/nodes/examples/network/http/06 - Post file to a flow.json, packages/node_modules/@node-red/nodes/examples/network/http/07 - Working with cookies.json, packages/node_modules/@node-red/nodes/examples/network/tcp/01 - Connect to TCP out server.json, packages/node_modules/@node-red/nodes/examples/network/tcp/02 - Connect to TCP in server.json, packages/node_modules/@node-red/nodes/examples/network/tcp/03 - Send reply to client of TCP connection.json, packages/node_modules/@node-red/nodes/examples/network/udp/01 - Transfer data using UDP protocol.json, packages/node_modules/@node-red/nodes/examples/network/websocket/01 - Connect to websocket in server.json, packages/node_modules/@node-red/nodes/examples/network/websocket/02 - Connect to websocket out server.json
This PR adds examples for network category nodes.
=> Network node examples

packages/node_modules/@node-red/nodes/core/network/10-mqtt.js
PR mqtt v5 fixes
- copy/paste issues with willMsg
- ensure helper func is ran for lwt messages
as discussed in the mqtt5 PR [here](https://github.com/node-red/node-red/pull/2778#issuecomment-786131890)
=> mqtt v5 fixes

packages/node_modules/@node-red/editor-api/lib/admin/index.js, packages/node_modules/@node-red/editor-api/lib/admin/nodes.js, packages/node_modules/@node-red/nodes/core/function/10-function.html, packages/node_modules/@node-red/nodes/core/function/10-function.js, packages/node_modules/@node-red/nodes/locales/en-US/messages.json, packages/node_modules/@node-red/registry/lib/util.js, packages/node_modules/@node-red/runtime/lib/api/nodes.js, packages/node_modules/@node-red/runtime/lib/index.js, packages/node_modules/@node-red/runtime/lib/nodes/index.js, packages/node_modules/@node-red/runtime/lib/nodes/npmModule.js
This PR is a draft implementation of NPM installation feature for function node as discussed in [this design note](https://github.com/node-red/designs/pull/31) intended for reviewing design direction of module specification UI and other detais.
The current implementation implements the automatic installation feature using "dynamicModule" property. The manual installation / uninstallation feature is not implemented yet.　In addition, there are some parts where the implementation  details such as error handling or internationalization are insufficient.
- Example Flow:
```
[{"id":"5c57bc44.6f35c4","type":"tab","label":"Flow 1","disabled":false,"info":""},{"id":"60762ac4.3add44","type":"function","z":"5c57bc44.6f35c4","name":"","func":"qr.toString(msg.payload, function (err, data) {\n …
```
=> [Draft] Npm installation for function node

packages/node_modules/@node-red/nodes/core/function/10-function.html, packages/node_modules/@node-red/nodes/core/network/10-mqtt.html, packages/node_modules/@node-red/nodes/locales/en-US/messages.json, packages/node_modules/@node-red/nodes/locales/ja/messages.json
This PR updates i18n support and Japanese message catalogue for the function node and the mqtt node.
=> Update i18n and Japanese message catalogue for function node and mqtt node

packages/node_modules/@node-red/editor-client/locales/en-US/editor.json, packages/node_modules/@node-red/editor-client/locales/ja/editor.json, packages/node_modules/@node-red/editor-client/src/js/red.js, packages/node_modules/@node-red/nodes/core/function/10-function.js, packages/node_modules/@node-red/nodes/locales/en-US/messages.json, packages/node_modules/@node-red/nodes/locales/ja/messages.json
I added Japanese translations for Node-RED v1.3.
=> Add Japanese translations for Node-RED v1.3

packages/node_modules/@node-red/nodes/locales/en-US/function/10-function.html
This PR adds help text about `node.outputCount`, which was forgotten in https://github.com/node-red/node-red/pull/2918
=> Function node: describe `node.outputCount` in help text

packages/node_modules/@node-red/editor-client/locales/ja/editor.json, packages/node_modules/@node-red/nodes/core/function/10-function.js, packages/node_modules/@node-red/nodes/locales/en-US/messages.json, packages/node_modules/@node-red/nodes/locales/ja/function/10-function.html, packages/node_modules/@node-red/nodes/locales/ja/messages.json, packages/node_modules/@node-red/nodes/locales/ja/storage/10-file.html
I update Japanese translations for Node-RED v1.3.1.
=> Add Japanese translations for Node-RED v1.3.1

packages/node_modules/@node-red/editor-client/src/sass/palette.scss
=> Fix margin between nodes on palette

test/nodes/core/function/90-exec_spec.js
Grunt test sometimes fail on exec node test case.
This is because the output of the exec node may be split into multiple messages.
This PR try to fix this issue.
=> fix grunt fail on exec node test

packages/node_modules/@node-red/nodes/core/network/21-httprequest.js
The original version would pick up the proxy servers port number
=> Fix msg.responseUrl

package.json, packages/node_modules/@node-red/nodes/core/parsers/70-JSON.js, packages/node_modules/@node-red/nodes/package.json, test/nodes/core/parsers/70-JSON_spec.js
=> Update ajv to 8.2.0 - drop support for JSON-Schema draft-04

packages/node_modules/@node-red/editor-client/locales/zh-CN/editor.json
Fix [Issue #3002](https://github.com/node-red/node-red/issues/3002)
=> fix typo in zh-CN translation

packages/node_modules/@node-red/editor-client/src/js/ui/editors/code-editors/monaco.js, packages/node_modules/@node-red/editor-client/src/types/node-red/func.d.ts, packages/node_modules/@node-red/editor-client/src/types/node-red/util.d.ts
update node-red typings for `env.get` as discussed [here](https://github.com/node-red/node-red/pull/2971#issuecomment-855215489)
=> Node red typings update

packages/node_modules/@node-red/nodes/core/storage/23-watch.js
before the node has finished processing them all.
Fixes #2996
=> Watch node throws errors if new files deleted

packages/node_modules/@node-red/editor-client/locales/en-US/jsonata.json, packages/node_modules/@node-red/editor-client/locales/ja/editor.json, packages/node_modules/@node-red/editor-client/locales/ja/jsonata.json, packages/node_modules/@node-red/nodes/locales/ja/messages.json, packages/node_modules/@node-red/runtime/locales/ja/runtime.json
This PR updates Japanese message catalogue according to recent updates on English messages.
It also updates English message catalogue of `$fromMillis` JSONata function because update to `$now` function  references updated contents of $fromMills.
=> Update message catalogue

packages/node_modules/@node-red/editor-client/src/js/ui/editor.js, packages/node_modules/@node-red/editor-client/src/js/ui/editors/code-editors/monaco.js, packages/node_modules/@node-red/editor-client/src/types/node-red/func.d.ts
Draft PR with fixes (as found) for monaco editor as [discussed here](https://discourse.nodered.org/t/node-red-2-0-0-beta-1-released/46990/20?u=steve-mcl)
- Allow setting of Readonly.
- Make node.status use choices for colour and shape.
- Let status node also be just a string.
=> Patches for Monaco editor

packages/node_modules/@node-red/runtime/lib/index.js, packages/node_modules/@node-red/runtime/locales/en-US/runtime.json
If running in readOnly this will add an info message to the log at startup
=> log readOnly on startup

package.json, packages/node_modules/@node-red/nodes/core/network/21-httprequest.js, packages/node_modules/@node-red/nodes/package.json
Update package.json to pick up 0.1.2 of hpagent
=> Bump hpagent to 0.1.2

packages/node_modules/@node-red/editor-api/lib/editor/theme.js
`cssFiles.concat` should be `scriptFiles.concat` on that line
=> Fix scriptFiles

packages/node_modules/@node-red/registry/package.json, packages/node_modules/@node-red/util/package.json
When I fixed the dependency in [the commit](https://github.com/node-red/node-red/pull/3052), I found that there are other necessary and unnecessary modules in package.json files. To suggest the fixing, I submit this pull request.
=> Add necessary modules and remove unnecessary module in dependencies

packages/node_modules/@node-red/nodes/core/network/21-httprequest.js
Check if there are any content to the credential object
Add to test to see if the http-request's credentials object is empty
=> Fix for #3067

packages/node_modules/@node-red/nodes/core/network/21-httprequest.js, test/nodes/core/network/21-httprequest_spec.js
=> Fix support for supplied CA certs

packages/node_modules/@node-red/nodes/core/network/21-httpin.html
Fixes the widths of the HTTP Response node header fields.
Moving to flex layout to remove the need to dynamically resize.
=> Fix sizing of HTTP Response header fields

packages/node_modules/@node-red/editor-client/src/js/ui/notifications.js
=> Allow RED.notify.update to modify any notification setting

packages/node_modules/@node-red/editor-client/package.json, packages/node_modules/@node-red/editor-client/src/js/ui/tab-help.js
The main entry pointed to non-existant entry (`./lib/index.js`).
Also fixed error when loading nodes lazily
=> Fix editor-client package.json

packages/node_modules/@node-red/nodes/core/common/20-inject.html
=> Do not modify inject node props in oneditprepare

packages/node_modules/@node-red/editor-client/src/js/ui/tour/tourGuide.js
=> Set dimension value for tour guide

packages/node_modules/@node-red/editor-client/src/js/ui/tab-info-outliner.js, packages/node_modules/@node-red/editor-client/src/js/ui/view.js
=> Do not show status for disabled nodes

packages/node_modules/@node-red/editor-client/src/js/ui/workspaces.js
=> Only toggle disabled workspace flag if on activeWorkspace

packages/node_modules/@node-red/editor-client/src/js/ui/utils.js, packages/node_modules/@node-red/util/lib/util.js
=> Handle RegExp types in Debug sidebar

packages/node_modules/@node-red/editor-client/locales/zh-CN/editor.json
Fixes #3272
Verified with Google Translate this is a better translation for
"Export to library"
=> Apply CN i18n fix

packages/node_modules/@node-red/editor-client/src/js/ui/common/autoComplete.js
=> Trigger change event when autoComplete fills in input

packages/node_modules/@node-red/editor-client/locales/ja/editor.json
I added Japanese translation to the message catalog for hidden flow.
=> Add Japanese translations for hidden flow

packages/node_modules/@node-red/editor-client/src/js/ui/workspaces.js
=> Fix storing hidden tab state when not hidden via action

packages/node_modules/@node-red/editor-client/src/js/ui/common/tabs.js
=> Fix findPreviousVisibleTab action

packages/node_modules/@node-red/nodes/core/common/20-inject.html
=> Fix incorrect clearing of blank payload property in Inject node

packages/node_modules/@node-red/nodes/core/function/rbe.js, test/nodes/core/function/rbe_spec.js
And add test
Fixes the initial start condition failure mode as discussed on the forum here As discussed https://discourse.nodered.org/t/the-filter-node-or-the-old-rbe-node/56371
=> Fix for filter node narrrowbandEq mode start condition failure

packages/node_modules/@node-red/nodes/examples/common/link/03 - Link call.json
This PR adds example of `link call` node added to latest Node-RED.
=> add link call example

packages/node_modules/@node-red/nodes/core/common/20-inject.html
JSON type property value is expected to be validated in inject node.  But it do not work correctly.
This is caused by missing variable reference of property type checking.
=> fix JSON propety validation of inject node

package.json, packages/node_modules/@node-red/editor-client/src/js/ui/utils.js
Updates `marked` to latest, which involves a major version bump and a change to how it is called.
=> Update marked to latest

packages/node_modules/@node-red/editor-client/src/js/ui/clipboard.js, packages/node_modules/@node-red/editor-client/src/sass/editor.scss
Reverts PR #3331 and applies the alternative fix originally proposed
in PR #3329
=> Revert copy-text change and apply alternative fix

packages/node_modules/@node-red/runtime/lib/flows/Flow.js, packages/node_modules/@node-red/runtime/lib/flows/Subflow.js, packages/node_modules/@node-red/util/lib/util.js, test/nodes/core/common/20-inject_spec.js, test/unit/@node-red/runtime/lib/flows/Subflow_spec.js
This PR adds support for accessing node id and node name using environment variable as discussed in:
https://discourse.nodered.org/t/proposal-make-node-name-accessible-as-environment-variable/56587/5
- id: `NODE_ID`
- name: `NODE_NAME`
=> Add support for accessing node id & name as environment variable

packages/node_modules/@node-red/editor-client/src/types/node-red/func.d.ts
- [#] Bugfix (non-breaking change which fixes an issue)
Update `node` declarations in func.d.ts to include `static` keyword
fixes #3376
=> Update `node` declarations in func.d.ts 

packages/node_modules/@node-red/runtime/lib/flows/Subflow.js, packages/node_modules/@node-red/util/lib/util.js, test/nodes/core/common/20-inject_spec.js, test/nodes/subflow/subflow_spec.js
This PR add support of accessing newly introduced `_path` property using environment variable `NR_NODE_PATH`.
=> add NR_NODE_PATH path support

packages/node_modules/@node-red/nodes/core/parsers/70-JSON.html
=> fix html label mistake

test/nodes/core/network/21-mqtt_spec.js
Adds unit tests for MQTT nodes
I have targeted Master as I wish to get these tests in place ASAP & before raising other PRs around MQTT.
Additionally, I would hope as soon as these tests are in place, Master should be merged into DEV. 
PS: these tests have already highlighted an issue in the MQTT nodes (will raise separate PR)
These are the current tests (by no means exhaustive, but a good range)
```
MQTT Nodes
√ should be loaded and have default values (110ms)
√ should send and receive string (auto) (58ms)
√ should send JSON and receive string (auto)
√ should send JSON and receive string (utf8)
√ should send JSON and receive Object (json)
√ should send String and receive Buffer (buffer)
√ should send utf8 Buffer and receive String (auto)
√ should send non utf8 Buffer and receive Buffer …
```
=> Add unit tests for MQTT nodes

packages/node_modules/@node-red/nodes/core/common/60-link.html, packages/node_modules/@node-red/nodes/core/common/60-link.js, packages/node_modules/@node-red/nodes/locales/en-US/common/60-link.html, packages/node_modules/@node-red/nodes/locales/en-US/messages.json, test/nodes/core/common/60-link_spec.js
closes #3441
fixes #3404
Add dynamic link call as discussed in #3441
=> Dynamic link call

packages/node_modules/@node-red/editor-client/src/js/nodes.js, packages/node_modules/@node-red/editor-client/src/js/red.js, packages/node_modules/@node-red/editor-client/src/js/ui/editors/panes/properties.js, packages/node_modules/@node-red/editor-client/src/js/ui/tab-config.js, packages/node_modules/@node-red/editor-client/src/js/ui/view.js, packages/node_modules/@node-red/editor-client/src/sass/colors.scss, packages/node_modules/@node-red/editor-client/src/sass/diff.scss, packages/node_modules/@node-red/nodes/core/network/10-mqtt.js, packages/node_modules/@node-red/nodes/core/network/31-tcpin.js, packages/node_modules/@node-red/nodes/core/parsers/70-JSON.html, test/nodes/core/network/21-mqtt_spec.js, test/nodes/core/network/31-tcpin_spec.js
Update dev branch with recent additions to master
=> Merge-master-dev

packages/node_modules/@node-red/editor-client/locales/en-US/editor.json, packages/node_modules/@node-red/editor-client/locales/ja/editor.json, packages/node_modules/@node-red/editor-client/src/sass/palette-editor.scss, packages/node_modules/@node-red/nodes/core/function/10-function.html, packages/node_modules/@node-red/nodes/core/sequence/19-batch.html, packages/node_modules/@node-red/nodes/locales/en-US/common/60-link.html, packages/node_modules/@node-red/nodes/locales/ja/common/60-link.html, packages/node_modules/@node-red/nodes/locales/ja/messages.json
I added Japanese translations for v3.0 in dev branch.
=> Add Japanese translations for v3.0

packages/node_modules/@node-red/nodes/core/common/20-inject.html
This unhides the option to allow fire at start when inject is set to at a fixed time mode... 
Can't see a real reason to not allow it - as the default is off - and the user may find it useful in some circumstances...
see request here
https://discourse.nodered.org/t/inject-node-feature-at-a-specific-time-inject-once-missing/57315
=> let inject optionally fire at start in only at time mode.

packages/node_modules/@node-red/runtime/lib/flows/Flow.js
fixes #3493
correction to `typeof` check (currently the `if` always evaluates to `true`)
=> correct "non string" check parenthesis

packages/node_modules/@node-red/editor-client/src/js/ui/deploy.js
Recent changes in `hasUnusedConfig` variable declarations from `var` to `let` made the scope of the variable stricter. 
As a result, the variable reference results in a reference error. 
This PR try to corrects this.
=> fix out of scope reference of hasUnusedConfig variable

packages/node_modules/@node-red/editor-client/src/sass/jquery.scss
Add custom style for jQuery widgets borders. Fixes #3518
=> Add custom style for jQuery widgets borders

packages/node_modules/@node-red/runtime/lib/nodes/credentials.js, packages/node_modules/@node-red/runtime/locales/en-US/runtime.json, test/unit/@node-red/runtime/lib/nodes/credentials_spec.js, test/unit/@node-red/runtime/lib/nodes/index_spec.js
Fix for https://github.com/node-red/node-red/issues/3496
Also warn if using unencypted credentials
=> Error on invalid encrypted credentials

packages/node_modules/@node-red/editor-client/src/js/ui/view.js
=> Fix recording removed links in edit history

packages/node_modules/@node-red/nodes/core/network/10-mqtt.html, packages/node_modules/@node-red/nodes/core/network/10-mqtt.js
fixes #3561 
Ensure the MQTT config node persists v5 User Properties
=> MQTT Node - save and restore v5 config user props

packages/node_modules/node-red/red.js
If the user doesn't have a defined home dir (env var `HOME`,
`USERPROFILE` or `HOMEPATH`) and the `userDir` is not passed on the
command line then we shouldn't start as we don't know where to copy the
default `settings.js` file to or where to store flows
fixes #3539
=> Don't start if user has no home directory

packages/node_modules/@node-red/nodes/core/storage/23-watch.js
=> Fix Watch node handling of recursive directories

packages/node_modules/@node-red/nodes/core/common/21-debug.html, packages/node_modules/@node-red/nodes/core/common/60-link.html
Tidy up a leftover development debug message ... with a smile!
=> Update 21-debug.html & 60-link.html

packages/node_modules/@node-red/editor-client/src/js/ui/search.js
fixes #3578
Fix browser console error `Uncaught TypeError` when searching certain terms 
See #3578
=> Fix browser console error Uncaught TypeError when searching certain terms

packages/node_modules/@node-red/editor-client/src/js/ui/editors/panes/flowProperties.js
fixes #3577
fix error initialising flow tab editor as described here: #3577
=> fix error initialising flow tab editor

packages/node_modules/@node-red/nodes/locales/en-US/common/60-link.html
Link-call node can can dynamically call link-in node by node id.  But it is not explained in info text.
This PR update the description.
=> update link-call node info according to current behavior

packages/node_modules/@node-red/editor-client/src/js/ui/common/typedInput.js, packages/node_modules/@node-red/editor-client/src/sass/ui/common/typedInput.scss
Looks like I left this one behind in #3515
<table>
<tr>
<td>Then
<td>Now
<tr>
<td><img width="525" alt="Screen Shot 2022-05-04 at 6 34 48 AM" src="https://user-images.githubusercontent.com/29807944/166667023-857ffa69-c713-4e15-87e4-392f3e9631a6.png">
<td><img width="539" alt="Screen Shot 2022-05-04 at 6 35 22 AM" src="https://user-images.githubusercontent.com/29807944/166667050-df4993b9-ca86-4303-a48c-222c7e15cf06.png">
</table>
=> Fix typedInput label not visible on themes

package.json, packages/node_modules/@node-red/nodes/core/network/10-mqtt.js
=> Handle removal of event handlers to allow mqtt client.end() to work 

packages/node_modules/@node-red/editor-client/locales/en-US/editor.json, packages/node_modules/@node-red/editor-client/src/js/ui/search.js, packages/node_modules/@node-red/editor-client/src/js/ui/view.js
fixes #3419
Allow user to search current flow via the filter `is:thisflow`
=> Add ability to search in current flow

packages/node_modules/@node-red/editor-client/src/js/ui/group.js
=> Remove duplicate history add of ungroup event

packages/node_modules/@node-red/editor-client/src/js/ui/view.js
=> Change slicing / slice-junction operations over to mouse button 0 (Left Mouse Button)

packages/node_modules/@node-red/editor-client/src/ace/mode/nrjavascript_worker.js
=> Ensure ACE worker options are set

packages/node_modules/@node-red/editor-client/src/sass/search.scss
Fixes a small typo in the CSS code.
=> Fix typo in CSS

packages/node_modules/@node-red/editor-client/src/js/ui/library.js
When the following operations are performed on the Function node, `New folder` menu of the library browser is not displayed.
1. Open settings of function node,
2. Select `Save to Library...`,
3. Click ellipses button on the right hand of an entry -> `New folder` menu is displayed,
4. Close dialog by clicking +Cancel*,
5. Re-select `Save to Library...`,
6. Click ellipses button on the right hand of an entry -> `New folder` menu is **not** displayed.
=> Fix new folder menu of save to library dialog

packages/node_modules/@node-red/editor-client/src/sass/panels.scss
A selector introduced in #3515 was misplaced and caused the issue described in #3631. This PR fixes that.
=> Fix selector placement

packages/node_modules/@node-red/editor-client/src/js/ui/clipboard.js
When exporting *current flow* from **Export** menu, junction nodes are not included in exported JSON data.
=> Fix to include junction to exported nodes

packages/node_modules/@node-red/editor-client/src/js/nodes.js, packages/node_modules/@node-red/editor-client/src/js/ui/subflow.js
Converting a flow containing Junction to Subflow using `Subflows`>`Selection to Subflow` menu causes editor runtime error.
=> Fix conversion of junction to subflow

packages/node_modules/@node-red/editor-client/src/js/nodes.js
Fix for converting junction to subflow introduced by this [PR](https://github.com/node-red/node-red/pull/3652) was incorrect.　
This PR try to fix it again.
=> Fix uncorrect fix of junction to subflow conversion

package.json, packages/node_modules/@node-red/nodes/core/network/10-mqtt.html, packages/node_modules/@node-red/nodes/core/network/10-mqtt.js
Backport of MQTT fixes in V3 to V2.x 
* https://github.com/node-red/node-red/pull/3563
* https://github.com/node-red/node-red/pull/3594
* https://github.com/node-red/node-red/pull/3626
(applied in that order)
Test results...
√ should be loaded and have default values (157ms)
√ basic send and receive tests (81ms)
√ should send JSON and receive string (auto)
√ should send JSON and receive string (utf8) (43ms)
√ should send JSON and receive Object (json)
√ should send String and receive Buffer (buffer)
√ should send utf8 Buffer and receive String (auto) (44ms)
√ should send non utf8 Buffer and receive Buffer (auto) (85ms)
√ should send/receive all v5 flags and settings (39ms)
√ should subscribe dynamically via action
√ should connect via "connect" action
√ should disconnect via "disconnect" …
=> Mqtt fixes in v3 for v2.x (backports #3563 #3594 #3626 to v2.x)

packages/node_modules/@node-red/editor-client/src/js/ui/group.js
=> Remove duplicate history add of ungroup event (backport #3581to v2.x)

packages/node_modules/@node-red/editor-client/src/js/ui/search.js
Backport...
Fix browser console error Uncaught TypeError when searching certain terms #3584
=> Fix browser console error Uncaught TypeError when searching certain terms (Backport #3548 to v2.x)

packages/node_modules/@node-red/nodes/core/common/20-inject.js, test/nodes/core/common/20-inject_spec.js
Fix JSONata evaluation of inject button (Backport 3632 to v2.x)
=> Fix JSONata evaluation of inject button (Backport 3632 to v2.x)

packages/node_modules/@node-red/editor-client/src/js/ui/library.js
Backport Fix new folder menu of save to library dialog #3633 to v2.x
=> fix new folder menu of save to library dialog (backport #3633 to v2.x)

packages/node_modules/@node-red/registry/lib/externalModules.js
Backport Fix ESM module loading in Function node #3645
=> Fix ESM module loading in Function node (Backport #3645 to v2.x)

packages/node_modules/@node-red/editor-client/src/js/ui/view.js
Reset mouse state when switching tabs (Backport #3643 to v2.x)
=> Reset mouse state when switching tabs (Backport #3643 to v2.x)

packages/node_modules/@node-red/editor-client/src/js/ui/view.js
Disabling junction using `Disable Selected Nodes` action causes editor runtime error.
=> Fix disable junction

packages/node_modules/@node-red/editor-client/src/js/ui/view.js
=> Include scroll offset when positioning quick-add dialog

packages/node_modules/@node-red/editor-client/src/js/ui/common/menu.js, packages/node_modules/@node-red/editor-client/src/sass/dropdownMenu.scss
=> Fix menu padding to handle both icons and submenus

packages/node_modules/@node-red/nodes/core/common/20-inject.html
Fixes the vertical alignment of the select boxes.
<table>
<tr>
<td>Before
<td>After
<tr>
<td><img width="1728" alt="Screen Shot 2022-06-21 at 11 21 17 AM" src="https://user-images.githubusercontent.com/29807944/174842330-3cea254e-b6a0-44ee-8c39-e4d59e6b73a1.png">
<td><img width="1728" alt="Screen Shot 2022-06-21 at 11 22 01 AM" src="https://user-images.githubusercontent.com/29807944/174842367-fc4666f3-c851-4c50-9834-f6a0aefe7253.png">
<tr>
<td><img width="1728" alt="Screen Shot 2022-06-21 at 11 44 12 AM" src="https://user-images.githubusercontent.com/29807944/174842397-012c00b1-1b99-406f-b64a-5249c9aab4a5.png">
<td><img width="1728" alt="Screen Shot 2022-06-21 at 11 44 26 AM" src="https://user-images.githubusercontent.com/29807944/174842465-325c9553-f2af-4061-b462-961c9327fd95.png"> …
=> Fix select boxes vertical alignment

packages/node_modules/@node-red/editor-client/src/js/ui/editors/panes/appearance.js
=> Fix use default button for node icon

packages/node_modules/@node-red/editor-client/locales/zh-CN/editor.json
=> fix chinese translate: 登陆 -> 登录

packages/node_modules/@node-red/editor-client/src/js/ui/workspaces.js
=> Ensure 'hidden flow' count doesn't include subflows

CHANGELOG.md, package.json, packages/node_modules/@node-red/editor-api/package.json, packages/node_modules/@node-red/editor-client/package.json, packages/node_modules/@node-red/editor-client/src/js/ui/tour/tourGuide.js, packages/node_modules/@node-red/editor-client/src/tours/welcome.js, packages/node_modules/@node-red/nodes/package.json, packages/node_modules/@node-red/registry/package.json, packages/node_modules/@node-red/runtime/package.json, packages/node_modules/@node-red/util/package.json, packages/node_modules/node-red/package.json
Update dependencies, versions, tourGuide and Change Log.
=> Update for 3 beta 4

CHANGELOG.md
Missed a couple PRs from the beta.4 changelog.
=> Add missing entries from beta.4 changelog

packages/node_modules/@node-red/runtime/lib/flows/Subflow.js, packages/node_modules/@node-red/runtime/lib/nodes/credentials.js
=> Do not remove unknown credentials of Subflow Modules

packages/node_modules/@node-red/editor-client/src/sass/palette.scss
=> Fix shade for node icon to be rounded rectangle

packages/node_modules/@node-red/editor-client/src/js/ui/group.js, packages/node_modules/@node-red/editor-client/src/js/ui/subflow.js
=> Focus editor for undo after some actions in menu

package.json, packages/node_modules/@node-red/editor-api/package.json, packages/node_modules/@node-red/editor-client/package.json, packages/node_modules/@node-red/nodes/package.json, packages/node_modules/@node-red/registry/package.json, packages/node_modules/@node-red/runtime/package.json, packages/node_modules/@node-red/util/package.json, packages/node_modules/node-red/package.json
Update version of dev branch so we don't get confused with master
=> Bump dev to 3.1.0-beta.0

packages/node_modules/@node-red/editor-client/src/js/ui/subflow.js
=> remove console.log

packages/node_modules/@node-red/nodes/core/sequence/17-split.js
=> Join-reduce keep existing msg properties (backport to v2.x)

packages/node_modules/@node-red/editor-client/src/js/ui/editors/envVarList.js
=>  Fix credential type input item of subflow template (backport to v2.x)

packages/node_modules/@node-red/editor-client/src/js/ui/workspaces.js
=> Ensure 'hidden flow' count doesn't include subflows (backport to v2.x)

packages/node_modules/@node-red/nodes/core/function/89-delay.js, packages/node_modules/@node-red/nodes/examples/function/delay/06 - Simple Queue with release
=> Fix delay rate limit last timing when empty (backport to v2.x)

packages/node_modules/@node-red/nodes/core/parsers/70-CSV.js, test/nodes/core/parsers/70-CSV_spec.js
=> Fix CSV node to handle \n when outputting text fields (backport to v2.x)

packages/node_modules/@node-red/runtime/lib/flows/Subflow.js, packages/node_modules/@node-red/runtime/lib/nodes/credentials.js
=> Do not remove unknown credentials of Subflow Modules (backport to v2.x)

packages/node_modules/@node-red/nodes/core/function/15-change.js
=> Fix change node, not handling from field properly when using context (backport to v2.x)

packages/node_modules/@node-red/editor-client/src/js/ui/subflow.js
=> Fix storing subflow credential type when input has multiple types (backport to v2.x)

packages/node_modules/@node-red/editor-client/locales/de/editor.json, packages/node_modules/@node-red/runtime/locales/de/runtime.json
With this PR I update the German translation.
I've often replaced "Berechtigung" with "Anmeldeinformation", since "Berechtigung" stands for "permission" rather than "credential".
Otherwise, it's more minor adjustments or adding texts that have not yet been translated.
Maybe @ralphwetzel can take a look at the PR? :)
=> Update german translation

packages/node_modules/@node-red/nodes/core/network/21-httprequest.html, packages/node_modules/@node-red/nodes/core/network/21-httprequest.js, packages/node_modules/@node-red/nodes/locales/en-US/messages.json
=> Allow HTTP Headers not in spec (backport to v2.x)

scripts/generate-publish-script.js
Ensures the generatePublishScript knows we're on 3 now, so generates appropriate commands for publishing maintenance releases.
=> Update gen pub script

packages/node_modules/@node-red/editor-client/locales/ja/editor.json, packages/node_modules/@node-red/nodes/locales/ja/messages.json
I added Japanese translation for Node-RED v3.0.2.
=> Add Japanese translation for v3.0.2

packages/node_modules/@node-red/nodes/core/network/21-httprequest.js, test/nodes/core/network/21-httprequest_spec.js
Also add tests for broken headers
copy `n.insecureHTTPParser` to `node` object used in later test
=> Add missing property to node object HTTPRequest

packages/node_modules/@node-red/editor-client/src/js/ui/editors/envVarList.js, packages/node_modules/@node-red/util/lib/util.js, test/nodes/subflow/subflow_spec.js, test/unit/@node-red/runtime/lib/flows/Flow_spec.js
This PR add support of JSONata expression for environment variable definition as proposed in[ this forum message](https://discourse.nodered.org/t/proposal-allow-jsonata-expression-in-environment-variable-definition/65341/2).
=> Env var jsonata

test/nodes/core/network/21-httprequest_spec.js, test/unit/@node-red/editor-api/lib/index_spec.js
Running grunt on current master causes following error:
```
Running "nyc:all" (nyc) task
Running "simplemocha:all" (simplemocha) task
Warning: done is not a function^G Use --force to continue.
```
This is caused by calling `done` as defined as an argument of callback function of `describe` function.
Because the callback do not take argument, it causes the error.
=> Remove done from describe

packages/node_modules/@node-red/editor-client/locales/ja/editor.json
There are a few inaccurate translation in Japanese  JSONata editor message.
This PR fixes them.
=> Fix Japanese translation for JSONata editor

packages/node_modules/@node-red/nodes/core/network/21-httpin.js
Fixes #3893
Used parseInt instead of the suggested fix so that we don't end up with statusCode = 200.5
=> Ensure statusCode is a number

packages/node_modules/@node-red/nodes/core/function/10-function.html
In this pull request, I fixed #3885 in case of entering ports for function node only.
=> Limit number of ports in function node

packages/node_modules/@node-red/editor-client/src/js/ui/common/typedInput.js
=> Fix autocomplete entry for responseUrl

packages/node_modules/@node-red/nodes/core/network/10-mqtt.js, test/nodes/core/network/21-mqtt_spec.js
* Removes old unused code around `usews` and brokerUrl from around 5ys ago.
* Adds test for bad birth topic
* fixes newly found bug in original PR #3869 (revealed by adding test)
=> Fix birth topic handling in MQTT node

packages/node_modules/@node-red/editor-client/locales/ja/editor.json
This PR add Japanese message for newly added editor actions for item URL copy:
- `core:copy-item-url`
- `core:copy-item-edit-url`
=> add Japanese message for item url copy actions

packages/node_modules/@node-red/editor-client/src/js/ui/deploy.js
The following operations stop the flow editor:
1. Add a new node to a blank tab,
2. Lock the tab,
3. Deploy
This is caused by changing the node in the locked flow on deploy.
=> fix deployment of locked flow

packages/node_modules/@node-red/nodes/core/common/25-catch.html
=> fix: fix typo in catch.html

packages/node_modules/@node-red/nodes/core/common/25-status.html
Because I found that there is the same typo as https://github.com/node-red/node-red/pull/3965, I fixed it by this pull request.
=> Fix typo in 25-status.html

packages/node_modules/@node-red/editor-client/src/js/ui/palette.js
Fixed https://github.com/node-red/node-red/issues/3979 by this pull request.
=> Hide subflow category after deleting subflow

packages/node_modules/@node-red/runtime/lib/storage/localfilesystem/projects/git/index.js
Fixed https://github.com/node-red/node-red/issues/3986 to ignore commit error.
=> Ignore commit error in project feature

packages/node_modules/@node-red/editor-client/src/sass/radialMenu.scss
As described in https://github.com/node-red-contrib-themes/theme-collection/issues/239, the text in the radial menu becomes unreadable when using themes. This PR fixes that.
<table>
<tr>
<td>
<td>Now
<td>Then
<tr>
<td>Default theme
<td><img width="161" alt="SCR-20221229-d6z" src="https://user-images.githubusercontent.com/29807944/209970147-e4df95d1-4416-4de8-90fb-90b12e431437.png">
<td><img width="161" alt="SCR-20221229-ddr" src="https://user-images.githubusercontent.com/29807944/209970173-81fdc09b-4ffe-4082-9b81-508fe6fc7f11.png">
<tr>
<td>Dark theme
<td><img width="161" alt="SCR-20221229-dqo" src="https://user-images.githubusercontent.com/29807944/209970905-dd4bd6fe-9065-4e26-acbc-3c6ff9d61715.png">
<td><img width="161" alt="SCR-20221229-dqw" …
=> Let themes change radialMenu text colors

packages/node_modules/@node-red/runtime/lib/flows/index.js
=> Ensure credentials object is removed before returning node in getFlow request

packages/node_modules/node-red/settings.js
=> Fix typos in settings.js

packages/node_modules/@node-red/runtime/locales/ja/runtime.json
I added Japanese translations for the master branch.
=> Add Japanese translations for v3.0.3

packages/node_modules/@node-red/nodes/core/network/31-tcpin.js
change the replace to a regex replace /g so it replaces all \\n \\r and \\t type characters (though why you would have multiple to signify a single new line is beyond me :-)
=> TCP Node: ensure newline substitution applies to whole message

packages/node_modules/@node-red/registry/lib/localfilesystem.js, packages/node_modules/@node-red/runtime/lib/storage/localfilesystem/projects/defaultFileSet.js
=> Rename package var to avoid strict mode error

packages/node_modules/@node-red/editor-client/src/js/red.js
=> Fix disabled menu items in project feature

packages/node_modules/@node-red/nodes/core/function/10-function.html
There is a glitch on the top corners of the modules list in the Function node's Setup tab. It's very subtle, which is why the screenshots are zoomed in. This Pr fixes that.
<table>
<tr>
<td>Now
<td>Then
<tr>
<td><img width="1730" alt="SCR-20230201-nvr" src="https://user-images.githubusercontent.com/29807944/216183610-8a2b2edf-2b38-4003-bae7-5af40391750b.png">
<td><img width="1730" alt="SCR-20230201-nw4" src="https://user-images.githubusercontent.com/29807944/216183663-b6e5b9b8-ea95-404a-9ead-5b5ca7a86007.png">
</table>
=> Fix border radius on Modules list header

packages/node_modules/@node-red/registry/lib/loader.js
Fixes #3523
Full credit to @tve for diagnosing the issue - details in the linked issue.
=> Fix async loading of modules containing both nodes and plugins

packages/node_modules/@node-red/editor-client/locales/en-US/editor.json, packages/node_modules/@node-red/editor-client/locales/ja/editor.json
I added Japanese translations for locking flow.
=> Add Japanese translations for locking flow

packages/node_modules/@node-red/editor-client/src/tours/welcome.js
I added the Japanese translations for the welcome tour.
=> Add Japanese translations for welcome tour of 3.1.0 beta.1

packages/node_modules/@node-red/editor-client/src/js/ui/projects/projectSettings.js
Currently, the preview of README.md on the Project settings UI doesn't support the Mermaid diagram. Therefore, I added the code to apply the Mermaid diagram in this pull request.
=> Apply Mermaid diagram for project settings UI

packages/node_modules/node-red/settings.js
closes #4074
Update out of date link in settings.js file
=> Update monaco docs link in settings.js

packages/node_modules/@node-red/editor-client/locales/ja/editor.json, packages/node_modules/@node-red/editor-client/src/js/ui/env-var.js
This [PR](https://github.com/node-red/node-red/pull/3941) added support for global environment variable.  
However, it lacks an editor action for accessing the edit panel.
This PR add support for the action.
=> Add action for global environment variable

packages/node_modules/@node-red/nodes/core/sequence/17-split.js
=> Join: ensure inflight status is cleared when in auto mode

packages/node_modules/node-red/lib/red.js
=> Bump minimum nodejs version supported to match documented value

packages/node_modules/@node-red/editor-client/src/js/ui/editors/code-editors/monaco.js
fixes #4102 
Ensure serverside function node editor gets a ref to the "timers" types
=> add "timers" types to known types

packages/node_modules/@node-red/editor-client/src/tours/welcome.js
I added Japanese translations for the welcome tour.
=> Add Japanese translations for welcome tour of 3.1.0 beta.2

packages/node_modules/@node-red/editor-client/src/js/ui/actionList.js
=> Support uppercase in keyword when searching action list

packages/node_modules/@node-red/editor-client/src/sass/editor.scss, packages/node_modules/@node-red/editor-client/src/sass/popover.scss, packages/node_modules/@node-red/editor-client/src/sass/tab-info.scss
=> Wrap long node name in tooltip, info sidebar, and node property

packages/node_modules/@node-red/editor-api/lib/admin/index.js, packages/node_modules/@node-red/editor-api/lib/editor/index.js, packages/node_modules/@node-red/editor-api/lib/editor/projects.js, packages/node_modules/@node-red/editor-api/lib/editor/settings.js, packages/node_modules/@node-red/editor-api/lib/editor/sshkeys.js, packages/node_modules/@node-red/editor-api/lib/editor/theme.js, packages/node_modules/@node-red/editor-api/lib/index.js, packages/node_modules/@node-red/editor-api/lib/util.js, packages/node_modules/@node-red/runtime/lib/index.js, test/unit/@node-red/editor-api/lib/editor/index_spec.js, test/unit/@node-red/editor-api/lib/editor/settings_spec.js, test/unit/@node-red/editor-api/lib/editor/sshkeys_spec.js
Fixes #4169
This creates a single utility function for creating express apps to ensure any server configuration is applied consistently.
=> Ensure express server options are applied consistently

packages/node_modules/@node-red/editor-client/src/js/ui/clipboard.js
=> Fix content type for downloading flows.json

packages/node_modules/@node-red/nodes/core/function/rbe.js
To close #4165
This fix check that the required property is present in the msg before trying to process - or rather - it ignores messages where the required property is not present.
- [] For non-bugfix PRs, I have discussed this change on the forum/slack team.
=> Fix RBE for missing "payload"

packages/node_modules/@node-red/runtime/lib/flows/Flow.js
Removes unused code left over from #3843 that I missed in #4185
=> Remove unused function

packages/node_modules/@node-red/editor-client/src/js/ui/editors/code-editors/monaco.js
fixes #4194
Changes use of internal/unstable _props to API stable (for now) counter parts.
=> fix function node error badge not shown

packages/node_modules/@node-red/editor-client/src/tours/welcome.js
I added Japanese translations for the welcome guide tour for Node-RED v3.1.0-beta.3.
=> Add Japanese translations for v3.1.0-beta.3

CHANGELOG.md, package.json, packages/node_modules/@node-red/editor-api/package.json, packages/node_modules/@node-red/editor-client/package.json, packages/node_modules/@node-red/editor-client/src/tours/welcome.js, packages/node_modules/@node-red/nodes/package.json, packages/node_modules/@node-red/registry/package.json, packages/node_modules/@node-red/runtime/package.json, packages/node_modules/@node-red/util/package.json, packages/node_modules/node-red/package.json
Update changelog etc for beta.3 release.
Will hold off merging for the moment - couple PRs may yet land that will need adding to the changelog.
=> Bump everything for beta.3

packages/node_modules/@node-red/editor-client/locales/zh-CN/editor.json
Update Simplified Chinese translation files
=> Add missing Simplified Chinese translations for editor.json

packages/node_modules/@node-red/editor-client/src/tours/3.0/welcome.js, packages/node_modules/@node-red/editor-client/src/tours/first-flow.js, packages/node_modules/@node-red/editor-client/src/tours/welcome.js
French translation of Welcome Tours. I hope I could translate this part 😅
=> French translation of Welcome Tours

packages/node_modules/@node-red/editor-client/src/js/ui/view.js, packages/node_modules/@node-red/editor-client/src/sass/flow.scss
Discussion: https://discourse.nodered.org/t/feature-request-little-tweak-on-wires/79336/5
Now:
Was:
=> Improve wiring for horizontally aligned nodes

packages/node_modules/@node-red/editor-client/locales/ja/editor.json, packages/node_modules/@node-red/nodes/locales/ja/messages.json
=> Add Japanese translation for 3.1.0

packages/node_modules/@node-red/nodes/core/network/21-httprequest.html
=> fix html syntax in 21-httprequest.html

packages/node_modules/@node-red/editor-client/src/js/nodes.js
=> fix: undefined node and wrong method name

packages/node_modules/@node-red/editor-client/src/sass/projects.scss
While I'm creating a document about the project feature, I found that the `Add remote` header in project settings UI doesn't have rounded corners.
I fixed this issue in this pull request.
=> Fix not rounded corners in project settings UI

packages/node_modules/@node-red/editor-client/locales/en-US/jsonata.json
Adds docs for the $clone jsonata function.
=> Add docs for $clone function

packages/node_modules/@node-red/nodes/core/network/21-httprequest.js, test/nodes/core/network/21-httprequest_spec.js
Reverts node-red/node-red#3991 following the conversation in #4279
=> Revert "Support form-data arrays"

README.md, package.json, packages/node_modules/@node-red/editor-client/src/js/red.js, packages/node_modules/@node-red/nodes/locales/de/function/10-function.html, packages/node_modules/@node-red/nodes/locales/en-US/function/10-function.html, packages/node_modules/@node-red/nodes/locales/fr/function/10-function.html, packages/node_modules/@node-red/nodes/locales/ja/function/10-function.html, packages/node_modules/@node-red/nodes/locales/ko/function/10-function.html, packages/node_modules/@node-red/nodes/locales/pt-BR/function/10-function.html, packages/node_modules/@node-red/nodes/locales/ru/function/10-function.html, packages/node_modules/@node-red/nodes/locales/zh-CN/function/10-function.html, packages/node_modules/@node-red/nodes/locales/zh-TW/function/10-function.html, packages/node_modules/node-red/README.md, packages/node_modules/node-red/package.json, packages/node_modules/node-red/red.js, packages/node_modules/node-red/settings.js, test/unit/@node-red/editor-api/lib/editor/theme_spec.js
Migrate `http://nodered.org` to secure `https://nodered.org` since `https` is the new default.
=> Migrate http -> https for nodered.org

package.json, packages/node_modules/@node-red/nodes/package.json, packages/node_modules/@node-red/registry/package.json, packages/node_modules/node-red/package.json
Some selected dependency updates. `npm audit --production` currently reporting no known issues.
=> Dependency updates

packages/node_modules/@node-red/nodes/core/network/10-mqtt.js
`"text/html"` was declared twice in the array.
=> Fix duplicate declaration

package.json, packages/node_modules/@node-red/editor-api/package.json, packages/node_modules/@node-red/editor-client/package.json, packages/node_modules/@node-red/nodes/package.json, packages/node_modules/@node-red/registry/package.json, packages/node_modules/@node-red/runtime/package.json, packages/node_modules/@node-red/util/package.json, packages/node_modules/node-red/package.json
Bumps the `dev` branch packages to `4.0.0-dev`... lets keep things moving.
=> Bump to 4.0.0-dev

CONTRIBUTING.md
Soften the language around unrequited PRs
=> Soften the language around unrequited PRs

packages/node_modules/@node-red/nodes/core/function/80-template.html
Fixed https://github.com/node-red/node-red/issues/4345.
=> Fix height of description editor in template node

.gitignore
Recently, there were some PRs with the `package-lock.json` file included. For example, https://github.com/node-red/node-red/pull/4261#issuecomment-1658484972 and https://github.com/node-red/node-red/pull/4352#discussion_r1329754858.
This PR adds `package-lock.json` to `.gitignore` to prevent it from being accidentally committed again.
=> Don't commit package-lock.json

packages/node_modules/@node-red/nodes/core/common/20-inject.html, packages/node_modules/@node-red/nodes/core/common/21-debug.html
Fixed #4398 by replacing the space with a tab to avoid `\n `.
=> Fix unintended new line in node name

packages/node_modules/@node-red/editor-client/src/js/ui/workspaces.js
=> Update browser title with flow name if set

packages/node_modules/@node-red/nodes/core/network/10-mqtt.js
to close #4414
Adds a check that the topic length > 0 before publishing. Raises error if it is 0.
=> check topic length > 0 before publish

CHANGELOG.md, package.json, packages/node_modules/@node-red/editor-api/package.json, packages/node_modules/@node-red/editor-client/package.json, packages/node_modules/@node-red/nodes/package.json, packages/node_modules/@node-red/registry/package.json, packages/node_modules/@node-red/runtime/package.json, packages/node_modules/@node-red/util/package.json, packages/node_modules/node-red/package.json
Update for 3.1.1 maintenance release
=> Bump for 3.1.1 release

packages/node_modules/@node-red/editor-client/locales/zh-CN/editor.json, packages/node_modules/@node-red/editor-client/locales/zh-CN/jsonata.json, packages/node_modules/@node-red/editor-client/locales/zh-TW/editor.json, packages/node_modules/@node-red/editor-client/locales/zh-TW/jsonata.json, packages/node_modules/@node-red/editor-client/src/js/ui/contextMenu.js
=> Added action list Chinese (Simplified and Traditional) translation + v3.1.1 changes

packages/node_modules/@node-red/editor-client/src/js/ui/palette.js
=> Fix location of subflow ports in palette

packages/node_modules/@node-red/editor-client/locales/de/editor.json, packages/node_modules/@node-red/editor-client/locales/en-US/editor.json, packages/node_modules/@node-red/editor-client/locales/fr/editor.json, packages/node_modules/@node-red/editor-client/locales/ja/editor.json, packages/node_modules/@node-red/editor-client/locales/ko/editor.json, packages/node_modules/@node-red/editor-client/locales/pt-BR/editor.json, packages/node_modules/@node-red/editor-client/locales/ru/editor.json, packages/node_modules/@node-red/editor-client/locales/zh-CN/editor.json, packages/node_modules/@node-red/editor-client/locales/zh-TW/editor.json, packages/node_modules/@node-red/editor-client/src/js/red.js
=> Replace `rename` by `edit` for the menu flow label

packages/node_modules/@node-red/editor-client/src/js/ui/typeSearch.js
=> Fix subflow ports in Quick Add dialog

packages/node_modules/@node-red/editor-client/src/js/ui/contextMenu.js
=> Focus Quick Add dialog from context menu

packages/node_modules/@node-red/editor-client/src/js/ui/contextMenu.js
=> Add handling to disable items on context menu

packages/node_modules/@node-red/editor-client/locales/ja/editor.json
I added Japanese translations for Node-RED v3.1.3.
=> Add Japanese translations for v3.1.3

packages/node_modules/@node-red/editor-client/locales/en-US/editor.json, packages/node_modules/@node-red/editor-client/locales/fr/editor.json, packages/node_modules/@node-red/editor-client/locales/ja/editor.json, packages/node_modules/@node-red/editor-client/locales/pt-BR/editor.json, packages/node_modules/@node-red/editor-client/locales/zh-CN/editor.json
Partial revert of #4368 who removed the `invalid-num-prop` messages.
It is still used in the number validator (`RED.validators.number`)
=> Add missing validation messages

packages/node_modules/@node-red/nodes/core/network/21-httprequest.js
See #4521 - this removes the use of the toLowercase but removing the unused function.
=> 21-httprequest.js remove unused code, because of broken use of toLowercase

packages/node_modules/@node-red/editor-client/src/js/ui/view.js
`RED.view.select` now accepts a `links` object (array of links to select).
=> Allow RED.view.select to select links

packages/node_modules/@node-red/editor-client/locales/de/editor.json
=> Update editor.json fix typo in German translation

packages/node_modules/@node-red/editor-client/locales/fr/editor.json, packages/node_modules/@node-red/runtime/locales/fr/runtime.json
Add French translation of v3.1.3 changes (#4470)
=> Add French translation of v3.1.3 changes

packages/node_modules/@node-red/nodes/locales/zh-CN/function/80-template.html
=> fix: template node zh-CN translation

packages/node_modules/@node-red/registry/lib/library.js, test/unit/@node-red/registry/lib/library_spec.js
=> Fix example flow name in import dialog

packages/node_modules/@node-red/editor-api/lib/admin/settings.js, packages/node_modules/@node-red/editor-api/lib/auth/strategies.js, packages/node_modules/@node-red/editor-api/lib/editor/index.js, packages/node_modules/@node-red/editor-api/lib/editor/library.js, packages/node_modules/@node-red/editor-api/lib/editor/locales.js, packages/node_modules/@node-red/editor-api/lib/editor/sshkeys.js, packages/node_modules/@node-red/editor-api/lib/editor/theme.js, packages/node_modules/@node-red/editor-api/lib/index.js
=> chore: remove never use import code

packages/node_modules/@node-red/runtime/lib/flows/Flow.js, packages/node_modules/@node-red/runtime/lib/flows/Group.js, packages/node_modules/@node-red/runtime/lib/flows/Subflow.js
=> Handle undefined env vars

package.json, packages/node_modules/@node-red/util/package.json
Pulls in fix for CVE-2024-27307
=> Update jsonata version

packages/node_modules/@node-red/editor-client/locales/ja/editor.json
=> Add Japanese translation for v3.1.6

packages/node_modules/@node-red/editor-client/src/sass/base.scss, packages/node_modules/@node-red/editor-client/src/sass/colors.scss, packages/node_modules/@node-red/editor-client/src/sass/header.scss, packages/node_modules/@node-red/editor-client/src/sass/sizes.scss, packages/node_modules/@node-red/editor-client/src/sass/style-custom-theme.scss, packages/node_modules/@node-red/editor-client/src/sass/style.scss, packages/node_modules/@node-red/editor-client/src/sass/variables.scss
Discourse Forum Post: https://discourse.nodered.org/t/header-styling-improvements-proposal-with-draft-pr/86270
- Modernise the layout with display: flex rather than fixed margins/padding
- Change the height from 40px to 48px (and parametrise this in the SCSS variables
- Add a 2px solid border below the header to prevent the sharp contrast between the navigation (black) and the editor background (white)
- 5px > 8px spacing between the icon and "Node-RED" heading
#C7C7C7 > white font color for the main title.
=> Improve the appearance of the Node-RED primary header

packages/node_modules/@node-red/nodes/locales/ja/common/91-global-config.html
=> Remove typo in global config

packages/node_modules/@node-red/editor-client/locales/fr/editor.json, packages/node_modules/@node-red/editor-client/src/tours/welcome.js, packages/node_modules/@node-red/nodes/locales/fr/common/91-global-config.html, packages/node_modules/@node-red/nodes/locales/fr/messages.json, packages/node_modules/@node-red/nodes/locales/fr/network/31-tcpin.html, packages/node_modules/@node-red/nodes/locales/fr/parsers/70-CSV.html
- Add missing global-config translation
- Add translations for TCP and CSV nodes
- Add translations for 4.0.0-beta.1
=> Add French translations for 4.0.0-beta.1

CHANGELOG.md, package.json, packages/node_modules/@node-red/editor-api/package.json, packages/node_modules/@node-red/editor-client/package.json, packages/node_modules/@node-red/nodes/package.json, packages/node_modules/@node-red/registry/package.json, packages/node_modules/@node-red/runtime/package.json, packages/node_modules/@node-red/util/package.json, packages/node_modules/node-red/package.json
=> Bump for 3.1.8

packages/node_modules/@node-red/nodes/core/function/15-change.js, test/nodes/core/function/15-change_spec.js
Fixes #4638
Includes test cases for the same
=> Fix change node handling of replacing with boolean

test/unit/@node-red/runtime/lib/multiplayer/index_spec.js
Missed the test file for multiplayer runtime code. Adding a placeholder to unblock
=> Add placeholder tests for multiplayer

CHANGELOG.md, package.json, packages/node_modules/@node-red/editor-api/package.json, packages/node_modules/@node-red/editor-client/package.json, packages/node_modules/@node-red/nodes/package.json, packages/node_modules/@node-red/registry/package.json, packages/node_modules/@node-red/runtime/package.json, packages/node_modules/@node-red/util/package.json, packages/node_modules/node-red/package.json
=> Bump for 3.1.9 release

packages/node_modules/@node-red/editor-client/src/js/ui/editors/code-editors/monaco.js
I found three typos in the monaco.js editor file while doing a code review.
=> Fix three error typos in monaco.js

packages/node_modules/@node-red/editor-client/src/js/ui/projects/projectSettings.js, packages/node_modules/@node-red/runtime/lib/storage/localfilesystem/projects/index.js
=> Enable updating dependency node of package.json in project feature

packages/node_modules/@node-red/editor-client/locales/fr/editor.json, packages/node_modules/@node-red/editor-client/src/tours/welcome.js, packages/node_modules/@node-red/runtime/locales/fr/runtime.json
Add French translations for 4.0.0-beta.2
=> Add French translations for 4.0.0-beta.2

package.json, packages/node_modules/@node-red/runtime/lib/flows/Subflow.js, packages/node_modules/@node-red/runtime/lib/flows/index.js, packages/node_modules/@node-red/runtime/lib/flows/util.js, packages/node_modules/@node-red/runtime/lib/nodes/index.js, packages/node_modules/@node-red/runtime/package.json
This PR was originally proposed by @anshumanr in #4607.
I've picked up the work done there and applied it cleanly to where we know we're handling clean JSON data.
This PR replaces #4607
=> Use rfdc for cloning pure JSON values

packages/node_modules/@node-red/registry/lib/externalModules.js
Remove polyfill for unsupported node =<12.
#4687
=> fix(polyfill): remove import module polyfill

packages/node_modules/node-red/lib/red.js
Remove if statement for unsupported node <16.
Add reference to issue for the workaround.
#4687
=> fix(dns): remove outdated node check

.github/workflows/tests.yml
Add new nodejs v22 to test matrix. See https://nodejs.org/en/blog/release/v22.0.0
=> feat(ci): add new nodejs v22

packages/node_modules/@node-red/editor-client/src/tours/welcome.js
Add French translation of tour for 4.0.0-beta.3
=> Add French translation of tour for 4.0.0-beta.3

package.json, packages/node_modules/@node-red/editor-api/package.json, packages/node_modules/@node-red/editor-client/package.json, packages/node_modules/@node-red/nodes/package.json, packages/node_modules/@node-red/registry/package.json, packages/node_modules/@node-red/runtime/package.json, packages/node_modules/@node-red/util/package.json, packages/node_modules/node-red/package.json
Republishing the beta to fix a packaging mistake.
=> Bump for beta 4-beta3-1

packages/node_modules/@node-red/editor-client/src/sass/tab-config.scss
Change the Config Node cursor from `default` to `pointer`.
It looks better and tells the user that they can click to open the edit box.
=> Change the Config Node cursor to `pointer`

packages/node_modules/@node-red/editor-client/locales/ja/editor.json, packages/node_modules/@node-red/editor-client/src/tours/welcome.js
=> Add Japanese translations for 4.0.0-beta.3

packages/node_modules/@node-red/editor-client/locales/ja/editor.json
=> Add Japanese translation for sidebar tooltip

Gruntfile.js
Build script should fail if source file is not available.
fixes #4738
=> feat(grunt): fail if files are missing

packages/node_modules/@node-red/runtime/lib/flows/Group.js, test/unit/@node-red/runtime/lib/flows/Group_spec.js
=> Fix clone of group env var properties

packages/node_modules/@node-red/nodes/locales/de/function/89-delay.html
To close #4748
Add/update German translations for delay node as per Issue #4748
=> Add/Update German Translations for delay node

CHANGELOG.md, package.json, packages/node_modules/@node-red/editor-api/package.json, packages/node_modules/@node-red/editor-client/package.json, packages/node_modules/@node-red/nodes/package.json, packages/node_modules/@node-red/registry/package.json, packages/node_modules/@node-red/runtime/package.json, packages/node_modules/@node-red/util/package.json, packages/node_modules/node-red/package.json
Updates for 3.1.11 release - including `ws` module update
=> Bump for 3.1.11 release

packages/node_modules/@node-red/editor-client/locales/ja/editor.json
=> Add Japanese translations for v4.0.0

packages/node_modules/@node-red/editor-client/locales/fr/editor.json
- Add missing French translations from v4.0.0
- Improved French translations
=> Improve the editor's French translations

packages/node_modules/@node-red/editor-client/src/js/multiplayer.js, packages/node_modules/@node-red/runtime/lib/multiplayer/index.js
As part of multiplayer mode, this adds support for displaying the position of other user's cursors within the workspace in real-time.
=> Multiplayer cursor tracking

packages/node_modules/@node-red/nodes/core/network/05-tls.js
part of #4877
This moves the SNI, ALPN and the Verify Server Cert check out of the check for if the supplied certs/key are actually valid as these may be still required for correct behaviour.
=> Move SNI, ALPN and Verify Server cert out of check

packages/node_modules/@node-red/nodes/locales/en-US/messages.json
=> fix typo: depreciated

packages/node_modules/@node-red/editor-client/locales/es-ES/editor.json, packages/node_modules/@node-red/nodes/locales/es-ES/messages.json, packages/node_modules/@node-red/nodes/locales/es-ES/network/31-tcpin.html, packages/node_modules/@node-red/nodes/locales/es-ES/parsers/70-CSV.html, packages/node_modules/@node-red/runtime/locales/es-ES/runtime.json
I would appreciate it if you could add the `hacktoberfest` tag to the project or the `hacktoberfest-accepted` tag to this PR if you are ok with that.
thanks
=> i18n(App) update with latest language file changes

CHANGELOG.md, package.json, packages/node_modules/@node-red/editor-api/package.json, packages/node_modules/@node-red/editor-client/package.json, packages/node_modules/@node-red/nodes/package.json, packages/node_modules/@node-red/registry/package.json, packages/node_modules/@node-red/runtime/package.json, packages/node_modules/@node-red/util/package.json, packages/node_modules/node-red/package.json
Updating 3.x stream to latest mermaid due to its internal usage of old dompurify version
=> Bump mermaid to latest

packages/node_modules/@node-red/nodes/core/function/89-trigger.js, test/nodes/core/function/89-trigger_spec.js
to fix #4914
Fixes trigger node handling of the new time type typed input.
=> Fix trigger node date handling for latest time type input

packages/node_modules/@node-red/editor-client/src/js/ui/palette-editor.js
Cleanup global Palette Manager variables:
- Remove unused variables
- Sort variables and move them
- Add comments
=> Cleanup global Palette Manager variables

packages/node_modules/@node-red/editor-client/src/js/nodes.js, packages/node_modules/@node-red/editor-client/src/js/ui/subflow.js
Bad number of `node.users` for Config Node:
- Deleting a Node inside a Subflow does not update the number of users.
- Replacing a Config Node overwrites the user list to empty.
- Remove duplicate "addUser" (L2426), `addNode` do it later.
Other changes:
- `updateConfigNodeUsers` - for either add or remove and either trigger the event
Related PR: #4757.
=> Fix the config node users count

packages/node_modules/@node-red/editor-client/src/js/ui/view-annotations.js
=> Apply zoom scale when calculating annotation positions

packages/node_modules/@node-red/nodes/core/function/89-delay.js
=> Fix delay node not dropping when nodeMessageBufferMaxLength is set

package.json, packages/node_modules/@node-red/editor-api/package.json, packages/node_modules/@node-red/runtime/package.json
Bump express to pick up CVE dependency fixes
=> Bump express 3.1.x

packages/node_modules/@node-red/editor-client/src/js/history.js, packages/node_modules/@node-red/editor-client/src/js/nodes.js, packages/node_modules/@node-red/editor-client/src/js/ui/editor.js, packages/node_modules/@node-red/editor-client/src/js/ui/editors/panes/envVarProperties.js, packages/node_modules/@node-red/editor-client/src/js/ui/editors/panes/properties.js, packages/node_modules/@node-red/editor-client/src/js/ui/subflow.js
This PR is a roll-up of the following PRs. They have been individual tested, but as they are all in heavily related areas (more or less), I wanted to pull them into a single branch to test against them as a whole set.
As of raising this PR, I haven't yet done that testing, but getting the PR raised for visibility.
- #4793 
- #4797 
- #4807 
- #4808 
- #4819 
- #4947
=> Roll up various fixes on config node change history

CHANGELOG.md, package.json, packages/node_modules/@node-red/editor-api/package.json, packages/node_modules/@node-red/editor-client/package.json, packages/node_modules/@node-red/nodes/package.json, packages/node_modules/@node-red/registry/package.json, packages/node_modules/@node-red/runtime/package.json, packages/node_modules/@node-red/util/package.json, packages/node_modules/node-red/package.json
Updates for 4.0.6 maintenance release
=> Update for 4.0.6

packages/node_modules/node-red/package.json
Updates package.json for the main node-red package
=> Update express in main package

CHANGELOG.md, package.json, packages/node_modules/@node-red/editor-api/package.json, packages/node_modules/@node-red/editor-client/package.json, packages/node_modules/@node-red/nodes/package.json, packages/node_modules/@node-red/registry/package.json, packages/node_modules/@node-red/runtime/package.json, packages/node_modules/@node-red/util/package.json, packages/node_modules/node-red/package.json
=> Bump for 3.1.15

CHANGELOG.md, package.json, packages/node_modules/@node-red/editor-api/package.json, packages/node_modules/@node-red/editor-client/package.json, packages/node_modules/@node-red/nodes/package.json, packages/node_modules/@node-red/registry/package.json, packages/node_modules/@node-red/runtime/package.json, packages/node_modules/@node-red/util/package.json, packages/node_modules/node-red/package.json
=> Bump for 4.0.7

CHANGELOG.md, package.json, packages/node_modules/@node-red/editor-api/package.json, packages/node_modules/@node-red/editor-client/package.json, packages/node_modules/@node-red/nodes/package.json, packages/node_modules/@node-red/registry/package.json, packages/node_modules/@node-red/runtime/package.json, packages/node_modules/@node-red/util/package.json, packages/node_modules/node-red/package.json
=> Bump for 4.0.8

packages/node_modules/@node-red/nodes/core/common/21-debug.js
Fixes the debug status node if sent a null payload.  As reported on thy forum here - https://discourse.nodered.org/t/debug-node-failing-to-report-null-as-part-of-the-node-status/94720
=> fix debug status reporting if null

packages/node_modules/@node-red/nodes/locales/de/network/10-mqtt.html
As requested: https://discourse.nodered.org/t/mqtt-subscribe-to-selectable-shelly/95339/6?u=kitori
=> Add details for the dynamic subscription to match the English docs

CHANGELOG.md, package.json, packages/node_modules/@node-red/editor-api/package.json, packages/node_modules/@node-red/editor-client/package.json, packages/node_modules/@node-red/nodes/package.json, packages/node_modules/@node-red/registry/package.json, packages/node_modules/@node-red/runtime/package.json, packages/node_modules/@node-red/util/package.json, packages/node_modules/node-red/package.json
Update changelog for 4.0.9 release
=> Update for 4.0.9

packages/node_modules/@node-red/editor-client/src/js/ui/utils.js
Update `DOMPurify` flag by removing outdated flag.
DOMPurify currently used 2.5.7.
Changelog DOMPurify 2.1.0:
> Removed the SAFE_FOR_JQUERY flag (we are safe by default now for jQuery)
https://github.com/cure53/DOMPurify/releases/tag/2.1.0
=> chore(editor): update `DOMPurify` flag

packages/node_modules/@node-red/editor-client/src/sass/ace.scss, packages/node_modules/@node-red/editor-client/src/sass/base.scss, packages/node_modules/@node-red/editor-client/src/sass/editor.scss, packages/node_modules/@node-red/editor-client/src/sass/flow.scss, packages/node_modules/@node-red/editor-client/src/sass/header.scss, packages/node_modules/@node-red/editor-client/src/sass/jquery.scss, packages/node_modules/@node-red/editor-client/src/sass/library.scss, packages/node_modules/@node-red/editor-client/src/sass/palette-editor.scss, packages/node_modules/@node-red/editor-client/src/sass/palette.scss, packages/node_modules/@node-red/editor-client/src/sass/popover.scss, packages/node_modules/@node-red/editor-client/src/sass/sidebar.scss, packages/node_modules/@node-red/editor-client/src/sass/style-custom-theme.scss, packages/node_modules/@node-red/editor-client/src/sass/style.scss, packages/node_modules/@node-red/editor-client/src/sass/tab-config.scss, packages/node_modules/@node-red/editor-client/src/sass/tab-info.scss, packages/node_modules/@node-red/editor-client/src/sass/tabs.scss, packages/node_modules/@node-red/editor-client/src/sass/ui/common/treeList.scss, packages/node_modules/@node-red/editor-client/src/sass/ui/common/typedInput.scss, packages/node_modules/@node-red/editor-client/src/sass/variables.scss, packages/node_modules/@node-red/editor-client/src/sass/workspace.scss, packages/node_modules/@node-red/editor-client/src/sass/workspaceToolbar.scss
Fix Sass deprecation warnings by migrating the global rules to the module system.
EDIT: The files were updated using the `sass-migrate` script as described in their [blog post](https://sass-lang.com/documentation/cli/migrator/).
This has been tested and works with the Sass package version currently used (v1.62.1).
Fixes #4921.
=> Fix Sass deprecation warnings

packages/node_modules/@node-red/nodes/core/network/21-httprequest.js
part of  node-red/node-red#5104
=> Fix the capitisation for ALPN settings in http-request

package.json, packages/node_modules/@node-red/editor-api/package.json, packages/node_modules/@node-red/nodes/package.json
Bump multer to 2.0.1 for CVE fixes
=> Bump Multer to 2.0.1

packages/node_modules/@node-red/runtime/lib/storage/localfilesystem/library.js
Don't leak absolute file paths when asking for non-existant library entries
=> Prevent library leaking full local paths

packages/node_modules/@node-red/editor-client/src/js/ui/editors/mermaid.js, packages/node_modules/@node-red/editor-client/src/js/ui/utils.js
A fix to the rendering of mermaid diagrams in Node-RED - see https://discourse.nodered.org/t/node-red-mermaid-rendering-is-off-by-one/97546 for details
=> Mermaid diagram fix for rendering diagrams inside Node-RED

package.json, packages/node_modules/node-red/package.json
=> Bump node-red-admin to latest

CHANGELOG.md, package.json, packages/node_modules/@node-red/editor-api/package.json, packages/node_modules/@node-red/editor-client/package.json, packages/node_modules/@node-red/nodes/package.json, packages/node_modules/@node-red/registry/package.json, packages/node_modules/@node-red/runtime/package.json, packages/node_modules/@node-red/util/package.json, packages/node_modules/node-red/package.json
=> Update for 4.1.0 release
